### ISSUE TITLE
Minor array dimensions inconsistency between atom selection and compute_distances on 1 pair

### ISSUE THREAD

**Issue by cing** [mdtraj/mdtraj#1003]
Let's say you want to compute the distance between ONLY two points and you're too lazy to run linalg.norm on (x1,y1,z1) and (x2,y2,z2), so you use `compute_distances()`. You encounter a little array shape issue. It's obviously an easy fix.

```
>>> import mdtraj as md
>>> prot = md.load('1vii_3frames.pdb')
>>> sel = prot.topology.select("residue 41 and (name N or name C)")
>>> sel
array([0, 2])
>>> sel.shape
(2,)
>>> md.compute_distances(prot, atom_pairs=sel)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/mdtraj-1.6.0.dev1-py2.7-macosx-10.5-x86_64.egg/mdtraj/geometry/distance.py", line 67, in compute_distances
    pairs = ensure_type(atom_pairs, dtype=np.int32, ndim=2, name='atom_pairs', shape=(None, 2), warn_on_cast=False)
  File "//anaconda/lib/python2.7/site-packages/mdtraj-1.6.0.dev1-py2.7-macosx-10.5-x86_64.egg/mdtraj/utils/validation.py", line 123, in ensure_type
    "You supplied %s" % (name, ndim, val.ndim)))
ValueError: atom_pairs must be ndim 2. You supplied 1
>>> sel2 = sel.reshape([1,-1])
>>> sel2.shape
(1, 2)
>>> md.compute_distances(prot, atom_pairs=sel2)
array([[ 0.24654114],
       [ 0.24654114],
       [ 0.24654114]], dtype=float32)
```

It's not problem for 99% of the world because typically users would pass more than 1 pair of indices in `compute_distances()`. Is this even a problem worth an issue/fixing? I'm not sure, just thought I'd throw it out there.

**Comment by ctk3b** [comment]
I would not consider this broken since it is working as advertised. The keyword is "atom_pair**s**", the error message is clear and the [docstring](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/distance.py#L51) also gives a clear explanation.

I suppose we could add a check to reshape the array like you did but then it's no longer working as advertised :)

**Comment by cing** [comment]
Fair enough!
