### ISSUE TITLE
Bug in Trajectory.slice() with copy=False

### ISSUE THREAD

**Issue by schilli** [mdtraj/mdtraj#1004]
Hi,
there seems to be a bug in the Trajectory.slice() function. When it is done in place (copy=False),
the topology variable in the "if copy" conditional remains undefined and crash the initialization of the new trajectory.
Cheers.
Oliver

**Comment by rmcgibbo** [comment]
Thanks for the bug report! That looks right -- I think it's just the `topology` variable (the others are defined before the conditional). Would you like to submit a pull request to fix it?

**Comment by schilli** [comment]
I will try, I've never done that though.

**Comment by rmcgibbo** [comment]
No problem :). There are some [instructions here](https://guides.github.com/activities/contributing-to-open-source/). I can answer any questions you have too.

**Comment by rmcgibbo** [comment]
You can actually do the whole thing through your browser without using the command line, if you prefer, by navigating to the file and then clicking the edit button up in the right.

![](http://idratherbewriting.com/images/restapicourse/github_making_branch_edits.png)

I often use this for simple commits that only need to change one line or two.

**Comment by schilli** [comment]
Too late ;-)
I already forked it and not and edits to the original branch will be added as a new branch to my own fork.
But I think I get it.

**Comment by schilli** [comment]
I submitted a pull request.

Just to make sure that I did it right (and in case you have further advice for future pull requests), here is what I did:
* fork the repo
* clone it locally
* build it with **python setup.py build**
* prepend the build dir to my PYTHONPATH environment variable
* tix the bug
* test it
* commit
* git push
* submit pull request

Do you have any objections and/or advice for me?
I don't have much experience with git yet.
Cheers,
Oliver

**Comment by rmcgibbo** [comment]
My suggestion would be to run either `pip install .` or `python setup.py install` (`pip install .` is newer and better) instead of running `python setup.py build` and then changing your PYTHONPAH environment variable. This will build the package and copy it into your python installation directory, without requiring any modification if your environment variables.

The other thing that you could do (I'll merge the PR anyways, but it's good practice) is to write a test that verifies the behavior and would have caught the bug if it had been in the test suite. Most of the tests for the trajectory object are in [test_trajectory.py](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/tests/test_trajectory.py). There is one test that currently checks the `slice` method [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/tests/test_trajectory.py#L116-L122), but you can see it doesn't check the `copy=False` option. So perhaps you could add something there.

Then, you can run the tests with `nosetests mdtraj -v`, which might require installing `nose` (`pip install nose` or `conda install nose` if you don't have it yet). You can run just the tests in that file with `nosetests mdtraj.tests.test_trajectory -v`

**Comment by rmcgibbo** [comment]
Also, you can update your pull request by making a second commit on the same branch and then pushing -- you don't need to make a second branch or second PR.

**Comment by schilli** [comment]
Thanks!
I did not use pip as I did not want to overwrite the mdtraj version I use with anaconda, as I was afraid that anaconda would not update it automatically anymore.
I will look into writing the test.

**Comment by rmcgibbo** [comment]
With anaconda, a convenient thing is to create a second environment that you can use for development:

```
conda create -n dev python=3.5 ipython cython numpy nose pytables scipy ...
source activate dev # on unix; on windows, I think it's just 'activate dev'
```
Now you're in a separate environment, and you can install stuff or mess around with your python installation in any way. Then if you run `source deactivate`, you'll go back to your original environment without any of those changes.

**Comment by schilli** [comment]
Thanks for your help.
my code changes seem to work fine, but still a test if failed:

    ======================================================================
    ERROR: mdtraj.formats.pdb.tests.test_pdb.test_pdb_from_url
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/site-packages/mdtraj/formats/pdb/tests/test_pdb.py", line 184, in test_pdb_from_url
        t1 = load_pdb('http://www.rcsb.org/pdb/files/4K6Q.pdb.gz')
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 150, in load_pdb
        with PDBTrajectoryFile(filename) as f:
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 250, in __init__
        self._file = urlopen(filename)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/urllib2.py", line 437, in open
        response = meth(req, response)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/urllib2.py", line 550, in http_response
        'http', request, response, code, msg, hdrs)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/urllib2.py", line 475, in error
        return self._call_chain(*args)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/home/oliver/software/programs/anaconda/envs/mdtrajtest/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    HTTPError: HTTP Error 500: Internal Server Error

I have the same problem with your master branch, so it is not broken by my changes.

**Comment by rmcgibbo** [comment]
Fixed now.
