### ISSUE TITLE
support trajectories of VTF format ?

### ISSUE THREAD

**Issue by WangZongan** [mdtraj/mdtraj#1008]
Hi, 

I'm a new user of mdtraj. 
I was wondering will mdtraj be supporting loading trajectories of VTF format ?
Thank you.

best, 
zongan

**Comment by rmcgibbo** [comment]
I'm not personally familiar with the VTF format, but in general the scope of mdtraj is to include support for as many MD trajectory formats as possible.

I don't have any plans to implement this myself, but if you or anyone else wanted to contribute this feature though a PR, I'd be happy to merge it in.

**Comment by Wzongan** [comment]
Yes, that would nice !
