### ISSUE TITLE
possible error on traj.xyz

### ISSUE THREAD

**Issue by Wzongan** [mdtraj/mdtraj#1018]
Hi,

I'm using MDtraj to do analysis. 
This is what I do:

![screen shot 2016-01-07 at 00 08 29](https://cloud.githubusercontent.com/assets/10877037/12163397/d8798d02-b4d2-11e5-9af8-1d0f4ca2bbe4.png)

I randomly choose a pdb file from PDB front webpage.

We can see that the coordinates are:

array([[[-3.144,  2.487,  0.842],
        [-3.091,  2.351,  0.857],
        [-3.15 ,  2.279,  0.979],
        ..., 
        [-3.297,  0.792,  3.633],
        [-2.128, -1.069,  4.03 ],
        [-3.084, -1.719,  0.341]]], dtype=float32)

However the actual coordinates are:

![screen shot 2016-01-07 at 00 10 26](https://cloud.githubusercontent.com/assets/10877037/12163422/17a528ba-b4d3-11e5-90bc-06247e44f11e.png)

ATOM      1  N   SER A  17     -31.435  24.869   8.424  1.00 44.70           N  
ATOM      2  CA  SER A  17     -30.912  23.508   8.565  1.00 43.97           C  
ATOM      3  C   SER A  17     -31.498  22.793   9.793  1.00 43.58           C  
ATOM      4  O   SER A  17     -32.011  23.452  10.706  1.00 44.46           O  
ATOM      5  CB  SER A  17     -29.385  23.507   8.599  1.00 48.69           C  
ATOM      6  OG  SER A  17     -28.867  22.190   8.473  1.00 58.47           O  

We can see that the coordinates extracted by traj.xyz are 10 times smaller, which I think implies a one-character shift error. 

best,
Zongan

**Comment by Wzongan** [comment]
Forgot to mention that the version of MDtraj I'm using was downloaded about 2 weeks ago.

**Comment by rmcgibbo** [comment]
This is a feature, not a bug. When data is loaded into MDTraj, all quantities that represent distances/positions are converted to nanometers, as mentioned in the [docs](http://mdtraj.org/latest/api/generated/mdtraj.Trajectory.html). The PDB format records positions in Angstroms, so that's where the factor of 10 you're seeing comes from.

**Comment by Wzongan** [comment]
Ah, I'm very sorry..... Thank you for telling me !
