### ISSUE TITLE
Specify format on loading

### ISSUE THREAD

**Issue by csadorf** [mdtraj/mdtraj#1021]
I'd like to use mdtraj for post-processing of hoomd-blue trajectory data. One of my obstacles right now is that all my hoomd-blue xml files end in `.xml` and not `.hoomdxml` and I don't see any way to manually specify the right format when loading.

I can work-around this problem by renaming all my files or creating symbolic links. I'd prefer to have an option to specify the correct format, is that possible?

**Comment by ctk3b** [comment]
Not directly via `md.load` since formats are simply ["detected"](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L149) based on their extension and the `.xml` extension is used for OpenMM XML files.

However, you can directly invoke the loader:

```python
topology = load_hoomdxml('your_file.xml').topology
```

**Comment by csadorf** [comment]
Hi Christoph! :)

Thank you for the quick help!

**Comment by ctk3b** [comment]
Oh hi Simon!
