### ISSUE TITLE
save_pdb only writes crystallographic record for first frame

### ISSUE THREAD

**Issue by Trayder** [mdtraj/mdtraj#1024]
I was using save_pdb to write out samples drawn from my msmbuilder dataset. However MDTraj only writes out the CRYST record for the first frame rather than for each "MODEL". This certainly has the potential to cause pbc errors but the problem I noticed was an incompatibility with gromacs' trjconv which expects pbc for every frame.

Saving out an xtc worked absolutely fine.

**Comment by rmcgibbo** [comment]
Have you checked the wwPDB spec? I thought -- but I'm not sure -- that for specification only allowed for one CRYST1 record in the header section, regardless of the number of models.

**Comment by Trayder** [comment]
That would make sense for a crystal structure, but I think it's one of those things where the modelling programs have bent the rules. A PDB file isn't really suitable for a MD trajectory otherwise.

In this case, you could imagine if the box size changed over a trajectory,using the one CRYST record for all models would incorrectly calculate PBCs.

**Comment by rmcgibbo** [comment]
yeah, I understand the implications. but the project has a general policy of trying to follow the relevant standards as exactly as possible.

**Comment by mpharrigan** [comment]
I would argue that a PDB file **isn't** suitable for an MD trajectory.

Maybe we should raise an exception if someone tries to save a multi-model pdb with box vectors that change. This behavior is pretty misleading

**Comment by rmcgibbo** [comment]
> Maybe we should raise an exception if someone tries to save a multi-model pdb with box vectors that change.

This seems like a good idea.

**Comment by Trayder** [comment]
Ugh, MD standards are a mess but yeah, an exception solves the problem nicely.

There'll be lots of cases where one still wants to end up with a universally recognised "pdb" file, but plenty of other programs can easily handle the filthy, non-standard conversion.
