### ISSUE TITLE
Request: A way to calculate distance between atoms and certain coordinate point

### ISSUE THREAD

**Issue by lambdalisue** [mdtraj/mdtraj#1025]
First of all, thanks for this awesome project ;-) I used to use MDAnalysis but this one is more simple and powerful to use. I like your implementation ;-)

Anyway, as I titled. I would like to select atoms existing only in certain distance from a certian coordinate.
 **In short, I would like to compute a distance between an atom and a certain coordinate via a function.**

So I checked document and found [compute_distances](http://mdtraj.org/latest/api/generated/mdtraj.compute_distances.html#mdtraj.compute_distances) or [compute_neighobors](http://mdtraj.org/latest/api/generated/mdtraj.compute_neighbors.html#mdtraj.compute_neighbors) but these functions calculate distances between atoms. So I cannot use these functions for selecting atoms for my purpose.

Even the code to achieve what I want is not so difficult, _I felt that calculating distance between an atom and coordinate is kind a fundamental function_. So I first tried to write a Python implementation but then noticed that mdtraj use a lot of C implementations to enhance the performance. So I wonder if you could add a function like `compute_distances_from(traj, coordinate, indices, periodic=True, opt=True)` or whatever.

Or maybe a way to add a pseudo atom into `xyz` then users can use that pseudo atom in `compute_distances`, `compute_neighbors` or other functions require atoms?

P.S.
I understand that mdtraj provide `select` function _in toporogy level_ and users cannot use distance-based selection; like PyMOL's `resn WAT within 5 of resi 10`; in `select` function, due to the lack of coordinate information. But it would be nice if I could do something like:

``` python
multi_indices = traj.topology.select('water and name O within 5 of resi 10', traj.xyz)
for i in range(len(traj.xyz)):
    atoms = traj.xyz[i, multi_indices[i]])
```

I just wonder.

**Comment by rmcgibbo** [comment]
Hi! Thanks for filing this, @lambdalisue.

Distance based `select` expressions are a feature I would like to see. The first feature request you mentioned, `compute_distances_from`, also would be a nice feature to have.

**Comment by lambdalisue** [comment]
> Distance based select expressions are a feature I would like to see. 

Wow. Sounds really exciting :smiley: I'm looking forward that.

**Comment by ajasja** [comment]
I second  (or third:) this! Especially the second request, which should probably be split into it's own issue.
