### ISSUE TITLE
Merge two trajectories

### ISSUE THREAD

**Issue by cxhernandez** [mdtraj/mdtraj#1027]
Would an "atom-wise" concatenation function be useful? A possible use case is if I have structures for both a protein and a ligand and then want them both to exist in the same `Trajectory` object.

This is the code I have so far:

``` python
def merge(sys1, sys2):
    xyz = np.hstack((sys1.xyz, sys2.xyz))
    top = sys1.topology.copy()
    top.add_chain()
    for res in sys2.topology.residues:
        top.add_residue(res.name, top.chain(-1), res.resSeq)
    for at in sys2.topology.atoms:
        top.add_atom(at.name, at.element,
                     top.chain(-1).residue(at.residue.index), at.serial)
    for at1, at2 in sys2.topology.bonds:
        top.add_bond(top.chain(-1).atom(at1.index),
                     top.chain(-1).atom(at2.index))
    return md.Trajectory(xyz, top)
```

**Comment by cxhernandez** [comment]
A possible improvement to this code would be to prevent the two systems from overlapping in the merge.

**Comment by kyleabeauchamp** [comment]
How is this different from http://mdtraj.org/latest/api/generated/mdtraj.Topology.html?highlight=join#mdtraj.Topology.join

**Comment by cxhernandez** [comment]
@kyleabeauchamp: oh, I didn't see that! Is there anything like this for the `Trajectory` object, though?

**Comment by kyleabeauchamp** [comment]
Can't remember, but should be easy enough to write if it's not there.

**Comment by cxhernandez** [comment]
I found it: http://mdtraj.org/latest/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.stack

Nevermind then.
