### ISSUE TITLE
Use mdtraj organization settings effectively

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#1033]
Github made organization settings more sane several months ago. I changed things for the msmbuilder organization, and those changes would probably be nice here as well.

The teams shouldn't be "secret". Members should default to full read access (not really relevant here because we don't have any private repos), and you can have a distinction between members (idk, for show) and people with commit access

**Comment by rmcgibbo** [comment]
Okay, I think I've done this now. Let me know what you think. I have you and I as both organization owners and on the team with commit privileges, and then the others on a team without commit privileges.

**Comment by rmcgibbo** [comment]
If I took commit privileges away from anyone that wants them, I can add it back.

**Comment by mpharrigan** [comment]
Looks good. Some comments

 - What's the purpose of the "members" team? How does it differ from the "members" tab?
 - The commiters team says is has 63 repositories lol

**Comment by rmcgibbo** [comment]
Can people be in the organization, but _not_ part of any team? If so, then there's no purpose for the Members "team".

**Comment by rmcgibbo** [comment]
Add, yes. You can be on zero teams, but still a member of the organization. So I'm going to remove the "Members" team then.

**Comment by rmcgibbo** [comment]
Okay, done now.
