### ISSUE TITLE
Is there a way to load  a part of trajectory? or lazy loading?

### ISSUE THREAD

**Issue by lambdalisue** [mdtraj/mdtraj#1034]
I noticed that `md.load()` takes times more than I expected. I only need a part of trajectory so I wrote a  code something like:

```python
# It seems md.load() loads everything so takes long time
t = md.load(netcdf, top=prmtop)
distances = md.compute_distances(t[1000:2000], atoms_pair)

# It returns a generator so not subscriptable but I just need coordinates from 1000
# so I don't want to iterate over until 1000.
t = md.iterload(netcdf, top=prmtop)
distances = md.compute_distance(t[1000:2000], atoms_pair)
# => 'generator' object is not subscriptable
```

But it seems that `md.load()` load everything first. **So I wonder if there is a way to load a part of trajectory or perform some lazy loading within MDTraj** (not by making a copy of trajectory file by using other software.)

Additionally, I'm not sure if I could but if I made a PR for a lazy loading (such as load fundamental informations like topology or nframes and load coordinates whenever the users access to `trajectory.xyz` attribute first time)  are you interested in?
I personally use netcdf for Amber so even I could, I'll make only the one for that though.

**Comment by rmcgibbo** [comment]
There is a function called `md.iterload`, which might service your purposes. There is an example of one way to use it here: http://mdtraj.org/latest/examples/iterload.html. There is also the function `md.open`, which will open the underlying trajectory file object, which is a file-like object for accessing the trajectory. 

One of the reasons that there isn't exactly a complete lazily-loaded trajectory object is that for most trajectory files, you can't do a random `seek` to a given frame in the trajectory on `O(1)` time, so the APIs exposed by the low-level classes like `md.NetCDFTrajectoryFile`, `md.DCDTrajectoryFile`, etc, doesn't give random access, but instead gives sequential access with `.read()`, `.seek()`, `.tell()`, etc.

**Comment by lambdalisue** [comment]
> One of the reasons that there isn't exactly a complete lazily-loaded trajectory object is that for most trajectory files, you can't do a random seek to a given frame in the trajectory on O(1) time, so the APIs exposed by the low-level classes like md.NetCDFTrajectoryFile, md.DCDTrajectoryFile, etc, doesn't give random access, but instead gives sequential access with .read(), .seek(), .tell(), etc.

Then, I'm wondering why you don't use `f.seek()` to skip parsing unwilling part of the trajectory in the core part of MDTraj.

I read the code and tried the following code and [**I got extreme improvement (1.5788 -> 0.0758)**](https://gist.github.com/lambdalisue/b803b19790279d648aaa#file-[quickrun%20output]) so I wonder if `trajectory.xyz` returns a pseudo iterator which does lazy loading things.

Or the coordinates what I got is completely wrong? (I couldn't be bothered to verify).

```python
import mdtraj as md

prmtop = 'alanine.prmtop'
netcdf = 'alanine.nc'

START  = 10000
STOP   = 20000
STRIDE = 100

def slice_after_load():
    t = md.load(netcdf, top=prmtop)
    t = t[START:STOP:STRIDE]
    print(t)

def slice_before_load():
    topology = md.load_topology(prmtop)
    with md.open(netcdf) as f:
        f.seek(START)
        t = f.read_as_traj(
            topology, n_frames=STOP-START, stride=STRIDE
        )
        print(t)
```

**Comment by lambdalisue** [comment]
It would be nice if there is something like `mdtraj.load_partial(filename, start=None, stop=None, stride=None, **kwargs)` if my code is correct and making a lazy loading mechanisms in current MDTraj is too tough job to do right now ;-)

**Comment by rmcgibbo** [comment]
It looks like you found a way to get good performance with `md.open`, which I'm glad to see. I guess in principle there could be more functions like `load_partial`, but I'm also concerned always about the added complexity of duplicative APIs.

Our design goals have always been to have easy high-level APIs like `md.load`, in addition to more flexible low-level building blocks like `md.open` and the >10 `[XXX]TrajectoryFile` objects that provide format-specific behavior and methods like `.read()` and `.seek()`. It looks like you've been able to use those building blocks for your application with `slice_before_load`, so that's great.

**Comment by lambdalisue** [comment]
Ok. Thnaks for leading me a correct direction ;-)

**Comment by rmcgibbo** [comment]
No problem. :-)
