### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by clonker** [mdtraj/mdtraj#1036]
In commit ee45a28a04bbb4ab53c06bca79f006c44895d5f6 you removed the "always" deprecation filter from the filter list but haven't released that change yet. In order to deal with issue markovmodel/PyEMMA#683, could you please release an updated version of mdtraj?

**Comment by rmcgibbo** [comment]
We are planning to make a release soon.

**Comment by marscher** [comment]
This can be closed IMHO, since it is on every bodies radar.
