### ISSUE TITLE
Make coding guidelines / style guidline less aggressive in tone

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#1046]
The tone is a little confrontational. It would be nice to have something to link to on pull requests from new contributors.

(the guidelines should still be aggressive in terms of good style)

**Comment by mpharrigan** [comment]
reference: http://mdtraj.org/1.6.1/style.html

**Comment by cxhernandez** [comment]
also just noticed a typo: ["line too ling"](https://github.com/mdtraj/mdtraj/blob/master/docs/style.rst#L14)

**Comment by mpharrigan** [comment]
More or less addressed in #1075
