### ISSUE TITLE
`mdtraj.Topology.from_openmm` fails due to missing `residue.segment_id`

### ISSUE THREAD

**Issue by jhprinz** [mdtraj/mdtraj#1047]
I recently updated mdtraj, openmm and openmmtolls to
```
mdtraj                    1.6.1               np110py27_0
openmm                    6.3.1                    py27_1
openmmtools               0.7.5                    py27_1
```
and when trying to convert a Topology from a testsystem to mdtraj Topology I get the following error

```py
import openmmtools as omt
import mdtraj as md
testsystem = omt.testsystems.AlanineDipeptideVacuum()
print testsystem.topology
>>> <Topology; 1 chains, 3 residues, 22 atoms, 21 bonds>

md.Topology.from_openmm(testsystem.topology)
```

resulting in

```py
    370             c = out.add_chain()
    371             for residue in chain.residues():
--> 372                 r = out.add_residue(residue.name, c, residue.segment_id)
    373                 for atom in residue.atoms():
    374                     if atom.element is None:

AttributeError: 'Residue' object has no attribute 'segment_id'
```

I assume that openmm has changed its Topology object somehow. Will this be fixed with the upcoming openmm 7.0 or should I make PR to quick fix this. 

From what I can tell they renamed `segment_id` to `id`?

**Comment by andrrizzi** [comment]
I can confirm this. I had the same problem and had to downgrade to ``mdtraj 1.5.1``. [This is the commit](https://github.com/mdtraj/mdtraj/commit/c4d43469705f395e21d2a6dc789223f4e0bbc6d3#diff-ce95bbb0db9dbb5dce66ba686ed67f2d) that changed it.

**Comment by jchodera** [comment]
Has this been fixed yet?  Is it safe to upgrade to the latest `mdtraj`?

**Comment by jchodera** [comment]
This is still present in the latest `mdtraj`:
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L351-L372
```python
    @classmethod
    def from_openmm(cls, value):
        """Create a mdtraj topology from an OpenMM topology
        Parameters
        ----------
        value : simtk.openmm.app.Topology
            An OpenMM topology that you wish to convert to a
            mdtraj topology.
        """
        app = import_('simtk.openmm.app')

        if not isinstance(value, app.Topology):
            raise TypeError('value must be an OpenMM Topology. '
                            'You supplied a %s' % type(value))

        out = cls()
        atom_mapping = {}

        for chain in value.chains():
            c = out.add_chain()
            for residue in chain.residues():
                r = out.add_residue(residue.name, c, residue.segment_id)
```
There is no `segment_id` referenced anywhere in OpenMM's `Topology.Residue` object:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/topology.py#L353-L365
```python
class Residue(object):
    """A Residue object represents a residue within a Topology."""
    def __init__(self, name, index, chain, id):
        """Construct a new Residue.  You should call addResidue() on the Topology instead of calling this directly."""
        ## The name of the Residue
        self.name = name
        ## The index of the Residue within its Topology
        self.index = index
        ## The Chain this Residue belongs to
        self.chain = chain
        ## A user defined identifier for this Residue
        self.id = id
        self._atoms = []
```
Can we get someone to fix this?  Pretty please?

**Comment by mpharrigan** [comment]
@jchodera you are more than welcome to help. Please see the relevant pr at #1048

**Comment by jchodera** [comment]
I'm not sure I can be of help, since
1. I have *absolutely no idea* what MDTraj intends `segment_id` to mean, and 
2. There was *never* a `segment_id` in the OpenMM `Topology` object to my knowledge

I think what is needed is for someone to simply reverse the `mdtraj` commit https://github.com/mdtraj/mdtraj/commit/c4d43469705f395e21d2a6dc789223f4e0bbc6d3#diff-ce95bbb0db9dbb5dce66ba686ed67f2d (how did this even get merged?) and then try to fix whatever that breaks.

**Comment by jchodera** [comment]
Who committed https://github.com/mdtraj/mdtraj/commit/c4d43469705f395e21d2a6dc789223f4e0bbc6d3?  Who is @hockyg?

**Comment by jchodera** [comment]
cc https://github.com/mdtraj/mdtraj/pull/1087

**Comment by rmcgibbo** [comment]
I think there's quite a bit of discussion of the purpose of the addition of segment_id in the original PR that added the feature.

**Comment by jchodera** [comment]
Is this it?

https://github.com/mdtraj/mdtraj/pull/1002

**Comment by rmcgibbo** [comment]
Yes

**Comment by jchodera** [comment]
Thanks---I hadn't seen that previously.

What's the correct behavior when interoperating with OpenMM `Topology` objects? Setting `segment_id` to be empty? Something is mentioned in #1002 about raising a warning---is that essential?

**Comment by rmcgibbo** [comment]
Setting it empty would be fine.

**Comment by mpharrigan** [comment]
Again, this is all discussed in the PR i referenced, #1048
