### ISSUE TITLE
Support for extreme box shapes

### ISSUE THREAD

**Issue by peastman** [mdtraj/mdtraj#1066]
I'm looking into rewriting the SSE based geometry code (see #1010).  I notice that the calculation for triclinic boxes is done in a very expensive way, many times slower than what's done in OpenMM (or in the neighborlist code I wrote for mdtraj).  The reason it's doing that is to support periodic boxes with extremely sharp angles.  But it still doesn't fully do that, because it assumes the nearest copy will be in one of the 27 adjacent boxes.  When the angles get extreme enough, that isn't guaranteed to be true.

So we have three options for how to do this calculation:

1. The method used in OpenMM.  It's fast and works for all typical boxes shapes, but can fail in extreme cases.

2. The method currently implemented in `compute_distances()`.  It's much much slower.  It works for some cases that method 1 fails on, but still fails on others.

3. Write something that's guaranteed to always find the correct result no matter the box shape, but might be even slower.

Which one of these do we want to do?  And if we pick either 1 or 2, we should add error checking to detect boxes that won't work correctly.

**Comment by cxhernandez** [comment]
Would it be possible to implement something that does method 1 if the box is standard and falls back on method 3 if it's something more exotic?

**Comment by peastman** [comment]
Yes, it's a possibility.

**Comment by rmcgibbo** [comment]
As long as we detect whether the box shape is extreme and give the right
error message instead of an incorrect solution and no common MD codes
actually use these extremely skewed boxes, then I support getting rid of it.

**Comment by swails** [comment]
What does OpenMM do?  I know there are fast methods you can use when running MD that won't work in the general case.  The original code (less the transposed inverse matrix) was sufficient for implementing MIC dynamics, but was only *guaranteed* to work for particles with at least one image within the maximum allowable cutoff.  Any particle whose closest image lies outside that range may, or may not, give the true minimum distance under those conditions.  That's why random atom-atom distances in a truncated octahedron was only correct ~75% of the time (and why I added code to loop over the 26 adjacent unit cells).  I *think* that is the code OpenMM uses, but @peastman can correct me if I'm wrong.

I agree with @rmcgibbo's assessment.

**Comment by peastman** [comment]
OpenMM uses the method given by equations 3.13 to 3.16 in the Gromacs manual.  It uses just a single line to subtract off the appropriate multiple of each box vector.  And it *claims* that as long as the requirements on the box vectors (equations 3.1 to 3.3) are satisfied, that will always be correct.

But they're wrong.  For example, here's a situation that came up in the test case.  The box vectors are:

```Python
a = Vec3(2.47163, 0, 0)
b = Vec3(-0.274939, 2.37699, 0)
c = Vec3(-0.470959, 0.538556, 0.355995)
```

Those satisfy all of the requirements.  And the displacement is

```Python
r0 = Vec3(2.19471, -1.09768, 0.388986)
```

After applying the rules to apply periodic boundary conditions, the new displacement is

```Python
r1 = Vec3(-0.0809009, 0.740755, 0.0329911)
```

That isn't actually the nearest copy:

```Python
>>> norm(r1)
0.7458896287823154
>>> r1-c
(0.3900581, 0.20219900000000002, -0.3230039)
>>> norm(r1-c)
0.5453084231806987
```

Subtracting off box vector c does make the z component larger, but the vector as a whole becomes smaller.  I'm still working out exactly what combination of conditions make that possible.  It's clearly related to the fact that `c[1] > c[2]`.

**Comment by peastman** [comment]
I *think* the actual restriction that's being violated in this case is `1.5*c[2] > 0.5*b[1]-abs(c[1])`.

**Comment by peastman** [comment]
No, there must be more to it than that.  For a rectangular box, there's no restriction on the relative sizes of `b[1]` and `c[2]`.

**Comment by peastman** [comment]
Ok, I think I see what's going on.  The calculation in the Gromacs manual works if and only if you are applying a cutoff, and that cutoff is less than half the smallest size of the box.

You can see that in the example above.  r1 has the smallest z displacement of any periodic copy.  When we add c to it, that's guaranteed to push it outside the cutoff: `abs(r1[2]+c[2]) > c[2]/2)`.  It also happens to make the overall distance shorter.  So r1 isn't guaranteed to be the nearest periodic copy.  But it is guaranteed that, if it isn't, then *no* periodic copy is within the cutoff distance.

So as far as `compute_neighborlist()` is concerned, the fast calculation is fine (but I should add code to it to make sure the box vectors are in reduced form).  But for `compute_distances()`, we need to do a more thorough check.

**Comment by swails** [comment]
> On Mar 10, 2016, at 4:48 PM, peastman <notifications@github.com> wrote:
> 
> Ok, I think I see what's going on. The calculation in the Gromacs manual works if and only if you are applying a cutoff, and that cutoff is less than half the smallest size of the box.
> 

Exactly :). That's what I meant when I said you could make assumptions in MD that don't always hold for simple minimum image distances. Any particle that lies outside the maximum allowable cutoff for MIC MD is not guaranteed to give the closest image using those equations for non-orthorhombic cells.

**Comment by peastman** [comment]
I changed it to do the calculation described above, but then check all of the 27 periodic copies closest to r1.  I'm still getting test failures, but now it's always because the reference Python code isn't finding the closest copy.  So I'll modify that to also work this way.

**Comment by peastman** [comment]
Closing this, since I think we have an answer.
