### ISSUE TITLE
WebGL widget throws SSL error

### ISSUE THREAD

**Issue by marcinofulus** [mdtraj/mdtraj#1068]
Hi,

I have problem displaying webGL widget when running jupyterhub over ssl connection.
Namely I get:
https://lab.jakiestfu.com/contextjs/context.standalone.css net::ERR_SSL_PROTOCOL_ERROR

the best
Marcin

**Comment by cxhernandez** [comment]
Thanks for reporting this @marcinofulus! It seems that https://lab.jakiestfu.com is down. One temporary solution might be to copy [context.standalone.js](https://github.com/jakiestfu/Context.js/blob/master/context.standalone.css) into the appropriate directory within your `nbextensions` directory (e.g. `~/.ipython/nbextensions/`).

 We're currently transitioning towards using [nglview](https://github.com/arose/nglview) (see https://github.com/mdtraj/mdtraj/issues/1022), so hopefully these issues will go away soon!
