### ISSUE TITLE
Single Atom RMSD

### ISSUE THREAD

**Issue by ParkerdeWaal** [mdtraj/mdtraj#1071]
Hi MDTraj,

I've encounter an error where MDTraj outputs incorrect RMSD values when performing the calculation on a single residue.

ex: 
`md.rmsd(aliTMD, aliTMD, frame = 0, atom_indices = aliTMD.top.select('resSeq 237 and backbone'), precentered=True)`

When performing an RMSD calculation for the core of the protein ('resSeq 35 to 310 and backbone') the results match VMD almost perfectly. yet for single atom RMSD the results are nothing close to the expected values.

If anyone could assist with this I would greatly appreciate it!

Cheers,
Parker

**Comment by rmcgibbo** [comment]
mdtraj will use the atom_indices you supply both for optimally aligning the
two frames and for computing the deviation. Perhaps your intent was to use
all of the atoms for the alignment/superposition, and only the specified
atoms for the distance calculation?

On Mon, Mar 14, 2016 at 8:00 PM, Parker de Waal <notifications@github.com>
wrote:

> Hi MDTraj,
>
> I've encounter an error where MDTraj outputs incorrect RMSD values when
> performing the calculation on a single residue.
>
> ex:
> md.rmsd(aliTMD, aliTMD, frame = 0, atom_indices =
> aliTMD.top.select('resSeq 237 and backbone'), precentered=True)
>
> When performing an RMSD calculation for the core of the protein ('resSeq
> 35 to 310 and backbone') the results match VMD almost perfectly. yet for
> single atom RMSD the results are nothing close to the expected values.
>
> If anyone could assist with this I would greatly appreciate it!
>
> Cheers,
> Parker
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mdtraj/mdtraj/issues/1071
>



-- 
-Robert
