### ISSUE TITLE
Possible regression with len(xtc_file)

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#1078]
I'm noticing some issues with the new xtc code #1038 

1. Just getting the length is slower than it used to be. It spends some time making the index rather than just telling you the length
2. Seems to fail on small number of frames

I'm going to write little test cases for both of these, because they're just conjecture at this point

**Comment by mpharrigan** [comment]
```python
import mdtraj as md
import numpy as np
from subprocess import call

with md.formats.XTCTrajectoryFile('smalltraj.xtc', 'w') as xtc:
    xtc.write(np.random.uniform(size=(5, 100000, 3)))

call(['ls', '-lh', 'smalltraj.xtc'])

f = md.open('smalltraj.xtc')
print(len(f))
```

```
$ python smallfile.py 
-rw-r--r-- 1 harrigan harrigan 1.9M Mar 22 14:51 smalltraj.xtc
Traceback (most recent call last):
  File "smallfile.py", line 11, in <module>
    print(len(f))
  File "mdtraj/formats/xtc/xtc.pyx", line 698, in xtc.XTCTrajectoryFile.__len__ (mdtraj/formats/xtc/xtc.c:10331)
  File "mdtraj/formats/xtc/xtc.pyx", line 675, in xtc.XTCTrajectoryFile.offsets (mdtraj/formats/xtc/xtc.c:9884)
  File "mdtraj/formats/xtc/xtc.pyx", line 649, in xtc.XTCTrajectoryFile._calc_len_and_offsets (mdtraj/formats/xtc/xtc.c:9560)
IndexError: Out of bounds on buffer access (axis 0)
```

**Comment by mpharrigan** [comment]
I can't reproduce (1) in a test environment. I suspect something somewhere is being clever and caching the files

**Comment by marscher** [comment]
Well maybe just one line of code needs to be adopted to really fix this. Please hold on

**Comment by marscher** [comment]
Just a comment to (1). The old code used to interpret all atom coordinates for every frame just to obtain the length, however the new code just reads one integer from a frame ignoring how many atoms there are. So do you really believe this could be any slower?

**Comment by marscher** [comment]
The error is caused by a simple rounding error during increasing the size of the offsets array. I'll prepare a PR.

**Comment by mpharrigan** [comment]
Ok, your comments on (1) have sold me on that as well
