### ISSUE TITLE
Short END lines in PDB output

### ISSUE THREAD

**Issue by salotz** [mdtraj/mdtraj#1082]
I found that OpenBabel requires all lines in a PDB to be at least 6 characters long or it won't read them (https://github.com/openbabel/openbabel/blob/e3db4783155e05e20ab6c9cd92407b53a9650e16/src/formats/pdbformat.cpp#L173). The pdb output seems to leave lines like 'END' with only 3 characters, making it annoying to use them with anything that use the openbabel reader. If I simply add a few spaces it works. I noticed that in rcsb pdbs the whole line is also padded with whitespace if it is short.

Would it be possible to change this to padding short lines like 'END' with spaces? 

Would be very easy and at least more consistent as I am guessing there is probably a good reason to have that requirement over at openbabel and rcsb.

**Comment by mpharrigan** [comment]
This is probably important for fast seeking in pdb files, if you can assume each line is 80 characters

**Comment by salotz** [comment]
It only requires that it be 6 characters long in the code.
