### ISSUE TITLE
RMSD nofit

### ISSUE THREAD

**Issue by ParkerdeWaal** [mdtraj/mdtraj#1083]
Hello MDTraj,

I'm currently porting all of my VMD .tcl scripts to MDtraj and noticed a discrepancy between RMSD calculations.

It appears that the following code realigns the trajectory on the selected atoms before calculating the RMSD:

```
        H8rmsd = md.rmsd(ali,r, frame = 0, atom_indices = t.topology.select('resSeq 311 to 322 and backbone'), precentered = True)
```

Can this feature be disabled? Similar to a rmsd_nofit option?

Cheers,
Parker

**Comment by cxhernandez** [comment]
This may be of interest: https://github.com/mdtraj/mdtraj/issues/523#issuecomment-98582886
