### ISSUE TITLE
Custom anchor_molecules for traj.image_molecules

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1086]
Is there a way to use MDTraj to reimage a trajectory inside a periodic box so that all molecules are wrapped to be the minimum-image distance from a given atom selection?

**Comment by mpharrigan** [comment]
You need the development release as it was recently added, but yes

http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules

**Comment by jchodera** [comment]
Thanks!  

From the docs:
>  It tries to be intelligent in deciding what molecules to center, so you can simply call it and trust that it will “do the right thing”.

Is there a way to specify what molecule should be at the "center" of the box via an optional selection argument?

**Comment by mpharrigan** [comment]
Not currently, but PRs welcome

**Comment by mpharrigan** [comment]
(It should be straightforward)

**Comment by jchodera** [comment]
How about we just expose `anchor_molecules` as an optional argument in [`image_molecules`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L1823)?  If specified by the user, this is used instead of the automatically-selected one.

**Comment by mpharrigan** [comment]
Yup! That's what I was thinking

**Comment by mpharrigan** [comment]
and maybe refactor the guessing logic into its own function
