### ISSUE TITLE
Cut bugfix release?

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1098]
Since there is no longer an active `mdtraj-dev`, could you cut a release now that #1089 has fixed the `segment_id`-induced incompatibilities with OpenMM?

Thanks!

**Comment by jchodera** [comment]
Bumping this again. Can we get you guys to cut a bugfix release now that #1089 has been fixed?

**Comment by rmcgibbo** [comment]
Unless other core-devs feel strongly, I don't think we'll do a bugfix release for a single PR. We should probably get the Appveyor build working again and then merge a couple of the outstanding PRs, and then cut a release from master.

This is the list of PRs merged since 1.6
```
$ gh-util list-prs mdtraj/mdtraj
Listing merged PRs since: MDTraj 1.6

PR #1093: Add Depsy badge
PR #1076: Update writing version.py
PR #1089: Fix segment_id issues take 3
PR #1085: [xtc] fix error status report during xdr_seek
PR #1077: Rewrote SSE geometry code
PR #1080: [xtc] fix a bug in calc of offsets array for short trajs.
PR #1075: Edits to documentation
PR #1074: Fixes for doc rework
PR #1067: Port doc building and deployment maintenence from msmbuilder
PR #1072: [compute_contacs] new opt arg periodic=True
PR #1058: [WIP] Created function for imaging molecules
PR #1064: Fix typo Sccessible -> Accessible
PR #1063: added hdf5 to list of top exists
PR #1062: Update whatsnew.rst
PR #1061: [load_pdb] new optional argument standard_names
PR #1059: Update gitignores
PR #1057: Created compute_neighborlist() function
PR #1051: Allow doc deployment on other branches
PR #1053: Fix clustering example
PR #1050: Fix example notebooks
PR #1044: Fix `update-versions.py`
```

**Comment by jchodera** [comment]
The need here is that OpenMM and MDTraj have been non-interoperable since 1.6.  All of our projects are still pinned to 1.5.1 because of the `segment_id` bug that was introduced prior to the 1.6 release, and you guys got rid of the `mdtraj-dev` builds because MDTraj was "stable".  

There have been two point-bugfix releases since 1.6.0, with two of them four days apart.  The last point bugfix release was two months ago at this point.  So it doesn't seem like a point bugfix to address a major OpenMM incompatibility issue would be unreasonable given the history of point bugfix releases for 1.6.

**Comment by jchodera** [comment]
I have no opinion on whether you backport #1089 into 1.6.2 or cut a new release from master, however.

**Comment by rmcgibbo** [comment]
Right. I understand where you're coming from; I'm just trying to think what makes the most sense for maximizing our ROI.

**Comment by jchodera** [comment]
Re-enabling `mdtraj-dev` would probably also work for us---at least for development/testing until you get a new release out---if that is easier.

**Comment by mpharrigan** [comment]
I agree we should get the codebase ship-shape and release a full release. I'll start tagging release blockers with the 1.7 milestone and move everything else to 1.8 or wishlist as appropriate

**Comment by rmcgibbo** [comment]
Good call @mpharrigan.
