### ISSUE TITLE
selection_string parameter for load()

### ISSUE THREAD

**Issue by mdimura** [mdtraj/mdtraj#1103]
At the moment, if user wants to load only certain atoms from the trajectory, two step procedure is needed. Either first loading the whole trajectory and then slicing:

```
traj=md.load('traj.h5')
idxs=traj.topology.select('protein')
traj.atom_slice(idxs,True)
```

or first loading first frame/topology, obtaining atom_indices, and then loading: `

```
frame=md.load_frame('traj.h5',0)
idxs=frame.topology.select('protein')
traj=md.load('traj.h5',atom_indices=idxs)
```

It would be very convenient if one could simply type 
`traj=md.load('traj.h5',selection_string='protein')`

**Comment by Burning-Daylight** [comment]
@hainm I updated original text so that it reflects the issue better.

**Comment by hainm** [comment]
yeah, it's reasonable request. (disclaimer: I am mdtraj dev).

could be
```python
traj=md.load('traj.h5', selection='protein')
```

**Comment by mpharrigan** [comment]
I'm not so sure about this idea. Running an atom selection requires loading the topology and doing logic on it. mdtraj usually promotes a simple api which leans on composability

The specific case you outlined may be a worst case since the `h5` format has both the trajectory and topology. I personally like having the logic separate so you can easily do more fancy things like 

```python
top = md.load_prmtop("mytopology.prmtop")
inds = top.select("protein")
np.save(inds, 'cache-these.npy') # for example
traj = md.load("traj.nc", top=top)
```

**Comment by Burning-Daylight** [comment]
@mpharrigan Of course, one should be able to do things explicitly, but in many cases atom_indexes do not contain any valuable information on their own and an _additional_ concise interface for load() could be helpful. Sometimes, one would want to load multiple similar but not-identical trajectories (with different number of water molecules, for example) and join them `selection_sting` would be a helpful option than.

**Comment by mpharrigan** [comment]
Ok, I'm warming to the feature
