### ISSUE TITLE
[core.trajectory] Substraction method 

### ISSUE THREAD

**Issue by ag1989** [mdtraj/mdtraj#1110]
Hello everybody, 

due to a typo I recognized that the trajectory object shows a not so nice behavior if one accidentally subtracts an numpy array. If you do so, the code is very slow and a not experienced user might not recognize this as a typo in the first instance. Looking into the mdtraj source code, I saw that there seems to be no explicit definition of the subtraction method (hope I didn't miss it). So the Trajectory object uses the default python object method. Therefore I would like to propose two different solutions:
1. Raise an error 
2. Define a subtraction method for trajectories and raise error for np.arrays.

Honestly the first one is my personal favorite because it is more consistent with the current API. However there are situation where you might want to subtract a mean structure from your trajectory, e.g. when computing fluctuations. In such a case it would make sense to have a call to the compute distance function as long as only a single frame is subtracted or if the trajectory to subtract has the same length as the original one. This would also avoid errors if users are not considering the minimum image convention in their own codes. Furthermore it avoids creation of many intermediate objects during analysis, saving memory and improving code readability.

**Comment by rmcgibbo** [comment]
I'm not really sure what's going on. This might be something more connected to numpy than mdtraj. The `mdtraj.Topology` object does not implement a subtraction method.
