### ISSUE TITLE
DSSP segmentation fault

### ISSUE THREAD

**Issue by stefdoerr** [mdtraj/mdtraj#1120]
Hi, I am trying to use DSSP on some systems but it seems to be segfaulting in roughly 1/10 of them.
If you want you can test it on the attached data
[segfault.zip](https://github.com/mdtraj/mdtraj/files/279275/segfault.zip)

```python
from mdtraj.geometry._geometry import _dssp as dssp
import numpy as np
xyz = np.load('xyz.npy')
nco_indices = np.load('nco_indices.npy')
ca_indices = np.load('ca_indices.npy')
proline_indices = np.load('proline_indices.npy')
chain_ids = np.load('chain_ids.npy')
data = dssp(xyz, nco_indices, ca_indices, proline_indices, chain_ids)
```

**Comment by stefdoerr** [comment]
Here is a PDB that causes a segfault if you want a whole PDB instead of just the arguments 
[1afo.zip](https://github.com/mdtraj/mdtraj/files/279556/1afo.zip)

**Comment by peastman** [comment]
Thanks!  I can reproduce the problem.  I'm investigating now.

**Comment by peastman** [comment]
Your `nco_indices` array is the wrong size.  Its shape is (36, 3), indicating there are 36 residues.  But all the other arrays have length 72, indicating 72 residues.

How did you create these arrays?  I tried loading your PDB file and calling `_prep_kabsch_sander_arrays()` on it, but that produces much larger arrays (and they're all consistent with each other).

**Comment by stefdoerr** [comment]
Oh yes you are absolutely right. Sorry for the false alarm. It's a bit hard to know what goes wrong when you only get a segfault :)
I was producing the arrays myself but I was not taking into account that there can be two chains with the same resids, so my nco array was missing one of the two chains.

Many thanks for the tip!

**Comment by peastman** [comment]
Even though this is an internal API, it would still be useful if it did error checking to catch this problem.  Better than a segfault!
