### ISSUE TITLE
shrake_rupley method fails for dinucleotide system

### ISSUE THREAD

**Issue by pgromano** [mdtraj/mdtraj#1121]
I'm unable to calculate the SASA for a small dinucleotide construct. I've tried for both mode='atom' and 'residue'. It looks like it's unable to get an atomic radius in either case. I've attached the .gro file I'm using, as it has residue names different from the format in most proteins. I've tried changing the residue names from DA5 --> DA --> A, but the same error persists. 

```
In [3]: trj = md.load('ApA.xtc', top='ApA.gro')

In [4]: sasa = md.shrake_rupley(trj, mode='residue')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-f78fa92c2752> in <module>()
----> 1 sasa = md.shrake_rupley(trj, mode='residue')

//anaconda/lib/python3.5/site-packages/mdtraj/geometry/sasa.py in shrake_rupley(traj, probe_radius, n_sphere_points, mode)
    120
    121     out = np.zeros((xyz.shape[0], dim1), dtype=np.float32)
--> 122     atom_radii = [_ATOMIC_RADII[atom.element.symbol] for atom in traj.topology.atoms]
    123     radii = np.array(atom_radii, np.float32) + probe_radius
    124

//anaconda/lib/python3.5/site-packages/mdtraj/geometry/sasa.py in <listcomp>(.0)
    120
    121     out = np.zeros((xyz.shape[0], dim1), dtype=np.float32)
--> 122     atom_radii = [_ATOMIC_RADII[atom.element.symbol] for atom in traj.topology.atoms]
    123     radii = np.array(atom_radii, np.float32) + probe_radius
    124

KeyError: 'VS'
```

[ApA.gro.zip](https://github.com/mdtraj/mdtraj/files/282604/ApA.gro.zip)

**Comment by rmcgibbo** [comment]
Looks like when your system is loaded, one of the elements has the symbol "VS", which is not in the periodic table or something we have radii for. Presumably this is due to the elements being parsed incorrectly when your file is loaded.

**Comment by pgromano** [comment]
Is there a way I can check where it's trying to parse "VS"? It doesn't look like there is any "VS" element in top.atoms.

```
In [38]: print(np.array([atom for atom in trj.top.atoms]).T)

[DA51-O5' DA51-H5T DA51-C5' DA51-H5'1 DA51-H5'2 DA51-C4' DA51-H4' DA51-O4'
 DA51-C1' DA51-H1' DA51-N9 DA51-C8 DA51-H8 DA51-N7 DA51-C5 DA51-C6 DA51-N6
 DA51-H61 DA51-H62 DA51-N1 DA51-C2 DA51-H2 DA51-N3 DA51-C4 DA51-C3'
 DA51-H3' DA51-C2' DA51-H2'1 DA51-H2'2 DA51-O3' DA32-P DA32-O1P DA32-O2P
 DA32-O5' DA32-C5' DA32-H5'1 DA32-H5'2 DA32-C4' DA32-H4' DA32-O4' DA32-C1'
 DA32-H1' DA32-N9 DA32-C8 DA32-H8 DA32-N7 DA32-C5 DA32-C6 DA32-N6 DA32-H61
 DA32-H62 DA32-N1 DA32-C2 DA32-H2 DA32-N3 DA32-C4 DA32-C3' DA32-H3'
 DA32-C2' DA32-H2'1 DA32-H2'2 DA32-O3' DA32-H3T]
```

**Comment by rmcgibbo** [comment]
Check `atom.element.symbol`

**Comment by ctk3b** [comment]
There is probably an atom that the .gro reader couldn't identify as an element and just assigned as a virtual site: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/gro.py#L316

**Comment by pgromano** [comment]
Yep, it looks like all atoms within the ribose sugar (labelled with ' or * in Amber99+parmbsc0) get read as virtual sites. 

```
In [63]: print(np.array([[atom, atom.element.symbol] for atom in trj.top.atoms]))[[DA51-O5' 'VS']
 [DA51-H5T 'H']
 [DA51-C5' 'VS']
 [DA51-H5'1 'VS']
 [DA51-H5'2 'VS']
 [DA51-C4' 'VS']
 [DA51-H4' 'VS']
 [DA51-O4' 'VS']
 [DA51-C1* 'VS']
 [DA51-H1' 'VS']
 [DA51-N9 'N']
 [DA51-C8 'C']
 [DA51-H8 'H']
 [DA51-N7 'N']
 [DA51-C5 'C']
 [DA51-C6 'C']
 [DA51-N6 'N']
 [DA51-H61 'H']
 [DA51-H62 'H']
 [DA51-N1 'N']
 [DA51-C2 'C']
 [DA51-H2 'H']
 [DA51-N3 'N']
 [DA51-C4 'C']
 [DA51-C3' 'VS']
 [DA51-H3' 'VS']
 [DA51-C2' 'VS']
 [DA51-H2'1 'VS']
 [DA51-H2'2 'VS']
 [DA51-O3' 'VS']
 [DA32-P 'P']
 [DA32-O1P 'O']
 [DA32-O2P 'O']
 [DA32-O5' 'VS']
 [DA32-C5' 'VS']
 [DA32-H5'1 'VS']
 [DA32-H5'2 'VS']
 [DA32-C4' 'VS']
 [DA32-H4' 'VS']
 [DA32-O4' 'VS']
 [DA32-C1' 'VS']
 [DA32-H1' 'VS']
 [DA32-N9 'N']
 [DA32-C8 'C']
 [DA32-H8 'H']
 [DA32-N7 'N']
 [DA32-C5 'C']
 [DA32-C6 'C']
 [DA32-N6 'N']
 [DA32-H61 'H']
 [DA32-H62 'H']
 [DA32-N1 'N']
 [DA32-C2 'C']
 [DA32-H2 'H']
 [DA32-N3 'N']
 [DA32-C4 'C']
 [DA32-C3' 'VS']
 [DA32-H3' 'VS']
 [DA32-C2' 'VS']
 [DA32-H2'1 'VS']
 [DA32-H2'2 'VS']
 [DA32-O3' 'VS']
 [DA32-H3T 'H']]
```

**Comment by ctk3b** [comment]
Might be worth improving the element identification a little bit. It looks like [ParmEd's](https://github.com/ParmEd/ParmEd/blob/9719218232a9b4bd5b8616efbcfbe030da247e57/parmed/periodic_table.py#L263) should be able to handle those atom names. Do you think that's general/robust enough, @rmcgibbo?

**Comment by rmcgibbo** [comment]
Yeah, that sounds great. I don't think most of the developers have worked with nucleic acids much, so perhaps it's not surprising that the code is a little rough around the edges in that respect.

**Comment by pgromano** [comment]
I can get around the issue by replacing the apostrophes/stars in the ribose sugar atoms with a new numbering (eg **C4'** --> **C40**). In general, it would be awesome if there was a better element identification for the strange characters the nucleic acids field has decided to adopt. I have to process name searches with raw/literal strings. These are all paper cuts, but it could save some new coders the grief of dealing with regular expressions.

```
In [199]: atoms = ["C4", "C5", "C4'", "C5'"]
In [200]: [trj.top.select('name == '+"%r"%atom) for atom in atoms]
```

**Comment by ctk3b** [comment]
Sorry, only just got around to looking at this again. We've had discussions about element name guessing a few times before: #909, https://github.com/ParmEd/ParmEd/pull/562. The general consensus in those discussions was that blindly moving to guessing behavior is probably not a good idea for formats that aren't primarily used for one specific type of molecule (e.g. proteins).

What do you think about creating a separate function like `guess_by_name` and provide an optional flag in readers to guess names?

**Comment by pgromano** [comment]
That would be a great implementation. Currently for nucleic acids, the name guessing results in some weird artifacts like read termination from asterisks or apostrophes, improper residue numbering from numbers in residue names (DX5 or DX3 for terminal ends).

**Comment by peastman** [comment]
PDBTrajectoryFile already has a private method `_guess_element()` that tries to guess the element based on the atom name, residue name, and number of atoms in the residue.  We could possibly move that to somewhere more public.

**Comment by pgromano** [comment]
This may not be easily implemented, but what about some type of function that would allow the user to specify the atom type. The user could supply a dictionary which defines nonstandard atom types and the associated element? Something like calcium would then not be overwritten by the standard alpha carbon.

`atomtype = { "carbon" : ["C1'", "C2'", "C3'", "C4'", "C5'"], "oxygen" : ["O1'", "O2'", "O3'"], "calcium":["Ca"]}`
