### ISSUE TITLE
Protein contact order

### ISSUE THREAD

**Issue by ajasja** [mdtraj/mdtraj#1124]
I recently implemented the calculation of [Contact order](https://en.wikipedia.org/wiki/Contact_order) using MDTraj [here](http://stackoverflow.com/questions/37608906/calculate-protein-contact-order-in-python/37608907#37608907).

Would you be interested in a PR for this?
Is there a better/faster way to do this? I tried using numpy vectorization and compute_distances, but I still could not get rid of the two for loop (and the implementation used a lot of memory and was getting needlessly complex.

**Comment by ajasja** [comment]
Bump; and I will not be offended by a no answer:)
The code does critically rely on Numba though...

**Comment by peastman** [comment]
Sorry, I think everyone must have been waiting for someone else to reply! :)

What about using `compute_neighborlist()`?  That will give you a list of all atom pairs within the cutoff distance.  Then you can just loop over those to build a `set` of all unique residue pairs that have any contacts.  Another option would be to use cython.  With a few cdefs, it should be able to compile that pretty efficiently.

Also, it would be good to make it easy to do the computation on just part of a topology.  For example, if you have explicit solvent, you don't want that to get included in the computation.  (Strictly speaking, I guess contact order is only really defined for a single chain?)
