### ISSUE TITLE
force overwrite =false

### ISSUE THREAD

**Issue by luirink** [mdtraj/mdtraj#1134]
As the code is right now, you cannot save a frame to an existing xtc file, as force overwrite is false will just give an eror if the xtc file already exists. (and i believe this holds for any format)
This would be very useful though. (memory wise for example.)

**Comment by hainm** [comment]
You will cry if your a-month-long-without-backing trajectory is accidentally overwritten.

**Comment by luirink** [comment]
Not overwrite.. Just add. So when you have a trajectory of one frame, and you do save_xtc, you add the frame to the existing one

**Comment by hainm** [comment]
I see.
