### ISSUE TITLE
Pledge to drop support for python 2

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#1138]
See http://python3statement.github.io/

We should make this pledge!

**Comment by mpharrigan** [comment]
(also we could advertise our package)

**Comment by hainm** [comment]
I don't think this is a good idea. Software development in scientific world happens much slower than them. In AMBER we support both python 2 and 3 but still auto install python 2, just because such popular programs like Rosetta or phenix is still using python 2.

**Comment by mpharrigan** [comment]
The pledge is specifically targeted at scientific python.

It's also a pledge to drop support in 2020, which is still 4 years out (although they hope people will do it sooner)

**Comment by ctk3b** [comment]
@hainm I think that's a good point but the pledge isn't particularly drastic:

> we currently accept the cost of writing cross-compatible code to allow a smooth transition, but we don’t intend to maintain this compatibility indefinitely

and 
> our projects plan to stop supporting Python 2 when upstream support ends in 2020

At this point in the game, it's more of a gentle nudge to users to make the switch.
