### ISSUE TITLE
[TNG] interpreter crash when try to open non-existant file

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1141]
```
import mdtraj
mdtraj.formats.TNGTrajectoryFile('does_not_exist.tng', mode='r')

output from gdb:
TNG library: Cannot open file out.tng. mdtraj/formats/tng/src/lib/tng_io.c: 893
TNG library: Cannot open file out.tng. mdtraj/formats/tng/src/lib/tng_io.c: 893

Program received signal SIGSEGV, Segmentation fault.
__GI_ftello (fp=0x0) at ftello.c:39
39      ftello.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_ftello (fp=0x0) at ftello.c:39
#1  0x00007fffe773d753 in tng_num_frames_get (tng_data=0x6bf370, n=n@entry=0x7fffe311ca00) at mdtraj/formats/tng/src/lib/tng_io.c:10270
#2  0x00007fffe770c3c2 in __pyx_pf_3tng_17TNGTrajectoryFile___cinit__ (__pyx_v_kwargs=0x7ffff7ee1848, __pyx_v_force_overwrite=<optimized out>, 
    __pyx_v_mode=<optimized out>, __pyx_v_filename=0x7ffff7e60920 "out.tng", __pyx_v_self=0x7fffe311c9c8) at mdtraj/formats/tng/tng.c:3024
```
Could be an upstream bug, since the "open" call to tnglib returns success...

**Comment by peastman** [comment]
> Could be an upstream bug, since the "open" call to tnglib returns success...

Wouldn't surprise me.  I ran into several bugs in that library in the course of implementing this feature.  Maybe the easiest thing is to just check whether the file exists before asking tnglib to open it?

**Comment by marscher** [comment]
On 12.07.2016 19:09, peastman wrote:
>     Could be an upstream bug, since the "open" call to tnglib returns
>     success...
> 
> Wouldn't surprise me. I ran into several bugs in that library in the
> course of implementing this feature. Maybe the easiest thing is to just
> check whether the file exists before asking tnglib to open it?
Yes that seems like a feasible workaround.
