### ISSUE TITLE
Periodic compute_neighbors() fails for GRO trajectory

### ISSUE THREAD

**Issue by cing** [mdtraj/mdtraj#1142]
Here's a bit of a puzzler in both the 1.6.1 and 1.7.2 releases of mdtraj (i.e. not caused by the new SSE code #1077). This works:
```
import mdtraj
from mdtraj.testing import get_fn
traj = mdtraj.load(get_fn('frame0.pdb'))
query_indices = traj.top.select('residue 1')
value = mdtraj.compute_neighbors(traj, 1.0, query_indices, periodic=True)
```
And this works:
```
import mdtraj
from mdtraj.testing import get_fn
traj = mdtraj.load(get_fn('frame0.gro'))
query_indices = traj.top.select('residue 1')
value = mdtraj.compute_neighbors(traj, 1.0, query_indices, periodic=False)
```
But this doesn't:
```
import mdtraj
from mdtraj.testing import get_fn
traj = mdtraj.load(get_fn('frame0.gro'))
query_indices = traj.top.select('residue 1')
value = mdtraj.compute_neighbors(traj, 1.0, query_indices, periodic=True)
```
Returning this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdtraj/geometry/neighbors.pyx", line 104, in mdtraj.geometry.neighbors.compute_neighbors (mdtraj/geometry/neighbors.cpp:2245)
ValueError: Buffer dtype mismatch, expected 'float' but got 'double'
```
Strangely, this works:
```
import mdtraj
from mdtraj.testing import get_fn
traj = mdtraj.load(get_fn('frame0.gro'))
query_indices = traj.top.select('residue 1')
value = mdtraj.compute_neighbors(traj[0:501], 1.0, query_indices)
```

I'm really not sure how the box vectors got the wrong dtype for this GRO file, they are all 1.0 in length and cubic. For a weirder box, I've encountered the same problem with compute_neighbors() on single frame GRO files in my research. 

The line in question appears to be this one, but the problem probably happens earlier:
https://github.com/mdtraj/mdtraj/blob/7f0836d47d0d18f02fbb0efe5ae71796853f76d5/mdtraj/geometry/neighbors.pyx#L104

**Comment by cing** [comment]
Oh, and I've only tested this on Python 2.7

**Comment by peastman** [comment]
It should be running the box vectors through `ensure_type()`.  It's the function's job to accept whatever dtype is given to it, not the caller's responsibility to give it a particular dtype.
