### ISSUE TITLE
Forums seem to be down

### ISSUE THREAD

**Issue by smsaladi** [mdtraj/mdtraj#1150]
I get a 502 bad gateway error.

Also reports the website is not accessible -- 
http://www.downforeveryoneorjustme.com/discourse.mdtraj.org

**Comment by rmcgibbo** [comment]
Yes. I'll fix it when I get back.

**Comment by mpharrigan** [comment]
Cool

**Comment by rmcgibbo** [comment]
looking at this now. its a VM on the group aws account.

**Comment by rmcgibbo** [comment]
```
ubuntu@ip-172-31-11-182:~$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/xvda1      30824600 30660992         0 100% /
```

**Comment by rmcgibbo** [comment]
I tried,
```
rm /var/discourse/shared/standalone/log/rails/unicorn.stderr.log
cd /var/discourse
sudo ./launcher restart app
```
restarting app through AWS console.

**Comment by rmcgibbo** [comment]
grr...

**Comment by rmcgibbo** [comment]
i'm over my head here.

**Comment by rmcgibbo** [comment]
oh, it looks back up here: http://ec2-54-183-242-174.us-west-1.compute.amazonaws.com/. must just be a dns issue.

**Comment by rmcgibbo** [comment]
okay. dns looks reset now.

**Comment by ctk3b** [comment]
Looks like the forum might be down again. Anyone else able to load it?
