### ISSUE TITLE
KeyError on executing SASA using example code (ver 1.7)

### ISSUE THREAD

**Issue by acnash** [mdtraj/mdtraj#1151]
I took the example code of a SASA from the MDTraj website and placed it into a very short script. 

import mdtraj as md
import numpy as np
from matplotlib.pylab import *
traj = md.load('./WT_LONG/wt_NPT_40ns.trr', top='./WT_LONG/wt_NPT_40ns.gro')
sasa = md.shrake_rupley(traj)
print(traj)
print('sasa data shape', sasa.shape)
total_sasa = sasa.sum(axis=1)
print(total_sasa.shape)

This returns with the error:
`Traceback (most recent call last):
  File "sasa.py", line 11, in <module>
    sasa = md.shrake_rupley(traj)
  File "//anaconda/lib/python2.7/site-packages/mdtraj/geometry/sasa.py", line 124, in shrake_rupley
    atom_radii = [_ATOMIC_RADII[atom.element.symbol] for atom in traj.topology.atoms]
KeyError: 'VS'`

I am using Python 2.7.11 :: Anaconda 4.0.0 (x86_64) and the latest release of MDTraj. I have not modified the MDTraj code and I've found a number of MDTraj functions (distance based) work OK.

**Comment by ctk3b** [comment]
Looks like there are only [a few radii](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/sasa.py#L39) currently supported. The quick fix for you will be to strip all the virtual sites from your trajectory. 

Longer term, it might make sense to add a filtering step that automatically discards virtual sites?

**Comment by andresordorica** [comment]
I had the same problem. I am running the analysis on a UA simulation and added the respective names and radii's to the sasa.py dictionary of the atomic radius. However, I keep getting the same error.
