### ISSUE TITLE
Search function on mdtraj.org not working in any browser

### ISSUE THREAD

**Issue by rafwiewiora** [mdtraj/mdtraj#1152]
Hey guys, 

The search function on mdtraj.org never worked in Safari for me, but at least worked in Chrome - now it doesn't seem to work in Safari, Chrome or Firefox - is constantly stuck on `Searching...`. Not sure if this is a problem on my side or something on yours? If someone could check that'd be awesome, thanks!

**Comment by ostrokach** [comment]
This is a bug in Sphinx: https://github.com/sphinx-doc/sphinx/issues/2296.

**Comment by mpharrigan** [comment]
We can try to remove unicode characters from the docs if they're not important (?)

**Comment by ostrokach** [comment]
I think the errors is caused by the line `blÃ£ Â¼ mel: 10` in `searchindex.js`. Not sure what the original word is.

**Comment by marscher** [comment]
This issue has reappeared again.
