### ISSUE TITLE
Timestamps from DCD files

### ISSUE THREAD

**Issue by smsaladi** [mdtraj/mdtraj#1154]
I posted this [question on the forums ](http://discourse.mdtraj.org/t/timestamps-from-dcd-trajectories/159) about a month ago (though it was down for a little bit #1150), but it doesn't look like the usergroup has thoughts. Might be related to #1148 

I am trying to load two DCD trajectory files from NAMD where one is a continuation of another.

```
traj_files = glob.glob("./itasser_4/itasser_4_autopsf_tip3p_NaCl.prod_tp*.dcd")
print(traj_files)
# In case glob, does not load provide the files in the correct order
traj_files.sort()

t = md.load(traj_files,
           top='./itasser_4/itasser_4_autopsf_tip3p_NaCl.pdb',
           discard_overlapping_frames=True)
print(t)
```

> ['./itasser_4/itasser_4_autopsf_tip3p_NaCl.prod_tp00.dcd', './itasser_4/itasser_4_autopsf_tip3p_NaCl.prod_tp01.dcd']
> < mdtraj.Trajectory with 6575 frames, 16231 atoms, 4956 residues, and unitcells>

However, it looks like the timestamps are not being interpreted correctly --

```
print(t.time)
print(t.time.size)
print(np.unique(t.time).size)
```

> [   0    1    2 ..., 1505 1506 1507]
> 6575
> 5067

Is there something I should be doing such that the timestamps for each frame are correctly read?

**Comment by mpharrigan** [comment]
From looking at the code, mdtraj does *not* load in time information from files. Does `dcd` contain a time field?

**Comment by mpharrigan** [comment]
ref: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/dcd.pyx#L391

**Comment by mpharrigan** [comment]
dcd does not store time information (besides timestep, but it even does that weirdly)

http://www.ks.uiuc.edu/Research/namd/2.9/ug/node11.html

**Comment by smsaladi** [comment]
Might not be interpreting this correctly, but I think the format stores the first step "step 1", step interval, and timestep:

http://www.ks.uiuc.edu/Research/vmd/plugins/molfile/dcdplugin.html

**Comment by mpharrigan** [comment]
Ah, I see. As written it looks like mdtraj doesn't read that info for dcd

**Comment by mpharrigan** [comment]
I think implementing this would be a matter of allocating a time array and reading `self.timestep.physical_time` for each frame in this loop

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/dcd.pyx#L462

**Comment by smsaladi** [comment]
I tried implementing this in a fork, but I seem to have encountered an odd error where I would get an error upon loading... I added a print statement for physical_time values at loading time. They don't seem right. Any thoughts?

See e1119c6840a4d9a528d6b905f9b5992ecc3d9975

```
(mdtraj_test)_  reference git:(patch-2) _ ipython
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import glob, mdtraj as md

In [2]: t = md.load("ala_dipeptide.dcd", top="ala_dipeptide.pdb")
-3.823
-3.823
-3.823
```

**Comment by mpharrigan** [comment]
Sorry, I may have led you astray. The dcd code wraps the vmd dcd reader plugin. VMD's plug-in interface has a field for storing time data. It looks like the dcd plugin doesn't fill out that field.

**Comment by smsaladi** [comment]
I see. Just to be clear, are you talking about [this function](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/src/dcdplugin.c#L456) in dcdplugin.c?

I wonder if the field is not read on purpose (maybe if NAMD doesn't write to it?) or if it was just never necessary.

**Comment by mpharrigan** [comment]
mdtraj calls `read_next_timestep` which in turn uses `read_dcdstep` to fill out that struct. They probably didn't include it because the timestep is saved in the header, not as a per-frame value. You'd need logic to take the step number and multiply it by the timestep. To implement this in mdtraj, you could put this logic in `read_next_timestep` or `read_dcdstep` *or* call the `read_dcdheader` from cython to get `ISTART` and `DELTA` values. I don't see `read_dcdheader` exposed in any `.h` files, so you'd also have to copy it's function prototype

**Comment by smsaladi** [comment]
Also, figuring it might be useful for users unsuspecting the time/timestep issue with DCD files (like myself), I implemented a warning when it looks like the timestep is not right.
```
In [3]: t = md.load_dcd(traj_files[1],
   ...:            top='./itasser_4/itasser_4_autopsf_tip3p_NaCl.pdb')

/ul/saladi/anaconda/envs/py3/bin/ipython:2: UserWarning: Timestep read as 0.020454829558730125; Consider use of `as_namd`
  if __name__ == '__main__':
```
Logic [here](https://github.com/smsaladi/mdtraj/commit/0f9034526d50d5d2faf35b38822b50654f5ae7c6#diff-6d52a30d80c728f7a06fcf19bca7fc53R405). Open to suggestions to make this check more robust.

**Comment by mpharrigan** [comment]
Wanna open a PR where we can discuss?
