### ISSUE TITLE
Moving website into its own repository

### ISSUE THREAD

**Issue by smsaladi** [mdtraj/mdtraj#1157]
Have you considered moving the website into its own repo? Other projects do that to keep PRs/commits related to the code separate to those from the website ([biopython](https://github.com/biopython) for example). Not sure how you're hosting it right now, but if you could potentially have it hosted by Github if you ran it out of a repo too.

**Comment by smsaladi** [comment]
I guess the downside is that it's less linked to releases. Though given the current userbase, I guess you wouldn't be making huge API changes in the near future.

**Comment by rmcgibbo** [comment]
-1. I don't see what use this serves. Currently the majority of the website is generated using the code docstrings, through sphinx apidoc/autodoc.

**Comment by smsaladi** [comment]
I see, I didn't realize that -- makes sense though. I was just thinking that changes to the docs/tutorials could be instantaneous once committed.

**Comment by mpharrigan** [comment]
Note that the docs are updated for the "Development" version http://mdtraj.org/development/ on each commit

**Comment by mpharrigan** [comment]
But navigating to mdtraj.org defaults to the latest released version of the docs, which doesn't get updated

**Comment by smsaladi** [comment]
Didn't realize that. Sounds like a good system though.
