### ISSUE TITLE
False input parameter check on atom_pairs in compute_distances?

### ISSUE THREAD

**Issue by ghoti687** [mdtraj/mdtraj#1160]
The maximum length of the array *atom_pairs* in the *compute_distances* function is restricted to be of length *traj.n_atoms*. It is documented to be of maximum length *num_pairs*. Is the check really necessary?
If it is necessary, should the maximum number of atom pairs not be determined by combinatorics? E.g. I have 12 atoms, and I want to monitor the distances between all pairs. The maximum number of atom_pairs is (12 *choose* 2), which evaluates to 12! / (2*(12-2)!) = 66, which is considerably larger than 12 according to the current criterion.

**Comment by peastman** [comment]
I don't see the check you're referring to.  It does check that each *element* of atom_pairs must be less than traj.n_atoms, but that's correct:

```Python
    if not np.all(np.logical_and(pairs < traj.n_atoms, pairs >= 0)):
        raise ValueError('atom_pairs must be between 0 and %d' % traj.n_atoms)
```

**Comment by ghoti687** [comment]
Ah, my apologies. I guess, I misunderstood the np.all function at this point. In that case, I must have done something else wrong in the assignment of atom_pairs. Thanks for the clarification.
