### ISSUE TITLE
Dihedral angle calculation

### ISSUE THREAD

**Issue by MamtaMohan** [mdtraj/mdtraj#1164]
Dear MDTraj team,

I am trying to calculate Dihedral angles for a trajectory.

Initially I am using an example trajectory and PDB structure. I can provide both files if you require them.

This is what I did:
```
traj=load('tmp.xyz', top='tmp.pdb')
top=load('tmp.pdb').topology
traj
top
indices=traj.top.select("resSeq 3 and (name N or name CA or name CB or name CG)")
indices
compute_dihedrals(traj,indices)
```

I am getting this error:
compute_dihedrals(traj,indices)
ValueError: indices must be ndim 2. You supplied 1

I am not sure how to solve this.

I would appreciate your response.

Mamta

**Comment by mpharrigan** [comment]
The `compute_dihedrals` function needs four atom indices per dihedral. http://mdtraj.org/1.7.2/api/generated/mdtraj.compute_dihedrals.html#mdtraj.compute_dihedrals

You can specify each of the four indices and pass an `(N, 4)` numpy array or you can do something like

```python
traj = load(...)
traj = traj.atom_slice(traj.top.select("..."))
compute_phi(traj)
compute_psi(traj)
```

**Comment by MamtaMohan** [comment]
Dear Matthew,

I am sorry to write but I do not understand how to define and pass indices. I am new to numpy and python. I tried various combinations but none seem to work for me.

Both command compute_phi(traj) and compute_psi(traj) work. It is compute_dihedrals(traj,indices) which I need and I am having trouble passing indices variable.

As you suggested this is what I tried:
In[257]:n=np.array([13,15,17,20])

In [258]: n.ndim
Out[258]: 1
In [259]: m=np.ndarray(n,4)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-259-0173de9fb14a> in <module>()
----> 1 m=np.ndarray(n,4)

TypeError: data type not understood

**Comment by mpharrigan** [comment]
To make a matrix with rows and columns (`ndim = 2`)

```python
n = np.array(
  [
    [1, 2, 3, 4],
    [1, 2, 3, 5],
    [5, 4, 3, 2]
  ]
)
```

To make a matrix with one row

```python
n = np.array(
  [
    [1, 2, 3, 4],
  ]
)
```

Your code makes a one-dimensional array. Change 
```python
n=np.array([13,15,17,20])
```
to
```python
n=np.array([[13,15,17,20]])
```

**Comment by MamtaMohan** [comment]
Dear Matthew,

I tried this:
n=np.array([[13,15,17,20]])
In [280]: m=(n,4)

In [281]: m
Out[281]: (array([[13, 15, 17, 20]]), 4)

In [282]: compute_dihedrals(traj,m)
ValueError: setting an array element with a sequence.

Still gives an error.

**Comment by cxhernandez** [comment]
@MamtaMohan 

Try simply:

```python
compute_dihedrals(traj, [[13, 15, 17, 20]])
```

**Comment by MamtaMohan** [comment]
Thank you. 

This works.

Could you please explain me what I was doing wrong in the last command.

**Comment by mpharrigan** [comment]
When I said `(n,4)` I was implicitly referring to the shape of the array. You should give an array with N rows (n is the number of dihedral angles you want to compute) and four columns

```
In [282]: compute_dihedrals(traj,m)
```
should be
```
In [282]: compute_dihedrals(traj,n)
```

**Comment by cxhernandez** [comment]
> Could you please explain me what I was doing wrong in the last command.

The indices are meant to be computed from a nested list where the inner lists are the four atom indices that define the dihedral angle. This is why the required dimensionality of `indices` is 2, where one dimension is the number of dihedrals (outer list) and the other is just the four atoms in a single dihedral (inner list).

**Comment by MamtaMohan** [comment]
Dear Matthew and Carlos,

Thank you very much.

Slice command worked, Last command compute_dihedrals(traj,n) worked.

And I found explanation very helpful.

Please understand I did not asked the questions blindly. I have been struggling to extract angles for almost week and a half and after going through python and numpy still did not make any headway.

Thank you again for all the help you gave me.

**Comment by cxhernandez** [comment]
Glad to help!
