### ISSUE TITLE
Trajectory PCA model 

### ISSUE THREAD

**Issue by MamtaMohan** [mdtraj/mdtraj#1166]
Hi,

Is there a way I can save the model built by MDtraj PCA.

Also for some reason after I plot the graph via command:
plt.scatter(reduced_cart[:, 0], reduced_cart[:,1], marker='x', c=traj.time)

next commands just wipe out the graph
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('PCA: Traj')

command: cbar = plt.colorbar()  --does not work

Thank you.

**Comment by mpharrigan** [comment]
Those commands shouldn't wipe out the plot. Are you doing this in a python script or ipython notebook? If the latter, you need to put all the commands in a single cell

**Comment by MamtaMohan** [comment]
After I started anaconda_py interpreter, I started session as: ipython qtconsole
because %matplotlib does not work in ipython and I am not using notebook. This is the alternative suggested (stackexchange).

Every thing worked and from command 'plt.xlabel' things sort of start going off.

Also could you please suggest how to save the model. This is production data I am working with and my session crashed while building model.

**Comment by cxhernandez** [comment]
> Also could you please suggest how to save the model. This is production data I am working with and my session crashed while building model.

I'd suggesting testing this with test data first. With the following:

```python
>> import mdtraj as md
>> from mdtraj.testing import get_fn

>> import matplotlib.pyplot as plt
>> from sklearn.decomposition import PCA

>> traj = md.load(get_fn('traj.h5'))

>> pca1 = PCA(n_components=2)
>> traj.superpose(traj, 0)

>> reduced_cartesian = pca1.fit_transform(traj.xyz.reshape(traj.n_frames, traj.n_atoms * 3))

>> plt.figure()
>> plt.scatter(reduced_cartesian[:, 0], reduced_cartesian[:,1], marker='x', c=traj.time)
>> plt.xlabel('PC1')
>> plt.ylabel('PC2')
>> plt.title('Cartesian coordinate PCA: alanine dipeptide')
>> cbar = plt.colorbar()
>> cbar.set_label('Time [ps]')

>> plt.savefig('pca_example.png')
```

I was able to recreate the figure from the [tutorial](http://mdtraj.org/1.7.2/examples/pca.html).

![mdtraj_example](https://cloud.githubusercontent.com/assets/5142365/17676798/1032bc30-62fe-11e6-9ad9-5382c9470868.png)


Although,  `ipython qtconsole` did not plot things interactively....

**Comment by cxhernandez** [comment]
> After I started anaconda_py interpreter, I started session as: ipython qtconsole
because %matplotlib does not work in ipython and I am not using notebook. This is the alternative suggested (stackexchange).

What do you mean by `%matplotlib` does not work? Does it throw an error, or does it not plot? Typically, one uses `%matplotlib inline` to get matplotlib functionality to work in the notebook.

**Comment by MamtaMohan** [comment]
with ipython when I give: %matplotlib --inline -- it gives error.

I am going to try example. Specifically for figures. 

Instead of figure I am looking to save the complete PCA model to load again to do analysis. Because it would be very inconvenient to build model every time when analysis is required.

PCA is just part of it.

I looked on google it it suggest Pickle but also says that data cannot be transported across the platforms. This is a potential issue. So I do not know how to save the model.

I am so new to Python and whole suite of programs (Sorry for mentioning it again) that I would rather mention to board first.

Thank you.

**Comment by cxhernandez** [comment]
> Instead of figure I am looking to save the complete PCA model to load again to do analysis. Because it would be very inconvenient to build model every time when analysis is required.

Ah, I understand. 

> I looked on google it it suggest Pickle but also says that data cannot be transported across the platforms. This is a potential issue. So I do not know how to save the model.

Pickle is definitely your best bet, and should be perfectly cross-platform as long as you stick to the same version of Python.

If you're interested in reproducible models and workflows, I recommend looking into our sister-project [MSMBuilder](http://msmbuilder.org). We have [methods](http://msmbuilder.org/3.5.0/persistence.html?highlight=pickle#datasets-and-persistence) for reliably loading/saving datasets and model objects.

**Comment by MamtaMohan** [comment]
It was qtconsole messing up figure.

I will look into MSMbuilder.

Thank you.
