### ISSUE TITLE
MDTRAJ import error

### ISSUE THREAD

**Issue by MamtaMohan** [mdtraj/mdtraj#1168]
Hello,

I used MDTraj before without any error for trajectory analysis.

To generate PCA model via MDTraj, I tried to load MDTraj in python session today.

I am  getting error:  

/home/mamta/anaconda2/lib/python2.7/site-packages/mdtraj/__init__.py in <module>()
     27 """
     28 
---> 29 from mdtraj.formats.registry import FormatRegistry
     30 from mdtraj.formats.xtc import load_xtc
     31 from mdtraj.formats.trr import load_trr

/home/mamta/anaconda2/lib/python2.7/site-packages/mdtraj/formats/__init__.py in <module>()
      1 from mdtraj.formats.arc import ArcTrajectoryFile
----> 2 from mdtraj.formats.dcd import DCDTrajectoryFile
      3 from mdtraj.formats.binpos import BINPOSTrajectoryFile
      4 from mdtraj.formats.xtc import XTCTrajectoryFile
      5 from mdtraj.formats.trr import TRRTrajectoryFile

__init__.pxd in init dcd (mdtraj/formats/dcd/dcd.c:10393)()

ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

I am little baffled by this error. I never had issues before.

I would appreciate your response.

**Comment by peastman** [comment]
It sounds like this problem: http://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling

You may just need to upgrade to a newer version of numpy.  What version do you currently have installed?

**Comment by cxhernandez** [comment]
Try `conda update numpy`

**Comment by MamtaMohan** [comment]
ok. Let me try.

**Comment by MamtaMohan** [comment]
Did I missed something?

**Comment by hainm** [comment]
or you can just install mdtraj from its source code with your given numpy version.
