### ISSUE TITLE
Mdtraj data for PCA computation

### ISSUE THREAD

**Issue by MamtaMohan** [mdtraj/mdtraj#1169]
Dear MDtraj team,

I have a question related to dimensionality reduction method.

Via MDtraj I was able to calculate PCA components. Which is good.

I am working with dihedral angles and prefer a nonlinear decomposition method instead of PCA. 

I looked into TICA but I am not looking currently temporal decomposition. Perhaps in second stage.

I realized MDS is also available in scikit and looks like in-place of PCA I can call that function while executing PCA commands.

Is it possible?

I will appreciate your response.

**Comment by cxhernandez** [comment]
Dihedral data from `mdtraj` is just a NumPy array. You should be able to apply any decomposition method in `sklearn` to it without any issues. If you want a non-linear method, I would suggest [`KernelPCA`](http://scikit-learn.org/stable/modules/decomposition.html#kernel-pca).

**Comment by MamtaMohan** [comment]
Thank you.


________________________________
