### ISSUE TITLE
Convert Amber topology to Gromacs topology

### ISSUE THREAD

**Issue by nanobiophys** [mdtraj/mdtraj#1179]
Hi, I have Amber topology files and trajectories to convert to Gromacs format. Trajectory.save_(gromacs format) works well in converting the trajectories.  
Do we have similar modules for topology conversion as well?  I didn't see one in the list.  Thanks in advance.

**Comment by rmcgibbo** [comment]
No. There are some other projects that have tools like this though, such as ParmEd.

**Comment by nanobiophys** [comment]
I used ParmEd but it rearrange a few blocks of residues and leads to inconsistent order of atoms between the topology and the coordinate files.  I have disulfide-like bonds between chains of molecules and suppose that's why ParmEd did the rearrangement.

**Comment by nanobiophys** [comment]
But thanks anyway.

**Comment by hainm** [comment]
>  I have disulfide-like bonds between chains of molecules and suppose that's why ParmEd did the rearrangement. 

you're always welcome to open an issue in ParmEd repo. It's hard to fix anything if we don't know about the issue.
https://github.com/ParmEd/ParmEd/issues
