### ISSUE TITLE
NaN propagation bug in compute_distances

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#1185]
When taking the distance between two atoms, it would be probably be a good idea if the result didn't depend on whether the coordinates of the 3rd atom are `NaN`. I would expect the result for `Out[2]` to be `array([[ 1.]], dtype=float32)`, as is the case with `Out[3]`.

```
In [1]: import mdtraj as md; import numpy as np; print(md.version.full_version)
1.7.2

In [2]: md.compute_distances(md.Trajectory(xyz=np.array([[1,1,1], [2,1,1], [np.nan, np.nan, np.nan]]).reshape(1,3,3), topology=None), [[0,1]])
Out[2]: array([[ nan]], dtype=float32)

In [3]: md.compute_distances(md.Trajectory(xyz=np.array([[1,1,1], [2,1,1], [0, 0, 0]]).reshape(1,3,3), topology=None), [[0,1]])
Out[3]: array([[ 1.]], dtype=float32)
```

I have a hunch (but no conformation) that this is the same bug observed in https://github.com/markovmodel/PyEMMA/issues/891.

**Comment by rmcgibbo** [comment]
Oh, this is just https://github.com/mdtraj/mdtraj/pull/1167.

**Comment by marscher** [comment]
Just a notice, the bug we encountered in markovmodel/pyemma#891 is not produced by NaN in the input coordinates, but by not writing proper values to the allocated distances array (which is empty).

**Comment by rmcgibbo** [comment]
This bug isn't _really_ related to NaNs in the input array -- it's a general bug with the SSE load4 instruction reading 32 bits off the end of the array. Depending on the memory layout, it could lead to lots of stuff, including segfaults.

**Comment by marscher** [comment]
Ah I understand, thank you.

**Comment by rmcgibbo** [comment]
But I don't actually know if it's related to your PyEMMA bug or not. It seems plausible, but it's not certain.

**Comment by marscher** [comment]
Well, we asserted that the input is finite and the output contained NaNs. However we do not understand how exactly the error is provoked,
as it happens at different frame indices and extracting this suspicious frame can not reproduce the error.

**Comment by rmcgibbo** [comment]
I don't have a ton of extra time, so if anyone wanted to clean up the rest of the places that the bug appears (basically find and replaced), we could get #1167 merged quickly.
