### ISSUE TITLE
Atom slicing issue

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1186]
Using the current `master`, I'm having trouble slicing a trajectory that was written by the same version of `mdtraj`:

``` python
import mdtraj as md
import os

h5_filename = 'traj.h5'
t = md.load(h5_filename)
solute = t.topology.select('not water')
tnew = t.atom_slice(solute, inplace=False)
tnew[0].save('test.pdb')
```

Example trajectory attached.

[traj.h5.zip](https://github.com/mdtraj/mdtraj/files/537965/traj.h5.zip)

**Comment by jchodera** [comment]
Oddly enough, I tested a few trajectories in `mdtraj/testing/reference/` but couldn't reproduce this issue on those trajectories.

**Comment by jchodera** [comment]
Output:
```
[chodera@gpu-2-4 analyze]$ python mdtraj-test.py
Traceback (most recent call last):
  File "mdtraj-test.py", line 8, in <module>
    tnew[0].save('test.pdb')
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 1304, in save
    return saver(filename, **kwargs)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 1397, in save_pdb
    bfactors=bfactors[i])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 672, in __exit__
    self.close()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 501, in close
    self._write_footer()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py", line 429, in _write_footer
    index1 = atomIndex[atom1]
KeyError: MOL1-P1
Exception KeyError: (MOL1-P1,) in <bound method PDBTrajectoryFile.__del__ of <mdtraj.formats.pdb.pdbfile.PDBTrajectoryFile object at 0x7f5303888550>> ignored
```

**Comment by JoaoRodrigues** [comment]
Bumping this because I am running into the same issue, although with a different use case:

```
import mdtraj as md
trj = md.load('whatever.nc', top='whatever.psf')
new_trj = trj[::5]  # Yes, I know I can use stride when loading but this is just an example
new_trj.save('whatever.pdb')
```

The problem is that the atoms in the topology and the (new) trajectory do not match. Funny thing is, they are in the atomIndex dictionary (at least they seem to be) so I am guessing this is down to the comparison in the dictionary. A copy of the object will not have the same hash key?

**Comment by badisa** [comment]
I ran into this issue in the past few months, would be nice if it could be fixed

**Comment by florentilda** [comment]
Has this issue been solved? I just ran into it myself.
F

**Comment by aasthajhunjhunwala** [comment]
I faced this issue as well.

**Comment by badisa** [comment]
Digging into this it looks like the atoms stored in the topology bonds and the atoms stored in the chains are not equal (the chain indices differ). I tried modifying the hash per @JoaoRodrigues recommendation and that didn't fix the issue though suspect that is part of the issue.

Opened a draft PR with a fix: https://github.com/mdtraj/mdtraj/pull/1605

**Comment by badisa** [comment]
Was working off an old version of master, looks to have been fixed here: https://github.com/mdtraj/mdtraj/commit/ce5c80060bcaffc79f4817cd4546e5f0ab754b28
