### ISSUE TITLE
creating fake trajectory

### ISSUE THREAD

**Issue by msultan** [mdtraj/mdtraj#1187]
So I have been trying to create a function which is capable of creating a fake protein given a sequence of amino acids. It doesn't need to be a "valid" trajectory but it should have the right connectivity information. Does anyone have something like that lying around or any recommendation on what the best way to create something like this would be?

**Comment by jchodera** [comment]
`leap` from `ambermini` can do this for you. You can create an `input.leap` file like
```
source oldff/leaprc.ff99
protein = sequence {ACE ALA ALA NME}
savepdb protein output.pdb
quit
```
then run it with 
```
tleap -f input.leap
```
and have a PDB file with the right connectivity and somewhat-ideal geometry.

**Comment by mpharrigan** [comment]
Do you want a semi-reasonable structure or would `np.random` work? How reasonable do you need it? bonded atoms near each other? pdb fixer probably has some code for this because it can add in missing residues

**Comment by cxhernandez** [comment]
Maybe it's worth having some basic residue template information ([like PDBFixer does](https://github.com/pandegroup/pdbfixer/tree/master/pdbfixer/templates)) to make generating a topology from a sequence more simple?

**Comment by jchodera** [comment]
> Maybe it's worth having some basic residue template information (like PDBFixer does) to make generating a topology from a sequence more simple?

This could be super useful.

**Comment by msultan** [comment]
Np.Random would work fine for my use case though I would prefer not to use amber since this is to design some functionality for msmbuilder. I will start looking at the pdbfixer code though

**Comment by jchodera** [comment]
[`ambermini`](https://anaconda.org/omnia/ambermini) is conda-installable via `omnia`, though I can understand if you want to avoid such a heavyweight dependency.

Then again, `pdbfixer` depends on `openmm`, which is also pretty heavyweight.

**Comment by msultan** [comment]
i was thinking of copying the template folder over to mdtraj and then defining a peptide bond maker function that takes in a existing topology and a residue name, returning the new topology with an additional peptide. Its definitely not gonna look pretty.

**Comment by msultan** [comment]
>ambermini is conda-installable via omnia
I didnt know that. That is really cool!

**Comment by msultan** [comment]
Np.Random would work fine for my use case though I would prefer not to use amber since this is to design some functionality for msmbuilder 

I know pdbfixsr can create point mutants which seems to indicate that it should have most of what we need already

**Comment by msultan** [comment]
Carlos suggested using parmed but that uses pyrosseta in the background which seems like a tad too complex of a solution

**Comment by peastman** [comment]
PDBFixer might be able to do this directly.  Try creating a PDB file with the sequence you want but no ATOM records then run it through PDBFixer.  Does it do what you want?  If not, we can probably make it work with only minor changes.
