### ISSUE TITLE
Cryptic Error with rmsd precentered=True and atom_indices != None

### ISSUE THREAD

**Issue by justinrporter** [mdtraj/mdtraj#1189]
The following code

``` python
trj = md.load('path/to/trj')
trj.center_coordinates()
md.rmsd(trj, trj[0], precentered=True, atom_indices=[1,2,3])
```

terminates with 

```
File "mdtraj/rmsd/_rmsd.pyx", line 171, in _rmsd.rmsd (mdtraj/rmsd/_rmsd.c:2935)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

For convenience, the offending line is:

``` python
if precentered and (reference._rmsd_traces is not None) and (target._rmsd_traces is not None) and atom_indices == slice(None):
```

It looks like the problem is that _both_ `precentered=True` and a non-None value for `atom_indices` are specified. I don't know enough about the guts of the rmsd calculation to know if that's reasonable, but the error could definitely be more informative. It actually looks like the code wants to ignore the precentered flag entirely but the comparison `atom_indices == slice(None)` fails because, as the error says, the truth value of an array is ambiguous.

It might also be nice to add some kind of warning if the precentered flag is being ignored because _rmsd_traces doesn't exist or something.

Thoughts? I'd be open to doing it myself, but I'm not too sure what the code _should_ do.

**Comment by rmcgibbo** [comment]
I'll fix this. To be clear though, `precentered` is (should be) ignored if `atom_indices != None`.

**Comment by justinrporter** [comment]
> To be clear though, precentered is (should be) ignored if atom_indices != None

Yeah, I suspected that wasn't an accident.

I'd propose some kind of warning, though, when precentered = True but it's ignored because atom_indices != None. I say this because I discovered this problem by unknowingly doing exactly that... 😊

**Comment by rmcgibbo** [comment]
I agree, adding a warning is not a bad idea.

**Comment by rmcgibbo** [comment]
How about: if #1190 builds properly and passes the tests, I'll merge it and then maybe you could add a warning in another PR?

**Comment by justinrporter** [comment]
> maybe you could add a warning in another PR?

Deal. 👍
