### ISSUE TITLE
how to download and install MDTraj 1.8.0

### ISSUE THREAD

**Issue by dart4869** [mdtraj/mdtraj#1194]
Hi, 

I am studying MSMbuilder tutorial which uses function MDTraj.join developed only in version 1.8.0. I am wondering where can I download the latest version? Any helps would be much appreciated.

**Comment by cxhernandez** [comment]
You can install the development version with either:

```
$ pip install git+git://github.com/mdtraj/mdtraj.git#egg=mdtraj
```

or 

```
$ git clone https://github.com/mdtraj/mdtraj.git && cd mdtraj
$ python setup.py install
```

**Comment by cxhernandez** [comment]
Just as an update: MDTraj 1.8 has been released and is now available through conda.
