### ISSUE TITLE
RMSF function

### ISSUE THREAD

**Issue by rafwiewiora** [mdtraj/mdtraj#1210]
I had to do some RMSF (Root-Mean-Square Fluctuation, definition: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2830444/#fd6) calculations recently, thought a function to do this might be useful. 

Related to #1188 because taking the expression for RMSD @jchodera gives there, RMSF is simply given by a different mean:

``` python
trajectory.superpose(reference, atom_indices=atom_indices1, ref_atom_indices=ref_atom_indices1)

rmsf = np.sqrt(3*np.mean((trajectory.xyz[:, atom_indices2, :] - reference.xyz[:, ref_atom_indices2, :])**2, axis=(0,2)))
```
(or maybe there's another way to do this faster?) 

Do people think this would be useful to have as a convenience function?

**Comment by jchodera** [comment]
I think it would be useful to provide a convenience function to do this in a numerically robust and fool-proof way. For example:
```python
rmsf = trajectory.rmsf(reference, rmsf_indices=atom_indices2, align_indices=atom_indices1, ref_atom_indices=ref_atom_indices1)
```

**Comment by rafwiewiora** [comment]
Need to also point out some differences in definitions here, I was calculating RMSF with respect to frame0 of the trajs with that expression above, but I actually see people generally calculating it w.r.t. to an atom's average position over all frames. The expression for RMSF w.r.t average positions should be: 

```python
trajectory.superpose(trajectory, atom_indices=atom_indices)
avg_traj = np.mean(trajectory.xyz[:, atom_indices, :], axis=0)
rmsf = np.sqrt(3*np.mean((trajectory.xyz[:, atom_indices, :] - avg_traj)**2, axis=(0,2)))
```

Perhaps we could support both ways?

**Comment by rmcgibbo** [comment]
+1 for this feature. I think it should be implemented as a function in the mdtraj namespace -- `md.rmsf`, to parallel `md.rmsd`.

**Comment by jchodera** [comment]
What would the API look like?

Should we take inspiration from the [MDAnalysis RMSF](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/rms.html#MDAnalysis.analysis.rms.RMSF)?

**Comment by rmcgibbo** [comment]
As close as possible to the rmsd API.

**Comment by jchodera** [comment]
> As close as possible to the rmsd API.

I took a stab at that, and found it didn't actually make sense.

* We align all the frames in `target` trajectory to some `reference` trajectory frame `reference_frame` using some `target_atoms` and `reference_atoms`
* For some `rmsf_atoms`, we compute some reference configuration: either the `mean` or a specific frame index (why choose this, @rafwiewiora?)
* We compute the RMSF of `rmsf_atoms` of `target` from this reference frame in a numerically stable way and return a scalar

**Comment by rmcgibbo** [comment]
What about that doesn't make sense?

**Comment by jchodera** [comment]
Oh, just that it's not that close to `md.rmsd`, though it *is* "as close as possible":
```python
mdtraj.rmsd(target, reference, frame=0, atom_indices=None, parallel=True, precentered=False)
mdtraj.rmsf(target, rmsf_atoms=None, rmsf_reference_frame=None, target_atoms=None, reference=None, reference_frame=None, reference_atoms=None)
```
`reference` should probably be optional because people generally just align to a single frame of the same trajectory.

**Comment by rafwiewiora** [comment]
+1 for the suggestion for the user to have to superpose the trap beforehand. I think that is much more transparent. 

It could work with very similarly to RMSD:
``` python
mdtraj.rmsf(target, reference=None, frame=0, atom_indices=None, ref_atom_indices=None)
```

`reference`: if you don't give it, then RMSF is calculated w.r.t. average atomic positions over the trajectory. If you give it, then RMSF is calculated w.r.t. the reference, which can be the same trajectory. Choose which frame of it with `frame`. 

Not clear if `parallel` and `precentered` apply in this case?
