### ISSUE TITLE
Would it be useful for mdconvert to have an option to image molecules?

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1211]
Would it be useful to add an option to `mdconvert` to call [`image_molecules()`](https://github.com/mdtraj/mdtraj/blob/aeba45c0544dcb07bf7972b0988b1ef6a9560df2/mdtraj/core/trajectory.py#L1899) on the trajectory being converted? This seems like a commonly-desired operation.

If so, what's the most consistent command-line argument for this? Does every long argument have to have a matching single-letter argument for specialized flags like this?

**Comment by mpharrigan** [comment]
Hi @jchodera : no one's monkeyed with the mdconvert script in a long time. PRs welcome
