### ISSUE TITLE
Trajectory.image_molecules fails (sometimes) to find a valid anchor.

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1213]
Since 1.8 we get the following exception within a test operating on a trajectory containing only C-alpha coordinates. Maybe we should define an anchor for this case, but it used to work before.
This change has been introduced in #1106. Ping @mpharrigan

Failure on Python-3.5 (win)
https://ci.appveyor.com/project/marscher/pyemma/build/1.0.2440/job/ntftvm8d0llk0ywj#L2740
Passes on Py2.7, 3.4 (win)
https://ci.appveyor.com/project/marscher/pyemma/build/1.0.2440

On OSX if fails for all tested Python versions (2.7, 3.4, 3.5):
https://travis-ci.org/markovmodel/PyEMMA/jobs/175731776#L2881-L2920

It is very unclear to me, why this succeeded on win-py35, because the topology is the same.

**Comment by leelasd** [comment]
@mpharrigan How can supply anchor_molecule ? I tried passing `t.topology.select('resid 0') ` but it did not work. Neither did `[atom for atom in t.topology.residue(0).atoms]` . Any suggestions would be very helpful !!

**Comment by mpharrigan** [comment]
@leelasd please open a new issue

@marscher in version 1.7, `image_molecules` would not complain if it couldn't find any "anchor molecules". With #1106, it raises the exception. Although your topology should be one molecule, it treats each alpha carbon as a distinct molecule.

What's the desired behavior here? I think the best case is to change the pdb reader to identifiy molecules. Should we accept the case where there is no anchor molecule found? Should we emit a warning?

**Comment by fabian-paul** [comment]
@leelasd : I recently played around with `anchor_molecules` too and I could only get it to work with `anchor_molecules=set(top.chain(0).atoms)`.
