### ISSUE TITLE
Specify chains in save_pdb method

### ISSUE THREAD

**Issue by jeiros** [mdtraj/mdtraj#1214]
I'm using MDtraj to cluster AMBER NetCDF trajectories and I'm saving centroids using the `save_pdb` method.

This works fine, but my system is made up of three subunits which originally are in three chains (A, B and C). I'm not entirely sure if the AMBER `prmtop` file stores chain information.

Is it possible to specify which residues belong to each chain when saving the PDB? For the moment I find myself having to manually edit the PDB files, changing the chains and entering TER lines between them, and it's quite cumbersome so I was wondering if that can be automated from MDtraj.

Thanks for any help!

**Comment by cxhernandez** [comment]
When you load one of these trajectories (let's call it `traj`), what's the value for `traj.n_chains`? If it's not the desired number, then you can create new chains for your topology with `traj.topology.add_chain()`. Every `residue` object in an MDTraj `Topology` has a chain attribute, which should be settable. This means you could do something like this:

```python
traj = md.load(...)
new_chain = traj.topology.add_chain()
for n in some_list:
    traj.topology.residue(n).chain = new_chain
```


As far as naming goes, this is what I found in the docs for [`PDBTrajectoryFile`](https://github.com/mdtraj/mdtraj/blob/c22c829baf7e0b0956fd29fc9b5d524d183679a5/mdtraj/formats/pdb/pdbfile.py#L453):

>When writing PDB files, PDBTrajectoryFile translates each chain's
index into a name -- the name is what's written in the file. By
default, chains are named with the letters A-Z.

You can specify custom chain names with `set_chain_names` when using `PDBTrajectoryFile` (which behaves like `open`) to write the PDB files:

```python
from md.formats import PDBTrajectoryFile

with PDBTrajectoryFile('mypdb.pdb', mode='w') as pdb_file:
    pdb_file.set_chain_names(my_chain_name_list)
    pdb_file.write(traj.positions, traj.topology)
```

**Comment by jeiros** [comment]
Hi Carlos,

I've tried to do what you're suggesting but I don't think I'm following. Here's what I've tried:

```python
>>> from mdtraj.formats import PDBTrajectoryFile
>>> test_frame = full_traj[0]
>>> test_frame.n_chains
1
```
Initially all the residues belong to the `A` chain. So I should only `add_chain` to
the residues that should be in chains `B` and `C`, if I understand correctly. So I've tried:
```python
my_chain_name_list = ['B', 'C']

for chain in my_chain_name_list:
    new_chain = test_frame.topology.add_chain()
    if chain == 'B':
        for n in range(161, 248):
            test_frame.topology.residue(n).chain = new_chain
    if chain == 'C':
            for n in range(248, 419):
                test_frame.topology.residue(n).chain = new_chain
```
So now I have three chains:
```python
>>> test_frame.n_chains
3
```
Finally (I've changed `.positions` with `.xyz[0]` because the first gives me `AttributeError: 'Trajectory' object has no attribute 'positions'`:
```python
with PDBTrajectoryFile('testing.pdb', mode='w') as pdb_file:
    pdb_file.set_chain_names(my_chain_name_list)
    pdb_file.write(test_frame.xyz[0], test_frame.topology)
```
But this doesn't work either:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-339-99e05cfcc4e2> in <module>()
      1 with PDBTrajectoryFile('testing.pdb', mode='w') as pdb_file:
      2     pdb_file.set_chain_names(my_chain_name_list)
----> 3     pdb_file.write(test_frame.xyz[0], test_frame.topology)

/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py in __exit__(self, *exc_info)
    669 
    670     def __exit__(self, *exc_info):
--> 671         self.close()
    672 
    673     def __len__(self):

/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py in close(self)
    499         "Close the PDB file"
    500         if self._mode == 'w' and not self._footer_written:
--> 501             self._write_footer()
    502         if self._open:
    503             self._file.close()

/Users/je714/anaconda3/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py in _write_footer(self)
    427             atomBonds = {}
    428             for atom1, atom2 in conectBonds:
--> 429                 index1 = atomIndex[atom1]
    430                 index2 = atomIndex[atom2]
    431                 if index1 not in atomBonds:

KeyError: S1P270-O1P
```
*Note*: I've also tried replacing `my_chain_name_list` with `['A', 'B', 'C']` but same error ensues.

My PDB has two non-standard residues (two adjacent phosphorylated Serines, which are name in this case S1P).

I'm kind of stuck. I think I could solve this issue by using the `.find_molecules()` method of the `topology` though?
I say this because it looks like it properly picks up the chains and their connectivity (it also knows about three Calcium atoms at the end which are not bound to anything, named `CA2`). The output is quite long (6820 atoms) so I'm not pasting it here, but I've uploaded it [elsewhere](http://lpaste.net/5580698917500092416).

Sorry if this is a bit involved, and thanks for any help!

**Comment by hainm** [comment]
you can use your original pdb file as topology file, given that if you already missing atoms added (e.g H, )

**Comment by jeiros** [comment]
Thanks @hainm that was surprisingly easy. I had a PDB lying around with the correct chains and TER cards. Using that to load the trajectory and then just saving a frame with the `save_pdb` method kept all the chain definitions 👍 
Good to know!

**Comment by cxhernandez** [comment]
Ah, didn't realize that you had a correct topology. Yeah, that's definitely easiest! Thanks @hainm
