### ISSUE TITLE
How to loading velocity data from .trr file, changing it and saving it using mdtraj

### ISSUE THREAD

**Issue by arjunwadhawan** [mdtraj/mdtraj#1216]
Hi,
We can load velocity data of a trajectory using mdtraj.load_trr

I want to know if it is possible now to edit this data or do some calculation on this data and save the new velocity data with coordinate using save option 

As per this page (http://mdtraj.org/latest/api/generated/mdtraj.Trajectory.html), save_trr(filename, force_overwrite=True) will write the velocity =0 . So ,is there any way around this?

I want to perform basic edits like 
-reverse the velocity of my trajectory from state A to state B 
-Add two trajectories with velocity

**Comment by rmcgibbo** [comment]
Sorry, this feature is not available. MDTraj does not read velocity information.
