### ISSUE TITLE
limited number of characters for residue index 

### ISSUE THREAD

**Issue by asgharrazavi** [mdtraj/mdtraj#1217]
I noticed that when a pdb file has more that 1000 residues, the top.atom method print only the first 3 digits of the residue number:

mem = md.load('membrane.pdb')

In [32]: mem.top.atom(11585)
Out[32]: POPE999-C4B

In [33]: mem.top.atom(11586)
Out[33]: POPE100-NH3

the Out[33] should be POPE1000-NH3

Any idea why this is happening?

**Comment by peastman** [comment]
What's the line from the PDB file corresponding to that atom?  Residue numbers are stored in columns 23-26, so if the file is formatted correctly it should allow four digits.

**Comment by asgharrazavi** [comment]
I see, that was the issue. My pdb file started from column 24 for residue number. Thank you.
