### ISSUE TITLE
Average structure

### ISSUE THREAD

**Issue by tabramy** [mdtraj/mdtraj#1218]
Hi,

I am trying to calculate RMSD of the ligand from the average structure in a protein-ligand trajectory (both after protein alignment and ligand alignment), however, I am not able to find a MDTraj built in function to calculate the average structure. Can you please let me know if such a built in function exists, for example similar to pytraj's pytraj.mean_structure.

If such a function does not exist, please let me know what is the best way to go around this using the MDTraj functions. Otherwise this has to be calculated by a user manually?

Thanks

**Comment by mpharrigan** [comment]
cc #1159
