### ISSUE TITLE
Need a way to adjust what's recognized as solvent

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#1219]
In Yank, I've [run into an issue](https://github.com/choderalab/yank/issues/606) where only certain solvents are recognized as solvent because of the provided set of solvent types in `mdtraj`. Is there a way to extend this when doing analysis, or can a way be added? I'm interested in being able to simulate and analyze arbitrary small molecules in arbitrary solvents, where the solvents might NOT already be well studied (or perhaps not even have been synthesized yet!) so having a frozen set of recognized solvents can be problematic for this.

**Comment by mpharrigan** [comment]
The code being called is 
```python
        atom_indices = [atom.index for atom in self.topology.atoms if
                atom.residue.name not in solvent_types]

        return self.atom_slice(atom_indices, inplace = inplace)
```

You can use this type of construct to do whatever you want.
