### ISSUE TITLE
compute_dssp output changes for slice, even for if the slice is [:]

### ISSUE THREAD

**Issue by John-Jumper** [mdtraj/mdtraj#1222]
I am new to MDTraj, and something really weird is going on for me in compute_dssp.  The code
```
traj = md.load('/path/to/file')
print ''.join(md.compute_dssp(traj   )[0])
print ''.join(md.compute_dssp(traj[:])[0])
```
has the output
```
CCCCCCCCCCCCCCCCCCCCCCCCCCHHHHCECCECCCCCCCCCCCCCCCCNA
CCCCCHHHHHHHHHHHCCCCCCCHHHHHHHHHHHCCCHHHHHHHHHCCCCCNA
```

The 'NA' on the end is expected, but I cannot see how the DSSP output can depend on whether I use traj or traj[:] as the Trajectory object.  Is this a bug or a misunderstanding on my part?

I am using the latest MDTraj from PyPI.  I wrote a custom Trajectory loader for my file format, but there is nothing exotic in it.  I use float32 as the numpy dtype.

Thank you,
John Jumper

**Comment by John-Jumper** [comment]
A bit more debugging shows the problem only happens with a copying slice
```
print np.all(md.compute_dssp(traj) == md.compute_dssp(traj.slice(slice(None,None,None),copy=True )))
print np.all(md.compute_dssp(traj) == md.compute_dssp(traj.slice(slice(None,None,None),copy=False)))
```
gives the output
```
False
True
```

**Comment by John-Jumper** [comment]
It looks like copying the Topology object can change the atom indices.  
```
print np.array([a.index for a in traj.topology.atoms][:10])
print np.array([a.index for a in traj.topology.copy().atoms][:10])
```
gives the output 
```
[0, 1, 2, 300, 3, 4, 5, 228, 301, 6]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
I am guessing that a change in the atom indices in the topology that does not match a change in the xyz array causes the problems that I am seeing.  

When I created my topology object, I added the atoms in an order that is not residue contiguous.  Is that permissible or could that be the cause of the issue?

**Comment by John-Jumper** [comment]
Any update on this?

**Comment by mpharrigan** [comment]
You're right that mdtraj re-orders the atom indices during a topology copy

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L209

There are a couple other issues related to non-contiguous residues. https://github.com/mdtraj/mdtraj/issues/1020 and https://github.com/mdtraj/mdtraj/pull/1135 and https://github.com/mdtraj/mdtraj/issues/1129

**Comment by mpharrigan** [comment]
Which dssp result is correct? the one after the copy or before. dssp probably requires the atoms to be continuous

**Comment by John-Jumper** [comment]
The DSSP results after the copy is correct.  I have since rewrote my trajectory loader to have contiguous atom indices on the residues.  Are non-contiguous residues allowed/acceptable in MDTraj?  Regardless, I will try to avoid them in the future.
