### ISSUE TITLE
atoms pair distance

### ISSUE THREAD

**Issue by mweka007** [mdtraj/mdtraj#1224]
Mdtraj can compute atoms pairwise distance from my trajectory between two groups (group1 and group2) using  mdtraj.compute_distances. Output atoms pairs and the distance?

**Comment by ctk3b** [comment]
Are you asking about creating the atom pairs? Check out [`top.select_pairs`](http://mdtraj.org/1.8.0/api/generated/mdtraj.Topology.html#mdtraj.Topology.select_pairs)

**Comment by mpharrigan** [comment]
or http://mdtraj.org/1.8.0/api/generated/mdtraj.compute_distances.html#mdtraj.compute_distances
