### ISSUE TITLE
SSE4 invalid read causing NaN in distance calculation (again)

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1225]
I thought we fixed this in #1167, but I just observed this with mdtraj-1.8 on Appveyor (windows):
```
self = <pyemma.coordinates.tests.test_featurizer.TestFeaturizer testMethod=test_Residue_Mindist_Ca_all>
    def test_Residue_Mindist_Ca_all(self):
        n_ca = self.feat.topology.n_atoms
        self.feat.add_residue_mindist(scheme='ca')
        D = self.feat.transform(self.traj)
        Dref = mdtraj.compute_contacts(self.traj, scheme='ca')[0]
>       assert np.allclose(D, Dref)
E       AssertionError: assert False
E        +  where False = <function allclose at 0x0000000002E875F8>(array([[ 0.86527866,  0.66415662,  0.7876637 , ...,  0.89559984,\n         1.21....82028967, ...,  0.87174141,\n                nan,         nan]], dtype=float32), array([[ 0.86527866,  0.66415662,  0.7876637 , ...,  0.89559984,\n         1.21....82028967, ...,  0.87174141,\n                nan,         nan]], dtype=float32))
E        +    where <function allclose at 0x0000000002E875F8> = np.allclose
```
https://ci.appveyor.com/project/marscher/pyemma/build/1.0.2650/job/59teu0aakqm0y94c#L2285

The code calls compute_contacts, which uses geometry.h from mdtraj. Again this behaviour is non-deterministic (the topology and coordinates are constant.

cc @fabian-paul fyi

**Comment by hainm** [comment]
it's better to encourage user to use [bash on Windows](http://www.windowscentral.com/how-install-bash-shell-command-line-windows-10) :D

**Comment by marscher** [comment]
It is better to encourage users not to use Windows at all :) This however does not solve the invalid memory access.

**Comment by hainm** [comment]
> It is better to encourage users not to use Windows at all :) 

Have you tried bash on Windows. It's exactly Ubuntu but running natively on Windows. Windows 10 is nice, anyway. 

>This however does not solve the invalid memory access.

From your 1st comment, I thought there was no issue with Linux tests.

**Comment by marscher** [comment]
So your guess is that the underlying C routine is faulty only on Windows? I'd bet that this is not the case. I just observed it there. @fabian-paul also reported that he still sometimes observes NaN in distance based calculations, but the problem is hard to reproduce.

**Comment by marscher** [comment]
Since the topology in this case has 58 atoms % 4 = 2 (NaNs) there is some padding missing. Can't we ensure this to be padded correctly inside the readers? This would avoid coping memory around for every distance calculation.

**Comment by marscher** [comment]
Sorry, the build for Appveyor used the previous release.
