### ISSUE TITLE
Velocities in trajectories

### ISSUE THREAD

**Issue by EnricoRiccardi** [mdtraj/mdtraj#1230]
Dear developers,

We are a group working on rare events (www.pyretis.org). We developed a code to manage md simulations to efficiently sample transition events. 

To increase the versatility of our code, we were thinking to use mdtraj such to be able to interface with several MD engines (gromcacs, amber etc) with a very elegant and direct implementation. 

Mdtraj seems to be exactly what we were looking for. Our problem is that we need to deal also with the velocities in a trajectories/frame. Do you think it is feasible to have this modification in an official release? We understand that this might influence the code speed, but for us, it would be the essential element which would make us decide if to use mdtraj or not. 

Thank you for consideration in any case and looking forward for an answer. 
Bests,
Enrico 

ps. is there any plan to deal with the hight precision .g96?

**Comment by John-Jumper** [comment]
I am a user of MDTraj as well and I was just about to file a similar feature request.

I would like to have a collection of additional timeseries as numpy arrays in the MDTraj trajectory.  I am thinking of simulation energy and replica exchange index for me.  The user would have to guarantee that all additional timeseries' first axis has length equal to n_frames.  The only requirements for MDTraj would be to (1) copy the additional data whenever the Trajectory is copied and (2) slice the additional timeseries when the trajectory is sliced (keeping the numpy dtype). 

Best regards,
John

**Comment by mpharrigan** [comment]
Hi @EnricoRiccardi and @John-Jumper 

We don't currently have plans for adding support for velocities or arbitrary timeseries data. Pull requests are welcome, however

**Comment by rmcgibbo** [comment]
These are both reasonable requests. The second is probably easier to implement than the first, because the crux of the first request will be modifying the appropriate loaders to load velocity information in the first place.

To my knowledge, neither of these features is currently a high priority for the existing development team, but PRs are always welcome.

**Comment by EnricoRiccardi** [comment]
I would allow myself to make a small proposal for a simple way out. Would be possible to load a trajectory as a collection of ONLY velocities (or forces)?  
As an example, the function md.load() would load only the positions of a trj as it is now, and 
the function md.vload() would load only the velocities (md.fload() the forces).

The rest of the code would not see any difference. We can do scripts and other trick to do it ourself to handle this, but I think it would be easier if it could be in the official release of mdtraj. 

ps. also the request of  John-Jumper would be useful to us.

**Comment by mpharrigan** [comment]
The difficult part is teaching each of the format loaders where to find velocity information in the files. Once that is done, making a good API would be easy. 

A really hacky thing to do would be to save your velocities *as* positions e.g. in an xtc file

**Comment by EnricoRiccardi** [comment]
yup, that how I did already, but it requires two slow steps more. Read Print and Read
