### ISSUE TITLE
PyEMMA lag time clarification

### ISSUE THREAD

**Issue by tabramy** [mdtraj/mdtraj#1232]
Dear All,

I have a question regarding PyEMMA. Since I cannot find a forum via their website I was wondering if I will find answers in this forum.

My question is regarding the lag time. There are two 'lag' that the tutorial mentions, one in here as part of TICA:
http://emma-project.org/latest/generated/MSM_BPTI.html#time-lagged-independent-component-analysis-tica
and another one is in here http://emma-project.org/latest/generated/MSM_BPTI.html#msm

The PyEMMA paper explains how to choose the optimal lag time from the implied time scales (ITS) graph, but I was wondering if the first lag time in the tutorial is the same as the one chosen from the ITS graph, because the first lag (first link above) is used to build TICAs which comes before the ITS is plotted (in other words before one has information enabling the deduction of the optimal lag time). Should these two lag numbers be the same?

**Comment by cxhernandez** [comment]
please refer to: https://github.com/markovmodel/PyEMMA

**Comment by tabramy** [comment]
Thanks, and apologies for posting this here.
