### ISSUE TITLE
does mdtraj support reading time dependent topology for TNG format

### ISSUE THREAD

**Issue by kash1102** [mdtraj/mdtraj#1243]
I wanted to ask if mdtraj supports reading time dependent topology for TNG format  i.e when the number of atoms are changing in each frame if yes than can someone link me to the code snippets where this part is being implemented.

**Comment by mpharrigan** [comment]
I don't think so. Large parts of the mdtraj api assume a constant topology. @peastman would know for sure, but I bet we just take the first topology and store that in the `Trajectory` object

**Comment by kash1102** [comment]
Since you guys must be updating coordinates in the trajectory object for every frame similarly we can change number of atoms. is this approach works ?

**Comment by swails** [comment]
> Since you guys must be updating coordinates in the trajectory object for every frame similarly we can change number of atoms. is this approach works ?

It's not really clear how you arrive at this conclusion.  The trajectory object contains a single topology and then a 3-dimensional array of the shape `(n_frames, n_atoms, 3)`.  This form for the data structure implies two severe constraints on the trajectory:

1. Every frame has the same number of atoms
1. Atoms appear in the same (or indistinguishable) *order* in every frame

Without some pretty serious changes to the underlying data structure in `MDTraj`, you would effectively need a separate `Trajectory` object (each with its own `Topology`) to analyze a simulation from any ensemble where N is not constant.

One thing I'll note here is that this constraint is present for *many* trajectory analysis programs.  It makes things simple and is easiest to code efficiently (significantly).

**Comment by peastman** [comment]
We use `tng_num_particles_get()` to read the number of particles, so that assumes it doesn't change.  And as @swails pointed out, that assumption runs through much of MDTraj.
