### ISSUE TITLE
what are the equation you used to calculate RMSD,SASA,PCA,RG

### ISSUE THREAD

**Issue by bioquery** [mdtraj/mdtraj#1250]
I just want to know the equation used bu you for following function or method:
(1)RMSD
(2)RG
(3)SASA
(4)PCA

please send me the email:bioquery@gmx.com

**Comment by cxhernandez** [comment]
Feel free to peruse the source code.

**Comment by marscher** [comment]
!google sasa mdtraj points you also into the right direction.
