### ISSUE TITLE
mdt.compute_phi/psi gives same angles for different geometries

### ISSUE THREAD

**Issue by jadeshi** [mdtraj/mdtraj#1252]
Hey all,
I used mdtraj to compute the phi/psi angles for these two structures:
[structs.zip](https://github.com/mdtraj/mdtraj/files/923137/structs.zip)

The phi/psi's are identical when computed with mdtraj, but the VMD generated Ramachandran plots show a few obvious discrepancies (i.e. bottom left quadrant), and the structures when rendered look very different.
![pinww_native](https://cloud.githubusercontent.com/assets/3607034/25058847/e21d5244-2132-11e7-934c-ec9362bd4703.png)
![pinww_pred](https://cloud.githubusercontent.com/assets/3607034/25058846/e21af71a-2132-11e7-8e5d-1d88923683e3.png)

Thanks in advance!
Jade

**Comment by cxhernandez** [comment]
@jadeshi: can I close this?

**Comment by jadeshi** [comment]
Yeah, go ahead.
