### ISSUE TITLE
Further TNG support?

### ISSUE THREAD

**Issue by OndrejMarsalek** [mdtraj/mdtraj#1255]
Are there any plans to support more types of data stored in TNG files like velocities and forces?

**Comment by rmcgibbo** [comment]
I don't think this kind of thing is really planned. MDTraj doesn't handle velocities or forces in the core `Trajectory` data structure anyways.

**Comment by OndrejMarsalek** [comment]
That's what I suspected. Would you be open to adding forces to the HDF5 format, which already supports a number of quantities, including velocities?

**Comment by mpharrigan** [comment]
Per #1271 I think the way forward is to slowly start modifying the hidden `_read` function for each file type and once most of them have it implemented we can think about exposing velocities and forces through the actual api

**Comment by marscher** [comment]
Please feel free to send a PR. Closing this in the mean time.
