### ISSUE TITLE
Extend definition of standard water to perceive bonds in PDB files

### ISSUE THREAD

**Issue by andrrizzi** [mdtraj/mdtraj#1256]
As far as I understand, the PDB file format doesn't require CONECT records for water molecules, so MDTraj attempts to automatically perceive the topology of the water molecules in a PDB files using the standard definitions in `mdtraj.formats.pdb.data.residues.xml`, which requires water molecules to have residue name `HOH` and atom names `O`, `H1` and `H2`. However, naming conventions for water molecules are less standard than amino acids, and different tools will create different water records (e.g. leap uses `WAT` as residue name for waters).

Would it be possible to detect water molecules independently from the specific names used used for residue/atoms? Or maybe to extend this definition to be more flexible?

Silent failing in perceiving water molecules topology recently introduced in our tools a bug that was tricky to track down (see choderalab/openmoltools#253).

**Comment by mpharrigan** [comment]
You can add alternative names here https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/data/pdbNames.xml#L272

**Comment by andrrizzi** [comment]
Ah! That's great, thanks. I missed that definition file.

Would it be ok then if I opened a PR to extend the definition to `TP3` as a residue name (used by CHARMM) and `O1` as oxygen name (used by OpenEye)?

**Comment by andrrizzi** [comment]
Actually, @jchodera suggest not to add `TP3` as it should no longer be an issue, and there's an official `TP3` residue now (http://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/TP3).

I'd still would like to add an `O1` oxygen name though.

**Comment by mpharrigan** [comment]
Go for it
