### ISSUE TITLE
Fail to install with pip.  

### ISSUE THREAD

**Issue by tbalius** [mdtraj/mdtraj#1259]
Hi,

I tried to install mdtraj with pip and failed: 
   pip install mdtraj --upgrade 

Here is the culprit line: 
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DDESRES_READ_TIMESTEP2=1 -Imdtraj/formats/dtr/include/ -Imdtraj/formats/dtr/ -I/mnt/nfs/home/tbalius/zzz.virtualenvs/virtualenv-1.9.1/myVEonGimel/lib/python2.7/site-packages/numpy/core/include -I/nfs/soft/python/versions/python-2.7.7/include/python2.7 -c mdtraj/formats/dtr/dtr.c -o build/temp.linux-x86_64-2.7/mdtraj/formats/dtr/dtr.o -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare
    gcc: mdtraj/formats/dtr/dtr.c: No such file or directory
    gcc: no input files
    error: command 'gcc' failed with exit status 1

So I used pip and download this:
  pip download mdtraj
  unzip mdtraj-1.8.0.zip
  cd mdtraj-1.8.0/

And ran the command: 
  python setup build 

and got the same error. 

If I look for the file: mdtraj/formats/dtr/dtr.c
it does not exist.

however, mdtraj/formats/dtr/dtr.cpp does exist. 

If I manually run the following:
  **g++** -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DDESRES_READ_TIMESTEP2=1 -Imdtraj/formats/dtr/include/ -Imdtraj/formats/dtr/ -I/mnt/nfs/home/tbalius/zzz.virtualenvs/virtualenv-1.9.1/myVEonGimel/lib/python2.7/site-packages/numpy/core/include -I/nfs/soft/python/versions/python-2.7.7/include/python2.7 -c mdtraj/formats/dtr/**dtr.cpp** -o build/temp.linux-x86_64-2.7/mdtraj/formats/dtr/dtr.o -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare 

it does compile. 

Am I doing something foolish or is this a bug?

**Comment by mpharrigan** [comment]
I can't reproduce this. Can you try upgrading your install of cython?
