### ISSUE TITLE
Conversion of tinker archive file to traj.xtc/traj.gro 

### ISSUE THREAD

**Issue by amithweth** [mdtraj/mdtraj#1262]
Hello all,

I installed MDTraj package in order to convert tinker.arc (tinker archive file) to gromacs gro file/traj.xtc. However I found out that there is a small bug during the conversion.
In every frame the first atom has been replaced by the box dimensions, other than that everything looks fine.

Here are the commands that I have used in python3.5 to write first 10 frames
>>> import mdtraj as md
>>> t = md.load('tinker.arc')
>>> t [0:10] .save_gro('traj.gro')

For example in tinker.arc file (first frame)....
 
12000
    66.205878   66.205878   66.205878   90.000000   90.000000   90.000000
     1  N     19.121423   25.472396  -12.366423   406     3     6     7
     2  N     19.594216   27.360442  -13.402911   407     6     8    10

 
but after the conversion .gro file looks like this.
   
Generated with MDTraj, t= 0.0
 12000
    1RES  66.205878    0   6.621   9.000   9.000
    1RES      N    1   1.959   2.736  -1.340
 

It has skipped the first atom, the first atom was replaced with box dimensions.
I'm pretty sure that this can be fix by going through the reading format of tinker.arc in MDTraj source code (most probably arc.py script) and change it according to the requirement. Have you ever found out a similar type of error and how can I fix this ?

Thank you very much !!!

W. D. Amith
Graduate Research Assistant
Department of Chemistry
University of Iowa

**Comment by mpharrigan** [comment]
Thanks for finding this bug. Do you have a small example arc file we can use to debug it?

**Comment by amithweth** [comment]
Herewith I have attached an example arc file with just one frame.


Thank you very much !!!


Regards

Amith

________________________________

**Comment by swails** [comment]
Note that the arc file doesn't NEED to have the box coordinates in the first line. It's optional.

**Comment by amithweth** [comment]
But I need those box coordinates for my analysis.



________________________________

**Comment by swails** [comment]
My point is that the parser still has to correctly parse files that do not have the box dimensions in the second line.

**Comment by mpharrigan** [comment]
Hi @amithweth , the file didn't get uploaded. I suspect email attachements don't work, and you have to attach it to a comment using the github web interface.

**Comment by amithweth** [comment]
Herewith I have attached the example arc file
[first-frame.pdf](https://github.com/mdtraj/mdtraj/files/997031/first-frame.pdf)

**Comment by amithweth** [comment]
[first-frame.zip](https://github.com/mdtraj/mdtraj/files/997097/first-frame.zip)
I also attached a zip file which has the original arc file
