### ISSUE TITLE
DeprecationWarning: generator 'iterload' raised StopIteration

### ISSUE THREAD

**Issue by OndrejMarsalek** [mdtraj/mdtraj#1263]
On Python 3.6, I get `DeprecationWarning: generator 'iterload' raised StopIteration` when using `iterload`. This is due to PEP 479. The way to silence it is described here: https://www.python.org/dev/peps/pep-0479/#id38

**Comment by mpharrigan** [comment]
Thanks for pointing this out. If I understand correctly, I think we could just change it to `return` and all will be well

**Comment by OndrejMarsalek** [comment]
I think that is the case for `iterload`, but note that elsewhere in the code `StopIteration` is also explicitly caught. Those places might need more care.

**Comment by mpharrigan** [comment]
Oh, good to know. Thought it was only in iterload :)

**Comment by OndrejMarsalek** [comment]
That's where I came across it, but a search suggests a couple more places:

https://github.com/mdtraj/mdtraj/search?q=stopiteration

**Comment by OndrejMarsalek** [comment]
Ideally, this would not go unaddressed. The above search still returns a few places where `StopIteration` is used.

**Comment by rmcgibbo** [comment]
Would you be able to file a pull request? It would help to have a failing test for example that illustrates the bug.

**Comment by OndrejMarsalek** [comment]
This is now actually resolved. Sorry I did close it earlier.
