### ISSUE TITLE
Map atom names between two different mol2 files

### ISSUE THREAD

**Issue by jeiros** [mdtraj/mdtraj#1272]
Hi all,

This might be a bit of an odd question:

I am trying to compare the charges on a small molecule to some earlier results that someone else got (using `mol2` files). I've found out _a bit too late_ that the atom names that I've used are different to the ones that I have to compare to. It's the exact same molecule, but the atoms have different names in a non-systematic way (for example, `H15` is `H8`, or `C22` is `C11`, `O1` is `O`, and so on). Is there a way to 'map' each atom in my mol2 file to it's equivalent in the second file? 

I know I could write down the equivalences by hand comparing the structures in Chimera, but I'm going to have to do this for several molecules in which this has happened and I was wondering if I could automate this with mdtraj.

Any suggestions in the right direction will be welcome since I'm a bit lost on how to approach this 😕

**Comment by rmcgibbo** [comment]
I bet you could use the `lprmsd` function to superpose the two molecules taking into account the permutation symmetry, and then match them up.

**Comment by jeiros** [comment]
Thanks! I'll take a look at it to try and make it work.

This would assume that the two molecules are in the same conformation to get the matches? Unfortunately, they are slightly different, since the conformer that was achieved from the Geometry Optimization procedure for charge derivation with RESP was different (also, I have different conformers for a given molecule, but all I really need is to get the mapping for the one I'm comparing against to see the differences in charges).

**Comment by rmcgibbo** [comment]
They would have to be in close conformations, but not exactly equivalent.
