### ISSUE TITLE
pip install fails on windows while working with conda

### ISSUE THREAD

**Issue by j0kaso** [mdtraj/mdtraj#1276]
tried to install mdtraj with 
`pip install mdtraj`
on windows (x84 and x64) but it failed. Nevertheless, it works with
`conda install -c conda-forge mdtraj`

tested with python2.7.13, pip9.0.1 and setuptools28.8.0

Are there differences in the installation versions or dependencies which could rise this error?

I attached the log from the installation with pip
[mdtraj-install-log.txt](https://github.com/mdtraj/mdtraj/files/1117204/mdtraj-install-log.txt)

**Comment by rmcgibbo** [comment]
> Are there differences in the installation versions or dependencies which could rise this error?

Yes. The difference is that with `conda`, you're installing pre-compiled binaries, whereas with `pip` you're compiling the package from source. When compiling from source, you're seeing an error related to the fact that Microsoft Visual Studio 2008 is missing some standard C header files. This issue was fixed in later versions of Visual Studio. Working around this requires installing the missing header files. (https://code.google.com/archive/p/msinttypes/)

**Comment by mpharrigan** [comment]
These compilation issues were fixed for the conda package via patches for the 1.7 release, but have been applied to master. So you should be able to pip install from master

**Comment by j0kaso** [comment]
Thanks for the explanation. 
Btw, I still run into the same error with using master, which as you say is likely the reason cause I use the Visual C++ 2008 Compiler Package for Python. I'm right now trying to set up a different version which seems to be quite messy...

**Comment by mpharrigan** [comment]
Tagging @marscher who has been maintaining compatibility for python 2.7 on windows

**Comment by marscher** [comment]
Tagging @mpharrigan who was too lazy to include my patches on master (eg. math_patches.h is unpatched).

**Comment by mpharrigan** [comment]
I thought you pull-requested them in after the conda package was built

**Comment by mpharrigan** [comment]
https://github.com/mdtraj/mdtraj/pull/1233

**Comment by mpharrigan** [comment]
@marscher are there additional patches? Can you PR them?

**Comment by mpharrigan** [comment]
Please re-open if this issue persists with the new release of v1.9
