### ISSUE TITLE
Wheels on PyPI?

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#1277]
Do we currently have a policy of not uploading wheels to PyPI for this project? I noticed we haven't put any up since maybe the 1.5.1 release.

**Comment by rmcgibbo** [comment]
(I was thinking of this in the context of #1276. We get a fair number of pip-install-compiling-from-source related issues filed.)

**Comment by rmcgibbo** [comment]
Also: it's probably fragile and against the spirit of the tools, but I think we _could_ just repack the files in the conda `.tar.bz2` archives into wheel files, at least for OS X and Windows. For linux, I think we'd run into CentOS6 glibc vs. manylinux1 issues in doing that.

**Comment by marscher** [comment]
for manywheels, you're right. Their docker file is based on CentOS 5

**Comment by hmarlo** [comment]
Having a wheel uploaded would be nice, so we can install without having Cython installed, it will be already compiled.
