### ISSUE TITLE
HDF5 Conventions tokens

### ISSUE THREAD

**Issue by salotz** [mdtraj/mdtraj#1279]
From what I can tell in the specification you suggest putting a token in the global `Conventions` variable (as well as the `ConventionVersion` (should it be `conventionVersion` like the other variables?)) that indicates a certain convention used in the HDF5 file. For instance you use the token `PANDE` for the original specification.

I am planning on making an extension as described and would add my own token. My question is how are users supposed to know what a particular token refers to. Should there be a URL to the convention page like an XML schema? Or a repo of known/trusted conventions? Has anyone else even made an extension publicly associated with mdtraj?

**Comment by rmcgibbo** [comment]
>  Has anyone else even made an extension publicly associated with mdtraj?

I suspect you're the first one to try.
