### ISSUE TITLE
md.Trajectory iteration is slow

### ISSUE THREAD

**Issue by justinrporter** [mdtraj/mdtraj#1284]
Hi all,

I've noticed that iterating through an `md.Trajectory` object can be very slow for large trajectories. Obviously, this is generally not a good idea if you can avoid it, but there situations (for example when an all-against-all comparison of two trajectories is needed) where it is difficult to avoid unless you are willing to switch to C/C++/Cython.

Here is an example of what I mean:

```python
for t in trj:
    md.rmsd(trj, t)
```

Takes about 2 seconds on my machine for a trajectory with length 200. Breaking it out into two steps reveals the problem:

```python
trj_list = [t for t in trj]
```

takes ~1 second, and

```python
for t in trj_list:
    md.rmsd(trj, t)
```

takes only 60 ms.

Taking advantage of the `md.Trajectory.slice` method's `copy=False` parameter, things can be sped up substantially:

```python
for i in range(len(trj)):
    f = trj.slice(i, copy=False)
    md.rmsd(trj, f)
```

takes only 75 ms. This is a factor of 25x faster!

I think it has to do with the way in which [`md.Trajectory.__getitem__`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L1098) leans on the default value of `copy` in [`md.Trajectory.slice`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L1102), which is `True`. This breaks with the way that numpy does things (usually creating a view unless a copy is explicitly requested), as well as the way a pure-python list of trajectories would behave (_ie_ returning a reference to each list item). That can lead to some wtfs like the following:

```python
for t in trj:
    t.xyz = np.zeros_like(t.xyz)
    
np.any(trj.xyz == np.zeros_like(trj.xyz))
```

returning `False`.

I guess my question is why? Having not investigated more deeply, I actually expected (and have been assuming for the ~1 year I've been using the library) that slicing and iteration would return in-place views.

I can think of three paths forward (there are likely others):

1. Change the default value of `md.Trajectory.slice` to `False`. This would make the indexing operator much faster, but is potentially an API-breaking change, and may be a gotcha for people.
2. Implement `__iter__` and `__next__` methods, using `md.Trajectory.slice(copy=False)` to speed up iteration over a trajectory, making it behave like a list. This would obviously be a less perturbative change, 
3. Do nothing.

**Comment by marscher** [comment]
thumbs up for solution 2.

**Comment by mpharrigan** [comment]
Thanks for the in-depth investigation. 2 seems alright, with the disadvantage that now

```python
[t for t in traj]
[traj[i] for i in range(len(traj))]
```

now have different semantics. I wonder if there's a lot of code "in the wild" that relies on a copy being performed with indexing

**Comment by marscher** [comment]
You're correct that changing the copy policy could potentially introduce 
hard to track bugs, but it very sane to assume, that Python programmers 
are aware of modifying instances in one place, will also modify the 
original source (eg. a list or dictionary). So in my opinion this 
"sanity" copy should be avoided.

Dunno about indexing issue though.

**Comment by justinrporter** [comment]
> I wonder if there's a lot of code "in the wild" that relies on a copy being performed with indexing

I honestly doubt it. I am sure that there is _some_ code, but if I had to hazard a guess, I would bet that most of the cases where this property is relied upon are actually accidental/unconsidered.

I wonder if there would be a good way to throw a warning when this property is relied upon somehow? Perhaps there's a way to introspect the underlying coordinates array flags (_eg_ `ndarray.flags.OWNDATA` or something?) to discover if doing it this way? That way we could drop a `RuntimeWarning`, or even throw a `DepricationWarning` and then later change the behavior?

**Comment by justinrporter** [comment]
I have two proposals for how to handle this. I agree with @marscher that this sanity copy is not so good, in part because it's a difference in the interfaces presented by `ndarray` and `md.Trajectory`. But I also think it sucks to change this kind of thing and potentially break depending code in a sneaky way. 

So, I propose either just doing it (and potentially breaking stuff for users) or doing a deprication cycle like so:
1. we set the default value for `copy` to `None`, then, if the value is none, do a view for `xyz`, but set `WRITABLE` to `False`.
2. in `__getitem__` (and other `xyz`-modifying functions), catch the exception  some kind of explanatory exception about what is wrong.
3. go one minor version number like this, then remove it.

One potential issue with this, however, is that some functions that don't seem like they should modify `xyz` actually _do_ (e.g. `md.rmsd`) and so this type of functionality wouldn't be available until step 3.

Thoughts?
