### ISSUE TITLE
Preferred way to iterate over residues?

### ISSUE THREAD

**Issue by patwin2** [mdtraj/mdtraj#1287]
I have what is probably a very stupid question: what is the preferred way to iterate over residues?

I'm calculating hydrogen exchange protection factors from an MD simulation using the method of Persson and Halle from their 2015 PNAS paper. They classify an amide H as "open" or "closed" in each frame of a simulation, with the criterion for "open" being 2 water oxygen atoms with 2.6 angstroms. The protection factor is just the ratio of "frames closed"/"frames open".

This was easy enough to do for one residue, but when I tried to iterate over residues, I don't get an error message, but instead all residues return 0 frames in the open state, which I know is wrong. I traced this to the fact that topology.select apparently won't recognize a variable in the selection:

 res = prot.top.select("protein and resid 342")
>>> print(res)
[2709 2710 2711 2712 2713 2714 2715 2716 2717]

in contrast:

sel = 342
>>> newres = prot.top.select("protein and resid sel")
>>> print(newres)
[]

Is this just a syntax error in how I'm putting the variable in the selection? I see that the topology has a attribute residues that is the iterator for residues, but I'm not clear on how to use it to do this.

Disclaimer: I'm mostly an experimentalist, and am pretty new to programming.

**Comment by rmcgibbo** [comment]
i think you're hitting a python syntax thing. `prot.top.select('protein and resid sel')` is just looking for atoms with the resid "sel", not atoms with the resid 342.

maybe try `prot.top.select('protein and resid %d' % sel)`

**Comment by patwin2** [comment]
That did it. Thanks. I suspected it was a stupid syntax error. In case anyone's interested, here's the code:

import mdtraj as md

def persson_halle_pf(traj, res):

	sol = traj.top.select("water and name O")
	aa = traj.top.select("protein and resid %d and name H" % res)
	closewaters = md.compute_neighbors(traj, 0.26, aa, haystack_indices=sol)

	opencount = 0
	closecount = 0

	for array in closewaters:
		if len(array) >= 2:
			opencount = opencount + 1
		else:
			closecount = closecount + 1

	if opencount != 0:
		PF = closecount/opencount
	else:
		PF = ("-")

	print("Protection Factor =")
	print(PF)
