### ISSUE TITLE
Error in wrapping serial numbers in write_gro()

### ISSUE THREAD

**Issue by tverho** [mdtraj/mdtraj#1301]
https://github.com/mdtraj/mdtraj/blob/8e85405586e549109f8865046867e1fda7f580d6/mdtraj/formats/gro.py#L407

In `formats/gro.py`, function `write_gro()`, the code says:

```
if serial >= 100000:
    serial -= 100000
```

when it should say

```
if serial >= 100000:
    serial %= 100000
```

As a result, gro files with more than 200000 atoms will become invalid.

**Comment by tverho** [comment]
The bot labeled this as wontfix but this really is a trivial bug and only requires a change of one character to fix.

**Comment by rmcgibbo** [comment]
Could you file a pull request with the change?
