### ISSUE TITLE
Overly restrictive RMSD sanity checks?

### ISSUE THREAD

**Issue by psolsson** [mdtraj/mdtraj#1304]
In doing a number of comparisons of trajectory data with structures from the PDB I bumped into a reoccurring problem with `md.rmsd`. I am getting ValueError exceptions if I provide selections (in both ref and target) which are not consistent with the other topology: fx. as selection A in topology X should be valid also for a topology Y and vice versa with a selection B in topology Y.
I've identified the follow checks in `rmsd/_rmsd.pyx` which I find may be overly restrictive (all in `rmsd(...)`):
` (atom_indices < reference.xyz.shape[1])`
i.e. all selected atom (target) indices should be within the range of the number of atoms in the reference (this is only the case if either selection is not given as argument)
` (ref_atom_indices < target.xyz.shape[1]) *`
i.e. all selected atom (reference) indices should be within the range of the number of atoms in the target (same as above)
` if not (target.xyz.shape[1] == reference.xyz.shape[1]):`
i.e. target and reference must have same number of atoms (this check should be done following the atom selection)

I think it is fairly straight-forward to resolve this, but before I proceed to change this and do a PR I'd like to consult with you to see if I'm overlooking something here.

**Comment by justinrporter** [comment]
bump--it would nice to see `rmsd` made a little less restrictive.
