### ISSUE TITLE
Adding Bond Orders to Topology

### ISSUE THREAD

**Issue by Lnaden** [mdtraj/mdtraj#1307]
I'd like to add Bond Order information to the `Topology` class to preserve additional structural information when available. 

The reason for this and the discussion of what information is needed can be found in the [OpenMM issues discussing this topic](https://github.com/pandegroup/openmm/issues/1443) and we are wanting to put something like this in [YANK to enable SMARTS string searches](https://github.com/choderalab/yank/issues/801) without having to constantly flip from MDTraj topologies to OpenMM and back again.

This would require extending information stored in the `bond` to have additional fields, and likely spin it off into its own class like `Atom` or `Residue` is. My current plan is to use the same class as the [OpenMM Topology for bond](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/topology.py#L446) which would have a `type` and a `order` fields that follow the logic outlined [here](https://github.com/pandegroup/openmm/issues/1443#issuecomment-256101964). The `type` could take either `None`, `'Aromatic'`, or `'Amide'`, and the `order` would take `None`, `1`, `2`, or `3`, instead of the OpenMM classes of `Single`, `Double`, etc.

The readers and writers for a specific file type would need to be extended to store this information if the file type supported it, such as `mol2` files.

Thoughts on the utility of this feature, implementation plan? 

cc @jchodera

**Comment by peastman** [comment]
> The type could take either None, 'Aromatic', or 'Amide', and the order would take None, 1, 2, or 3, instead of the OpenMM classes of Single, Double, etc.

In OpenMM there are six allowed bond types: None, Aromatic, Amide, Single, Double, and Triple.  That's similar to the options in a mol2 file.  We discussed this quite a lot before settling on that list.

**Comment by Lnaden** [comment]
> In OpenMM there are six allowed bond types:

And I want to preserve those, but I found the distinction between `order` and `type` a bit nebulous. From the discussion it seems the `type` is the class of the bond and the `order` is additional info assigned exclusively `Aromatic` and `Amide` type bonds; e.g. `type=Dobule, order=3` does not really make sense, but `type=Double, order=2` is redundant. 

The murkiness is compounded by the OpenEye OEMolTools repo which treats the OpenMM bond `order` as a check for the class of the bond (1,2,3) and uses the `type` field to assign aromatic, no mater what its value is ([code is here](https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py#L177-L195))

Correct me if I am mis-interpreting how `type` and `order` are suppose to be used, and also let me know if the OEMolTools is also be mis-interpreting it and I can open an issue there. I'm happy to include the bond-scheme from OpenMM almost verbatim if permitted. but thats also why I opened this issue to make sure before I start working on a PR

**Comment by peastman** [comment]
I can't speak for what OpenEye is doing.  They have their own representation of bond orders, and they need to translate other representations into it however makes sense to them.  Our goal was to be able to import bond orders from lots of different sources, and be able to preserve the most important information.  Compare the ways that OpenEye, RDKit, mol2, and SDF represent bond orders.  You'll find they're all really different from each other.

**Comment by Lnaden** [comment]
> I can't speak for what OpenEye is doing. They have their own representation of bond orders, 

True, I was using that function as example of how to use the OpenMM Bond order feature in practice since we will likely use something like that in YANK and it was confusing to me. I'll raise an issue with them to get clarity. 

> Compare the ways that OpenEye, RDKit, mol2, and SDF

Fully agree! Its part of what spawned this issue. We were deciding how to bring in bond orders in YANK now for over a month and decided to use OpenMM-type bond-orders + mdtraj search ability, but locally subclassing the MDTraj Topology would have been too hack-y, hence the this issue.

**Comment by jchodera** [comment]
I think all we need to do for now is to have MDTraj preserve the same information OpenMM stores regarding bond types/orders so that the OpenMM -> MDTraj -> OpenMM `Topology` conversion is no longer lossy. We neglected to add this to MDTraj when we introduced them into OpenMM, and need to remedy that. We're pretty confident that the information in OpenMM bond types/orders is sufficient to allow tools like RDKit and OpenEye to reconstitute small molecules correctly and then be able to deal with issues of aromaticity models subsequently within these tools.

**Comment by Lnaden** [comment]
Is there any objection to me porting over the OpenMM Topology Bonds representation to MDTraj then, and then just extending the readers/writers to parse this info if possible? Whether from a programatic or legal standpoint (since I'll mostly just be copying the OpenMM code)?

**Comment by peastman** [comment]
Fine with me.
