### ISSUE TITLE
Error converting .h5 file to .xtc

### ISSUE THREAD

**Issue by sbhakat** [mdtraj/mdtraj#1309]
I was trying to convert a .h5 file to .xtc using mdconvert but always gettingthe following error.
My command was

> mdconvert tica_trajs.h5 -o test.xtc -t top.pdb

Error

> Traceback (most recent call last):
>   File "/Users/sbhakat/anaconda/bin/mdconvert", line 6, in <module>
>     sys.exit(mdtraj.scripts.mdconvert.entry_point())
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/mdtraj/scripts/mdconvert.py", line 500, in entry_point
>     main(args)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/mdtraj/scripts/mdconvert.py", line 288, in main
>     atom_indices=atom_indices)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/mdtraj/scripts/mdconvert.py", line 401, in read
>     _data = infile.read(chunk, stride=stride, atom_indices=atom_indices)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/mdtraj/formats/hdf5.py", line 572, in read
>     total_n_frames = len(self._handle.root.coordinates)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
>     return self._f_get_child(name)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
>     self._g_check_has_child(childname)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
>     % (self._v_pathname, name))
> tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``coordinates``
> 

Any solutions will be highly appreciated?

**Comment by rmcgibbo** [comment]
How did you produce the h5 file? Is it in the [mdtraj hdf5 format](http://mdtraj.org/latest/hdf5_format.html)?

**Comment by sbhakat** [comment]
I produced this file as an output of MSMBuilder. Here it is attached and the corresponding structure file.

[TICA_h5_top_git.tar.gz](https://github.com/mdtraj/mdtraj/files/1470795/TICA_h5_top_git.tar.gz)
