### ISSUE TITLE
Import Topology from MDAnalysis?

### ISSUE THREAD

**Issue by OliverEvans96** [mdtraj/mdtraj#1311]
Is there any way to load an MDAnalysis trajectory into mdtraj?

I'm trying to use the LAMMPS [peptide example](https://github.com/lammps/lammps/tree/master/examples/peptide) with mdtraj, but I can't seem to load the topology. I'm able to do it in MDAnalysis as follows:
```
import MDAnalysis
top_data = MDAnalysis.topology.LAMMPSParser.DATAParser('lammps-6Mar15/examples/peptide/data.peptide')
top = top_data.parse()
```

And then, I was hoping that I could do something to the effect of 
```
mdtraj.load_lammpstrj('lammps-6Mar15/examples/peptide/dump.peptide', top)
```
But that produces 
```
TypeError: A topology is required. You supplied top=<MDAnalysis.core.topology.Topology object at 0x2aaaba89d6a0>
```

I also had no luck with
```
mdtraj.Topology(top)
```

Any suggestions?
Thanks!
Oliver

**Comment by mpharrigan** [comment]
Although they're both named `Topology`, the two objects are different "under the hood". You could probably write a function to convert as much data as possible from one format to the other but this doesn't exist in `mdtraj`.

Alternatively, you could save the topology from mdanalysis to some shared format (e.g.) pdb and use mdtraj to load that
