### ISSUE TITLE
atom_indices

### ISSUE THREAD

**Issue by mohanpradhan** [mdtraj/mdtraj#1312]
Hi,
I am getting an error "ValueError: atom_indices must be valid positive indices" in the following line of code

print  mdtraj.rmsd(traj1,traj2,atom_indices=np.array([91,99,110,124]),ref_atom_indices=np.array([1643,1651,1662,1676]))

Atom indices are atom nos. right?

**Comment by rmcgibbo** [comment]
How many atoms are in traj1 and traj2?

**Comment by anotherjoshsmith** [comment]
@mohanpradhan looks like the same issue was discussed in #1304, which was closed by #1392. 

@marscher can you please confirm, and close this issue?
