### ISSUE TITLE
`+` and `a` modes for low-level formats.

### ISSUE THREAD

**Issue by Lnaden** [mdtraj/mdtraj#1313]
Short version: We would like to use the MDTraj formats to to open an exiting file in a read+write mode, seek to a specific point, then operate from that point. Is there an existing solution to this already or would the formats need to be extended to support this feature?

Longer version:
We're wanting to use MDTraj's readers and writers for storing data trajectory data without having to keep the whole trajectory in memory. We would like to be able to use the writers (e.g. XTC) writer to open a trajectory file, seek to a specific point, then write trajectory data to that point. 

Right now, we can only use the formats to dump and load full trajectory information, which is untenable as we are doing replica exchange with anywhere from 20-80 trajectories, so we cannot keep them all in memory, and we cannot afford to load, append, then dump them with the MDTraj Trajectory Python object each time we want to store a new iteration. 

Our main use cases are as follows:
* Append a new set of coordinates (of equal size) to the the end of the file
* Recover from a simulation crash by reading from an iteration which is not necessarily the last one in the file, then being able to write from that iteration+1. Alternatively, read the last iteration as a way to resume or extend simulations, then resume writing without deleting the existing file.

cc @jchodera @andrrizzi

**Comment by rmcgibbo** [comment]
As you probably know, writing trajectories from a running simulation wasn't a use case that I designed around. With that said, this makes a lot of sense and the amount of surgery required to support it is probably quite small.

It depends slightly on the format. For something like NetCDF, the underlying library already supports what you need, so it just amounts to a couple lines of code to set some flags correctly and change the list of allowed modes [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/netcdf.py#L127). For XTC as well as lots of the text-based formats, the format itself is binary appendable, so there's nothing complicated to do. (I.e. as a workaround for xtc, just write two files and then concatenate them with `cat`). For DCD, every time you append you have to rewind back to the beginning of the file to update the header, so that's slightly more complex and probably less performant.

**Comment by Lnaden** [comment]
We were already using NetCDF directly to store all the trajectories in a monolith of a file, but we are finding that has some compression problems and was not the most portable solution as the act of opening the files tends to be slow depending on how big the file is. So we have have been looking at options and initially thought the XTC would make good, compressed format to use and wanted to see if we could leverage MDTraj for it since already has a wrapper and we are using many other features. 

It sounds like there really isn't a general solution here, which I figured would be the case given the diversity of formats and the code which is wrapping them, but thought it would be worth asking about. I'll tinker some more with the NetCDF format we have and see if I can't come up with something. I'd like to leave this open for a bit (the week) and see if others have ideas, then I'll close it in a few days.

**Comment by jchodera** [comment]
@lnaden: I think @rmcgibbo is saying this would be easy for most formats. Why don't we start by extending the [XTC writer](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/xtc/xtc.pyx#L176-L195) to support the `a` mode? That may be enough to enable what we are trying to do here.

Later, once enough formats have append support, we could look into extending the format-agnostic APIs to add append ability (for those formats that support it).

**Comment by Lnaden** [comment]
Ah good point, I think I did misread that.

My concern is how much time do we think would be required to put this feature into the XTC Format (from someone more familiar with it than I), then have a 1.9.1 cut of MDTraj? Or would it be preferred to enable this feature to all the writers before a cut was made? 

My other concern, is that XTC may be binary appendable, but an "append" is often controlled by the OS. Python handles its "append" mode on its own, but does the XTC format such that you can open a file in an `append` mode and then seek to arbitrary point (hence the question behind `r+w` mode)

**Comment by peastman** [comment]
This would be much harder to implement for some other formats.  For example, PDB requires some other information to go at the end of the file, after all the structures.  It's probably better to start with just adding this to the formats where it's easy and where you care about doing it.

**Comment by Lnaden** [comment]
> This would be much harder to implement for some other formats.

Which is something I am concerned about from a big picture as to "what features does MDTraj support?" question. If this only is available to the writers which its easy to do with, then you have divergent features in writers which are loosely supposed to be interchangeable.

**Comment by peastman** [comment]
I don't see that as a problem.  Different formats are different.  We can try to provide a consistent interface for all of them, but some writers will necessarily have different capabilities than others because the formats they're writing have different capabilities.

**Comment by Lnaden** [comment]
That is a very good point, I had not thought of it that way

**Comment by rmcgibbo** [comment]
Adding mode=`a` for xtc, trr, and netcdf would be the simplest ones, I believe. We're talking like 10 lines of code plus tests.

**Comment by rmcgibbo** [comment]
My point abound binary appendability is that you can, *today*, append to an xtc file by doing the following dance:

```
import tempfile
import shutil
try:
    tempd = mkdtemp()
    tempfn = tempd + 'tmp.xtc'
    my_trajectory.save_xtc(tempfn)
    with open('destination-to-append-to.xtc', 'ab') as fdest:
        with open(tempfn, 'rb') as fsrc:
            shutil.copyfileobj(fsrc, fdest)
finally:
    shutil.rmtree(tempd)
