### ISSUE TITLE
Question: Trajectories with zero length?

### ISSUE THREAD

**Issue by dwhswenson** [mdtraj/mdtraj#1319]
Is it theoretically possible to have an MDTraj trajectory of length 0?

This is for a check on something I'm doing in OpenPathSampling (https://github.com/openpathsampling/openpathsampling/pull/731). We allow zero-length trajectories in OPS; the question is whether we can convert those to MDTraj. A quick experiment raises a `ValueError` for a bad shape of `.xyz` (in `ensure_type`) if I try to give an empty list. Am I correct in assuming that this means that zero-length trajectories are not allowed?

(Note: This is a question, not a feature request. Honestly, my life might be a bit easier if MDTraj doesn't allow zero-length trajs, but if there's a way to get them, OPS should support the conversion.)

**Comment by rmcgibbo** [comment]
I believe that most things ought to work as expected with a trajectory of length. For the xyz, you'd need to give a numpy array with ndim=3 of `shape=(0, n_atoms, 3)`, not an empty list, which would be converted to an array of ndim=1 with `shape=(0,)`.

**Comment by rmcgibbo** [comment]
For example:
```
In [6]: from mdtraj.utils import ensure_type

In [7]: ensure_type(np.zeros((0,10,3)), np.float64, 3, 'xyz', shape=(None, None, 3), warn_on_cast=True, add_newaxis_on_deficient_ndim=False)

Out[7]: array([], shape=(0, 10, 3), dtype=float64)
```

But on the other hand:
```
In [8]: ensure_type([], np.float64, 3, 'xyz', shape=(None, None, 3), warn_on_cast=True, add_newaxis_on_deficient_ndim=False)  # doesn't work
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-c0a442b3a5e9> in <module>()
----> 1 ensure_type([], np.float64, 3, 'xyz', shape=(None, None, 3), warn_on_cast=True, add_newaxis_on_deficient_ndim=False)

/Users/mcgibbon/miniconda/lib/python3.5/site-packages/mdtraj/utils/validation.py in ensure_type(val, dtype, ndim, name, length, can_be_none, shape, warn_on_cast, add_newaxis_on_deficient_ndim)
    121         else:
    122             raise ValueError(("%s must be ndim %s. "
--> 123                 "You supplied %s" % (name, ndim, val.ndim)))
    124
    125     val = np.ascontiguousarray(val, dtype=dtype)

ValueError: xyz must be ndim 3. You supplied 1
```

**Comment by dwhswenson** [comment]
Thanks @rmcgibbo! This answers my question; I will close the issue.
