### ISSUE TITLE
Trajectory.superpose() does not alter box vectors

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1321]
It appears that [`Trajectory.superpose()`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L922-L982) does not rotate box vectors, leading to incorrectly imaged solvent boxes if `.image_molecules()` is called subsequently.

**Comment by jchodera** [comment]
If it sounds like it would be reasonable to add this feature (perhaps as default behavior), any pointers on how best to do so?

**Comment by peastman** [comment]
I'd think it would just make the box vectors parallel to the ones from the structure you're superposing onto.

**Comment by jchodera** [comment]
I've been trying to align a solvated biomolecule that tumbles within the solvent box onto a single frame and re-image the solvent into a rectilinear box around the solute with the following:
```python
import mdtraj
# Image trajectory
traj = mdtraj.load('in.dcd', top='in.pdb')
# Align all states onto first frame
align_atoms = traj.topology.select('name==P')
traj.superpose(traj, frame=0, atom_indices=align_atoms)
# Image water back into box
traj.image_molecules()
# Write trajectory
trajectory_temporary_filename = 'out.dcd'
traj.save('out.dcd')
traj[0].save('out.pdb')
```
MDTraj doesn't do anything to the box vectors, and when `image_molecules` is called, the resulting trajectory ends up with large gaps in the solvent volume. I've attached an example input/output.
![example](https://user-images.githubusercontent.com/3656088/34328530-e3b62f24-e8ae-11e7-9b04-79af39859858.png)
[example.zip](https://github.com/mdtraj/mdtraj/files/1585021/example.zip)

**Comment by rmcgibbo** [comment]
This is definitely a bug / missing feature. The superpose code doesn't touch (or look at) the box vectors. See e.g. [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx#L337-L341).

One relatively simple solution would be for the cython superposing function to return the [rotation matrices](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx#L378), so that Trajectory.superpose() could fix up the box vectors.

**Comment by peastman** [comment]
Note that many file formats don't support arbitrary box vectors.  They represent them as lengths and angles.  So it's required that the first vector be parallel to the x axis.

**Comment by rmcgibbo** [comment]
That could be a complication. Perhaps during the save, if requested, we'd want to do another rotation, since it would depend on the format.

**Comment by jchodera** [comment]
What about re-imaging into the original box vectors frame? That could be done, but only if the box vectors are correctly rotated with the alignment.

**Comment by therealambuj** [comment]
Hello all, I also ran into this issue recently while aligning an ab initio trajectory. Are there any pointers on how to circumvent this ? I am new to python and mdtraj but won't mind coding it on my own. Thanks in advance!

**Comment by CharlieLaughton** [comment]
I would be tempted to try something like:
1. Translate the solute to place it in the centre of the periodic box in each frame
2. Call image_molecules()
3. Do the superposition
4. Accept the fact that the box vectors are now messed up, but at least you have a (non-periodic) trajectory in which the solute is aligned and always in the middle of the water environment.

**Comment by jchodera** [comment]
@CharlieLaughton : This procedure results in a solvent box that rotates around the protein. If you try to do an analysis that involves periodic boundary conditions, the erroneous box vectors result in large voids in the middle of the solvent.

**Comment by CharlieLaughton** [comment]
True, but if, by following the above recipe, in every frame the solute is then sitting nicely in the centre of the solvent environment, and is least-squares fitted to some reference conformation, can you not get away with ignoring PBC for your subsequent analysis? (I appreciate this is a work-round, not a solution).

**Comment by jchodera** [comment]
True! But we're trying to analyze statistics of the solvent and ion environment around the solute, so we really do need the solvent box re-imaged about the solute in a sensible way.

**Comment by CharlieLaughton** [comment]
OK - well good luck with your original query, I hope a fix emerges.

**Comment by jchodera** [comment]
I *think* it should be possible to rotate the box vectors as well as the box contents, and then re-image the contents of the box back into the original box vectors, since not all formats support arbitrary box vectors. Would the MDTraj devs be OK with this solution?

**Comment by jchodera** [comment]
Sniff, we'll miss you, Issue #1321...
