### ISSUE TITLE
 undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by renato-lombardo** [mdtraj/mdtraj#1326]
Hi all,
I am trying to use mdtraj on Ubuntu 17.10 and python 2.7 but when I try to import it, I  get this error:
ERROR: Failure: ImportError (/usr/local/lib/python2.7/dist-packages/mdtraj/_rmsd.so: undefined symbol: PyFPE_jbuf)

I didn't have any problem in Ubuntu 17.04 and I don't have problems using python3.
I tried reinstalling it, without success.
Searching on Google didn't help.
Any suggestion?

**Comment by rmcgibbo** [comment]
I'm sorry, I don't really know what the problem is here. It's related to how you installed MDTraj, and possibly having two versions installed simultaneously. Googling for "PyFPE_jbuf" brings up a number of instances of this issues from many packages. I recommend reinstalling MDTraj from source.
