### ISSUE TITLE
seek multiple frames with mdtraj.load_frame ?

### ISSUE THREAD

**Issue by sstolzenberg** [mdtraj/mdtraj#1328]
Hello,

would it be possible to have 
mdtraj.load_frame
optionally load multlple frames using the underlying 
seek/read strategy from
md.formats.XTCTrajectoryFile
?

Thanks,
Sebastian

**Comment by rmcgibbo** [comment]
This is a sensible feature request. Ideally it would be implemented uniformly across all of the formats.

**Comment by rmcgibbo** [comment]
It looks like this was previously requested in #794 as well.
