### ISSUE TITLE
"within" and "chain" in md.topology.select ?

### ISSUE THREAD

**Issue by sstolzenberg** [mdtraj/mdtraj#1329]
Hello,

would it be possible for md.topology.select to have "within" and "chain" capabilities as in VMD?
E.g. to select
[atomselect top "water and within 3 of chain A"]
[atomselect top "ion and exwithin 3 of chain A and resid 77"]

Thanks,
Sebastian

**Comment by rmcgibbo** [comment]
I'll mark this as wishlist, but I think it's unlikely, to be honest. The difficult part is `within`. Currently, the selection language looks only at the topology, and doesn't do any calculations based on the positions of the atoms. This means that implementing `within` requires a relatively major upgrade.
