### ISSUE TITLE
Shrake-Rupley Parallelization?

### ISSUE THREAD

**Issue by justinrporter** [mdtraj/mdtraj#1335]
When I run the `shrake_rupley` algorithm, I don't see any benefit to using multiple cores, although it looks from `sasa()` in `sasa.cpp` that OpenMP should be being used to compute the SASA of frames in parallel.

I am measuring this by comparing walltime to used cpu time. For example, with `rmsd`:

```python
%time _ = md.rmsd(t, t)
CPU times: user 4.12 s, sys: 3.36 s, total: 7.48 s
Wall time: 243 ms
```

Here, CPU several times higher than the walltime, implying the use of many cores.

When I do the same with `shrake_rupley`:

```python
%time md.shrake_rupley(t[0:20], probe_radius=0.28, n_sphere_points=960*4)
CPU times: user 3min 11s, sys: 121 ms, total: 3min 12s
Wall time: 3min 12s 
```

Here, walltime and CPU time match, suggesting no parallelization.

Does anyone have any thoughts for how to track this down further?

**Comment by peastman** [comment]
What OS are you using?  Last time I checked, the compiler on macOS didn't support OpenMP, so it won't get parallelized on macs.

**Comment by justinrporter** [comment]
We're running RedHat.

```bash
$ cat /proc/version
Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017
```

  Also, I thought cython also uses OpenMP to do its parallelization? If so `rmsd` should fail to parallelize.

**Comment by justinrporter** [comment]
So, I've dug into the shrake-rupley code a bit, and it seems that it's using parallelization by calling OpenMP directly in the C (e.g. [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/src/sasa.cpp#L225)], whereas the rmsd code uses `prange` and the features of cython to use OpenMP (e.g. [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx#L191)).

Could the lack of parallelization be a configurational difference between the way these two pieces of code are compiled? If so, perhaps someone who knows more about that could weigh in (@peastman @rmcgibbo ?). Being a bit ignorant in the ways of OpenMP and Cython compilation, the first thing I would try is just pulling the contents of `sasa.cpp:sasa()` into a cython file and going from there, which seems a sub-optimal solution.

**Comment by peastman** [comment]
> Could the lack of parallelization be a configurational difference between the way these two pieces of code are compiled?

I think you may be right.  I notice that when it compiles the rmsd extension, it includes the flags and libraries for OpenMP: https://github.com/mdtraj/mdtraj/blob/master/setup.py#L170-L173.  But when it compiles the geometry extension, it doesn't: https://github.com/mdtraj/mdtraj/blob/master/setup.py#L217-L218.  Possibly we just need to add them and it will work.

**Comment by justinrporter** [comment]
Hmm... that means that this problem probably affects DIRD, neighbors, and potentially LPRMSD calculations as well, as all these files make use of the `#ifdef _OPENMP` check.

Any thoughts as to where this stuff is configured? I really don't know very much about python packaging.

**Comment by peastman** [comment]
It's all done in setup.py.  Just add `compiler.compiler_args_openmp` to `compiler_args`, and add `compiler.compiler_libraries_openmp` to `libraries`, same as it does for the rmsd extension.
