### ISSUE TITLE
nosetests may have some bug 

### ISSUE THREAD

**Issue by autodataming** [mdtraj/mdtraj#1340]
if the function have get_fn parameter, the test was failed.  nose may cannot recognize conftest.py file. can you give me some advice?

**nosetestsanapy2.exe  mdtraj -v**
ERROR: mdtraj.tests.test_zipped.test_write_bz2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\anaconda2py2764\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_write_bz2() takes exactly 1 argument (0 given)

----------------------------------------------------------------------
Ran 484 tests in 26.330s

FAILED (errors=317)

**pytestanpy2.exe  -v  .\tests\**
-- Docs: http://doc.pytest.org/en/latest/warnings.html
 9 failed, 925 passed, 106 skipped, 63 xfailed, 31 warnings in 792.96 seconds =

**nosetestsanapy2.exe  -v .\tests\**
======================================================================
ERROR: mdtraj.tests.test_zipped.test_write_bz2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\anaconda2py2764\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_write_bz2() takes exactly 1 argument (0 given)

----------------------------------------------------------------------
Ran 484 tests in 15.880s

**Comment by marscher** [comment]
the documentation is outdated, one should now use pytest to run the test suite.
