### ISSUE TITLE
issues importing mdtraj

### ISSUE THREAD

**Issue by reinhardtm-mpi** [mdtraj/mdtraj#1341]
Hello everyone,

I installed mdtraj successfully with conda (python 2.7). However, 

`import mdtraj`

leads to the error:
`  File "<stdin>", line 1, in <module>`
`  File "/xxx/python2.7/site-packages/mdtraj-1.9.1-py2.7-linux-x86_64.egg/mdtraj/__init__.py", line 29, in <module>`
 `   from .formats.registry import FormatRegistry`
 ` File "/xxx/python2.7/site-packages/mdtraj-1.9.1-py2.7-linux-x86_64.egg/mdtraj/formats/__init__.py", line 18, in <module>`
  `  from .tng import TNGTrajectoryFile `
`ImportError: /xxx/python2.7/site-packages/mdtraj-1.9.1-py2.7-linux-x86_64.egg/mdtraj/formats/tng.so: undefined symbol: PyFPE_jbuf`

Has anyone had a similar issue before? Am I missing any dependency?
Thanks in advance.

**Comment by chewycharis** [comment]
Hi, was this issue ever resolved? 
I also managed to install mdtraj, but using pip. And I tried to ran the nosetests and ended up with an import error that identifies this: 
ImportError: /home/.local/lib/python2.7/site-packages/mdtraj/_rmsd.so: undefined symbol: __kmpc_end_serialized_parallel
