### ISSUE TITLE
atom_slice: order of the indices

### ISSUE THREAD

**Issue by gph82** [mdtraj/mdtraj#1343]
traj.atom_slice conserves the (potentially arbitrary) order of atom_indices when selecting the coordinates, but sticks to the original, sequential order in the topology, leading to this behavior. 
``` python
sliced = igeom.atom_slice([0,1])
for aa in sliced.top.atoms:
     print(aa, aa.index, sliced.xyz[:, aa.index])
#MET1-N 0 [[ 4.38999987  3.79559994  1.90639997]]
#MET1-H 1 [[ 4.40560007  3.75        1.81830001]]

sliced = igeom.atom_slice([1,0])
for aa in sliced.top.atoms:
     print(aa, aa.index, sliced.xyz[:, aa.index])
#MET1-N 0 [[ 4.40560007  3.75        1.81830001]]
#MET1-H 1 [[ 4.38999987  3.79559994  1.90639997]]
```

Forcing the sorting prior to slicing here 
https://github.com/mdtraj/mdtraj/blob/2d7ba6458d4bfcd163cdcc940aeb399643343964/mdtraj/core/trajectory.py#L1714
and 
https://github.com/mdtraj/mdtraj/blob/2d7ba6458d4bfcd163cdcc940aeb399643343964/mdtraj/core/trajectory.py#L1717

might be a solution, but changes API behavior. If okay, happy to contribute with PR with that solution.

Otherwise, at least a line in the doc specifying that atom_indices must be sorted or else unexpected behavior can occur.

**Comment by justinrporter** [comment]
Good find!

I am wondering... could `aa.index` be made match xyz, rather than the other way around?

In other words, if I ask for atoms `[1, 0]`, maybe the resulting topology should also store atom 1 first? By analogy to pandas, where `df.iloc[[1, 0]]` will return rows 1 then 0.

**Comment by bertadenes** [comment]
Found the same bug in v1.9.3.

**Comment by weiHelloWorld** [comment]
I got the same issue, is there any update on this?

**Comment by bertadenes** [comment]
In my local repo I implemented a check for sorting and redundancy, also happy to create a pull request if OP had not.

**Comment by justinrporter** [comment]
I don't have merge bits, but maybe @rmcgibbo could say if he'd merge such a PR?

**Comment by rmcgibbo** [comment]
Sure. Which ever behavior you think is more intuitive. We could also just raise an error if they aren't sorted.

**Comment by justinrporter** [comment]
My intuition is to conserve the arbitrary order throughout, in the way `numpy` and `pandas` handle the similar problem, but I think the error option would be an easier (and good one), too!

@bertadenes @gph82 do we have already-implemented versions of either of these features?

**Comment by bertadenes** [comment]
> My intuition is to conserve the arbitrary order throughout, in the way `numpy` and `pandas` handle the similar problem, but I think the error option would be an easier (and good one), too!
> 
> @bertadenes @gph82 do we have already-implemented versions of either of these features?

Not exactly. I'm just doing it since it does exactly what I thought it should. Is there a suitable Exception one should raise or would you reckon implementing a new?
