### ISSUE TITLE
image_molecules() truncated octahedron support

### ISSUE THREAD

**Issue by mdimura** [mdtraj/mdtraj#1348]
Currently (v. 1.9.1), if a trajectory with truncated octahedron box is loaded, image_molecules() still treats it as a rectangular box and produces a botched rectangular arrangement.

**Comment by marscher** [comment]
I think mdtraj assumes triclinic cells all over the place.

**Comment by sroet** [comment]
Doing a quick google: any repeating shape that fills all of space (such as a truncated octahedron) is equivalent to a triclinic box ([initial source](http://www.omnia.md/blog/2015/8/12/triclinic-periodic-boxes) and [proof](https://www.rug.nl/research/portal/files/3251564/c3.pdf)) . So it should be correct, even if it is not the shape you expect

**Comment by mdimura** [comment]
This equivalence is probably not helpful with respect to image_molecules(), since it produces a trajectory with clashing molecules and huge chunks of empty space instead of the original octahedron cell.

**Comment by sroet** [comment]
Sounds like you are seeing the effect reported in #1321?
