### ISSUE TITLE
Performance of compute_contacts

### ISSUE THREAD

**Issue by hernan3009** [mdtraj/mdtraj#1351]
Hello,

I am using the `compute_contact`  function the following way:
```
    for block in md.iterload(traj_file, top=top_file, chunk=chunk, skip=skip,stride=stride):
        # Check http://mdtraj.org/development/api/generated/mdtraj.compute_contacts.html for details
        # Compute distances
        distances = md.compute_contacts(block, contacts=pairs, scheme='closest')
```
`pairs` is a list of pairs of residues, its length is approximately 90*4600= 414 000.

The code works, but I find it too slow. It takes about 1 minute for chunk=50. My trajectory has 1281250 frames, so I expect it takes 17 days.

I noticed that changing the chunk size does not have a large effect in the time used for processing the chunk.  For example, if chunk=5,  it takes 50.5 s for the last line. For chunk=50, takes 54.5s.

This suggest that I just can use a larger chunk, but this lead me to RAM issues. 

Although I could use another PC with larger RAM, it would takes more time than the simulation itself. So, I doubt if I am taking the right approach. My final goal is to compute the distances of 4600 molecules to 90 residues for molecules that closer than some value.

Thank you in advance

**Comment by rmcgibbo** [comment]
it sounds like it takes more time to load the trajectory than do any calculations. is that correct? what fraction of the time is spent in `compute_contacts`?

**Comment by hernan3009** [comment]
Thanks for the reply. Excuse me, the times I reported were only for the execution of `compute_contacts`. I've just measured the block loading time, which was much smaller.

Loading block time:  0.3022637367248535
Computing distances time:  54.47489833831787

**Comment by rmcgibbo** [comment]
the only way to solve your high level problem is to use a more efficient data structure then. `compute_neighbors` for example, uses a voxelhash.

**Comment by rmcgibbo** [comment]
it depends what fraction fall within the cutoff. you'll have to experiment.
