### ISSUE TITLE
Angle between helices?

### ISSUE THREAD

**Issue by jeiros** [mdtraj/mdtraj#1359]
Hello,

Is it possible to compute the angle between two helices? As in, build a vector for each helix (assuming it's linear enough) and then calculate the angle between them.

I guess I could do this by hand using MDTraj, but I'm just asking to see if you have a low level fast implementation of this that I haven't found.

Cheers

Juan

**Comment by sroet** [comment]
An angle between two helices is a bit of a poor definition. If you consider them to be 4 points (top + bottom atom of each of the helices), 2 angles exist: The proper dihedral angle and the improper dihedral angle. Anyway, `mdtraj.compute_dihedrals` is probably what you are looking for.

**Comment by jeiros** [comment]
What's the difference between proper and improper dihedral angle? I was suggesting something akin to what ambertools' cpptraj does: define a vector for each helix and get the angle between them.

**Comment by sroet** [comment]
First of all, 'improper' and 'proper' dihedral are only defined for the 2 types of 'bonded' 4 particle systems and are the angles either along a bond of a linear molecule (proper) 
![image](https://user-images.githubusercontent.com/19587267/40233736-76f9cf86-5aa4-11e8-8c52-57167fea73b1.png)

and the deviation from a plane if there is one central atom (improper)
![image](https://user-images.githubusercontent.com/19587267/40233698-5183851c-5aa4-11e8-8d36-2c313f11dc04.png)
 
Now these are not really the correct terms, but can be used to describe the two different angles that you need.

I have no experience with ambertools, but you need at least 2 angles to describe the relation between 2 vectors in 3D space. The simplest example of this are spherical coordinates. When the sphere is spanned by one vector, and the coordinate vector by the other it needs 2 angles (theta and phi).

Now when using this googled figures as an example (it is an example for spherical coordinates, but I don't have time to make one for this specific use case):
![image](https://user-images.githubusercontent.com/19587267/40232323-8a1ef3ee-5a9e-11e8-942b-d899653ef287.png)

Say one vector runs from 0->x (where rh intersects the x axis)  and the other from z (where P intersects the z axis)->P, a common dihedral (x,0,z,P) is the angle between the x0z plane and the 0zP plane (denoted as phi in the figure). 
Now, the other angle is the angle that would change if either point z or P moved along the z-axis (the vector z->P does not lay parallel to the xy-plane anymore). This angle from a plane can be calculated by an improper dihedral (z,0,x,P) (which is  a measure for the angle between the z0x plane than the 0xP plane). 
The combination of these 2 angles gives the relation between your two vectors (assuming constant r).

For MDTraj this is as easy as defining the `indices` in `mdtrja.compute_dihedrals` as `[A1,A2,B2,B1]` for the proper dihedral (A1 & A2 meaning start + end of helix A) and as `[B2,A1,A2,B1]` for the improper dihedral. 

I hope this answers your question.

**Comment by jeiros** [comment]
It does! Thanks for the detailed explanation :)

**Comment by ctk3b** [comment]
This may also be helpful for accomplishing what you want since you probably do not want to simply use 4 atom indices to describe the vectors of the two helices

http://mdtraj.org/1.9.0/api/generated/mdtraj.compute_directors.html#mdtraj.compute_directors

**Comment by sroet** [comment]
@ctk3b I am pretty sure this break horribly when the helix is broken across periodic images (eg without a trajectory that is pre-treated to make molecules whole), as does anything that is based on a center of mass (com). 
Imagine for example a cylinder of length l and radius r that is oriented along the x-axis and placed in the center of a cubic periodic box (which loops at +x,-x,+y,-y,+z,-z). The directors are based on the the center of mass (which would be placed at the center of the box) and would correctly describe the longest vector from the com to the furthest point of the helix to be (roughly) along the x-axis.
Now we translate the cylinder by +y and it is broken such that you have r ->+y and -y ->r. The com in this case would still be placed at the center of the box and if the box is actually bigger than l the longest vector from the com to the helix would be in the y direction!
There are ways of placing the center of mass in a periodic system that behave better for broken molecules (such as using a circular mean instead of an arithmetic mean, as described here: https://www.tandfonline.com/doi/abs/10.1080/2151237X.2008.10129266 ), but these are not implemented anywhere as far as I know.

**Comment by ctk3b** [comment]
Yes you would need to pre-process the trajectory. Check out:

http://mdtraj.org/1.9.0/api/generated/mdtraj.Trajectory.html?highlight=make_molecules_whole#mdtraj.Trajectory.make_molecules_whole

and related: 

http://mdtraj.org/1.9.0/api/generated/mdtraj.Trajectory.html?highlight=image_molecules#mdtraj.Trajectory.image_molecules

**Comment by jeiros** [comment]
Hi @sroet  just a small note, 

Defining the vectors you used for your example, as 0 to x and z to P, if x is A1, 0 is A2, z is B1 and P is B2, wouldn't the first dihedral be `[A1, A2, B1, B2]` instead of `[A1,A2,B2,B1]`, since the documentation says:

```
The angle is between the planes spanned by the first
    three atoms and the last three atoms, a torsion around the bond
    between the middle two atoms.
```
So indeed the `A2 - B1` would be the one capturing the phi angle, and the `[B2,A1,A2,B1]` you mention is the theta, since that is the A1 to A2 torsion.

**Comment by jeiros** [comment]
I see, I meant to say that the first vector goes from x to 0, then that'd make sense. Thanks for the clarification!

**Comment by jeiros** [comment]
Hi @ctk3b ,

Sorry for bringing this up again, but I could use some help 😄 

I'm trying to replicate the results from an old paper which does not go about in detail of how they calculated a particular 'interhelical angle'.
As you mentioned, doing this with dihedral angles from particular atoms does not capture very well in some instances the angle and I cannot replicate the results from the paper, so I thought maybe using the `compute_directors` function would refine the analysis.

My trajectories are already centered and superposed on top of the same reference structures, so I don't have to worry about translational or rotational motions.

From what I've gathered reading the docs, the function computes the vector that better describes the orientation of a particular group of residues. Once I have the vectors for each helix and frame, am I correct in calculating their angle just from the cosine formula? `cos(theta) = dot(u,v)/(norm(u)*norm(v))`

Also I'm not sure I'm using the `indices` argument of the function correctly:

```python
traj = mdtraj.load(meta.iloc[0]['traj_fn'], top=top)
# First helix is from residue 13 to 24
# Second helix is from residue 37 to 46
dirs = mdtraj.compute_directors(traj, [list(range(13, 25)), list(range(37, 47))])

# dirs has shape (n_frames, 2, 3)
# Now manually compute the angle
# Example: just the first frame
v1 = dirs[0, 0, :]
v2 = dirs[0, 1, :]
# No need to compute product of norms since they already are normalized
angle = np.rad2deg(np.arccos(np.dot(v1,v2)))
>>> 46.01
```
Now I'm a bit confused because if I load only the atoms for each helix into separate trajectories and separately compute the directors, then repeat the analysis, I get a different result for the angle:

```python
A_atoms = top.select('resid 13 to 24') # first helix
B_atoms = top.select('resid 37 to 46') # second helix

Atraj = mdtraj.load(meta.iloc[0]['traj_fn'], top=top, atom_indices=A_atoms)
Btraj = mdtraj.load(meta.iloc[0]['traj_fn'], top=top, atom_indices=B_atoms)
# First helix is from residue 13 to 24
# Second helix is from residue 37 to 46
dirsA = mdtraj.compute_directors(Atraj)
dirsB = mdtraj.compute_directors(Btraj)

v1 = dirsA[0, 0, :]
v2 = dirsB[0, 0, :]
angle2 = np.rad2deg(np.arccos(np.dot(v1,v2)))
>>> 64.37
```

Any help will be greatly appreciated 👍

**Comment by ctk3b** [comment]
> I'm still not entirely sure which angle is calculated using the formula I provided above. 

![image](https://user-images.githubusercontent.com/3527431/40675280-2419ee82-632c-11e8-8fdf-f17d10e538f2.png)

> As we discussed earlier on this thread, you kind of need two angles to specify the directions of two 3d vectors, right? 

Depends on the angle you're after. Without knowing more about what you're really trying to measure it's hard to recommend which angle you should be computing.
