### ISSUE TITLE
Fast and direct way to get the number of atoms in a residue

### ISSUE THREAD

**Issue by hernan3009** [mdtraj/mdtraj#1360]
I wish to obtain the number of atoms of a residue knowing the residue name. For example, "how many atoms has a residue of 'HOH'.

Although I could solve this problem by creating a function, it takes me 5 or more lines to accomplish the job, and it involve loops.  I think that maybe I missing something.

Is there a fast and direct way?

Thanks

**Comment by peastman** [comment]
You're assuming there's a universal correspondence of residue name to number of atoms.  That isn't necessarily true.  For example, even though a physical water molecule contains three atoms, some water models include four or five particles.  Usually you can at least assume that all the water molecules in a given Topology will have the same number, but it may vary between Topologies.  But for other residues that won't always be true.  For example, different HIS residues may have different numbers of atoms depending on how they're protonated.  Residues at the end of a chain will also generally have one or two extra atoms.  And CYS residues will vary depending on whether they form disulfide bonds.

So you can ask how many atoms a particular residue has, but it may not be the same for all residues of that type.

**Comment by hernan3009** [comment]
Thank you. You are right. What I wanted has not sense.

Regards
