### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1362]
Is there anything urgent blocking a release? The previous dcd stride handling breaks some parts of PyEMMA so it would be very nice to have this one soon. We could also go for a patch release, eg. 1.9.3

**Comment by cxhernandez** [comment]
Let me add a test for #1242, and perhaps can do a release this week!

**Comment by marscher** [comment]
@peastman somebody revealed to me, that you are willing to do the release management by now. It would be most appreciated to have a release soon, because this DCD stride bug is serious (for PyEMMA).

**Comment by peastman** [comment]
Who told you that?  I haven't had much involvement in MDTraj development for quite a while, and I don't know anything about how releases are done.
