### ISSUE TITLE
Bfactor limited to - 10;100

### ISSUE THREAD

**Issue by tubiana** [mdtraj/mdtraj#1363]
Greatings!

I want to use the bfactor field to write on a pdb my own calculated property, but this field seems to be locked for value only between - 10 and 100.
Bfactor can be greater than 100 and this field can be used to add other properties. Is it possible to remove this values range (pdbfile.py lines 318, 319) for the next version? 

Kind regards,
Thibault Tubiana.

**Comment by justinrporter** [comment]
Link: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L318

It looks like this was added by @schwancr when he originally added the b-factor code--Christian, do remember why you picked this range originally?
