### ISSUE TITLE
Topology pickle broken

### ISSUE THREAD

**Issue by justinrporter** [mdtraj/mdtraj#1366]
Pickles made with versions <= 1.9 cannot be manipulated using the code at `master`.

For example, 

```python
import pickle

with open('path/to/pickle-v19.pkl', 'rb') as f:
    centers = pickle.load(f)
    atms = centers.top.select('(name N or name C)')
    centers.atom_slice(atms)
```

gets:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-16f63eb40072> in <module>()
      5
      6 atms = centers[0].top.select('(name N or name C)')
----> 7 centers[0].atom_slice(atms)

/home/jrporter/miniconda2/envs/std3/lib/python3.6/site-packages/mdtraj-2.0.0.dev0-py3.6-linux-x86_64.egg/mdtraj/core/trajectory.py in atom_slice(self, atom_indices, inplace)
   1715         topology = None
   1716         if self._topology is not None:
-> 1717             topology = self._topology.subset(atom_indices)
   1718
   1719         if inplace:

/home/jrporter/miniconda2/envs/std3/lib/python3.6/site-packages/mdtraj-2.0.0.dev0-py3.6-linux-x86_64.egg/mdtraj/core/topology.py in subset(self, atom_indices)
    933             like to retain.
    934         """
--> 935         return _topology_from_subset(self, atom_indices)
    936
    937     def select_expression(self, selection_string):

/home/jrporter/miniconda2/envs/std3/lib/python3.6/site-packages/mdtraj-2.0.0.dev0-py3.6-linux-x86_64.egg/mdtraj/core/topology.py in _topology_from_subset(topology, atom_indices)
    113             newTopology.add_bond(old_atom_to_new_atom[atom1],
    114                                  old_atom_to_new_atom[atom2],
--> 115                                  type=bond.type,
    116                                  order=bond.order)
    117         except KeyError:

AttributeError: 'tuple' object has no attribute 'type'
```

If I fall back to v1.9.1, there's no problem.

Could this be related to @Lnaden 's fixing of that bond order issue?

Example broken pickle (zipped, because github won't attach '.pkl' files): [pickle-v19.pkl.gz](https://github.com/mdtraj/mdtraj/files/2146104/pickle-v19.pkl.gz)

**Comment by rmcgibbo** [comment]
This is generally a problem with the pickle format. I don't think you can count on them to be forward-portable between different versions of the library.

**Comment by marscher** [comment]
Robert is right, magic needs to be done to solve this, but it is possible (state manipulation on unpickling).

**Comment by marscher** [comment]
On 01.07.2018 16:25, Justin R. Porter wrote:
>> magic needs to be done to solve this
> 
> I agree this isn't worth it.
> 
> I'm curious, though, how would you serialize a group of topologies (or, better, single-frame trajectories) to a single file in a future-proof way? The reason this came up is that I needed to save a list of trajectories with different topologies, so I pickled them.
> 

I have a code in PyEMMA to do this. I use state customization and HDF5
as file backend. The serialized objects are only forward compatible.
This is achieved by state patching prior unpickling and the code for
patching it is contained in the class. Every time the class is
refactored, the programmer has to provide patches for every version of
the class. For each intermediate version every patch is executed
sequentially.

As you see things can get quite complicated.

To solve your problem you should simply use a quasi standard topology
format and wrap the files in HDF5/zip etc. This would save you a lot of
trouble I'd guess.

**Comment by justinrporter** [comment]
Hm. Yes, this does sound quite complicated. One thought I had--going way back--was to implement a way of serializing to subnodes in an HDF5 file, so that you could store multiple, independent trajectories in the same file.

Perhaps the time has come to actually do this...
