### ISSUE TITLE
notebooks no longer work on website

### ISSUE THREAD

**Issue by fraserlab** [mdtraj/mdtraj#1369]
e.g. http://mdtraj.org/home/travis/build/mdtraj/mdtraj/docs/_build/html/examples/centroids/centroids.ipynb returns a 404 Not Found

**Comment by rmcgibbo** [comment]
It's likely the case that something in https://github.com/mdtraj/mdtraj/blob/master/docs/sphinxext/notebook_sphinxext.py is out of date with respect to the latest  IPython.

It also looks like this has been the case since about 1.7.2, which was released 2 years ago.
