### ISSUE TITLE
Problem with importing MDtraj

### ISSUE THREAD

**Issue by batoolm** [mdtraj/mdtraj#1377]
MDtraj works very well in my Mac but when I tried to install it in linux, it seems to be installed fine in the command line but can't be imported in python. 

I connect to linux remotely (Red Hat Enterprise Linux Server), created my own environment and install all the packages there. I tested with _nosetests mdtraj -v_
Ran 0 tests in 0.002s
OK
Also, when I checked _conda list -n myenv_, I found it successfully installed.
mdtraj                    1.9.1            py36h447964c_2    conda-forge
However, when I open Jupyter notebook and import it 
_import mdtraj as md_
it says: 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-19def7c8408e> in <module>()
----> 1 import mdtraj as md
ModuleNotFoundError: No module named 'mdtraj'

I tried to uninstall it with conda and install it again with pip but nothing changed. 
Please note that I have numpy and all the other packages installed with conda are working just fine in linux (e.g.openmm, pandas, ...).

I spent 3 hours trying to figure out the problem but can't make it work. Can you help me, please?

Many Thanks,
Batool

**Comment by rmcgibbo** [comment]
Take a look at the output of `which pip`, `which conda`, and `which nosetests`, `which jupyter`. The most likely thing is that you're `nose`/`jupyter` from one python installation, but you installed `mdtraj` into a different installation of python.

**Comment by batoolm** [comment]
Thank you for your reply, 

mdtraj is listed under 
packages in environment at /anaconda3:
which only has python 3.6

And when I look at the output of 
[batool@lxc ~]$ module load anaconda3
[batool@lxc ~]$ which python
/apps/anaconda/anaconda3/bin/python
[batool@lxc ~]$ python -V
Python 3.6.5 :: Anaconda, Inc.
[batool@lxc ~]$ which pip
/apps/anaconda/anaconda3/bin/pip
[batool@lxc ~]$ which conda
/apps/anaconda/anaconda3/bin/conda
[batool@lxc ~]$ which nosetests
/apps/anaconda/anaconda3/bin/nosetests
[batool@lxc ~]$ which jupyter
/apps/anaconda/anaconda3/bin/jupyter 

I still don't know what might be the problem. Can I ask for any more suggestion, please?

**Comment by marscher** [comment]
which jupyter?

**Comment by batoolm** [comment]
Even without using jupyter notebook, when I import it in python, it says ModuleNotFoundError: No module named 'MDTraj'

**Comment by marscher** [comment]
python -c 'import mdtraj' not 
python -c 'import MDTraj'

**Comment by batoolm** [comment]
Sorry, I did them both. I used to write it as mdtraj then I start to play with it when it didn't work. 
mdtraj in /home/batool/.conda/envs/myenv/lib/python3.6/site-packages (1.9.1)

Sorry, can I ask what did you mean with which jupyter?

**Comment by marscher** [comment]
so now you are using "myenv" as conda environment. What does conda list -n myenv | grep mdtraj say?

I thought you were trying to import from a jupyter notebook, related to the hint Robert has given, I assumed you might use the wrong env.

**Comment by batoolm** [comment]
I'm sure of the environment because I created it myself and I always make sure all the packages are installed in it. As I mentioned in my first post, it's listed under ( conda list -n myenv ).
I did 
conda list -n myenv | grep mdtraj
and I got this:
mdtraj                    1.9.1            py36h447964c_2    conda-forge

**Comment by marscher** [comment]
And you can also reproduce this using another (fresh) env?

**Comment by batoolm** [comment]
Oh, thank you. I created a new env and re-installed Jupyter and mdtraj with pip in the new env. Now everything works very well. It must have been something wrong with env. Thank you so much for your help.
