### ISSUE TITLE
mol2 test failure on py27

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1387]
================================== FAILURES ===================================
```
________________________ test_load_all_mol2[adp.mol2] _________________________
mol2_file = 'adp.mol2', get_fn = <function _get_fn at 0x089200B0>
    @pytest.mark.parametrize('mol2_file', [('li.mol2'),
    ('lysozyme-ligand-tripos.mol2'), ('imatinib.mol2'),
    ('status-bits.mol2'),('adp.mol2')])
    def test_load_all_mol2(mol2_file, get_fn):
>       trj = md.load_mol2(get_fn(mol2_file))
tests\test_mol2.py:156: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\_test_env\lib\site-packages\mdtraj\formats\mol2.py:130: in load_mol2
    top = Topology.from_dataframe(atoms_mdtraj, bonds_mdtraj)
..\_test_env\lib\site-packages\mdtraj\core\topology.py:510: in from_dataframe
    a = Atom(atom['name'], elem.get_by_symbol(atom['element']),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
symbol = 'O3'
    def get_by_symbol(symbol):
        s = symbol.strip().upper()
>       return Element._elements_by_symbol[s]
E       KeyError: 'O3'
..\_test_env\lib\site-packages\mdtraj\core\element.py:230: KeyError
=========================== short test summary info ===========================
```

**Comment by marscher** [comment]
@rmatsum836 Your introduced test uses 'O3' as element name, which suprisingly only raises this error on Python 2.7. Can you please have a look again?

**Comment by mattwthompson** [comment]
I think `O3` is not a valid SYBYL atom type, so changing it to `O.3` would make it more proper. But I'm not entirely sure because I don't work with SYBYL and I'm not sure which google result is the correct documentation.

**Comment by marscher** [comment]
On 10/1/18 5:00 PM, Matt Thompson wrote:
> I think |O3| is not a valid SYBYL atom type, so changing it to |O.3| 
> would make it more proper. But I'm not entirely sure because I don't 
> work with SYBYL and I'm not sure which google result is the correct 
> documentation.

Thanks for the insight. The funny thing is that is passing on Python3, 
shouldn't the atom type also be invalid there?

**Comment by rmatsum836** [comment]
For this test, I just included all of the existing mol2 files in `data` to load in.  I missed this error since I use Python 3.5.  Regardless it seems that the mdtraj mol2 reader was originally written to be compatible with Sybyl mol2 atom types, which I don't believe `O3` is a valid Sybyl mol2 atom type.

In reference to #1378, `'O3'` would have previously been acceptable since `'O3'.strip(".")[0]` would have simply returned `O`.

To fix this test, I think we should simply fix these mol2 files to have valid Sybyl mol2 atom types or simply the element names.

However, I'm not sure why this test only fails for Python2...

**Comment by rmatsum836** [comment]
Seems like @mattwthompson already answered your question.  Fixing the atom types in `adp.mol2` and `imatinib.mol2` should causes this test to pass for all builds.

**Comment by mattwthompson** [comment]
It would be useful for us to agree on whether or not the atom types in [that](https://github.com/mdtraj/mdtraj/blob/master/tests/data/adp.mol2) file and others are valid. I don't know where they came from but we should be open to changing them if they fail to meet SYBYL or some other specification. It's just that I don't know enough about the file format to be conclusive - hopefully somebody else does?

**Comment by rmatsum836** [comment]
Right, we should change them only  _if_ they do not meet SYBYL specifications.  The following list displays a list of SYBYL atom types: http://scbx.mssm.edu/mezeilab/molmod/gold_docs/gold.1.290.html

**Comment by marscher** [comment]
When trying to convert adp.mol with OpenBabel one gets a fairly long list of errors. So I think we should just replace this test file with something which complies with the de facto standard.
[conversion_errors.txt](https://github.com/mdtraj/mdtraj/files/2457467/conversion_errors.txt)
