### ISSUE TITLE
Incorrect assignment of positions/types in hoomdxml reader

### ISSUE THREAD

**Issue by summeraz** [mdtraj/mdtraj#1389]
I've come across an issue today that appears to be related to the assignment of positions and atom types (names) when reading from a Hoomd XML file. Digging a bit deeper, the issue appears to affect all systems that contain _both_ molecules (i.e. having bonds) and single particles.

[As the topology is being built](https://github.com/mdtraj/mdtraj/blob/ec8ac223cc2dc20c1df21a79e3420db205a54320/mdtraj/formats/hoomdxml.py#L112-L121), atoms are [first added](https://github.com/mdtraj/mdtraj/blob/ec8ac223cc2dc20c1df21a79e3420db205a54320/mdtraj/formats/hoomdxml.py#L117) for all particles that are part of a chain; this is followed by [adding all particles that are not part of any bonds](https://github.com/mdtraj/mdtraj/blob/ec8ac223cc2dc20c1df21a79e3420db205a54320/mdtraj/formats/hoomdxml.py#L121). As a result, the order of atoms within the `Topology` is not guaranteed to be the same as the order of atoms in the XML file. This becomes a problem when the `Trajectory` is built, as [the order of the `positions` array loaded from the XML file is not updated](https://github.com/mdtraj/mdtraj/blob/ec8ac223cc2dc20c1df21a79e3420db205a54320/mdtraj/formats/hoomdxml.py#L126). As a result, positions will be assigned incorrectly unless all atoms that were part of chains happened to be listed first within the XML file.

I've attached a [minimal example](https://github.com/mdtraj/mdtraj/files/2451018/example.zip) of this for a box of water containing some ions. The `position` and `type` sections of the XML look like this:
```xml
<position units="sigma" num="302">
20.0    20.0    20.0 
30.0    30.0    30.0 
24.07900047302246   10.14900016784668   16.643999099731445
25.046998977661133  9.96500015258789    16.474000930786133
...
25.14900016784668   0.04100000113248825 42.55500030517578
</position>
<type>
Cl
Na
O
H
...
H
</type>
```
However, when running the following script to query the position of the sodium ion:
```python
import mdtraj as md

filename = 'water-box.hoomdxml'
traj = md.load_hoomdxml(filename)
sodium = traj.top.select("name 'Na'")
sodium_slice = traj.atom_slice(sodium)
print(sodium_slice.xyz)
```
the output is:
```
[[[2.5149e+01 4.1000e-02 4.2555e+01]]]
```
which is the position of the last atom in the XML (a hydrogen), rather than the expected position of ```[[[3.0000e+01 3.0000e+01 3.0000e+01]]]```.

**Comment by rmcgibbo** [comment]
(cc @tcmoore3 who contributed that code)

**Comment by rmcgibbo** [comment]
If you have an idea bout how to fix this, feel free to file a PR.
