### ISSUE TITLE
RunTimeWarning with numpy 1.15.0

### ISSUE THREAD

**Issue by jht0664** [mdtraj/mdtraj#1390]
Hello,

I recently installed mdtraj (v 1.9.2) with miniconda (python=3.6.6) and numpy 1.15.0 on Linux server.
When I do `import mdtraj`, it makes warning message like:
```
/home/htjung/miniconda3_env/envs/mdtraj_env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/htjung/miniconda3_env/envs/mdtraj_env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
```
which does not be shown with numpy 1.14.5.

**Comment by marscher** [comment]
I've just looked into the build logs on conda-forge, mdtraj has been built against numpy version 1.9.3 for Python3.6. So mdtraj can not be the culprit here, but something which is imported within mdtraj.

@jht0664 maybe you can provide a traceback by turning the warning into an error:

`python -W error -c 'import mdtraj'`

**Comment by marscher** [comment]
```
Traceback (most recent call last):                                                                                                                                          
  File "<string>", line 1, in <module>                                                                                                                                      
  File "/home/marscher/miniconda3/envs/plot/lib/python3.6/site-packages/mdtraj/__init__.py", line 29, in <module>                                                           
    from .formats.registry import FormatRegistry                                                                                                                            
  File "/home/marscher/miniconda3/envs/plot/lib/python3.6/site-packages/mdtraj/formats/__init__.py", line 4, in <module>                                                    
    from .dcd import DCDTrajectoryFile                                                                                                                                      
  File "__init__.pxd", line 155, in init dcd (mdtraj/formats/dcd/dcd.c:11272)                                                                                               
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
```

So it is within the dcd extension built on conda-forge. Really strange...

**Comment by jht0664** [comment]
@marscher I see. I did not recognize mdtraj has been build with the specific numpy version. In my case, if I did not choose the specific numpy version 1.9.3, conda automatically would install latest version of numpy (1.15.0). For example, to make my virtual environment `mdtraj_env`, I commanded like:
`conda create -n mdtraj_env python=3.6 mdtraj -c conda-forge`

Anyway, as for combination of numpy 1.15.0 with mdtraj 1.9.2, I got the same message what @marscher did above.

**Comment by marscher** [comment]
https://github.com/numpy/numpy/pull/432

**Comment by marscher** [comment]
On 10/8/18 4:36 PM, Hyuntae Jung wrote:
> @marscher <https://github.com/marscher> I see. I did not recognize 
> mdtraj has been build with the specific numpy version. In my case, if I 
> did not choose the specific numpy version 1.9.3, conda automatically 
> would install latest version of numpy (1.15.0). For example, to make my 
> virtual environment |mdtraj_env|, I commanded like:
> |conda create -n mdtraj_env python=3.6 mdtraj -c conda-forge|
> 
> Anyway, as for combination of numpy 1.15.0 with mdtraj 1.9.2, I got the 
> same message what @marscher <https://github.com/marscher> did above.
> 

usually the numpy binary interface should be future compatible, so we 
build with a very old still compatible version and use a recent one at 
runtime. So if you just install from conda-forge conda will always 
install the most recent numpy version unless restricted by something else.

**Comment by jht0664** [comment]
I got it. Thank you for your help.
