### ISSUE TITLE
1.9.3 bugfix release?

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1393]
#1382 fixes what was a critical bug for mbuild, which uses mdtraj to read mol2 files. Our unit tests can't read in mol2 files using 1.9.2, the latest release on conda (see our travis [logs](https://travis-ci.org/mosdef-hub/mbuild/builds/441852103?utm_source=github_status&utm_medium=notification) from today, which fails many times by what is described in https://github.com/mdtraj/mdtraj/issues/1379). We can pin to 1.9.1 in the mean time, but for obvious reasons that's not a desired solution. Is there any way we can convince the devs (@cxhernandez?) to stitch together a patch release (1.9.3)?

**Comment by marscher** [comment]
IMO we should fix the test for mol2 first prior releasing. I think we have somehow agreed that the test case is faulty, but I lack the knowledge to fix this. Please file another PR on this and we can release very soon. Thank you!

**Comment by mattwthompson** [comment]
I think we should be ready for a 1.9.3 release? We've had a good number of PRs merged since 1.9.2.
