### ISSUE TITLE
mol2.py bug

### ISSUE THREAD

**Issue by pingjun2000** [mdtraj/mdtraj#1397]
mdtraj.formats.mol2.py line 122:
        bond_augment[:, 0] = [float(bond_type_map[bond_value]) for bond_value in bonds["bond_type"].values]

should be:

        bond_augment[:, 0] = [float(bond_type_map[**str**(bond_value)]) for bond_value in bonds["bond_type"].values]

since bond type for some mol2 file without 'am' or 'ar' bond type will be read as integer array.

**Comment by mattwthompson** [comment]
This has been updated in [master](https://github.com/mdtraj/mdtraj/blob/34f77aaf767f27d486e8f4762c08fbfd5d3ea03e/mdtraj/formats/mol2.py#L122) (see #1382 #1379). You're probably using a version from conda, which still has this bug until we make a new released. But in the meantime, you can clone master for a development version.
