### ISSUE TITLE
Flush XTC file

### ISSUE THREAD

**Issue by cescgina** [mdtraj/mdtraj#1406]
Is there a way to flush an XTCTrajectoryFile? I am running the XTCReporter from #1403 and it seems that until the file is closed nothing is written to disk. The XTCTrajectoryFile object does not have a flush method neither a fileno method to call os.fsync.

**Comment by marscher** [comment]
We should definitely bind xdrlib.flush to the cython extension and call 
it for a chunk of frames to avoid data loss (e.g. hitting wall times on 
compute nodes etc.)
