### ISSUE TITLE
Incomplete set of results

### ISSUE THREAD

**Issue by FNunes1996** [mdtraj/mdtraj#1408]
Good afternoon,

I am trying to obtain the director of a set of molecules, however when I print the result it appears incomplete, is it possible to tweak mdtraj in order to display the full set of results?

Thank you for your time

**Comment by rmcgibbo** [comment]
You may have to be more specific. I for one don't really understand what you're talking about.

**Comment by cxhernandez** [comment]
Please share some example code if possible!

**Comment by FNunes1996** [comment]
For example, I am trying to compute the directors of a system containing 1022 molecules of 5CB and bear in mind that my python skills are very poor.

And this is what kind of code i am using

import mdtraj as md
traj = md.load("path to trajectory", top = 'path to topology')
indices= [[x+n for x in range(38)] for n in range( 0, 49172, 38)]
S2 = md.compute_directors(traj, indices)
import csv
with open('directors.csv', 'w', newline='') as f:
        thewriter = csv.writer(f)
        thewriter.writerow(['T(ns)', 'S2'])
        thewriter.writerow([[(0, 2)], S2])

And when  I run the script it only contains 6 vectors instead of 1022 and I am wondering if I could display the whole system instead of only the six vectors.

**Comment by FNunes1996** [comment]
Yes I could print both of the stuff,

print(S2.shape) = (1, 1294, 3)
print (traj.n_atoms) = 49172

These were the results

**Comment by FNunes1996** [comment]
Yes I could print both of the stuff,

print(S2.shape) = (1, 1294, 3)
print (traj.n_atoms) = 49172

These were the results

**Comment by ctk3b** [comment]
Check out the docs here: http://mdtraj.org/1.9.0/api/generated/mdtraj.compute_directors.html#mdtraj.compute_directors
http://mdtraj.org/1.9.0/api/generated/mdtraj.compute_nematic_order.html#mdtraj.compute_nematic_order

The `indices` argument is used to _define_ what you want to consider individual molecules/groups to compute directors for. The way you've written it, every 38 atoms form a molecule/group.

The shape of the output vector (you've called it S2 but that usually refers to the nematic order parameter) is 49172/38=1294 molecules and for each of those a length 3 vector.

**Comment by FNunes1996** [comment]
[array([[-0.47604601,  0.58800698,  0.65393271],
       [-0.53072284, -0.47344226, -0.70298343],
       [-0.39875472,  0.10126985,  0.9114489 ],
       ...,
       [-0.76269017, -0.10020591, -0.63895421],
       [-0.81655583, -0.4561305 ,  0.35381003],
       [ 0.07972657, -0.52323729, -0.84844941]])]

That is how my output is shown, and I don't know what is the meaning of the three points.
That is why I think it should be shown 1294 vectors.
One for molecule.

**Comment by ctk3b** [comment]
> That is why I think it should be shown 1294 vectors.
One for molecule.

There are exactly 1294 vectors, one per molecule.

> That is how my output is shown, and I don't know what is the meaning of the three points.

Those three points are the x, y and z components of the 1294 vectors.

---

What exactly are you trying to compute?

The [function that you're using](http://mdtraj.org/1.9.0/api/generated/mdtraj.compute_directors.html#mdtraj.compute_directors) computes a vector describing the orientation of each molecule. The red arrows in this diagram are a good way to think about it.

![image](https://user-images.githubusercontent.com/3527431/49812217-c8392c80-fd19-11e8-9861-e9df5253cc09.png)

**Comment by FNunes1996** [comment]
I am trying to compute the average of all the directions.

But I can't because if I print the outputs only shows those vectors that I showed.

(Sorry for wasting your time, but my python skils are close to inexistent)

**Comment by FNunes1996** [comment]
Not the three values, I understood that those values were the coordinates, but the suspension points after the first three vectors.

**Comment by ctk3b** [comment]
Ooooo you're asking about why Python displays `...,` in the middle of the array output?

When you print an array in an interactive interpreter it can shorten the output like that just to not dump all 1294 entries on your screen. The data is all still in the array as evidenced by your `S2.shape` result.

Does that answer your question?

To compute averages, use `numpy.mean` on the array. https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

You'll probably want `numpy.mean(your_array, axis=0)` in order to get the average x, y and z values (if I understand your goal correctly)
