### ISSUE TITLE
Clean installation on Mojave (via pip/conda) requires conda-forge lapack?

### ISSUE THREAD

**Issue by alexholehouse** [mdtraj/mdtraj#1410]
Not so much an issue, but something to note if other people run into this issue.

[*NOTE*: installing `mdtraj` via `conda-forge` as recommended [`conda install -c conda-forge mdtraj`] works fine, so this is far from a critical issue].

Apparently - for whatever reason–  the recent Xcode 10/Mojave update has caused various issues with library includes (some discussion around the web on this, but all fairly package specific). 

I recently had to fully re-install my entire setup from scratch - I manage Python packages via `conda` with an embedded `pip` where required. Anyway - long story short, I could not install `mdtraj` via `pip` and kept getting the same error:

```
    In file included from mdtraj/formats/dtr/dtr.cpp:661:
    mdtraj/formats/dtr/include/dtrplugin.hxx:48:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    2 warnings and 1 error generated.
    error: command 'clang' failed with exit status 1
```

Having got this (reproducibly) working the key steps which seem critical:

1) Install XCode (I used the version from the Appstore [Oct 30 2018 release], although there's some discussion as to if this is the best way to get XCode).

2) Install the XCode command-line tools (I did this in the opposite order, which again is apparently the 'wrong' order though things seemed to have worked out.

3) Once all standard dependencies are installed via `conda` I ALSO then had to run
`conda install -c conda-forge lapack`. I do not know why this should fix a library issue with the Clang C++ compiler, but, proof is in the pudding - can reproducibly not install mdtraj before this but works after. 

Hopefully this saves someone some time/effort. No need to keep this issue open, unless there is reason to believe this is actually an `mdtraj` issue - my hunch is this is some weird OSX config. problem and not worth trying to figure out given it appears solvable.

**Comment by marscher** [comment]
Thanks for sharing this! I'm not a Mac user, so I can not try to reproduce it. As you said it is not critical, because we have working binaries.

**Comment by mattwthompson** [comment]
I've had a handful of issues with MDTraj and other packages since upgrading to Mojave. I think it's related to macOS playing fast and loose with clang and gcc and/or which libraries are linked

**Comment by machism0** [comment]
I ran into the same issue while trying to compile mdtraj on mac os x.

@mattwthompson had a good solution.
