### ISSUE TITLE
Difference between resid and residue in top.select

### ISSUE THREAD

**Issue by asgharrazavi** [mdtraj/mdtraj#1413]
When using the top.select command, apparently, there is no difference between selection commands `resid` and `residue`. For example: top.select('residue 10') and top.select('resid 10'), return the same residue and the residue numbering for both `resid` and `residue` starts from 0. In VMD `resid` refers to actual residue number from pdb file. Is there a way to select residues according to their actual residue numbering from pdb file in mdtraj?

**Comment by justinrporter** [comment]
This is documented [here](http://mdtraj.org/latest/atom_selection.html).

I don't use VMD regularly, but based on your description, the VMD semantic and the MDTraj semantic should be the same. Could it be that the PDB you're using happens to be numbered such that `resid[i] == residue[i]`?

**Comment by asgharrazavi** [comment]
Testing on several pdb files, seems that `redidue` of mdtraj is equivalent to `resid` in VMD. Thanks.

**Comment by justinrporter** [comment]
Glad to help. Cheers!
