### ISSUE TITLE
Cannot read or wrap DCD files previously written with MDTraj on windows

### ISSUE THREAD

**Issue by PaulNobrega** [mdtraj/mdtraj#1415]
I am unable to read a DCD file created with DCDReporter using the following line:

traj = md.load("reporter.dcd", top="initialstate.pdb")

**The resulting error is:**
File "mdtraj/formats/dcd/dcd.pyx", line 134, in dcd.load_dcd (mdtraj/formats/dcd/dcd.c:2241)
File "mdtraj/formats/dcd/dcd.pyx", line 221, in dcd.DCDTrajectoryFile.__cinit__ (mdtraj/formats/dcd/dcd.c:2767)
OSError: Could not open file: "...\reporter.dcd"

I can use the command line utility "mdconvert" to convert the reporter.dcd file to pdb.  The file is also read into VMD without issue.

I also noticed that I cannot re-image dcd files or pdb files created by the reporter class using: md.Trajectory.image_molecules.  In these cases there is no complaint of error. However, the resulting output is identical to the input.  In these cases I have no issues wrapping them in VMD so I know the files are in the right format.

**Comment by rmcgibbo** [comment]
Is something wrong with the path? `Could not open file` suggests that you're trying to load a file that doesn't exist.

**Comment by PaulNobrega** [comment]
Thanks for the reply.  It looks like full path (and re-imaging) is not supported for windows:

code
------------------
def dcd_to_wrappedpdb(dcdfile, initialstatepdb, outputfile):
    if not os.path.isfile(dcdfile):
        print("File Does Not Exist!")
        return False
    else:
        print("File Exists!")
        traj = mdt.load(dcdfile, top=initialstatepdb)
        traj = mdt.Trajectory.image_molecules(traj, inplace=True)
        traj.save_pdb(outputfile)
    return True

Output
------------------
When dcdfile = "trajectory.dcd" 
    >>>"File Exists!"
                ValueError: Buffer dtype mismatch, expected 'intp' but got 'long'
                Exception ignored in: 'mdtraj.geometry._geometry.image_frame'
                ...
    >>>exit code 0

When dcdfile = r"C:\trajectory.dcd"  or  "C://trajectory.dcd"
    >>>"File Does Not Exist!"


Comment
------------------
In windows, trajectory re-imaging does not work:
                ValueError: Buffer dtype mismatch, expected 'intp' but got 'long'
                Exception ignored in: 'mdtraj.geometry._geometry.image_frame'
                ...

Should I start a new thread for this or is it resolved elsewhere?

**Comment by rmcgibbo** [comment]
I think I just merged a fix for that last night?

**Comment by PaulNobrega** [comment]
for re-imaging?

**Comment by rmcgibbo** [comment]
#1409
