### ISSUE TITLE
Topology.from_openmm() doesn't store box vectors

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1428]
It looks like [`Topology.from_openmm()`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L365-L408) doesn't retain box vectors, while [`Topology.to_openmm()`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L309-L362) does retain box vectors. 

Was there a reason for this, or is this a simple omission that should be fixed?

**Comment by rmcgibbo** [comment]
Sounds like an omission

**Comment by jchodera** [comment]
Thanks! I'll see if I can fix this in a PR.

**Comment by jchodera** [comment]
On further inspection, the mdtraj `Topology` object does not store box vectors. Box vectors can be extracted from an mdtraj `Trajectory` in `Topology.to_openmm()` because they are available at the trajectory (but not topology) level, but there is no place to store them at the topology level in `Topology`.

We noticed this when converting from an mdtraj `Topology` object to an OpenMM  one to create a `Simulation` and use the `HDF5Reporter`. It turns out that a `Simulation` initiated from `topology.to_openmm()` will never record box vectors in any mdtraj reporter even if `cell=True` is requested because the resulting OpenMM `Topology` will lack box vectors, and [this line](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/reporters/basereporter.py#L176-L177) will cause it to be turned off, leading to confusing behavior.
