### ISSUE TITLE
Don't automatically disable box vector writing in reporters  if user requests it

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1429]
A `Simulation` initiated from `topology.to_openmm()` will never record box vectors in any mdtraj reporter even if `cell=True` is requested because the resulting OpenMM `Topology` will lack box vectors, and [this line](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/reporters/basereporter.py#L176-L177) will cause it to be turned off, leading to confusing behavior.

Would it be OK if we changed the default behavior to remove that logic so that, if the user requests box vectors, they are stored regardless of whether the `Topology` object contains box vectors or not?

**Comment by rmcgibbo** [comment]
If an OpenMM topology wants box vectors, maybe the mdtraj.topology.to_openmm() function should have an argument where you can pass in the box vectors?

**Comment by jchodera** [comment]
`mdtraj.Topology.to_openmm()` can already [accept an optional `traj` kwarg](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L309-L316) that extracts box vectors from the first frame of the trajectory. But it's still inconvenient to set up a `Reporter` this way because (1) you don't yet have a `Trajectory` object, and (2) it's especially easy to make logic errors if you don't know that MDTraj silently drops the box vectors and then does not include box vectors even if you ask the `Reporter` to include them.

Is there a compelling reason that the `Reporter` should not include box vectors in the trajectory file if the user requests it? This seems to be the counterintuitive behavior.

**Comment by rmcgibbo** [comment]
> Is there a compelling reason that the `Reporter` should not include box vectors in the trajectory file if the user requests it?

Not that I can think of. Changing this sounds fine.
