### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by robraddi** [mdtraj/mdtraj#1433]
I'm currently attempting to install mdtraj via `requirements.txt`. I've tried collecting mdtraj from pip install mdtraj as well as pip install -e git+git://github.com/mdtraj/mdtraj as shown below. The same error message is given regardless of the method. Both cython >=0.19.0 and numpy >=1.6.0 are installed prior to mdtraj. 

```
/home/docs/checkouts/readthedocs.org/user_builds/biceps/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/biceps/.cache/pip -r doc/requirements.txt
Collecting cython>=0.19.0 (from -r doc/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d1/05/34111590348c227d8e9f738c4b1ea2dce0410de5a658998f59df629ce57f/Cython-0.29.5-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
Requirement already satisfied: numpy>=1.6.0 in /home/docs/.pyenv/versions/2.7.14/lib/python2.7/site-packages (from -r doc/requirements.txt (line 2)) (1.16.0)
Collecting mdtraj==1.9.1 (from -r doc/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/af/93/8ad08f58668db6e3bf85e402c9c753fa4425c249de276b55f20c08e3fff7/mdtraj-1.9.1.tar.gz (2.0MB)
    Complete output from command python setup.py egg_info:
    --------------------------------------------------------------------------------
    Error: building mdtraj requires numpy and cython>=0.19
    
    Try running the command ``pip install numpy cython`` or
    ``conda install numpy cython``.
    
    or see http://docs.scipy.org/doc/numpy/user/install.html and
    http://cython.org/ for more information.
    
    If you're feeling lost, we recommend downloading the (free) Anaconda python
    distribution https://www.continuum.io/downloads, because it comes with
    these components included.
    --------------------------------------------------------------------------------
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zxgpqe/mdtraj/
```

```
...
Collecting cython==0.28 (from -r requirements/pip.txt (line 96))
  Using cached https://files.pythonhosted.org/packages/fa/86/0c8311bcba3b3f0944c135db95312e057a353058f522692e4dcf6d4bb978/Cython-0.28.tar.gz
Collecting numpy==1.14 (from -r requirements/pip.txt (line 97))
  Using cached https://files.pythonhosted.org/packages/ee/66/7c2690141c520db08b6a6f852fa768f421b0b50683b7bbcd88ef51f33170/numpy-1.14.0.zip
Obtaining mdtraj from git+git://github.com/mdtraj/mdtraj#egg=mdtraj (from -r requirements/pip.txt (line 98))
  Cloning git://github.com/mdtraj/mdtraj to ./venv/src/mdtraj
    Complete output from command python setup.py egg_info:
    --------------------------------------------------------------------------------
    Error: building mdtraj requires numpy and cython>=0.19

    Try running the command ``pip install numpy cython`` or
    ``conda install numpy cython``.

    or see http://docs.scipy.org/doc/numpy/user/install.html and
    http://cython.org/ for more information.

    If you're feeling lost, we recommend downloading the (free) Anaconda python
    distribution https://www.continuum.io/downloads, because it comes with
    these components included.
    --------------------------------------------------------------------------------

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/.../github/readthedocs.org/venv/src/mdtraj/
```

**Comment by rmcgibbo** [comment]
Can you check value of `Cython.__version__` that you're getting at build time: https://github.com/mdtraj/mdtraj/blob/master/setup.py#L25?

**Comment by marscher** [comment]
for automatic dependency resolution we should add Cython in the setup_requires field, not the install_requires. Also the setup script should not import cython prior the processing of package metadata.

Background: https://github.com/mdtraj/mdtraj/issues/1119

**Comment by marscher** [comment]
Cython is simply not yet installed during the invocation of mdtrajs setup.

**Comment by rmcgibbo** [comment]
oh right, @marscher.

pip now supports pep518 pyproject.toml, so maybe the whole thing could be moved over to that.

@robraddi: in the near term, i recommend not trying to install mdtraj via requirements.txt. unfortunately it's just kind of broken for us.

**Comment by rmcgibbo** [comment]
@marscher: looks fairly simple: https://github.com/QuLogic/cartopy/commit/e2dd1f69f65627e62edf655c603e339f676ea999

**Comment by marscher** [comment]
Cool, I'll add it soon.

**Comment by marscher** [comment]
This stuff works only when pip is used to install. If one invokes 
setup.py directly it fails to install build requirements.

**Comment by robraddi** [comment]
@rmcgibbo Sorry for getting back so late...`Cython.__version__` = 0.29.5 
Thank you, gentlemen.

**Comment by robraddi** [comment]
I'm curious about the progress. Not a huge rush. 
Also, please let me know if anyone has any suggestions for circumventing this issue for the time being. Thanks again.

**Comment by marscher** [comment]
As the error message suggests, please install NumPy and Cython (a recent one). Sorry for the delay

**Comment by robraddi** [comment]
@marscher, the Numpy & Cython requirements (versions as per the error message) have been satisfied before receiving an error message.

**Comment by marscher** [comment]
On 25.02.19 00:03, Rob Raddi wrote:
> @marscher, the Numpy & Cython requirements (versions as per the error message) have been satisfied before receiving an error message.
>
For some reason the check fails with an ImportError. What is the output of python -c "import Cython; print(Cython.__version__)"?

**Comment by robraddi** [comment]
The versions I specified for Cython and numPY were correct indeed. 
I'm rather certain the error was due to my lack of knowledge in setting up packages.  
```Solution: MDtraj needs to be in a separate requirements.txt file and installed after numPY and Cython. ```
Thanks again everyone.  I greatly appreciate everyone who tried to help me resolve this issue.
