### ISSUE TITLE
How to use compute contacts with only selected loaded residues

### ISSUE THREAD

**Issue by orthonalmatrix** [mdtraj/mdtraj#1435]
I have a large protein and only want to look at certain residues to see how often they are in contact. When I load the trajectory I do so by only loading the residues I'm interested in analyzing (for speed and space). However, I cannot get past the error on the Compute_contacts function:

if not np.all((residue_pairs >= 0) * (residue_pairs < traj.n_residues)):
            raise ValueError('contacts requests a residue that is not in the permitted range')

Since I want to look at contacts 78-79 and 78-227 (for instance) but I only load 22 residues in total, this error is raised. The problem is that it is checking simply of there are enough residues so I'm assuming that its mapped the residues available to some array index. How can I verify these are in the same order?
For instance if I atom_slice to residues 78,79,110,227 how can I be sure contact pair 1,3 refers to residues 79 and 227? Are they guaranteed to be in order?

**Comment by wiliamwalace** [comment]
They should be ordered but there may be other bugs as reported in #1440.
A workaround is not to eliminate the entire residue but keep one atom in the original residue in atom_indices, so that the index of residues are not confused.
