### ISSUE TITLE
wrong and weird behavior for md.rmsd

### ISSUE THREAD

**Issue by JoaoRodrigues** [mdtraj/mdtraj#1438]
Hi there,

Sorry, could not come up with a better/more descriptive title. 

I am calculating RMSDs of a trajectory in DCD format to the initial frame and surprisingly, the first RMSD value is not zero. Weirder still, if I call `traj.center_coordinates()` a couple of times and then call `md.rmsd` (without modifying the precentered option) the result changes and eventually settles at 0.0 for the first frame. If I save the first frame to a PDB file and load it and calculate the RMSD with itself, it does work (returns 0.0). I confirmed this on the latest development branch and both on Windows and Linux (both 64-bit archs). 

Some sample code to illustrate the problem:
```
In [1]: import mdtraj as md

In [2]: t = md.load('dummy.dcd', top='trimmed.pdb')

In [3]: subset = t.top.select('name CA')

In [4]: rms = md.rmsd(t, t[0], atom_indices=subset)

In [5]: rms
Out[5]:
array([0.00150352, 0.15014476, 0.15507188, 0.21114771, 0.23219837,
       0.28330612, 0.26107663, 0.24835569, 0.2446993 , 0.25087443],
      dtype=float32)

In [6]: t[0].xyz
Out[6]:
array([[[2.566496 , 4.9778986, 3.945816 ],
        [2.5863113, 4.971833 , 3.8246758],
        [2.438263 , 5.0456715, 3.9919465],
        ...,
        [7.937589 , 5.8869495, 5.201521 ],
        [7.985898 , 5.728813 , 5.211792 ],
        [7.985576 , 5.837641 , 5.366194 ]]], dtype=float32)

In [7]: t.center_coordinates()
Out[7]: <mdtraj.Trajectory with 10 frames, 450 atoms, 29 residues, and unitcells at 0x7f12ad95bf60>

In [8]: t[0].xyz
Out[8]:
array([[[-3.0707936 , -0.6593933 , -1.691472  ],
        [-3.0509782 , -0.6654587 , -1.8126123 ],
        [-3.1990266 , -0.59162045, -1.6453416 ],
        ...,
        [ 2.3002996 ,  0.24965763, -0.43576717],
        [ 2.3486085 ,  0.09152126, -0.4254961 ],
        [ 2.3482866 ,  0.20034885, -0.27109432]]], dtype=float32)

In [9]: rms = md.rmsd(t, t[0], atom_indices=subset)

In [10]: rms
Out[10]:
array([0.00106315, 0.150141  , 0.15507188, 0.21114102, 0.23219837,
       0.28330612, 0.26108095, 0.24836138, 0.2446993 , 0.25087443],
      dtype=float32)

In [11]: t.center_coordinates()
Out[11]: <mdtraj.Trajectory with 10 frames, 450 atoms, 29 residues, and unitcells at 0x7f12ad95bf60>

In [12]: t[0].xyz
Out[12]:
array([[[-3.0707939 , -0.6593932 , -1.6914718 ],
        [-3.0509784 , -0.66545856, -1.812612  ],
        [-3.1990268 , -0.5916203 , -1.6453414 ],
        ...,
        [ 2.3002994 ,  0.24965772, -0.43576697],
        [ 2.3486083 ,  0.09152136, -0.4254959 ],
        [ 2.3482864 ,  0.20034894, -0.2710941 ]]], dtype=float32)

In [13]: rms = md.rmsd(t, t[0], atom_indices=subset)

In [14]: rms
Out[14]:
array([0.        , 0.15014476, 0.15507188, 0.21114102, 0.2321935 ,
       0.28330612, 0.26107663, 0.24836138, 0.24470392, 0.25087443],
      dtype=float32)
```

I would be happy to debug this and write a PR, but I don't know where to start looking for an answer. My initial guess is that this somewhat a precision issue or an issue with DCD files? Happy to provide data via e-mail to reproduce this.

**Comment by JoaoRodrigues** [comment]
Weirdly enough, doing the same calculation on the _backbone_ instead of only _alpha carbons_ works as expected from the start:

```
In [1]: import mdtraj as md

In [2]: t = md.load('dummy.dcd', top='trimmed.pdb')

In [3]: subset = t.top.select('backbone')

In [4]: rms = md.rmsd(t, t[0], atom_indices=subset)

In [5]: rms
Out[5]:
array([0.        , 0.14530027, 0.15630928, 0.22043258, 0.2277237 ,
       0.28202495, 0.2640715 , 0.25721255, 0.24545738, 0.26058984],
      dtype=float32)
```

**Comment by rmcgibbo** [comment]
what happens if you load the trajectory twice into two different variables, and then calculate the RMSD between the two identical frames using the values from the two different variables? I think there might be a special optimization that is sometimes able to check that you're computing the RMSD from one frame to itself by seeing that they're the same address in memory, so that could be where the 0 is coming from?
