### ISSUE TITLE
Bug in compute_contact() in trajectory loaded with atom_indices with scheme='closest' etc.

### ISSUE THREAD

**Issue by wiliamwalace** [mdtraj/mdtraj#1440]
In `mdtraj/mdtraj/geometry/contact.py`  with scheme in 'closest', 'closest-heavy', 'sidechain', 'sidechain-heavy', the code
```python
elif scheme in ['closest', 'closest-heavy', 'sidechain', 'sidechain-heavy']:
        if scheme == 'closest':
            residue_membership = [[atom.index for atom in residue.atoms]
                                  for residue in traj.topology.residues]

        residue_lens = [len(ainds) for ainds in residue_membership]

        atom_pairs = []
        n_atom_pairs_per_residue_pair = []
        for pair in residue_pairs:
             atom_pairs.extend(list(itertools.product(residue_membership[pair[0]], residue_membership[pair[1]])))
```
will lead to incorrect `atom_pairs` if `traj` is loaded with `atom_indices` in which not all residues are present.

Because in the last line the residue index in `pair` is used as index of `residue_membership`. This actually assumes `[residue.index for residue in traj.topology.residues] == range(len(residue_membership))`, which is not necessarily  true if `traj` is loaded with `atom_indices`, especially when there are residues missing in `atom_indices`.

**Comment by rmcgibbo** [comment]
How about adding a check and throwing an exception if this implicit assumption is violated (i.e. just making the assumption explicit)?
