### ISSUE TITLE
MDTraj release planning?

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#1442]
As @marscher  pointed out in https://github.com/mdtraj/mdtraj/issues/1430#issuecomment-489118570, MDTraj won't `pip install` on pyrhon3.7 because of an issue with what cython version we were requesting that has since been fixed in master.

We probably ought to do a new release. But before doing so, I think we should figure out which of the outstanding pull requests (e.g. those related to the setup.py // install process) ought to be merged.

1. Is anyone up for managing the release?
2. Should we cut the current master as the release, or should we try to merge some of the outstanding PRs?

cc: @mdtraj/developers

**Comment by marscher** [comment]
I have merged the PR for pep517 handling from my side there are not further urgent things to include. It would be nice to have this flaky tests thing fixed, so we can have at least one proper CI run before the actual release.

I can handle packaging on PyPi and Conda-Forge, but it would be nice if somebody could do the fancy change log and (unhandy) version handling in the repo.

**Comment by marscher** [comment]
In my opinion we are good to go.

**Comment by marscher** [comment]
It seems like versions.json is out of date (latest release is still 1.9.0). Who has push rights for Amazon S3?

**Comment by mattwthompson** [comment]
When the website went down a year ago it was @cxhernandez that paid the bills. Not sure if anybody currently in Pande's lab is a better point of contact

**Comment by rmcgibbo** [comment]
I don't have access to it. But the embedded credentials inside travis still work, right?

**Comment by marscher** [comment]
How about hosting at readthedocs.org?

Am 16. Mai 2019 19:29:07 MESZ schrieb Matt Thompson <notifications@github.com>:
>When the website went down a year ago it was @cxhernandez that paid the
>bills. Not sure if anybody currently in Pande's lab is a better point
>of contact

**Comment by rmcgibbo** [comment]
It seems to me the current solution is actually working fine, and I don't want to embark on a big project to change the docs hosting unless we have the engineering resources to take it on.

The reason that the 1.9.1 and 1.9.2 aren't deployed onto mdtraj.org is that the CI was broken when we did those releases, I think. It's fixed now.

The system requires travis-ci to run and complete with `mdtraj.version.release == True`. Then https://github.com/mdtraj/mdtraj/blob/master/devtools/travis-ci/update_versions_json.py#L9 runs and modifies the versions.json file to point to the latest version as the release, I think.
