### ISSUE TITLE
cpptraj testing

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1445]
Currently this fails because cpptraj (on linux) is linked against an external (e.g. not conda-contained) version of netcdf:
```
cpptraj: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory
```
Does anybody know how to solve this quickly? Otherwise I would just skip the cpptraj test by not installing the library.

**Comment by rmcgibbo** [comment]
> Otherwise I would just skip the cpptraj test by not installing the library.
I think this is the best choice for now.

**Comment by marscher** [comment]
removed cpptraj in #1444
