### ISSUE TITLE
Minimum numpy version?

### ISSUE THREAD

**Issue by sroet** [mdtraj/mdtraj#1446]
Since the merge of #1434 the install of mdtraj fails for `numpy<1.16.0`

```
pip install numpy==1.15.4
pip install git+https://github.com/mdtraj/mdtraj.git
```
returns:
```
Collecting git+https://github.com/mdtraj/mdtraj.git
  Cloning https://github.com/mdtraj/mdtraj.git to /tmp/pip-req-build-uwdlta2y
  Running command git clone -q https://github.com/mdtraj/mdtraj.git /tmp/pip-req-build-uwdlta2y
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.6 in /home/sander/miniconda3/envs/test_min_ver/lib/python3.7/site-packages (from mdtraj==1.9.3) (1.15.4)
Collecting scipy (from mdtraj==1.9.3)
  Using cached https://files.pythonhosted.org/packages/3e/7e/5cee36eee5b3194687232f6150a89a38f784883c612db7f4da2ab190980d/scipy-1.2.1-cp37-cp37m-manylinux1_x86_64.whl
Building wheels for collected packages: mdtraj
  Building wheel for mdtraj (PEP 517) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-xx_so094/wheels/d5/31/7c/0f0973e884bfb3d9b9d9f49a4692c9b59f84bc7492e3c86479
Successfully built mdtraj
Installing collected packages: scipy, mdtraj
Successfully installed mdtraj-1.9.3 scipy-1.2.1

```

now running in python
```python
import mdtraj as md
```
Raises
```python
>>> import mdtraj as md
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/miniconda3/envs/test_min_ver/lib/python3.6/site-packages/mdtraj/__init__.py", line 30, in <module>
    from .formats.registry import FormatRegistry
  File "/home/sander/miniconda3/envs/test_min_ver/lib/python3.6/site-packages/mdtraj/formats/__init__.py", line 4, in <module>
    from .dcd import DCDTrajectoryFile
  File "__init__.pxd", line 918, in init mdtraj.formats.dcd
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
Calling the same line again, after that, now raises:
```python
>>> import mdtraj as md
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/miniconda3/envs/test_min_ver/lib/python3.6/site-packages/mdtraj/__init__.py", line 31, in <module>
    from .formats.xtc import load_xtc
  File "/home/sander/miniconda3/envs/test_min_ver/lib/python3.6/site-packages/mdtraj/formats/__init__.py", line 4, in <module>
    from .dcd import DCDTrajectoryFile
  File "mdtraj/formats/dcd/dcd.pyx", line 143, in init mdtraj.formats.dcd
AttributeError: type object 'mdtraj.formats.dcd.DCDTrajectoryFile' has no attribute '__reduce_cython__'
``` 

So my question is: Did the minimum `numpy` version of mdtraj change (from `1.6` to `1.16`)?

**Comment by rmcgibbo** [comment]
Can you run `pip install` with more verbosity? What build dependencies did pip pick when running the `Installing build dependencies` phase?

**Comment by sroet** [comment]
Sure, here you go (this is with the command `pip install git+https://github.com/mdtraj/traj.git -v &> pip_install_log.txt`)
[pip_install_log.txt](https://github.com/mdtraj/mdtraj/files/3157989/pip_install_log.txt)

An interesting line in that file (for me)is:
`Successfully installed Cython-0.29.7 numpy-1.16.3 setuptools-41.0.1 wheel-0.33.1` (line 3284)
Which looks like it is (temporarily) building `numpy==1.16.3`  in order to build `mdtraj`

**Comment by rmcgibbo** [comment]
Yeah. that's what I expected. I don't know how to solve your problem though. You're building mdtraj against numpy 1.16, which because of the numpy ABI stuff, means that you need numpy 1.16+ at runtime.

**Comment by sroet** [comment]
Ah I found a solution:
I can install `numpy` and `cython` and then run:
`pip install --no-use-pep517 git+https://github.com/mdtraj/mdtraj.git` 
to get the old behavior back (pre #1434) 
This solves this issue for me as this was only failing my "minimum version requirement" CI.

Sorry for the noise on your issue tracker, and thanks for the help.

**Comment by rmcgibbo** [comment]
This may be a good question for distutils-sig or the pip issue tracker.

**Comment by marscher** [comment]
I have tried to pin a minimum version of NumPy per as Python major 
version, but the combined requirement did not succeed.
