### ISSUE TITLE
Is there any tools to switch lammpstrj to hoomd data file?

### ISSUE THREAD

**Issue by Roy-Kid** [mdtraj/mdtraj#1450]
I want to switch a lammps data file to hoomd data file, so i want to ask if there is any available script to do this. If not, how about I write some code to do this job?

**Comment by mattwthompson** [comment]
For data files you might be better off with other tools. I think in this case the best might be Axel Kohlmeyer's [topotools](https://sites.google.com/site/akohlmey/software/topotools) in VMD

**Comment by Roy-Kid** [comment]
Thanks for your kindly reply. I just wrote a script to convert lammps data file to XML and GSD, but i dont think Topotools is fit my need. I will close this issue and sorry to bother you.
