### ISSUE TITLE
trajectory load 

### ISSUE THREAD

**Issue by iammecanchie** [mdtraj/mdtraj#1460]
I am simulating a system using LAMMPS and in that i use the compute command to calculate ke/atom but when i load the trajectory in , i am not able to access the ke/atom . 
is there any way to read additional attributes other than the xyz coordinates ?
thanks

**Comment by ctk3b** [comment]
This is not currently possible. 

There have been some discussions about supporting the loading of "extra data" and attaching them to trajectory objects but to my knowledge no one has started working on this.
