### ISSUE TITLE
How to supply anchor_molecules in image_molecules

### ISSUE THREAD

**Issue by harish-srini** [mdtraj/mdtraj#1462]
May I please know how to supply anchor_molecules manually for the image_molecules procedure.

I have tried the following:

`anchor_molecules=set(u.topology.residue(0).atoms)`

but it returns an error saying, `Atom is not iterable`

I also tried 
`anchor_molecules=[a for a in u.topology.residue(0).atoms]`
 and this time it returns an `AttributeError`, saying

`set item has no attribute 'name'`

PS: The heuristic is not able to find any anchor molecules!

**Comment by peastman** [comment]
From the documentation at http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules, `anchor_molecules` should be a list of atom sets.  That is, one set for each molecule.  So try changing that to

```python
anchor_molecules=[set(u.topology.residue(0).atoms)]
```
