### ISSUE TITLE
Any reason for wasteful round-trip calculation of unitcell vectors?

### ISSUE THREAD

**Issue by sroet** [mdtraj/mdtraj#1463]
I was looking at the `Trajectory` object and I noticed it is round tripping `unitcell_vectors` during computations, when the loaded file format supports them, like `.xtc` ( so the current behaviour is: load `unitcell_vectors` -> compute&set `unitcell_angles/unitcell_lengths` -> compute `unitcell_vectors` every time a function needs it). 

That round trip seems wastefull when doing multiple calculations of compute_distances ( which uses unitcell_vectors), as the unitcell_vectors are computed every time. 

It also leads to discrepancies (`abs. diff` of `2e-6` and `rel. diff` of `1.1e-5` for my test system) when comparing computing distances with either the loaded unitcell_vectors and the round-tripped unitcell_vectors.

Is there any reason why the unitcell vectors are not set together with unitcell_angles and unitcell_lengths if loaded, or computed **once** from the available properties otherwise? 

PS: If there is no reason. would you mind a PR from me to fix this?

**Comment by marscher** [comment]
I do not think we should recompute quantities already present in the file format. I'd be happy if you could file a PR to fix this behaviour. Thanks

**Comment by sroet** [comment]
I haven't had time for this yet (or in the forseeable future), but it is still on the list. If anyone encounters this, feel free to pick it up.

**Comment by sroet** [comment]
it has been 6 months again, time flies. Still somewhere towards the bottom of the priorities list
