### ISSUE TITLE
PDBTrajectoryFile.write() does not keep consistent units?

### ISSUE THREAD

**Issue by weiHelloWorld** [mdtraj/mdtraj#1464]
I am trying to use `PDBTrajectoryFile` for pdb file writing, and notice that if I do following:

```Python
a = md.load('/tmp/out.pdb')
my_f = md.formats.PDBTrajectoryFile('/tmp/out_1.pdb', mode='w')
my_f.write(a.xyz[0][atom_idx, :], topology=a.topology)
my_f.close()
```

the coordinates value in '/tmp/out_1.pdb' would be scaled by a factor of 10.  I believe the reason is that `md.formats.PDBTrajectoryFile.write()` does not convert units to Angstrom before writing coordinates into a pdb, therefore we need to explicitly multiply the coordinates by 10 to fix that.  I am wondering if it would be better to add an additional option in `md.formats.PDBTrajectoryFile.write()` to avoid this confusion?

Thank you!

**Comment by rmcgibbo** [comment]
If you just to `a.save("out_1.pdb")`, the units are converted correctly. It's done at a higher level.

The PDBTrajectoryFile object is relatively low level, and expects you to give data in the correct format.
