### ISSUE TITLE
Should we pin numpy in pyproject.toml

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#1465]
I had an environment with numpy1.14 installed, and running `pip install mdtraj`, because of build isolation, builds against a more recent version of numpy leading to a package that fails to import. The issue is discussed here: https://github.com/astrofrog/fast-histogram/issues/35

**Comment by sroet** [comment]
I had the same issue come up in #1446. The quick way around that for me was to run 
```pip install --no-use-pep517 mdtraj```  

Ps I would be against pinning numpy in the `.toml`, as I am pretty sure that would break the install the other way around (so for more recent numpy versions).

**Comment by rmcgibbo** [comment]
I think since it's forward compatible it wouldn't break the install the other way around, but maybe someone could could test that.

**Comment by marscher** [comment]
I think you're absolutely right about pinning. We should do it. I even 
tried pinning it by Python major minor releases, but I didn't manage pip 
to parse my toml file. So we should just go for the oldest supported 
(pypi) version.
