### ISSUE TITLE
Adding option to pass in desired precision when saving files.

### ISSUE THREAD

**Issue by EqualAPriori** [mdtraj/mdtraj#1470]
Great work, super useful package. I was wondering if it would be possible to add an option to the save() function to specify the desired precision of saved trajectories. Right now I've made spot-changes for specific file formats that I use, but it would be nice if there is a universal way to specify precision that every file format can use.

Thanks!

**Comment by rmcgibbo** [comment]
I think precision is actually quite a subtle feature that depends on the use case. Can you clarify exactly what you want to do? In some circumstances, I can see wanting to rounding to a specific number of decimal places, but for others I can see wanting to round the binary representation. You can always just perform whatever numpy operations you like on the Trajectory.xyz attribute I guess.

**Comment by EqualAPriori** [comment]
Normally I save all trajectories using .dcd, which outputs to a high
precision, and is sufficient for saving trajectories to process later.

However, we also have legacy code that only processes the .lammpstrj
format. Unfortunately the lammps processing in that code is pretty low
level and would take some refactoring to change to use mdtraj's reader
instead, and it was easier to first convert my .dcd files to .lammpstrj
files before feeding into the legacy code. Right now mdtraj is hardcoded to
output .lammpstrj with a precision of 3, which was too imprecise for
subsequent re-processing of the trajectory.

I was thinking of an option along the lines of
mdtraj.save('filename.format', precision = MyDesiredPrecision)
