### ISSUE TITLE
mdtraj.rmsd not working as expected?

### ISSUE THREAD

**Issue by eventfulsean** [mdtraj/mdtraj#1479]
I have a DCD file containing four chains. I'm trying to produce an RMSD matrix for chain B on structures superposed by chain A. However, the RMSD matrix produced contains very small (near 0) RMSD values and inconsistent with those calculated with PyMol and general visual inspections.

1) Superpose on chain A Calpha atoms (chainid = 0)
align_atoms = traj.topology.select("(chainid == 0) and (name == CA)")
traj.superpose(traj, frame=0, atom_indices=align_atoms)

2) Calculate RMSD on chain B Calpha atoms (chainid = 2)
rmsd_atoms = traj.topology.select("(chainid == 2) and (name == CA)")
dist = np.empty((traj.n_frames, traj.n_frames))
for i in range(traj.n_frames):
    dist[i] = md.rmsd(traj, traj, i, atom_indices=rmsd_atoms)

But the following command:
max_dist = np.max(dist)
print("Max pairwise rmsd: %f" % max_dist)
**>> Max pairwise rmsd: 0.0012800 nm**

I exported traj and calculated a few RMSDs on chain B via pymol and yielded > 13 angstroms (as expected).

The behavior suggests that there's some type of superposition happening within mdtraj.rmsd, which is not the expected behavior. Has anyone else seen this?

Thanks.

**Comment by rmcgibbo** [comment]
yes, mdtraj.rmsd computes the optimally-superposed rmsd using Theobald's QCP method http://scripts.iucr.org/cgi-bin/paper?sh5029

**Comment by eventfulsean** [comment]
Thanks for the prompt response. That was based on what I read, too, so apologies if this is a duplicate. But based on what I read on mdtraj, I'd have to do the true RMSD calculations separately, without the translation/rotation optimization.

Thanks again.
