### ISSUE TITLE
'mdconvert not defined'

### ISSUE THREAD

**Issue by Mattyboi123** [mdtraj/mdtraj#1480]
I am very new to coding, I am currently trying to use MDtraj to perform some analyses of MD trajectories. Specifically,  I want to go on to use AVtraj to calculate the available volumes for two dyes attached at arbitrary positions, returning a trajectory of the AVs. I also want to use PCA to propose the likely range of distances between the mean positions of the dyes. AVTraj takes .h5 files as its input and I wanted to use the 'mdconvert' script in MDtraj to convert my .xtc file plus starting topology PDB file to a nice .h5 file. However, upon trying the following code

import mdtraj as md
from mdtraj import *
import avtraj as avt
import json
import pylab as p
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
#%% load a trajectory PDB file
t = md.load_xtc(r'C:\Users\fbsmawadmin\Desktop\ongoing work\SurA\MD\sura_open_1us_rep_1.xtc',
                top = r'C:\Users\fbsmawadmin\Desktop\ongoing work\SurA\MD\sura_core-p1_open_start.pdb')
print(t)
#%%
t5 = mdconvert(r'C:\Users\fbsmawadmin\Desktop\ongoing work\SurA\MD\sura_open_1us_rep_1.h5',
               top = r'C:\Users\fbsmawadmin\Desktop\ongoing work\SurA\MD\sura_core-p1_open_start.pdb',
               input = r'C:\Users\fbsmawadmin\Desktop\ongoing work\SurA\MD\sura_open_1us_rep_1.xtc' )

I am told that: 

NameError: name 'mdconvert' is not defined

This 'such and such is not defined' issue seems to come up a heck of a lot, and I thought that I had it worked out but its really not clear to me what to do in this instance. Does one usually have to 'define' all of the scripts contained within an imported module before they can be executed within the IDE? I hadn't thought so. What would one write to 'define' the mdconvert script in this case such that it could be used? I'm aware that this is before what should be any kind of hurdle but really I don't know where to begin...

The PCA code also threw an error but thats for another day

**Comment by rmcgibbo** [comment]
In mdtraj, `mdconvert` is a command-line program that's installed into the system. It's not a Python function.

**Comment by Mattyboi123** [comment]
OK...could you provide a worked example of how to implement it please, when you say command line would it work from the anaconda prompt?

CHeers
Matt

**Comment by rmcgibbo** [comment]
From the command line, try `mdconvert -h`. Does that work?

**Comment by Yuanruikang** [comment]
hello,rmcgibbo
I just installed mdtraj.It can run perfectly.but I can not run mdconvert in my terminal.Please help me!
I use the whereis mdconvert/which mdconvert command,there is no result.
