### ISSUE TITLE
Malformed files left open (TRR, but possibly elsewhere)

### ISSUE THREAD

**Issue by dwhswenson** [mdtraj/mdtraj#1481]
If you open a malformed TRR file, MDtraj leaves the file open (at least, with macOS 10.14.6). This is a problem: we're trying to use MDTraj's TRR reading to read a file while it is being written. Occasionally we try to read something that is malformed (in the middle of being written). We catch the `OSError` and handle it in our code (wait and try again). But this can happen often enough that we hit the OS-imposed limit on open files, since MDTraj leaves the files open.

I suspect this may apply to other file types as well (at least, probably XTC).

### Example

Create a (very) malformed "TRR file":
```bash
$ echo "foo" > malformed.trr
```

Run the following little script:

```python
#!/usr/bin/env python
import mdtraj
import psutil

print("Before: " + str(psutil.Process().open_files()))

try:
    mdtraj.formats.TRRTrajectoryFile("malformed.trr")
except OSError as e:
    print("OSError: " + str(e))

print("After: " + str(psutil.Process().open_files()))
```

Output:

```
Before: []
OSError: Malformed TRR file. Number of atoms <= 0. Are you sure this is a valid GROMACS TRR file?
After: [popenfile(path='/Users/dwhs/tmp/mdtraj_malformed_trr/malformed.trr', fd=4)]
```

### Workaround/Fix (Mac/Unix)

One workaround would be for the user to change the max number of files with `ulimit -n`, but that's not very user-friendly.

Here's an outline of the workaround I've implemented for us:

```python

open_files = psutil.Process().open_files()  # get open files owned by current process

def filter_criterion(popenfile):
    ... # client code for identifying the files that are relevant, return bool

files_to_close = [p for p in open_files if filter_criterion(p)]  # filter
for p in files_to_close:
    open(p.fd).close()  # I think Windows needs something else here
```

My understanding is that Windows works differently with file descriptors (namely, that there's only one per file), so maybe `open(p.path).close()` would work? Or maybe this isn't a problem in Windows? I don't have a Windows box to try stuff on.

If you wanted to add this to MDTraj, the `filter_criterion` would just check whether the path `popenfile.path` matches the input file. The downside is that you'd need to add psutil as a requirement. Otherwise you leave it to users to fix the problem on their end if it causes them problems -- I hope this issue will help them!

**Comment by rmcgibbo** [comment]
This is probably pretty easy to just fix in the TRRTrajectoryFile constructor/destructor: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/xtc/trr.pyx#L227

It probably opens the file, but doesn't get to the line that sets self.is_open=True (line 260), so the destructor doesn't close the handle.

**Comment by dwhswenson** [comment]
That's what I thought at first, but the error raised is on the line *before* that. Is there any way that `fh` would still get set? (I didn't experiment with this because I've had trouble compiling Cython stuff locally -- problems on my end with conflicting compilers.)

My guess was that somehow `trrlib.read_trr_natoms` is leaving the file open. I don't know why that would be -- it usually closes it, and the code for it is pretty clear, and sure looks like it closes. I also don't see an immediately obvious problem in the `xdrfile_open`/`close` pair, but I don't spend as much time looking at C code these days, so I may have missed something.

**Comment by rmcgibbo** [comment]
https://github.com/mdtraj/mdtraj/blob/e41a92299990fa6586a8f35739653a1801e33c31/mdtraj/formats/xtc/src/xdrfile_trr.c#L483?

**Comment by dwhswenson** [comment]
@rmcgibbo Yup, that looks pretty suspicious. Don't know why I didn't notice the early return in the event of error. Should be easy to fix, too, right? `xdrfile_close` before the return? I can make a PR if you want (would also clean up the indentation of `read_trr_nframes`, which confused me when I read it).

**Comment by rmcgibbo** [comment]
Yeah that’s be great, and you can use your test from above to see if it solves the problem.
