### ISSUE TITLE
amber12 netcdf timestamp

### ISSUE THREAD

**Issue by scdantu** [mdtraj/mdtraj#1483]
When I process netcdf amber trajectory, generated from pmemd of amber12 package, the time stamp is strange. 9969209968386869046778552952102584320.0000

Any suggestions on how to resolve this?

**Comment by marscher** [comment]
Dunno, maybe use brute force intelligence

Am 1. Oktober 2019 15:31:40 MESZ schrieb scdantu <notifications@github.com>:
>When I process netcdf amber trajectory, generated from pmemd of amber12
>package, the time stamp is strange.
>9969209968386869046778552952102584320.0000
>
>Any suggestions on how to resolve this?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mdtraj/mdtraj/issues/1483

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rmcgibbo** [comment]
It could be type confusing -- pmemd could have saved the as an int and we're interpreting it as a double or something. Or endian confusion. Have you made any progress on this?

**Comment by scdantu** [comment]
@rmcgibbo I checked with the Amber forum and the issue is with amber12 cpptraj. When it processes the trajectory, it does not add time stamp. Not sure if you will be interested in adding an inbuilt check for this.

**Comment by rmcgibbo** [comment]
Yes, if you could fix our code (something like checking for whether that field exists?) and add a test case so that it's compatible with amber12 cpptraj that would be amazing!
