### ISSUE TITLE
Error loading in MOL2 files with various residues

### ISSUE THREAD

**Issue by rmatsum836** [mdtraj/mdtraj#1485]
I'm attempting to load a mol2 file into a trajectory with multiple residue names.  I am getting the following error:
```ValueError: All of the atoms with residue index 1 do not share the same residue name```

Tracing this error, I believe this is due to the way that `resSeq` and `chainID` are all set to one in lines 119-120 in `formats/mol2.py`. 

In `from_dataframe` in `topology.py`, there is a for loop starting at line 501 attempting to loop through the unique `resSeq`.  However since each atom has `resSeq` of 1, we end up checking if all of the residue names in the system are equal to a particular residue name, which will return False every time.   

The suggested fix here is to change how `resSeq` is defined in the atoms data frame so that each residue name has a unique `resSeq`.

**Comment by rmcgibbo** [comment]
Nice find! Thanks so much. Would you be able to make that change (and add a test case) as a Pull Request?

**Comment by rmatsum836** [comment]
Yes, I'll take a look this week.
