### ISSUE TITLE
No module named 'mdtraj.formats.dcd'

### ISSUE THREAD

**Issue by csalame17** [mdtraj/mdtraj#1486]
I installed mdtraj into my conda environment and keep getting stopped by this error. 

<img width="889" alt="Screen Shot 2019-10-19 at 9 51 31 AM" src="https://user-images.githubusercontent.com/56762983/67146161-2a29c300-f256-11e9-82d4-5296ce8ce297.png">

Anyone knows what to do?

**Comment by rmcgibbo** [comment]
I suspect it has something to do with the compiled code being incorrect for your system, but without more details it's hard to know.

**Comment by mattwthompson** [comment]
I've triggered this error a handful of times in the past, IIRC each time it was actually a bad compilation that was the root problem. I'm not sure how to elegantly handle that sort of issue so it raises a more accurate exception. But I second that it has something to do with the install, maybe go through the cycle of uninstalling/re-installing (make sure you're using `conda-forge` and Python 3.6+)
