### ISSUE TITLE
pip install fails with clang

### ISSUE THREAD

**Issue by justinrporter** [mdtraj/mdtraj#1487]
Installing mdtraj with `pip install mdtraj` fails with clang on my macOS 10.14.6 laptop with python 3.6.5 and pip 19.3.1.

```
  building 'mdtraj._rmsd' extension
  creating build/temp.macosx-10.13-x86_64-3.6/mdtraj/rmsd
  creating build/temp.macosx-10.13-x86_64-3.6/mdtraj/rmsd/src
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Imdtraj/rmsd/include -I/private/var/folders/sr/lt69jgxx4p3034gfk5w7vj180000gn/T/pip-build-env-ultot4az/overlay/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c mdtraj/rmsd/_rmsd.c -o build/temp.macosx-10.13-x86_64-3.6/mdtraj/rmsd/_rmsd.o -fopenmp -msse2 -mssse3 -O3 -funroll-loops -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare
  clang: error: unsupported option '-fopenmp'
  error: command 'clang' failed with exit status 1
```

If I manually point mdtraj at my gcc installation, like `$ CC=gcc-8 CXX=gcc-8 pip install mdtraj` everything works fine.

Is this expected behavior? For a time, I thought there was an effort to cause mdtraj to simply compile without openmp if only clang was available?

UPDATE
Actually installing mdtraj this way doesn't work fine... the compilation is borked. (This could actually be a problem with my gcc install...

```
$ python -c 'import mdtraj'
$ python -c 'import mdtraj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jrporter/.envs/archil-enspara/lib/python3.6/site-packages/mdtraj/__init__.py", line 30, in <module>
    from .formats.registry import FormatRegistry
  File "/Users/jrporter/.envs/archil-enspara/lib/python3.6/site-packages/mdtraj/formats/__init__.py", line 15, in <module>
    from .dtr import DTRTrajectoryFile
ImportError: dlopen(/Users/jrporter/.envs/archil-enspara/lib/python3.6/site-packages/mdtraj/formats/dtr.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt8ios_base4InitD1Ev
  Referenced from: /Users/jrporter/.envs/archil-enspara/lib/python3.6/site-packages/mdtraj/formats/dtr.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/jrporter/.envs/archil-enspara/lib/python3.6/site-packages/mdtraj/formats/dtr.cpython-36m-darwin.so
```

**Comment by marscher** [comment]
Hi Justin,

as you see, pip/setuptools is simply ignoring your CC, CXX setting. I think you can set the compiler when invoking setup.py directly by a --compiler directive.
But I do not know the exact details.

Best,
Martin

**Comment by justinrporter** [comment]
Martin,

Right. So, in my case, this is not a problem since I figured it out. However, does this mean that mdtraj cannot be used if the mac in question does not have a gcc installation? (Since clang doesn't support openmp?)

**Comment by rmcgibbo** [comment]
On my mac laptop "gcc" is just a symlink to clang. I think it's OS X 10.12. I don't believe it supports OpenMP, but it still runs fine.

**Comment by rmcgibbo** [comment]
There's a bunch of code here that's supposed to detect whether the compiler supports OpenMP: https://github.com/mdtraj/mdtraj/blob/master/basesetup.py#L164. It definitely predates OSX 10.14 though. When you run `python setup.py build` does it show any information about "Attempting to autodetect OpenMP" and such?

**Comment by justinrporter** [comment]
> On my mac laptop ... I think it's OS X 10.12

Yes, IIRC this actually used to work on my laptop.

> When you run python setup.py build does it show any information about "Attempting to autodetect OpenMP" and such?

On the money. Look's like it thinks that clang supports OpenMP for some reason. Here's an excerpt to the first few lines after I run `python setup.py build`:

```
C compiler:
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Attempting to autodetect OpenMP support... Compiler supports OpenMP
Attempting to autodetect SSE3   support... Compiler supports SSE3
Attempting to autodetect SSE4.1 support... Compiler supports SSE4.1
```

**Comment by duutabib** [comment]
I had similar issue with openssl:
    ld: library not found for -lssl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1

You might want to brew install openmp then export CPPFLAGS & LDFLAGS for openmp like [here:](https://github.com/psycopg/psycopg2/issues/997) 

Also, check for outdated build tools like wheel and setuptools (and upgrade them):
                        pip list --outdated 
                        pip install --upgrade 'tool'
I hope this helps
