### ISSUE TITLE
Two failed windows tests

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#1489]
From https://dev.azure.com/rmcgibbo/mdtraj/_build/results?buildId=122

FAILED tests/test_distance.py::test_0p - AssertionError: 
FAILED tests/test_distance.py::test_3p - AssertionError:

It looks to me that these tests don't always fail, so it's possible that there's something stochastic here on Windows?

**Comment by mattwthompson** [comment]
[log_36_122.zip](https://github.com/mdtraj/mdtraj/files/3776506/log_36_122.zip)

FWIW you can download logs from Azure (although I prefer travis just giving you the log in browser 🤷‍♂). In this case it seems like the functions are actually doing different things, which is kinda spooky if that only happens on Windows
