### ISSUE TITLE
md.iterload() ignores skip argument for multimodel .pdb

### ISSUE THREAD

**Issue by mewall** [mdtraj/mdtraj#1492]
Running on OS X 10.13.6 or Linux:

Darwin orokonui.lanl.gov 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

Linux version 3.10.0-1062.1.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Sep 13 22:55:44 UTC 2019

mdtraj version 1.9.2, python 2.7

When md.iterload() is used to read a multimodel .pdb trajectory, the skip argument appears to be ignored.

Here are some diagnostics for three different skip values when reading the multimodel .pdb file:

skip =  0  chunk =  7  start time =  0  coords of first atom =  [-1.203  3.271 -0.834]
skip =  7  chunk =  7  start time =  0  coords of first atom =  [-1.203  3.271 -0.834]
skip =  14  chunk =  7  start time =  0  coords of first atom =  [-1.203  3.271 -0.834]

In contrast, here they are when reading the original .xtc format trajectory:

skip =  0  chunk =  7  start time =  110000.0  coords of first atom =  [-1.203  3.271 -0.834]
skip =  7  chunk =  7  start time =  110014.0  coords of first atom =  [-1.1899999  3.3079998 -0.88     ]
skip =  14  chunk =  7  start time =  110028.0  coords of first atom =  [-1.1999999   3.266      -0.82699996]

**Comment by rmcgibbo** [comment]
Thanks for the bug report! I believe I see in the code where this is happening.

**Comment by mewall** [comment]
You're welcome. Thanks for taking a look.


While I have your attention, I actually have a related question that might save me a little digging:


- Can you recommend a mdtraj method to determine quickly the number of frames in a trajectory file?


Thanks,


Mike


________________________________

**Comment by ahy3nz** [comment]
```python3
>>> import mdtraj
>>> traj = mdtraj.load(your_files_here, top=your_topology)
>>> len(traj)
4151
>>> traj.n_frames
4151
```

**Comment by mewall** [comment]
Is there any way to do it for a large trajectory without reading it? For example, a 500,000-frame trajectory with 125,000 atoms. Get the number of frames and then use md.iterload() with this info in hand.
________________________________

**Comment by marscher** [comment]
@mewall to continue the off topics here, it depends on the format you are using. I think DCD you can obtain the number of frames by reading just the head (a couple of bytes), while XTC has to be processed like a linked list to get this information (read the whole file).
