### ISSUE TITLE
PDB parser assigning the md.element of K+ and Cl- wrong. 

### ISSUE THREAD

**Issue by pedrojuanbj** [mdtraj/mdtraj#1493]
Hello, 

I detected that the mdtraj parser for PDB files (I'll attach the pdb as a proof for format) is getting wrong the element of Potassium and Chlorine Ions. Inside the class of the atoms, they have a nested class called element which has almost all atom possibilities. If you fetch the atom.element you will see that the POT (Potassium Ions) are assigned as Phosphorous and the CLA (Chlorine Ions) are assigned as Carbons. I believe it is due to reading the last column which is a P and a C.

This PDB comes from using Charmm-GUI and NAMD so beware this kind of formats.  

[pdb_file.zip](https://github.com/mdtraj/mdtraj/files/3809172/pdb_file.zip)

**Comment by peastman** [comment]
It's reading the file correctly.  The file is incorrect.  On an ATOM record, the element goes in columns 77-78.  On the POT lines, those columns contain " P" for phosphorous.  On the CLA lines, those columns contain " C" for carbon.

**Comment by pedrojuanbj** [comment]
> It's reading the file correctly. The file is incorrect. On an ATOM record, the element goes in columns 77-78. On the POT lines, those columns contain " P" for phosphorous. On the CLA lines, those columns contain " C" for carbon.

You can see that the file was generated with MDTraj 1.9.3 (Second row on the file), if I open this in pymol/vmd it gets them right. In addition, the original pdb file that this "cropped.pdb" comes from is a Charmm-GUI generated topology file. In that file, the element column is not there, unlike the cropped.pdb which has the element column just after the segname. 

I suspect this is due to loading the Charmm-GUI file in mdtraj and writing a new one out of it. The pdb writer may not work properly or at least it should not be added when the format corresponds to those. of Charmm-GUI.

[Charmm_GUI-step3_pbcsetup.zip](https://github.com/mdtraj/mdtraj/files/3810533/Charmm_GUI-step3_pbcsetup.zip)

I attached the original PDB file.

**Comment by peastman** [comment]
If the element column was missing in the original file, that's the origin of the problem.  MDTraj had to just guess at the element because it wasn't specified.  So it guessed P for atoms called POT and C for atoms called CLA, and therefore wrote those out to the file it created.  If elements had been specified in the original file it wouldn't have had to guess.

Guessing the element based on the first letter of the atom name isn't robust, but it does usually work.  And it's hard to really do better than that.
