### ISSUE TITLE
Regarding Shiftx2

### ISSUE THREAD

**Issue by Krishnendu39** [mdtraj/mdtraj#1495]
Hi
Can you please help me to calculate chemical shift for phosphorylated residues using MdTraj and Shiftx2. I found in MDTraj Phosphorylated residues CS calculation not yet included.
Thanks 
KB

**Comment by rmcgibbo** [comment]
This may be a better question for the developers of ShiftX2. I don't know whether this is supported or not.

**Comment by Krishnendu39** [comment]
Shiftx2 support for phosphorylation. I tried to use it with MDTraj for my long trajectories and MDTraj skipping the phos residues. So I think it's not passing the arguments of shiftx2 i.g -k and -c

**Comment by rmcgibbo** [comment]
My recommendation would be that you make that edit in your local copy, test that everything is working as expected (including that the results for the non-phosphorylation residues are unchanged), and then if it works propose a pull request here on github.

Thanks!
