### ISSUE TITLE
Zero-indexed requirement in shrake_rupley limits SASA calcs for contiguous atom slices

### ISSUE THREAD

**Issue by anotherjoshsmith** [mdtraj/mdtraj#1496]
I've run into a problem with the `shrake_rupley` implementation for what I imagine is a fairly common use case. I'm trying to calculate the change in SASA for proteins upon binding, using a Trajectory object for a protein-protein complex and Trajectory objects for each binding partner derived using `complex_traj.atom_slice(protein_1)` and `complex_traj.atom_slice(protein_2)`. The requirement in `shrake_rupley` that residues be zero-indexed (lines 165-168 below) prevents the calculation of SASA for the protein_2 Trajectory object, which retains its residue indices from the original PDB. 

https://github.com/mdtraj/mdtraj/blob/d5e40b636050ecb6bf1adfd5532c294f89e02cd7/mdtraj/geometry/sasa.py#L163-L168

I fixed the problem locally by adding the following line between lines 164 and 165 above:
`atom_mapping = atom_mapping - atom_mapping.min()`

This should maintain the requirement that the Trajectory object contains a contiguous residue set, but removes the limitation that the indices start at 0. Happy to make a PR with this change unless there is good reason to retain the 0-indexed requirement that I'm missing.

**Comment by rmcgibbo** [comment]
If you could file a PR for that and add some tests, that would be ideal.
