### ISSUE TITLE
Invalid values (NaN) encountered in 'mdtraj.compute_angles '

### ISSUE THREAD

**Issue by slowlightx** [mdtraj/mdtraj#1499]
This issue happens when calculating the angles of a triplet in a trajectory. I use all the angles to sort those angles smaller than a cutoff. Although it does not influence the final results, there is a warning that says 'invalid value encountered in greater'. 

I have printed the angles and found that there are some triplets whose angles are close to zero in all the frames and some just give the NaN results. This makes me think that maybe because the three atoms of the triplet indeed lie on a line, the results of angles' computation are smaller than the accuracy of Python float. 

Plus, I am pretty sure that each triplet consists of three different atoms.

**Comment by mattwthompson** [comment]
Wouldn't the angle simply be pi if they fell along a line?


```$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mdtraj as md
>>> import numpy as np
>>> xyz = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 2]])
>>> t = md.Trajectory(xyz=xyz, topology=None)
>>> md.compute_angles(t, [[0, 1, 2]])
array([[3.1415925]], dtype=float32)
```



Does this behavior depend on `opt`?

**Comment by slowlightx** [comment]
1. whether it being 0 or pi just depends on the order. In your case, if you change the order into [[0,2,1]], the angle will simply be [[0.]]. However, in my case, the resulting angles of some triplets are being like [[0. , 0. , 0.000xx, nan, 0]].

2. I am sorry that I haven't checked this since I've been busy with applications for graduate schools recently...

**Comment by slowlightx** [comment]
> Wouldn't the angle simply be pi if they fell along a line?
> 
> ```
> Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
> [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import mdtraj as md
> >>> import numpy as np
> >>> xyz = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 2]])
> >>> t = md.Trajectory(xyz=xyz, topology=None)
> >>> md.compute_angles(t, [[0, 1, 2]])
> array([[3.1415925]], dtype=float32)
> ```
> 
> Does this behavior depend on `opt`?
1. whether it being 0 or pi just depends on the order. In your case, if you change the order into [[0,2,1]], the angle will simply be [[0.]]. However, in my case, the resulting angles of some triplets are being like [[0. , 0. , 0.000xx, nan, 0]].

2. I am sorry that I haven't checked this since I've been busy with applications for graduate schools recently...
