### ISSUE TITLE
The SASA function does not recognize "Br" and "Cl" because atom.element.symbol returns "B" and "C" respectively

### ISSUE THREAD

**Issue by cespos** [mdtraj/mdtraj#1502]
While running the SASA calculation using the mdtraj.shrake_rupley function, I realized that instead of using the atomic radii of Br and Cl, the algorithm picks the ones of Boron (B) and Carbon (C), respectively. I realized that this was a problem associated with the lines:
`    if bool(modified_radii):`
    `atom_radii = [modified_radii[atom.element.symbol] for atom in traj.topology.atoms]`
`else:`
    `atom_radii = [_ATOMIC_RADII[atom.element.symbol] for atom in traj.topology.atoms]`

Especially, if the atom is Br, the atom.element.symbol = B and not Br.

I solved it by replacing the above lines with 

`for atom in traj.topology.atoms:`
    `atom_name = "{}".format(atom).split('-')[1]`
    `element = ''.join(i for i in atom_name if not i.isdigit())`
    `print("{} : {}".format(element, _ATOMIC_RADII[element]))`
    `if bool(modified_radii):`
        `atom_radii.append(modified_radii[element])`
    `else:`
        `atom_radii.append(_ATOMIC_RADII[element])`

I hope this can be useful to solve the issue!

**Comment by cespos** [comment]
Excuse me for writing again.

Have you investigated this issue?

**Comment by rmcgibbo** [comment]
This probably has nothing to do with the SASA code. The problem is likely that you PDB file is nonstandard and and the elements are not being determined correctly when reading the file.

**Comment by rmcgibbo** [comment]
> Especially, if the atom is Br, the atom.element.symbol = B and not Br.

Presumably what you really mean is that the atom is a Boron in your topology, right?

**Comment by cespos** [comment]
Thank you for the suggestion. 
I actually realized that the problem was that the atom symbol column was missing in the pdb and this is why the atom symbols were not recognized correctly.

**Comment by rmcgibbo** [comment]
Great. No problem.
