### ISSUE TITLE
mdconvert -c does not limit memory usage when specifying indices with -i

### ISSUE THREAD

**Issue by austinjpaul** [mdtraj/mdtraj#1503]
When using mdconvert to try to read in a very large dcd file in chunks, it instead attempts to read in the whole file, using lots of memory.

```
~$ mdconvert -o /tmp/OUTPUT/ARG1_1_85A_v1/slice_test.dcd -c 1000 -f -i 0:33950 /tmp/OUTPUT/ARG1_1_85A_v1/ARG1_1_85A_v1.bkp.dcd
...
  File "mdtraj/formats/dcd/dcd.pyx", line 457, in mdtraj.formats.dcd.DCDTrajectoryFile.read
MemoryError: Unable to allocate array with shape (38220, 80192, 3) and data type float32
```

I would expect it to only try to allocate an array of size (1000, 80192, 3), since 1000 is the chunk size.

**Comment by marscher** [comment]
Thanks for your report, can you please post the full stack trace?

**Comment by austinjpaul** [comment]
Yeah, sorry about that. Had to sanitize the paths.
```
Traceback (most recent call last):
  File "/home/ajp/miniconda3/envs/b-running/bin/mdconvert", line 11, in <module>
    sys.exit(entry_point())
  File "/home/ajp/miniconda3/envs/b-running/lib/python3.7/site-packages/mdtraj/scripts/mdconvert.py", line 500, in entry_point
    main(args)
  File "/home/ajp/miniconda3/envs/b-running/lib/python3.7/site-packages/mdtraj/scripts/mdconvert.py", line 288, in main
    atom_indices=atom_indices)
  File "/home/ajp/miniconda3/envs/b-running/lib/python3.7/site-packages/mdtraj/scripts/mdconvert.py", line 401, in read
    _data = infile.read(chunk, stride=stride, atom_indices=atom_indices)
  File "mdtraj/formats/dcd/dcd.pyx", line 457, in mdtraj.formats.dcd.DCDTrajectoryFile.read
MemoryError: Unable to allocate array with shape (38220, 80192, 3) and data type float32
```

And lastly,
```~$ conda list
# packages in environment at /home/ajp/miniconda3/envs/b-running:
#
# Name                    Version                   Build  Channel
...
mdtraj                    1.9.3            py37h00575c5_0    conda-forge
...
```

**Comment by marscher** [comment]
Thanks again. Indeed, this is weird. As you said it should only allocate 1000 frames in one shot.
The chunk or n_frames variable is passed as Python integer and is then converted to a C int in the actual read function, but I can not see any cause, why this conversion should fail for such small numbers.

**Comment by austinjpaul** [comment]
Here's an interesting bit of [logic](https://github.com/mdtraj/mdtraj/blob/7275066bb5bfa8068d835c7f7e331074a94ee874/mdtraj/scripts/mdconvert.py#L221):

```
    if args.index is not None:
        args.chunk = None
```

**Comment by kyleabeauchamp** [comment]
I imagine a refactor is out of scope but I'm a big fan of defopt: https://defopt.readthedocs.io/en/stable/features.html

**Comment by austinjpaul** [comment]
Just found this comment a little further down in `main()` which explains the above logic.
```
    if args.index is not None:
        assert len(args.input) == 1
        # when chunk is None, we load up ALL of the frames. this isn't
        # strictly necessary, and it costs more memory, but it's ALOT
        # harder to get the code correct when we need to use data[start:end]
        # notation when all of the data isn't loaded up at once. it's easy
        # for hdf5 and netcdf, but for the others...
        assert args.chunk is None
```
If an implementation isn't possible, I guess the easy way out is to document `chunk` and `index` as incompatible, but I'd love to know if there's a workaround for this use case.

I have a very large dcd and all I want to do is truncate the last few (hundred) frames. My script that uses `iterload` to read and `DCDTrajectoryFile` to write is quite slow.

**Comment by marscher** [comment]
It should not be slower than mdconvert if you use the low level DCDTrajectoryFile class in a loop. You could post the code somewhere, maybe I can spot the bottleneck (or maybe not).

**Comment by austinjpaul** [comment]
Ah, it seems my system is very I/O limited which explains the slowness.
