### ISSUE TITLE
[DOCS] Repeated versions in version dropdown

### ISSUE THREAD

**Issue by dwhswenson** [mdtraj/mdtraj#1504]
Something has gone weird in http://mdtraj.org/versions.json. For some reason, several copies of 1.8/1.8.0 and 1.9.3 have been added. Here's what I'm seeing in the version menu:

![image](https://user-images.githubusercontent.com/8178546/69892991-d8bc2b80-130b-11ea-94b4-52da354fb853.png)

I assume this is something that would be trivial for someone with upload permissions to mdtraj.org to fix (although I'm curious about the underlying problem, since I'm planning use some similar code on OpenPathSampling's docs.)

**Comment by rmcgibbo** [comment]
The “statefulness” of the versions.json file is really bad. I wouldn’t recommend it.

**Comment by rmcgibbo** [comment]
Fixed manually.

**Comment by rmcgibbo** [comment]
I committed e544514: Untested attempt to fix #1504, and fixed the versions.json file manually in the S3 web UI
