### ISSUE TITLE
Creating subset trajectory with selected residues

### ISSUE THREAD

**Issue by sbhakat** [mdtraj/mdtraj#1505]
Hi,

I wanted to create a subset of trajectory within selection residue index 78-83.

I am trying something like this using mdtraj dataset

```
a = np.arange(1083,1324) #the atom indices of residues 78-83
ds = dataset("../../trajfit.xtc", topology="../../prot0.pdb", atom_indices= a)
```
I think we can also do like following:

```
a = np.arange(1083,1324) #the atom indices of residues 78-83
trj = md.load_xtc('tfit_100.xtc', top='prot.pdb', atom_indices= a)
```
However this is changing the numbering of the atom indices.

**Is there any way I can make a subset of trajectory using a selected residue range without changing the atom numbering of the original file?**

**Comment by rmcgibbo** [comment]
No, I don’t think you can make a subset without changing the atom numbering. Sorry.
