### ISSUE TITLE
Regarding saving xyz format.

### ISSUE THREAD

**Issue by swillow** [mdtraj/mdtraj#1507]
The xyz format is
'
number of atoms
comment
element x y z
...
'
Hence, I would like to ask that the atom_type (types) is replaced by atom_element in the following line :
https://github.com/mdtraj/mdtraj/blob/e5445149d0c9843cf1a2d49737c4d7288daa9e69/mdtraj/formats/xyzfile.py#L328

**Comment by rmcgibbo** [comment]
The documentation for the code states

```
    While there is no universal standard for this format, this plugin adheres
    to the same format as the VMD plugin:
    
http://www.ks.uiuc.edu/Research/vmd/plugins/molfile/xyzplugin.html
```

The VMD documentation linked uses indicates "atom name followed by xyz coords". I think what MDTraj is doing is appropriate, and that it would be unwise to silently change the behavior (it's been this way since @ctk3b added this code 4 years ago).

**Comment by rmcgibbo** [comment]
I'm marking this as wontfix. Let me know if you strongly object, @swillow.

**Comment by ctk3b** [comment]
> stale bot removed the wontfix label 4 minutes ago

Cheeky...

**Comment by swillow** [comment]
I used a 'xmakemol' to open a xyz file and realized that 'xmakemol' cannot open a xyz file generated by mdtraj. Besides, I agree with you that vmd can open a xyz file generated by mdtraj.

It is OK to me that you won't fix it.

**Comment by rmcgibbo** [comment]
Thanks.
