### ISSUE TITLE
python 3.8 incompatibility in selection

### ISSUE THREAD

**Issue by Olllom** [mdtraj/mdtraj#1509]
Python 3.8 requires an argument `posonlyargs` in `ast.arguments`.

The error message is:
``` 
 File "lib/python3.8/site-packages/mdtraj/core/topology.py", line 1048, in select
    filter_func = parse_selection(selection_string).expr 
  File "lib/python3.8/site-packages/mdtraj/core/selection.py", line 400, in __call__    
    compile(ast.fix_missing_locations(func), '<string>', mode='eval'),        
TypeError: required field "posonlyargs" missing from arguments
```

https://github.com/mdtraj/mdtraj/blob/f80d885d374a357a7badeefafc0d331de617bd52/mdtraj/core/selection.py#L394

Adding `posonlyargs=[]` here should fix the problem, see for example https://github.com/xonsh/xonsh/pull/3304/files .

(I have not checked if this change is backwards compatible with python 3.5-3.7 or if there are other usages of `ast.arguments` in mdtraj.)

**Comment by rmcgibbo** [comment]
Sounds good. Would you be able to file a pull request with that change?

**Comment by acnash** [comment]
Is there a brief example of the solution? I've got the same issue. I'm very new to Python and I expect I've probably changed the core code incorrectly. 

`            signature = ast.arguments(args=args, vararg=None, kwarg=None,
                                      posonlyargs=[],
                                      kwonlyargs=[], defaults=[],
                                      kw_defaults=[])`

**Comment by mattwthompson** [comment]
I'm not new to Python (but far from an expert) and that change looks to be correct. Have you been able to see if it works for you locally?

**Comment by acnash** [comment]
Any assistance is welcome. From within PyCharm:
`str(md)`
**"<module 'mdtraj' from '/Users/anthonynash/PycharmProjects/AGE/venv/lib/python3.8/site-packages/mdtraj/__init__.py'>"**

And the location of the file I've changed:
/Users/anthonynash/PycharmProjects/AGE/venv/lib/python3.8/site-packages/mdtraj/core

After making the change I imported MDTraj and reran the respective python commands but with no success. Any handy means of dumping the selection.py source to the command line? Thanks.

**Comment by acnash** [comment]
I was running it through the PyCharm IDE and it was getting all a bit muddled. Issues resolved.

**Comment by rahabet** [comment]
so how did you solved it? is there a step I should follow? I am new for python and I am getting that error and I couldn't find anything that helps me on how to fix it

**Comment by mattwthompson** [comment]
@rahabet after #1523, the master branch should have this fixed. So if you are using a local copy, it should work. If you are installing from pip or conda that will have to wait, probably until this weekend when I have time to push a new release but potentially much longer if 3.8 isn't supported
