### ISSUE TITLE
Residue name and atom name are forcibly rewritten

### ISSUE THREAD

**Issue by mumeiyamibito** [mdtraj/mdtraj#1514]
In Gromacs, water molecule recognized as the residue name SOL, atom name OW, and HW.
However, save_gro() and save_pdb() output water molecule as residue names HOH, atom names O, H1, and H2.
I'd like to use mdtraj to extract from the trajectory into each frame for use as an initial structure of next MD simulation.
Is there a way to keep residue and atom names in the topology file?

```py
import mdtraj
for frame_idx, frame_obj in enumerate(mdtraj.iterload("test.xtc", top = "test.gro", chunk = 1)):
    if frame_idx == 0:
        frame_obj.save_gro("test.gro", force_overwrite = True)
    else:
        break
```

**Comment by peastman** [comment]
I thought Gromacs had switched to using standard PDB names (HOH instead of SOL) years ago?

**Comment by mumeiyamibito** [comment]
@peastman Thank you for replying and the information.

In some super computer systems, old version Gromacs is installed for compatibility.

Where does mdtraj get information from? Normally, users think that residue and atom information in output will be based on the given topology.

**Comment by peastman** [comment]
The names of atoms and residues are standardized as part of the PDB chemical components dictionary.  MDTraj tries to follow the principle, "Be tolerant about what you accept as inputs and strict about what you produce as outputs."  If your input file uses nonstandard names, it will do its best to interpret them correctly.  It then does its best to make the files it writes fully standards compliant.

**Comment by mumeiyamibito** [comment]
@peastman OK. I understood.

In output process, I use subprocess with trjconv instead of mdtraj.
