### ISSUE TITLE
save_xyz() method

### ISSUE THREAD

**Issue by fabiotrovato** [mdtraj/mdtraj#1517]
Hi,

when I save the coordinates to xyz format, I get the following (first few lines of the .xyz file):
674
Created with MDTraj 1.9.3, 2019-12-22
CA -337.500 -164.059 1927.749
CA -337.562 -157.264 1924.705
CA -333.164 -152.305 1928.297

How do I eliminate "Created with MDTraj 1.9.3, 2019-12-22"?

Thanks for your help,
Fabio

**Comment by mattwthompson** [comment]
You _could_ comment out [this ](sed )line or accomplish this trimming with `sed`, but it's unadvisable; MDTraj adheres to the most common XYZ format structure and dropping the comment line is likely to provide headaches downstream if you're using mature software later in your workflow.

**Comment by fabiotrovato** [comment]
Thanks for the suggestion!

**Comment by fabiotrovato** [comment]
Usually the comment line in the .xyz format can be any comments (even a blank line). Are sed and awk the only ways to change the default comment or there's a method in mdtraj to do that? This would be helpful, as I would like to specify my comment(s) for my xyz file that represents a trajectory.

**Comment by mattwthompson** [comment]
[here](https://github.com/mdtraj/mdtraj/blob/10a0b08f53d4a7c3be48ebe301b5a91222c78e1a/mdtraj/formats/xyzfile.py#L324) is where MDTraj writes out that line; one could modify that line to write a blank line or some other comment. However, I must caution you that MDTraj adheres to the file format specification (to the extent there is one for XYZ, but that's a different story) and tinkering with this should not be necessary. Most any reader should deal with the comment line fine no matter its contents.
