### ISSUE TITLE
Defining new hydrogen bond atom acceptors and donators. 

### ISSUE THREAD

**Issue by acnash** [mdtraj/mdtraj#1521]
The link to an MDTraj forum was throwing up security warnings so I'm hoping I'll be able to get a response here. 

Is it possible to add custom atom names to the hydrogen bonding functionality in MDTraj? I've parameterised a post-translational modified amino acid as part of the existing amber99sb-ildn as shipped with the latest Gromacs distributions. New atom types along with atom names have been defined e.g., from a gromacs trajectory file: 

11DOG1     N  125   2.839   1.991   0.862
   11DOG1    HN  126   2.800   1.927   0.926
   11DOG1   CD1  127   2.984   2.047   0.922
   11DOG1   HD1  128   2.960   2.144   0.955
   11DOG1     C  129   3.152   2.039   0.863
   11DOG1   OD1  130   3.211   1.938   0.891
   11DOG1   CD3  131   3.013   2.011   1.079
   11DOG1  HD31  132   2.985   2.087   1.140
   11DOG1  HD32  133   3.120   2.015   1.102
   11DOG1   CD4  134   2.960   1.889   1.143
   11DOG1  HD41  135   3.015   1.872   1.235
   11DOG1  HD42  136   2.990   1.805   1.081
   11DOG1   CD5  137   2.812   1.902   1.182
   11DOG1  HD51  138   2.751   1.952   1.108
   11DOG1  HD52  139   2.804   1.964   1.271
   11DOG1   CD6  140   2.746   1.769   1.215
   11DOG1  HD61  141   2.639   1.783   1.226
   11DOG1  HD62  142   2.782   1.744   1.315
   11DOG1   ND2  143   2.785   1.659   1.124

ND2, N, HN and OD1 are chemically able to hydrogen bond. However, I know of only the "N" from this list that would be accepted in the hydrogen bond analysis of GMX (gromacs executable) and other API analysis tools e.g., MDAnalysis. 

Thanks
Anthony

**Comment by acnash** [comment]
Thanks to some folk on Twitter I've managed to track down the code in hbonds.py to change in order to accept customised atom names. I'll make the change myself. Hopefully, time permitted, I can submit the code to Git for others to use.

**Comment by ahy3nz** [comment]
From the [mdtraj hbond code](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/hbond.py#L366), it looks like identifying hbond triplets involves finding the donors and acceptors based on the `element` attribute of each `atom` in your `topology`. 

You could trace back this problem to how your `topology` is constructed from your `gro` file, in that [an element is attempted to be inferred from your atom name](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/gro.py#L317). If your ND2, HN, and OD1 don't get tagged with the nitrogen, hydrogen, or oxygen `element` attributes, then the mdtraj hbond code will end up ignoring them. So you could modify your `gro` file such that the atom names can more easily be related to elements, or maybe you could modify your `mdtraj.Topology` object, replacing `mdtraj virtual elements` with `mdtraj real elements`

**Comment by acnash** [comment]
Hi, thanks for the comment. In terms of software sustainability, I think it would be best practice to generalise how MDTraj reads the topology/interprets hbonds rather than adjusting the GROMACS trajectory itself. I'm thinking that a user-provided list or two as an argument to the hbond function would suffice. Or, as you said the `mdtraj real elements` route might be better, however, I've yet to put any thought in that approach as I'm relatively new to MDTraj. I'll give it some thought when I've got a day spare. Thanks.
