### ISSUE TITLE
mdtraj.shrake_rupley causes a deadlock in multiprocessing

### ISSUE THREAD

**Issue by ostrokach** [mdtraj/mdtraj#1522]
It appears that `mdtraj.shrake_rupley` causes a deadlock when executed using Python's `ProcessPoolExecutor`.

I have not seen this issue with other mdtraj analysis function.

I am using mdtraj version 1.9.3.

```python
import concurrent.futures
import tempfile
import urllib.request

import mdtraj


# Download demo PDB file (works with any PDB file AFAIK)
with tempfile.NamedTemporaryFile(suffix=".pdb.gz") as pdb_file:
    with open(pdb_file.name, "wb") as fout:
        fout.write(urllib.request.urlopen("https://files.rcsb.org/download/4DKL.pdb.gz").read())
    traj = mdtraj.load(pdb_file.name)


# Calculations work in the current REPL
sasa = mdtraj.shrake_rupley(traj, mode="residue")


# Calculations deadlock when using `concurrent.futures.ProcessPoolExecutor`
with concurrent.futures.ProcessPoolExecutor() as pool:
    futures = pool.map(mdtraj.shrake_rupley, [traj, traj])
    retults = list(futures)
```

**Comment by rmcgibbo** [comment]
I believe you're seeing an incompatibility between Python's multiprocessing and OpenMP. This has been documented in a few places, e.g. https://github.com/numpy/numpy/issues/5752, https://github.com/pytorch/pytorch/issues/17199, https://stackoverflow.com/questions/49049388/understanding-openmp-shortcomings-regarding-fork
