### ISSUE TITLE
Topology.from_openmm fails to identify resname HSD as protein

### ISSUE THREAD

**Issue by SimoneCnt** [mdtraj/mdtraj#1524]
Hello,

I'm converting a charmm topology from OpenMM to MDTraj using:

    top_md = mdtraj.Topology().from_openmm(top_omm)

If I try to select all protein atoms with:

    protein_indices = top_md.select('protein').tolist()

this fails to identify HSD residues as protein.

I think the problem is in `core/topology.py` at line 1457, which defines as proteins all residues in `_PROTEIN_RESIDUES`, but this does not contain HSD.

Is it possible to solve this, or am I missing something?

Sample code to reproduce the issue:

    from simtk.openmm import app
    import mdtraj

    # Make a OpenMM topology
    top_omm = app.topology.Topology()
    chain_a = top_omm.addChain('A')
    res_ala = top_omm.addResidue('ALA', chain_a)
    top_omm.addAtom('CA', app.element.carbon, res_ala)
    res_his = top_omm.addResidue('HIS', chain_a)
    top_omm.addAtom('CA', app.element.carbon, res_his)
    res_hsd = top_omm.addResidue('HSD', chain_a)
    top_omm.addAtom('CA', app.element.carbon, res_hsd)
    res_ala = top_omm.addResidue('ALA', chain_a)
    top_omm.addAtom('CA', app.element.carbon, res_ala)

    # Convert to MDTraj
    top_md = mdtraj.Topology().from_openmm(top_omm)

    # Select protein
    protein_indices = top_md.select('protein').tolist()
    print(protein_indices)  # Will print [0, 1, 3] missing atom 2

**Comment by peastman** [comment]
According to the PDB chemical components dictionary, HSD is (1S,2S,3R,6R)-6-amino-4-(hydroxymethyl)cyclohex-4-ene-1.  (Whatever that is!)  Looks like a problem with nonstandard names?

**Comment by SimoneCnt** [comment]
Sorry, I didn't specify. HSD is neutral histidine in charmm force field.

**Comment by peastman** [comment]
MDTraj doesn't know that.  It expects Topologies to use standard naming, so histidine should be called HIS.

Of course, that translation really should be done for you automatically.  Looking over the code, it appears both OpenMM and MDTraj check for nonstandard names when loading PDB, Amber, or Gromacs files, but not when loading CHARMM files.  It would be good to fix that in both of them.

**Comment by SimoneCnt** [comment]
MDTraj already recognizes HSD residues as protein if read directly from pdb files; see #700 and #637. 
What's missing here is when converting from an OpenMM topology.

**Comment by peastman** [comment]
I fixed the error on the OpenMM side: https://github.com/openmm/openmm/pull/2557.  It will now replace nonstandard names when loading a PSF file.  MDTraj still needs a corresponding fix in its own loader.
