### ISSUE TITLE
Update conda?

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#1526]
The conda release is 1.9.1; mdtraj is currently on 1.9.3. What are the chances of getting the conda build updated?

**Comment by mattwthompson** [comment]
It looks like the versions on forge are updated - I assume you're pulling from omnia to see 1.9.1 as the most recent?

**Comment by davidlmobley** [comment]
Ah, that's probably it. But I was also referring to the badge on the main Readme.md which lists 1.9.1.

**Comment by marscher** [comment]
fixed by 48cdc3d
