### ISSUE TITLE
mdconvert can not convert .DCD file (2.8 GB) to .pdb file

### ISSUE THREAD

**Issue by hima111997** [mdtraj/mdtraj#1531]
I have a dcd file of size 2.8 GB and I want to convert it to PDB file. when I try to use mdconvert it gives me this error:
OSError: Could not open file: D:/GP/research/1_doctor_abdo/zikv/cluster/N_5.dcd

what is the problem?

**Comment by mattwthompson** [comment]
It looks like there is something wrong with the path to that file - the OS couldn't find it even before MDTraj tried to open it

**Comment by hima111997** [comment]
@mattwthompson 
mdconvert -o D:\pep42.pdb -s 1000 -a D:\atoms.txt -t D:\N_wb.pdb D:\N_5.dcd

I copied the files to the D partition and used this command.

this is the error:
dcdplugin) Could not access file 'D:\N_5.dcd'.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\newenv\Scripts\mdconvert-script.py", line
10, in <module>
    sys.exit(entry_point())
  File "C:\ProgramData\Anaconda3\envs\newenv\lib\site-packages\mdtraj\scripts\md
convert.py", line 500, in entry_point
    main(args)
  File "C:\ProgramData\Anaconda3\envs\newenv\lib\site-packages\mdtraj\scripts\md
convert.py", line 284, in main
    with InFileFormat(fn, 'r') as infile:
  File "mdtraj\formats\dcd\dcd.pyx", line 221, in mdtraj.formats.dcd.DCDTrajecto
ryFile.__cinit__
OSError: Could not open file: D:\N_5.dcd

**Comment by hima111997** [comment]
I tried mdconvert command with another .dcd file (10 MB) and it worked well

**Comment by mattwthompson** [comment]
That error is saying it did not find a file at that path

**Comment by hima111997** [comment]
![image](https://user-images.githubusercontent.com/55895327/75753121-b8e53b00-5d32-11ea-969e-abf8f664d521.png)

@mattwthompson 
this is an image for the directory containing the files and the command line with the error

**Comment by hima111997** [comment]
@sunnyhao1992 i cant remember how did i solve it but when i locked back at the command i noticed that there is one "\". try to convert every single back slash into double back slash --> mdconvert -o D:\\pep42.pdb -s 1000 -a D:\\atoms.txt -t D:\\N_wb.pdb D:\\N_5.dcd.
if it did not work try another library
