### ISSUE TITLE
Atom Selection Question

### ISSUE THREAD

**Issue by Teohoho** [mdtraj/mdtraj#1532]
Hello. At the moment I'm using VMD to extract atom indices from a molecule, according to a user-generated selection, but I'd like to switch to MDTraj, since python is much more well-known than Tk/Tcl. However, I've noticed that, while VMD has a selection for atoms involved in rings, using the "pucker" keyword, MDTraj does not. Is there a way to systematically select all atoms involved in aromatic/non-aromatic rings, similar to the one in VMD?

Thank you.

**Comment by rmcgibbo** [comment]
No, unfortunately there's no feature for this currently.
