### ISSUE TITLE
[tests] DataFrame.ix method removed in pandas-1.0.0

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#1535]
We need to adopt tests using the long deprecated DataFrame.ix method.

- [ ] test_pdb.test_3nch_serial_resSeq

**Comment by marscher** [comment]
set_index seems to remap the indicies to a consecutive sequence, thereby dropping the "holes" in the pdb file. I guess there is a Pandas like solution to this, but I'm not an expert.

**Comment by mattwthompson** [comment]
Seems to be fixed in #1536, although it was purely a pandas fix and had nothing to do with PDB stuff
