### ISSUE TITLE
image_molecules into conda / pip versions

### ISSUE THREAD

**Issue by ljmartin** [mdtraj/mdtraj#1537]
Hi and thankyou for mdtraj which has been so useful. 

I don't know if this is a big ask, but is it possible to get https://github.com/mdtraj/mdtraj/pull/1466 into the conda / pip installable versions? For project reproducibility it helps to use a conda environment but then the `image_molecules` function won't work because they install 1.9.3.

Thanks!

**Comment by dwhswenson** [comment]
Just a little bump on this. It's been most of a year since 1.9.3, and there are important improvements since then (waiting for the `int32_t` fixes in #1466 and #1511 is particularly frustratng). If there's anything I can do to help make a new release possible, I might be able to put a few hours into it.

**Comment by mattwthompson** [comment]
Right now the conda-forge maintainers are @rmcgibbo @mpharrigan @marscher, although I believe each individual has mostly moved on to bigger and better things. 

https://github.com/conda-forge/mdtraj-feedstock/blob/c0a955821827ff235fde69db5873854d6f521aab/recipe/meta.yaml#L62-L64

I am also willing to offer some of my time to keep this package maintained

**Comment by rmcgibbo** [comment]
@mattwthompson: do you feel comfortable doing a release? the instructions in https://github.com/mdtraj/mdtraj/tree/master/devtools are a little outdated (it mentions omnia rather than conda-forge) but i think correct. i can add you as a maintainer on here/pypi/etc

**Comment by mattwthompson** [comment]
Sure, I've spent the past couple years maintaining a couple of projects inherited from Christoph that have a similar enough release process. I should be able to infer updates from the dev docs, like the migration to `conda-forge`

**Comment by rmcgibbo** [comment]
What's your username on pypi?

**Comment by mattwthompson** [comment]
mattwthompson

**Comment by rmcgibbo** [comment]
That was easy, you should have all the permissions now :)
