### ISSUE TITLE
Mdtraj topology select names with apostrophe

### ISSUE THREAD

**Issue by jasperdenduijf** [mdtraj/mdtraj#1538]
I have an .xtc and a .gro file, showing a part of DNA. I want to select certain atoms by name. The problem is that certain names contain ' (apostrophe). We have for example O4' or C2'. 

`topology.select("name O4' and resid 3")` or differently written `topology.select("name O4\' and resid 3")` result both in the following error: 

`ValueError: Expected end of text (at char 7), (line:1, col:8): name O4' and resid 3`

Since using an apostrophe it is the standard, proper notation for DNA with sugar elements, I was hoping there is a way to work around this problem?

**Comment by rmcgibbo** [comment]
It might work if you quote the resname like `topology.select('name "O4\'" and resid 3')

**Comment by jasperdenduijf** [comment]
> It might work if you quote the resname like `topology.select('name "O4\'" and resid 3')`

That did indeed work. Much appreciated!

**Comment by rmcgibbo** [comment]
No problem!
