### ISSUE TITLE
Add coordinates of a newly added atom

### ISSUE THREAD

**Issue by mghattas100** [mdtraj/mdtraj#1539]
I'm implementing mdtraj in a protein preparation python script that I'm developing currently. 

I noticed that I can add new atoms to the topology object using either add_atom or insert_atom. Is there a way to add coordinates of the new atom that I'm trying to add? 
I searched all your script documentation but I failed to find any function or methods to add positions to a newly added atom.
I understand that coordinates are stored in structure.xyz. Is the only way to do it is by adding the new coordinates to the list? Or is there a method/function to add coordinates that i don't know about?

**Comment by mghattas100** [comment]
It seemed that the shape of numpy array of xyz can’t be added meaning I can’t add new coordinates to the list.

**Comment by sroet** [comment]
If you want to add new molecules to an existing trajectory, I normally use [`stack`](http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.stack)

```python
# load traj and traj2
traj3 = traj.stack(traj2)
```
(if traj2 contains your new atoms)

Now if you want to add atoms to existing residues/chains, you need to alter the topology.
The fastest way I have found it to do that is to take everything outside the trajectory and then make a new one.

```python
# load your trajectory
# get all the variables for a new trajectory
top = traj.top
xyz = traj.xyz
time = traj.time
ul = traj.unitcell_lengths
ua = traj.unitcell_angles

# Add your atom to topology here
top.add_atom(....)
# Add to xyz here (stack along the 'atom' axis)
xyz3 = np.stack((xyz, xyz2), axis=1)

# Now make a new trajectory
traj2 = md.Trajectory(xyz=xyz3, topology=top, time=time, unitcell_lengths=ul, unitcell_angles=ua)
```
