### ISSUE TITLE
ERROR on pip installation

### ISSUE THREAD

**Issue by sperezconesa** [mdtraj/mdtraj#1541]
Hello,
I am trying to install mdtraj on my Raspberry Pi which has ARM architecture (I am not sure if this is the problem). I am using python 3.7.3. I get the following given bellow.
Thank you very much in advance!
Best,
Sergio

```text
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mdtraj
  Using cached mdtraj-1.9.3.tar.gz (907 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/sperez/mdsrv_env/bin/python /home/sperez/mdsrv_env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp9w06niy8
         cwd: /tmp/pip-install-w5c5eyqe/mdtraj
    Complete output (15 lines):
    Using built-in specs.
    COLLECT_GCC=arm-linux-gnueabihf-gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
    Target: arm-linux-gnueabihf
    Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
    Thread model: posix
    gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
    ./basesetup.py:415: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-tzu39ssy'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    C compiler:
    Attempting to autodetect OpenMP support... Compiler supports OpenMP
    Attempting to autodetect SSE3   support... Did not detect SSE3 support
    Attempting to autodetect SSE4.1 support... Did not detect SSE4.1 support
    
    mdtrajs setup depends on NumPy. Install it prior invoking setup.py
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/sperez/mdsrv_env/bin/python /home/sperez/mdsrv_env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp9w06niy8 Check the logs for full command output.
```

**Comment by justinrporter** [comment]
You need `numpy` installed to use `mdtraj`. In my limited experience, though, it's not as straightforward on raspberry pi as you'd like, but I think it is possible.

**Comment by rmcgibbo** [comment]
Two things:
1. As @justinrporter said, you need to first install numpy before installing mdtraj. That's what the error message is trying to say.
2. There are definitely some features of mdtraj that will not work on ARM because the C/C++ code using SSE intrinsics isn't going to compile (RMSD, optimized distance/angle/dihedral calculations). Given that I don't have high confidence (once numpy is installed) that mdtraj will compile.

**Comment by rmcgibbo** [comment]
Related: https://github.com/mdtraj/mdtraj/issues/888, https://github.com/mdtraj/mdtraj/issues/1432.

**Comment by sperezconesa** [comment]
I have been able, with some trouble to install numpy with pip in the raspberry. Now I get another error related to PEP 517. It sounds familiar from looking up issues, I will search up to sea if there are related posts. 

I think this issues with SSE might be irrelevant since I only need MDTraj for mdsrv (http://nglviewer.org/mdsrv/)

**Comment by justinrporter** [comment]
> I think this issues with SSE might be irrelevant

It looks like `mdsrv` uses `mdtraj` for loading trajectories, and at least some of this functionality is compiled (the `xtc` i/o, for example), although I don't know if it uses any fancy SSE intrinsic.

> Now I get another error related to PEP 517

Try `--no-use-pep517` or `--no-binary` to prevent pip from trying to download a precompiled binary.

However, in light of your need to only compile a subset of the compiled extensions, it might be worth your time to clone the project and run `setup.py install` in the cloned repo. It'll error out when it tries to compile the SSE-using extensions, then you might be able to comment out certain parts of `setup.py` to avoid their compilation.

This is obviously not a supported context for mdtraj, but if you're committed it could work. :)

**Comment by rmcgibbo** [comment]
Closing this, since porting to ARM is not on the agenda.

**Comment by rmcgibbo** [comment]
I just ported the RMSD and distance code to aarch64. If your RPi is 64-bit, it ought to work now with the master branch.

**Comment by sperezconesa** [comment]
Unfortunatelly it is 32bit armv7l :(
Thanks a lot anyway for making the effort. :)
