### ISSUE TITLE
Documentation for mdtraj.rmsf() describes mdtraj.rmsd() instead

### ISSUE THREAD

**Issue by mewall** [mdtraj/mdtraj#1543]
It looks like the documentation for mdtraj.rmsf() at http://mdtraj.org/1.9.3/api/generated/mdtraj.rmsf.html describes the mdtraj.rmsd() method instead.

I just tested both methods. It looks like rmsd() computes the RMSD of each frame over all selected atoms, with respect to a reference. This is what the docs say.

On the other hand, it looks like rmsf() computes the RMSF of each selected atom over all frames (after aligning each frame to the reference?). This is different from what the docs say.

I was actually looking for the rmsf() method in mdtraj and nearly gave up on it, thinking it was being used as a synonym for rmsd(), before I tested it out...

Here's what rmsd() produces:

rmsd1 = md.rmsd(t,s,frame=0,atom_indices=sel_indices, parallel=True)

![image](https://user-images.githubusercontent.com/4061841/80005247-8f1dda00-8480-11ea-8f26-19851694cba0.png)

And here's what rmsf() produces:

rmsd = md.rmsf(t,s,frame=0,atom_indices=sel_indices, parallel=True)

![image](https://user-images.githubusercontent.com/4061841/80005290-9ba23280-8480-11ea-8ae0-78e82013ad82.png)

Related to issues #1210 and #1414

**Comment by rmcgibbo** [comment]
Could you submit a change to the docstring that you think would clarify it?

**Comment by mewall** [comment]
I think whoever wrote this code should document it correctly...however, I attach an edit of the text, based on what I can see in the rmsf code here: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx

Maybe this will help. But it probably should be checked by someone who is already familiar with the code.

Please also see the *** notes, I'm not sure the parallel code in there is correct, but I'm not familiar with the programming model.

I'm not sure how to edit the docs directly but if you can point me to instructions I can try, given permissions to create a new branch and submit a pull request. 

Thanks.

[mdtraj.rmsf.docx](https://github.com/mdtraj/mdtraj/files/4690903/mdtraj.rmsf.docx)

**Comment by mewall** [comment]
OK, I see cython prange will treat that reduction properly:

https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html

I think you can ignore the comment about the parallel regions.

**Comment by Yoshanuikabundi** [comment]
There's (at least) one more error in the docstring - the stated shape of the return array is incorrect:
```
    Returns
    -------
    rmsf : np.ndarray, shape=(target.n_frames,)
        A 1-D numpy array of the optimal root-mean-square fluctuations from
        the `frame`-th conformation in reference to each of the conformations
        in target.
```
on line 281 should be something like
```
    Returns
    -------
    rmsf : np.ndarray, shape=(len(atom_indices) OR target.n_atoms,)
        A 1-D numpy array of the optimal root-mean-square fluctuations from
        the `frame`-th conformation in reference to each of the conformations
        in target.
```

**Comment by rmcgibbo** [comment]
If you go to this page, you should be able to propose edits by tapping the little pencil icon: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/_rmsd.pyx

Here are instructions: https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-another-users-repository

**Comment by mewall** [comment]
Thanks for taking a look. Yes, there might be other issues, I just made one pass through the documentation myself...

________________________________

**Comment by mewall** [comment]
Thanks for the clarification about how to do this.


I didn't know about this feature when I responded, so I just attached a doc with some edits to the issue. I hope it can be used to fix the docstring.


Thanks.

________________________________

**Comment by apayne97** [comment]
Well I don't think I have the power to re-open this but this issue still hasn't been fixed!

**Comment by rmcgibbo** [comment]
I re-opened it. It'd be great if someone could propose a PR with a fix.

**Comment by apayne97** [comment]
I maybe still don't understand RMSF but why would you ever need a reference trajectory? Isn't the whole point to compare to the AVERAGE of the target trajectory (which is what the code does)?

**Comment by apayne97** [comment]
Hi @rmcgibbo! I could make a PR with a fix once I understand exactly how the code should work and whether or not its doing what it should be doing!

**Comment by mewall** [comment]
This is what I came up with as a suggestion a while ago. Ignore the thread-safe comment.


Presumably the alignment was put in to minimize contributions of overall rigid-body translations and rotations.

________________________________
From: Alexander Matthew Payne ***@***.***>
Sent: Thursday, September 23, 2021 2:42:11 PM
To: mdtraj/mdtraj
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [mdtraj/mdtraj] Documentation for mdtraj.rmsf() describes mdtraj.rmsd() instead (#1543)


Hi @rmcgibbo<https://github.com/rmcgibbo>! I could make a PR with a fix once I understand exactly how the code should work and whether or not its doing what it should be doing!

**Comment by apayne97** [comment]
ok finally just reading your doc here, I'll make edits to the docstring in this comment for easy viewing.

I'm not sure about the part regarding pre-centering? in the example. The main thing I added was
```
reference : md.Trajectory, or None
        A trajectory with the same number of atoms as in the target to be used
        as a reference. If None, the average xyz positions of each atom will be used.
```

new version:
```
    """rmsf(target, reference, frame=0, atom_indices=None, parallel=True, precentered=False)
    Compute RMSF of atom positions in target trajectory. This will center target conformations in place.
    Parameters
    ----------
    target : md.Trajectory
        Compute the RMSF of atom positions in target trajectory. 
    reference : md.Trajectory, or None
        A trajectory with the same number of atoms as in the target to be used
        as a reference. If None, the average xyz positions of each atom will be used.
    frame : int, default=0
        The index of the conformation in `reference` to measure
        distances to.
    atom_indices : array_like, or None
        The indices of the atoms to use in the RMSF calculation. If not
        supplied, all atoms will be used. If the atoms used in alignment
        and the atoms used in RMSF calculations are different, the trajectory
        must be aligned first manually.
    ref_atom_indices : array_like, or None
        Use these indices for the reference trajectory. If not supplied,
        the atom indices will be the same as those for target.
    parallel : bool
        Use OpenMP to calculate each of the RMSFs in parallel over
        multiple cores.
    precentered : bool, default=False
        Assume that the conformations are already centered at the origin, and that
        the "rmsd_traces" have been computed, as is done by
        `Trajectory.center_coordinates`. The "rmsd_traces" are intermediate
        calculations needed for the RMSF calculation which can be computed
        independently on each trajectory. Note that this has the potential to
        be unsafe; if you use Trajectory.center_coordinates and then modify
        the trajectory's coordinates, the center and traces will be out of
        date and the RMSFs will be incorrect.
    Examples
    --------
    >>> import mdtraj as md                                      # doctest: +SKIP
    >>> rmsf = md.rmsf(trajectory, trajectory, 0)                # doctest: +SKIP
    >>> print rmsf                                               # doctest: +SKIP
    array([ 0.0,  0.03076187,  0.02549562, ...,  0.06230228,
        0.00666826,  0.24364147])
    The calculation is slightly faster if you precenter the trajectory
    >>> trajectory.center_coordinates()
    >>> rmsf = md.rmsf(trajectory, trajectory, 0, precentered=True)
    If the atoms used in alignment and RMSF calculations are different,
    align the trajectory before using this method.
    >>> trajectory.superpose(atom_indices=atom_indices)
    >>> rmsf = md.rmsf(trajectory, None, atom_indices=rmsf_atom_indices)
    See Also
    --------
    Trajectory.center_coordinates
    Notes
    -----
    This function uses OpenMP to parallelize the calculation across
    multiple cores. To control the number of threads launched by OpenMP,
    you can set the environment variable ``OMP_NUM_THREADS``.
    Returns
    -------
    rmsf : np.ndarray, shape=(atom_indices,)
        A 1-D numpy array of the optimal root-mean-square fluctuations of the
       selected atoms.
    """
```

**Comment by rmcgibbo** [comment]
Could you put this into a pull request?

**Comment by apayne97** [comment]
Created pull request https://github.com/mdtraj/mdtraj/pull/1676!

**Comment by apayne97** [comment]
I think this issue can be resolved now?
