### ISSUE TITLE
Assign fames to predefined cluster centroids

### ISSUE THREAD

**Issue by PeptideSimulator01** [mdtraj/mdtraj#1544]
Dear all,

Clusterring all trajectories from a production takes too long. Therefore i clustered (based on RMSD Ward Hierarchical) a subset of the trajectories and got my centroid structures (5 centroids). In my opinionen the 5 centroids from the subset clustering represent most of the sampling space. Right now, I want to assign or distribute the remaining majority of the trajectories to these 5 clusters to observe which of the 5 clusters is used the most. 

Any help or hint is appreciated.
Thanks for your effort.

**Comment by justinrporter** [comment]
Hi! Yes this is quite a common task. You can write the code to do this yourself by computing the RMSD of each frame in your production trajectories to each centroid and argmax'ing the result. Alternatively, [enspara](https://github.com/bowman-lab/enspara) has an application that does this, called `reassign.py`, which basically is just MDTraj under the hood.
