### ISSUE TITLE
Iterload function: "chunk" parameter is "chunk" multiplied by "stride"

### ISSUE THREAD

**Issue by alberginia** [mdtraj/mdtraj#1545]
I am using MDTraj with large trajectory files (dcd with 10001 frames) and I was trying to use "iterload" to carry out my calculations. 

Fixing "stride = 1", the chunks seem to be OK and of the specified size. 

However, anything other than that, yields the most weird behaviour, with strange number of chunks not corresponding to the specified size.

After pulling my hair out trying to understand how it works, I've found out looking at the code that instead o using "chunk" for the chunk size it is actually MULTIPLYING both parameters:   n_frames=chunk*stride  (see lines 520 and 522 of trajectory.py file).

Being a large trajectory, I'd like to take one of every n-th frames of the trajectory and then handle the calculations of those selected frames one by one to take it easy on computer resources (hence, I want to use "chunk = 1" or at least a small number). And right now it is impossible to do so, chunk is always a large number because stride is, which is the opposite of what you would normally need when you are using iterload.

I cannot imagine for what reason could this be the intended behaviour, but it seems strange that it was an accident. Do you have an explanation for that or could maybe fix it?

Thanks!

**Comment by rmcgibbo** [comment]
Great. All fixed now. Thanks for the contribution.
