### ISSUE TITLE
Possible signature modification to mdtraj.geometry.hbond.baker_hubbard()

### ISSUE THREAD

**Issue by mcs95** [mdtraj/mdtraj#1553]
Hi,
 
In the context of the baker_hubbard hydrogen bond function, I was wondering whether you could implement the suggestion on  [this line of the code](https://github.com/mdtraj/mdtraj/blob/10a0b08f53d4a7c3be48ebe301b5a91222c78e1a/mdtraj/geometry/hbond.py#L221) to expose the distance_cutoff and angle_cutoff criteria as function arguments.

Thank you in advance,
Maria Chiara

**Comment by rmcgibbo** [comment]
Yeah, that seems very reasonable. Are you interested in filing a pull request to add that?

**Comment by mcs95** [comment]
Great thank you! I will file a pull request in the next few days.

**Comment by mcs95** [comment]
I've made a PR [here](https://github.com/mdtraj/mdtraj/pull/1556)

**Comment by mcs95** [comment]
I've updated the PR to change angle_cutoff to degrees.

**Comment by rmcgibbo** [comment]
👍
