### ISSUE TITLE
How to set SHIFTX2 path?

### ISSUE THREAD

**Issue by bcallen95** [mdtraj/mdtraj#1555]
I'm unable to reach the mdtraj forum using the link provided on the website, so I thought I'd ask the question here: How do I ensure that SHIFTX2 is accessible on my path? I've got shiftx2 downloaded (following the instructions on the SHIFTX2 website) and have mdtraj working, but I get an error when I call mdtraj.chemical_shifts_shiftx2(trj, pH=5.0, temperature=298.0): 

OSError: External command not found. Looked for shiftx2.py in PATH. `chemical_shifts_shiftx2` requires the external program SHIFTX2, available at http://www.shiftx2.ca/

I appreciate your help.

**Comment by rmcgibbo** [comment]
PATH is an environment variable. If you use a shell like bash, you can set it with `export`, and then simply check on the command line that you can run `$ shiftx2.py`

**Comment by bcallen95** [comment]
This solves the issue. Now it's just a matter of getting shiftx2 to work correctly. Thanks for the help!

**Comment by rmcgibbo** [comment]
Np
