### ISSUE TITLE
Signature modification of baker_hubbard to consider heavy atom distances rather than D-H...A distances

### ISSUE THREAD

**Issue by mcs95** [mdtraj/mdtraj#1557]
I was wondering whether it would be possible to have an additional parameter to the function that allows the user to consider heavy atom distances rather than D-H...A distances. Considering heavy atom distances over D-H...A atom distances may be preferred when looking at hydrogen bonding in X-ray crystal structures, as the hydrogen positions are less reliable than heavy atom positions.

 I have an example of how I would implement the changes [here](https://github.com/mcs95/mdtraj/commit/2109f6d8778ae84b8b61c75de898fdb5c59835a7)

Thanks and best regards,

Maria Chiara

**Comment by rmcgibbo** [comment]
It seems like that might be something better done in a different function, since it does not correspond to what the Baker/Hubbard paper did.

**Comment by mcs95** [comment]
That makes sense. However in that case also the previous change that I made to the baker_hubbard function, where I added the angle_cutoff and the distance_cutoff in the signature of the function would also not represent the definitions of the paper.

I would suggest this:
Reverting the baker_hubbard function to:
def baker_hubbard(traj, freq=0.1, exclude_water=True, periodic=True, sidechain_only=False)

Creating a new "customizable_hbond" function which would look like this:
def customizable_hbond(traj, freq=0.1, exclude_water=True, periodic=True, sidechain_only=False
                  distance_cutoff=0.25, angle_cutoff=120, heavy_atom_distance=False)
