### ISSUE TITLE
Calculating tensor of inertia and principal moments of inertia (p1,p2,p1) using MDtraj

### ISSUE THREAD

**Issue by arjunwadhawan** [mdtraj/mdtraj#1559]
Hi 

I have a system which comprises a growing nucleus in a liquid to solid phase transformation   (nucleation in NPT ensamble) where I want to get the principal moments of inertia(which is obtained by a diagonalization of the tensor of inertia) to understand the shape of the nucleus. 
I use: `moment_of_inertia =  mdtraj.compute_inertia_tensor(partial_trajectory).`
Here `partial_trajectory` is the selected set of atoms in the box (which are the atoms belonging to the solid nucleus). I use `partial_trajectory = full_trajectory.atom_slice([index of solid atoms])`

In the end, `moment_of_inertia` for each frame that has 3 set of values 

My question is what are these 3 set of values and what are the units associated ?
Is this the p1,p2,p1 ?? How can I compare these p1,p2,p1 to comment on the type of structure 

If for example I calculate the center of mass (`mdtraj.compute_center_of_mass(partial_trajectory)`)  and then calculate the distance between center of mass and these set of 3 values then is that the principal moments of inertia (in Angstrom ?)

Here is an example 
![image](https://user-images.githubusercontent.com/21062948/83859347-10be8400-a71e-11ea-8d4c-36b90785fa06.png)

**Comment by mattwthompson** [comment]
MDTraj uses nanometer as the distance unit. I don't know what the units of this tensor are; if it's distance it's nanometers, and if it's derived from distance, it's nanometers plus other stuff
