### ISSUE TITLE
Issue with shrake_rupley SASA calculation

### ISSUE THREAD

**Issue by nope-sto** [mdtraj/mdtraj#1560]
Just ended up with an error using following code:
`close_water_definition_file = 'production_3.pdb'
close_water_definition_traj=mdt.load(close_water_definition_file)
solvent_accessible_area_definition=mdt.shrake_rupley(close_water_definition_traj)`

Error also occurs with .h5 trajectory filetype:
`Traceback (most recent call last):
  File "test_waters.py", line 18, in <module>
    solvent_accessible_area_definition=mdt.shrake_rupley(close_water_definition_traj, probe_radius=0.14, n_sphere_points=960, mode='atom')
  File "/home/pst/anaconda3/envs/sim/lib/python3.7/site-packages/mdtraj/geometry/sasa.py", line 184, in shrake_rupley
    atom_radii = [_ATOMIC_RADII[atom.element.symbol] for atom in traj.topology.atoms]
  File "/home/pst/anaconda3/envs/sim/lib/python3.7/site-packages/mdtraj/geometry/sasa.py", line 184, in <listcomp>
    atom_radii = [_ATOMIC_RADII[atom.element.symbol] for atom in traj.topology.atoms]
KeyError: 'VS'`

Shouldn't this be straight forward?

**Comment by rmcgibbo** [comment]
The error message suggests that you’ve got an atom whose element is named “VS”, which is it a recognized element.

**Comment by nope-sto** [comment]
I also thought about this, but there ist no "VS" in the whole file...

**Comment by nope-sto** [comment]
Problem seems be known - sugars are the problem for me to: 
[https://github.com/mdtraj/mdtraj/issues/1121](url)
For my case it was enough to remove sugar, but maybe for others this could get a problem (e.g. glykosylated proteins)
