### ISSUE TITLE
MdTraj installed successfully but no mdtraj module found

### ISSUE THREAD

**Issue by bb-ind** [mdtraj/mdtraj#1561]
Hi, everyone, I have installed mdtraj from GitHub source. It was showed that Successfully installed mdtraj but when I have run the 'pytest mdtraj -v' it was showing that "ERROR: file not found: mdtraj".
Please help me how to install mdtraj properly. I am new in this Python world. Thank you.

**Comment by rmcgibbo** [comment]
I'm sorry, but I don't have the bandwidth to assist with this kind of thing. I would consider asking for help from a friend, on stackoverflow, or one of the beginner-friendly chat servers like https://pythondiscord.com/.
