### ISSUE TITLE
Issue related to Nematic order parameter

### ISSUE THREAD

**Issue by sarthok1991** [mdtraj/mdtraj#1563]
Hi,

For an apolar molecule, the unit vector associated with the apolar molecule is calculated from the inertia tensor. It is then further used to calculate the nematic order parameter. In the source code, this procedure is written in python. However, for a polar molecule, the orientation vector (or the unit vector) associated with the polar molecule is given. Hence, for polar molecule, how one can calculate the nematic order parameter using the same source code written for an apolar molecule.  

Is there any to calculate the nematic order parameter for polar molecules when the unit vector is given.

**Comment by ctk3b** [comment]
There is no top level function implemented that allows this. However, you could easily stitch together lower level code to accomplish this.

The basic steps for computing the nematic order parameter are:
1) compute vectors describing the orientation of the molecules
2) compute the Q-tensor
3) compute the nematic order parameter

If you have the vectors that specify the directors of your molecules (step 1), you can use the remaining portions of the code to compute the order parameter:
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/order.py#L97-L102
