### ISSUE TITLE
Is there a way to combine two different pdb files, with different proteins, into one? 

### ISSUE THREAD

**Issue by asgharrazavi** [mdtraj/mdtraj#1564]
If I have loaded two different pdb files with different proteins in each file, how can I merge them?
 
    import mdtraj as md
    pdb1 = md.load('protein1.pdb')
    pdb2 = md.load('protein2.pdb')
    # is there a function like: pdb1_2 = md.merge(pdb1,pdb2) ?

Thanks,
Asghar

**Comment by mattwthompson** [comment]
PDBs tend to be landmines but [ParmEd](pmd.load_file('protein1.pdb')) is the first thing I'd try for this

```python3
import parmed as pmd


pdb1 = pmd.load_file('protein1.pdb')
pdb2 = pmd.load_file('protein2.pdb')

combined = pdb1 + pdb2
combined.save('combined.pdb')
```

**Comment by asgharrazavi** [comment]
This method also seems to be working that I modified from [here](https://github.com/mdtraj/mdtraj/issues/1539#issuecomment-601600933). 

   ```
import mdtraj as md
import numpy as np

p1 = md.load('protein1.pdb') 
p2 = md.load('protein2.pdb')

top1, xyz1, time1, ul1, ua1 = p1.top, p1.xyz, p1.time, p1.unitcell_lengths, p1.unitcell_angles
top2, xyz2, time2, ul2, ua2 = p2.top, p2.xyz, p2.time, p2.unitcell_lengths, p2.unitcell_angles

top1_2 = top1.join(top2)
xyz1_2 = np.concatenate((xyz1, xyz2), axis=1)

p1_2 = md.Trajectory(xyz=xyz1_2, topology=top1_2, time=time1, unitcell_lengths=ul1, unitcell_angles=ua1) 
p1_2.save('combined.pdb')
```
