### ISSUE TITLE
How to get atomic coordinates without PBC  

### ISSUE THREAD

**Issue by arjunwadhawan** [mdtraj/mdtraj#1565]
Hi, This can be a very naive question. 

I want to get the atomic coordinates that are not periodic boundary condition(PBC) shifted. 
If I have a trajectory (traj), then `traj.xyz` gives me the PBC shifted coordinates. Is there a fast way to get the coordinates that are not shifted ? (something like periodic =False for coordinates?)

**Comment by arjunwadhawan** [comment]
As an example, I show a box below which has some atoms (shown in green). Some set of atoms have moved across the PDC to the top. For this frame when I do `traj.xyz`, it returns me the coordinates of the top atoms. I want to get the coordinates without PBC 

![image](https://user-images.githubusercontent.com/21062948/87224222-d5018480-c383-11ea-9161-f04cb1312144.png)

**Comment by rmcgibbo** [comment]
http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules might be what you want
