### ISSUE TITLE
pytest not working

### ISSUE THREAD

**Issue by rcrehuet** [mdtraj/mdtraj#1568]
I have installed mdtraj with conda, using Anaconda3-2020.02. The import works, but the tests fail: `pytest mdtraj -v` gives:
```
=============================================== test session starts ================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /home/marcr/anaconda3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/marcr/.hypothesis/examples')
rootdir: /home/marcr
plugins: remotedata-0.3.2, doctestplus-0.5.0, hypothesis-5.5.4, astropy-header-0.1.2, openfiles-0.4.0, arraydiff-0.3
collected 0 items                                                                                                  

============================================== no tests ran in 0.01s ===============================================
ERROR: file not found: mdtraj

```

**Comment by ahy3nz** [comment]
From the mdtraj directory, try `python -m pytest` or just `pytest`

**Comment by rcrehuet** [comment]
Thanks.
There is no error now, but no tests are run:
```
(base) marcr@xoriguer:~/anaconda3/lib/python3.7/site-packages/mdtraj$ pytest
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/marcr/anaconda3/lib/python3.7/site-packages/mdtraj
plugins: remotedata-0.3.2, doctestplus-0.5.0, hypothesis-5.5.4, astropy-header-0.1.2, openfiles-0.4.0, arraydiff-0.3
collected 0 items                                                              

============================ no tests ran in 0.06s =============================
(base) marcr@xoriguer:~/anaconda3/lib/python3.7/site-packages/mdtraj$
```

**Comment by sroet** [comment]
The tests are not packaged with the conda install (the examples and docs are also not packaged). (If you `ls` that conda directory, you will see it corresponds to the [`mdtraj` subdirectory](https://github.com/mdtraj/mdtraj/tree/master/mdtraj) from this code, and not the [main code directory](https://github.com/mdtraj/mdtraj))

You can't circumvent this by installing with pip or getting the releases from pypi.rog as those also [don't include the tests](https://pypi.org/project/mdtraj/#files), they do include the examples. However, those are thrown away during the wheel building when running `pip install`. (the wheel building also prevents you from testing it with `pip install git+https://github.com/mdtraj/mdtraj.git`)

So what is left is to use git to download the complete repository ([or download the right release zip](https://github.com/mdtraj/mdtraj/releases)) with the tests and run `pytest` from that directory:
```
git clone https://github.com/mdtraj/mdtraj.git
cd mdtraj
# Have your conda environment active
py.test
```

**Comment by rcrehuet** [comment]
Makes sense. But then the documentation should be corrected. The documetation suggests that after installation (with conda or pip) one can test the installation with pyest.

**Comment by rmcgibbo** [comment]
> But then the documentation should be corrected.

Done.
