### ISSUE TITLE
atom_slice: residue index

### ISSUE THREAD

**Issue by gph82** [mdtraj/mdtraj#1577]
Hi, this is connected #1343. 

What do you think should be the behavior of `Residue.index` after atom_slice? It's initialized here:
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L1391

but not updated after atom_slice. This leads to a behavior like this:
```
jgeom = igeom.atom_slice(igeom.top.select('resid 0 2'))
jgeom.top.residue(1).index
# 2
```

which seems (IMO) like something to avoid (and also contradicts the doc)
```
    index : int
        The index of the Residue within its Topology
```
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L1377

I can work around it by simply monkey-patching the `index` attribute after every   `atom_slice` call, but it seems like something that could be implemented.

Would you be willing to accept a PR?

Thanks!

**Comment by rmcgibbo** [comment]
Yeah, sounds like a bug

**Comment by gph82** [comment]
So, before I start, there's two options:

Obvious quick-n-dirty ad-hoc bugfix directly in `atom_slice` here:
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L1747
```
        if self._topology is not None:
            topology = self._topology.subset(atom_indices)
            for ii, rr in enumerate(topology.residues):
                rr.index = ii
                # or also setattr(rr, "index",ii)
```

Or going deeper into `add_residue` (called by `_topology_from_subset` called by `self._topology.subset`)
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L626

in the "analogous" `add_atom` this re-indexing gets done automagically by calling `Atom(...,index=self._numAtoms)`. We could do something similar there. But that's more invasive and could break things.

**Comment by gph82** [comment]
sorry, I now see that option nr. is the way it's supposed to work anyway, so I guess I gotta think a bit more about this
