### ISSUE TITLE
Problem with save_gro

### ISSUE THREAD

**Issue by imitxelena003** [mdtraj/mdtraj#1582]
I'm using save_gro in order to save a gro file corresponding to a specified frame of a simple system, alanine dipeptide. The code line reads as

`traj[frame].save_gro(fn)`

Then, when I use Gromacs' command `pdb2gmx` I obtain the next error: "Atom H1 in residue ACE 1 was not found in rtp entry ACE". Therefore the gro generated by MDTRAJ is not well defined.

Any suggestion/help/comment will be appreciated,
thanks in advance.

**Comment by mattwthompson** [comment]
This is likely an issue with the other data GROMACS uses in `pdb2gmx`. `.gro` files are relatively simple and hard to mangle. It would help if you had a reference file that GROMACS reads well
