### ISSUE TITLE
traj.save writes internal atom ID and not the topology serial number

### ISSUE THREAD

**Issue by gitkol** [mdtraj/mdtraj#1583]
Hi, I am trying to write a simple script that reads a trajectory, restricts it to a subset of the frames and, finally, writes a PDB file that includes only a subset of the atoms.
```
import mdtraj as md
import sys
trj_name = sys.argv[1]
top_name = sys.argv[2]
select_frames = sys.argv[3]
frame_indx = [266,448,90,30,50,46,444,115,39,84,230,350,476,478,344,346,28,9,70,196,155,10,19,75,76,24,185]
traj = md.join(md.load_frame(trj_name, index=frame_i, top=top_name) for frame_i in frame_indx)
print(traj.top)
table, bonds = traj.top.to_dataframe()
print(table.head())

keep_atoms = traj.top.select("resid 39 to 74 and name CA")
print(keep_atoms)
traj.atom_slice(keep_atoms, inplace=True)
print (traj)
print(traj.top)
table, bonds = traj.top.to_dataframe()
print(table.head())

traj.save(select_frames)

```
Here is the screen output and the top of the saved PDB file.
```
<mdtraj.Topology with 13382 chains, 13655 residues, 44606 atoms, 31234 bonds>
   serial name element  resSeq resName  chainID segmentID
0       1    N       N       1     VAL        0          
1       2    H       H       1     VAL        0          
2       3   H2       H       1     VAL        0          
3       4   H3       H       1     VAL        0          
4       5   CA       C       1     VAL        0          
[ 644  659  673  688  704  723  742  764  780  799  811  833  843  860
  884  898  919  930  945  956  976  996 1011 1021 1031 1042 1059 1076
 1087 1109 1128 1139 1156 1178 1195 1214]
<mdtraj.Trajectory with 27 frames, 36 atoms, 36 residues, and unitcells>
<mdtraj.Topology with 1 chains, 36 residues, 36 atoms, 0 bonds>
   serial name element  resSeq resName  chainID segmentID
0     645   CA       C      40     GLU        0          
1     660   CA       C      41     THR        0          
2     674   CA       C      42     GLU        0          
3     689   CA       C      43     VAL        0          
4     705   CA       C      44     LEU        0          


REMARK   1 CREATED WITH MDTraj 1.9.3, 2020-10-13
CRYST1   72.954   84.873   72.598  90.00  90.00  90.00 P 1           1 
MODEL        0
ATOM      1  CA  GLU A  40      10.065  42.742  14.046  1.00  0.00          C   
ATOM      2  CA  THR A  41      13.494  44.117  15.196  1.00  0.00          C   
ATOM      3  CA  GLU A  42      14.974  47.559  14.577  1.00  0.00          C   
ATOM      4  CA  VAL A  43      18.241  47.314  12.479  1.00  0.00          C   
ATOM      5  CA  LEU A  44      21.103  49.728  11.344  1.00  0.00          C   
ATOM      6  CA  LEU A  45      21.715  49.412   7.660  1.00  0.00          C   
ATOM      7  CA  LYS A  46      25.216  50.215   6.203  1.00  0.00          C   

```
The problem is that in the PDB file the ATOM IDs are saved as the MDTraj internal ID+1 but I need the original ATOM IDs 645, 660, 674, etc. traj.save wrote the correct residue serial numbers, but not the atom serial numbers. Is there a workaround to fix this?

Thank you very much for your kind assistance,

   Istvan

**Comment by sroet** [comment]
When looking into this, it was quite easy to alter.
Now, I don't know if this would break the `pdb` standard, so I don't know if (and when) it will get merged.

Feel free to try it out and let me know if it does not work (as expected). 
Assuming you have `git` and `pip` available, you can install it by running:
`pip install git+https://github.com/sroet/mdtraj.git@edit_pdb_writing`

**Comment by gitkol** [comment]
Thanks a million! I have mdtraj currently installed via anaconda3. Can I still install your version with pip?

**Comment by sroet** [comment]
**Disclaimer** It has been years since I had to run python on a windows machine (which I assume you are running on), so this might be outdated.

It looks like you should be able to open up `anaconda prompt` and run that `pip` command (you might need to install `git` in your anaconda environment first)(A quick search popped up [this website](https://datatofish.com/how-to-install-python-package-in-anaconda/), where you can replace `cx_Oracle` with `git+https://github.com/sroet/mdtraj.git@edit_pdb_writing`.)

I will unfortunately not be able to help any further on the installation side on windows machines

If you are not running on windows: you can activate the right `conda` environment on command line and it should come with `pip`.
After that running the above `pip install` should work out of the box.

**Comment by gitkol** [comment]
Sorry, I didn't mean Windows, I am all Linux. :) Yes, I was able to install
it in my anaconda base environment and it works flawlessly. Normally, it
wouldn't matter what the ATOM IDs are but I am using this script to prepare
reference PDB files for PLUMED and, unfortunately, PLUMED has no abstract
selection options, the only way to reference an atom is through it's ATOM
ID.

Thanks again!

Best,

   Istvan
