### ISSUE TITLE
test for SSE2 to support non-intel architectures

### ISSUE THREAD

**Issue by drew-parsons** [mdtraj/mdtraj#1588]
Currently the mdtraj build tests if SSE3 and SSE4.1 are supported by the compiler.  If so, then ` -mssse3` is added to the build flags.

But the build assumes Intel architecture and always includes `-msse2 ` in the build flags.

This causes the mdtraj build to fail on non-Intel architectures, e.g. arm64.  Build logs for various architectures running Debian Linux can be found at https://buildd.debian.org/status/package.php?p=mdtraj
For example, the arm64 build fails with the error message
```
creating build/temp.linux-arm64-3.9/mdtraj/rmsd/src
aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imdtraj/rmsd/include -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.9 -c mdtraj/rmsd/_rmsd.c -o build/temp.linux-arm64-3.9/mdtraj/rmsd/_rmsd.o -fopenmp -msse2 -O3 -funroll-loops -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-msse2’
error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
```

It would be good for portability if support for SSE2 could be tested before adding `-msse2` to build flags,  just as SSE3 and SSE4.1 are tested (in `basesetup.py`).

**Comment by drew-parsons** [comment]
Looks like you've fixed or worked around this already in commit #b28df2c.

**Comment by rmcgibbo** [comment]
Is it possible for you to check if the current master branch works for debian/arm64 with your whole pipeline.

If so, we could do cut another release.

**Comment by mattwthompson** [comment]
It would be nice to incorporate these changes into the conda-forge feedstock, which can be built on ARM. I don't know much about their compiler defaults, though.

I have a Pi that I'd gladly offer up for testing, but it looks like Debian already has plenty of hardware access.

**Comment by drew-parsons** [comment]
I can't fully test master just yet. It requires `astunparse`, which is not packaged yet for debian.

**Comment by rmcgibbo** [comment]
It may be possible to run some basic tests with just skipping `astunparse` -- it's only used in one file.

**Comment by drew-parsons** [comment]
I'll give it a try.

**Comment by drew-parsons** [comment]
Master builds on arm64,
https://buildd.debian.org/status/package.php?p=mdtraj
https://buildd.debian.org/status/fetch.php?pkg=mdtraj&arch=arm64&ver=1.9.4%2Bgit20201015.068f29a-1&stamp=1603445213&raw=0

I had to revert commit a8b2b9c to keep astunparse from getting in the way,

**Comment by rmcgibbo** [comment]
This should be all fixed up in the new release, I think.
