### ISSUE TITLE
SSE4 build flags not applied

### ISSUE THREAD

**Issue by drew-parsons** [mdtraj/mdtraj#1589]
The mdtraj build tests if SSE4.1 is supported by the compiler.  If so, then `compiler_args_sse41` is set to `-msse4` in `basesetup.py`.

But that flag is not actually applied. In `setup.py`, `compiler_args_sse2` and `compiler_args_sse3` are added to `compiler_args`.  But `compiler_args_sse41` is not added.

Is this deliberate or is it an accidental omission?

**Comment by rmcgibbo** [comment]
Sounds accidental. Although if it builds on x64, that probably means we're not using sse4.1 anyways.

**Comment by drew-parsons** [comment]
Fair call. SSE3 is used to define REDUCTION_EPILOGUE, used in rmsd/src/theobald_rmsd.c. But the SSE4 symbol isn't being used.
