### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by kimlabSchatterjee** [mdtraj/mdtraj#1592]
I was trying to install through conda channel but I think i am not able to install it
(base) kimlab@kimlab-800V7A:~/Desktop$ conda create -n mdtraj
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/kimlab/miniconda3/envs/mdtraj

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mdtraj
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) kimlab@kimlab-800V7A:~/Desktop$ conda activate mdtraj
(mdtraj) kimlab@kimlab-800V7A:~/Desktop$ conda install -c conda-forge mdtraj
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /home/kimlab/miniconda3/envs/mdtraj

  added / updated specs:
    - mdtraj

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astor-0.8.1                |     pyh9f0ad1d_0          25 KB  conda-forge
    mdtraj-1.9.4               |   py38h7fc68a0_0         1.8 MB  conda-forge
    mock-4.0.2                 |   py38h32f6830_1          51 KB  conda-forge
    numexpr-2.7.1              |   py38hc5bc63f_3         198 KB  conda-forge
    pytables-3.6.1             |   py38hf9f05d5_3         1.5 MB  conda-forge
    snappy-1.1.8               |       he1b5a44_3          32 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  astor              conda-forge/noarch::astor-0.8.1-pyh9f0ad1d_0
  blosc              conda-forge/linux-64::blosc-1.20.1-he1b5a44_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_3
  c-ares             conda-forge/linux-64::c-ares-1.16.1-h516909a_3
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.6.20-hecda079_0
  certifi            conda-forge/linux-64::certifi-2020.6.20-py38h924ce5b_2
  hdf5               conda-forge/linux-64::hdf5-1.10.6-nompi_h1022a3e_1110
  krb5               conda-forge/linux-64::krb5-1.17.1-hfafb76e_3
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35-h769bd43_9
  libblas            conda-forge/linux-64::libblas-3.9.0-2_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-2_openblas
  libcurl            conda-forge/linux-64::libcurl-7.71.1-hcdd3856_8
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h5dbcf3e_17
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-he4bcb1c_17
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-he4bcb1c_17
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h5dbcf3e_17
  liblapack          conda-forge/linux-64::liblapack-3.9.0-2_openblas
  libnghttp2         conda-forge/linux-64::libnghttp2-1.41.0-h8cfc5f6_2
  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_h4812303_1
  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_5
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h2ae2ef3_17
  lzo                conda-forge/linux-64::lzo-2.10-h516909a_1000
  mdtraj             conda-forge/linux-64::mdtraj-1.9.4-py38h7fc68a0_0
  mock               conda-forge/linux-64::mock-4.0.2-py38h32f6830_1
  ncurses            conda-forge/linux-64::ncurses-6.2-he1b5a44_2
  numexpr            conda-forge/linux-64::numexpr-2.7.1-py38hc5bc63f_3
  numpy              conda-forge/linux-64::numpy-1.19.2-py38hf89b668_1
  openssl            conda-forge/linux-64::openssl-1.1.1h-h516909a_0
  pandas             conda-forge/linux-64::pandas-1.1.3-py38hddd6c8b_2
  pip                conda-forge/noarch::pip-20.2.4-py_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pytables           conda-forge/linux-64::pytables-3.6.1-py38hf9f05d5_3
  python             conda-forge/linux-64::python-3.8.6-h852b56e_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  scipy              conda-forge/linux-64::scipy-1.5.2-py38hd9480d8_2
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h924ce5b_2
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_3
  sqlite             conda-forge/linux-64::sqlite-3.33.0-h4cf870e_1
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_1
  wheel              conda-forge/noarch::wheel-0.35.1-pyh9f0ad1d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010

Proceed ([y]/n)? y

Downloading and Extracting Packages
mock-4.0.2           | 51 KB     | ##################################### | 100% 
mdtraj-1.9.4         | 1.8 MB    | ##################################### | 100% 
snappy-1.1.8         | 32 KB     | ##################################### | 100% 
pytables-3.6.1       | 1.5 MB    | ##################################### | 100% 
numexpr-2.7.1        | 198 KB    | ##################################### | 100% 
astor-0.8.1          | 25 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(mdtraj) kimlab@kimlab-800V7A:~/Desktop$ pytest mdtraj -v
============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python2
cachedir: .cache
rootdir: /home/kimlab/Desktop, inifile:

========================= no tests ran in 0.00 seconds =========================
ERROR: file not found: mdtraj

Please help

**Comment by rmcgibbo** [comment]
It looks like it installed correctly. Try `python -c 'import mdtraj'` in your conda-env. I think it's just pytest is not finding it.

**Comment by sroet** [comment]
So there are a couple issues here:

1) You don't install `pytest` in your environment so it is grabbing it from your default python (it runs python `2.7` instead of the expected python `3.8` from your environment).
2) The command is wrong and should have been `py.test --pyargs mdtraj -v` 
3) The tests are not actually packaged with the `pip` or `conda` versions so `pytest` will not run any tests anyway

What @rmcgibbo adviced (testing if the import works) is as much testing as possible with the current conda/pip packages
