### ISSUE TITLE
memory allocation when opening XTC trajectory on OSX Catalina

### ISSUE THREAD

**Issue by tubiana** [mdtraj/mdtraj#1594]
Dear all! 

I have a memory issue when I try to open a small trajectory on OSX Catalina. It worked well on Mojave, but since the update a few days ago I have this error message : 
```
t = md.load("example.xtc", top="example.pdb")
python(98821,0x11a008dc0) malloc: can't allocate region
:*** mach_vm_map(size=96180599144448, flags: 100) failed (error code=3)
python(98821,0x11a008dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thibault/miniconda3/envs/ttclust3.9/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 433, in load
    value = loader(filename, **kwargs)
  File "mdtraj/formats/xtc/xtc.pyx", line 168, in mdtraj.formats.xtc.load_xtc
  File "mdtraj/formats/xtc/xtc.pyx", line 175, in mdtraj.formats.xtc.load_xtc
  File "mdtraj/formats/xtc/xtc.pyx", line 339, in mdtraj.formats.xtc.XTCTrajectoryFile.read_as_traj
  File "mdtraj/formats/xtc/xtc.pyx", line 408, in mdtraj.formats.xtc.XTCTrajectoryFile.read
  File "mdtraj/formats/xtc/xtc.pyx", line 445, in mdtraj.formats.xtc.XTCTrajectoryFile._read
MemoryError: Unable to allocate 87.5 TiB for an array with shape (3509216256, 2284, 3) and data type float32
```

This is on a fresh conda environment installation (`conda create -n mdtraj -c conda-forge mdtraj`).
The trajectory is here: https://github.com/tubiana/TTClust/tree/master/examples (1000 frames actually and not 3509216256 )

Also, I tried on a CentOS 7 computer I have, it worked...
Do you have any clue on what this problem might be ?

Thank you for your support :-) 
Best regards,
Thibault Tubiana.

**Comment by mattwthompson** [comment]
First guess is that it's related to https://github.com/mdtraj/mdtraj/issues/1574 - what version of clang are you using?

**Comment by rmcgibbo** [comment]
I think we've seen this issue on our CI, but none of the developers have the right kind of machine to reproduce it, which is why there hasn't been any progress.

**Comment by tubiana** [comment]
Thank you for your fast reply and sorry for my late one, I didn't received any notification...

My clang version is 10.0.0.
I use MDTraj on another computer in the meantime :)

**Comment by gph82** [comment]
I  am experiencing the same exact issue on my CI, what did you do about yours?
Here's the output:
https://github.com/gph82/mdciao/runs/1381258119

**Comment by rmcgibbo** [comment]
> I think we've seen this issue on our CI, but none of the developers have the right kind of machine to reproduce it, which is why there hasn't been any progress.

This update still stands. I haven't looked at it, and I presume nobody else has either.

**Comment by rmcgibbo** [comment]
I rented a Mac mini by the hour from a cloud provider, and I can reproduce this issue.

**Comment by rmcgibbo** [comment]
This should be fixed on master!

**Comment by ziyoujiyi** [comment]
what is the 98821 meaning? very thanks for your reply!
