### ISSUE TITLE
mdtraj homepage died

### ISSUE THREAD

**Issue by lucl13** [mdtraj/mdtraj#1595]
Hi all,

I cannot open the homepage. It seems that mdtraj homepage died, isn't it?

Best

**Comment by mattwthompson** [comment]
There were some issues with paperwork that seem to have been resolved. It should be up within a day or so, if not, check on this issue https://github.com/mdtraj/mdtraj/issues/1593

**Comment by rmcgibbo** [comment]
The website should be back up now, containing the 1.9.4 release docs.
