### ISSUE TITLE
mdtraj.rmsd without alignment

### ISSUE THREAD

**Issue by tubiana** [mdtraj/mdtraj#1597]
Dear all,

After an investigation, I chose to change my issue.
I would like to align a trajectory first on a specific atom group, then calculate the RMSD on the full protein.
But I saw on another issue (https://github.com/mdtraj/mdtraj/issues/1479) that RMSD perform alignement first. Is it possible to remove deactivate  ?

Best regards,
Thibault Tubiana.

**Comment by rmcgibbo** [comment]
I don't think there's specifically a function for this. There is a `superpose` function, and then you could calculate the RMSD yourself using numpy.linalg.norm or something.
