### ISSUE TITLE
Compute center of mass for a given selection of atoms

### ISSUE THREAD

**Issue by prateekbansal97** [mdtraj/mdtraj#1598]
Hello,

I need to find the center of mass of only given selected atoms for every frame in a trajectory. The atoms are selected by the trajectory.topology.select() function. 

The current method I am using is to extract coordinates for those atoms and compute it manually, by taking a weighted average of the coordinates. Is there a better way to do this? 

Any help would be appreciated. Thanks in advance!

**Comment by toontun** [comment]
Hello, 

I don't know if it is a better way but you can do it with mdtraj.

**First, create your string selection:**
`string_selection = "resid 456 to 661 or resid 1118 to 1323"`

**Second, select your atoms in your trajectory:**
`atoms_of_interest = traj.top.select(string_selection)`

Here I selected all atoms in residues 456 to 661 and 1118 to 1323. 

**Then, compute centers of mass along your trajectory:**
`centers_of_mass =  mdtraj.compute_center_of_mass(traj.atom_slice(atoms_of_interest))`

**Comment by mattwthompson** [comment]
The above is the preferred way of doing an analysis of a portion of a trajectory. I'd only emphasize that `traj.atom_slice` _returns_ a new `mdtraj.Topology` object, which can be carried along and run whatever other analysis on. So, if one wanted to run analysis on that selection multiple times,

```python3
com_traj = traj.atom_slice(atoms_of_interest)
centers_of_mass = mdtraj.compute_center_of_mass(com_traj)
#  Some other analysis on `com_traj`
...
```

**Comment by prateekbansal97** [comment]
Hello,

Thank you for the solutions. I was able to successfully implement it using the traj.atom_slice() method.

**Comment by MauriceKarrenbrock** [comment]
Hello,

I think it would be nice to create a wrapper function that makes this process easier and less error prone.
If you like the idea I will do a pull request.

I was thinking about something as easy as

```
def compute_center_of_mass_with_selection(trajectory, selection_string='all'):

    atoms_of_interest = trajectory.topology.select(selection_string)

    return  compute_center_of_mass(trajectory.atom_slice(atoms_of_interest))
```

**Comment by rmcgibbo** [comment]
I think the most convenient thing would be to add a `selection` keyword argument to `compute_center_of_mass`

**Comment by MauriceKarrenbrock** [comment]
Here you are, let me know what you think about it
