### ISSUE TITLE
Compute pka along a trajectory

### ISSUE THREAD

**Issue by toontun** [mdtraj/mdtraj#1599]
Hello, 

Is there any way to compute the pka of each residue in each frame along a trajectory? 

In other words,  I want to use, for instance, propka3.1 on each frame. I know there is propkatraj but it uses MDAnalysis and I developed all my work with mdtraj... 

Thanks,
toontun

**Comment by rmcgibbo** [comment]
This feature does not exist in mdtraj. I think you could do it, but you'd need to code up the glue between mdtraj and propka yourself.
