### ISSUE TITLE
Selecting atom indices within a particular distance

### ISSUE THREAD

**Issue by mayankb3192** [mdtraj/mdtraj#1600]
Hello,
Is there a way to select atom indices within a particular distance of another atom? 
For example to select water molecules within 0.3 nm of protein for a trajectory t, could we use 

t.topology.select('water and within 0.3 of protein')
However this brings up issue of 'Cannot use literals as truth'
I have had issues with a distance based atom selection. Any help appreciated.

**Comment by sroet** [comment]
So there is an inherent issue with selection based on a distance from a `trajectory`; it is not well-defined.
Say; A trajectory with 2 frames and in frame `1` atoms `[1,2,3]` are within the cutoff, and in frame `2` atoms `[3,4]`. 

Would you then expect this to return "**any** atom that is within the cutoff at **any point** in the trajectory" so in this case `[1,2,3,4]` or "**any** atom that is within the cutoff for the **whole** trajectory" so in this case `[3]`.?

What would you like to achieve with this selection?

**Comment by mayankb3192** [comment]
Ideally I would like to update it every frame, but even if not can I at least select it for a particular frame? Like VMD gives two options for something like this - update every frame and second keep it constant from the first frame.

**Comment by sroet** [comment]
[mdtraj.compute_neighbors](https://mdtraj.org/1.9.4/api/generated/mdtraj.compute_neighbors.html#mdtraj.compute_neighbors) Should work for you then. 

Something like this should work (**DISCLAIMER:** I did not test or run this code)
```python
import mdtraj as md
t = md.load('trajectory.extension')
query = t.topology.select('protein')
haystack = t.topology.select('water')

#This should be a list of 1D np arrays that contain all the water atom indices that are within the cutoff per frame
waters_in_contact_per_frame = md.compute_neighbors(t, cutoff=0.3, query_indices=query, haystack_indices=haystack)
```

If you want to do more in-depth analysis of these contact, I would like you to point to another package called:
[`ContactMapExplorer`](https://github.com/dwhswenson/contact_map/) Which is still in development, but reaching maturity ;)

**Comment by mmfarrugia** [comment]
> So there is an inherent issue with selection based on a distance from a `trajectory`; it is not well-defined. Say; A trajectory with 2 frames and in frame `1` atoms `[1,2,3]` are within the cutoff, and in frame `2` atoms `[3,4]`.
> 
> Would you then expect this to return "**any** atom that is within the cutoff at **any point** in the trajectory" so in this case `[1,2,3,4]` or "**any** atom that is within the cutoff for the **whole** trajectory" so in this case `[3]`.?
> 
> What would you like to achieve with this selection?

This is from a long time ago, but would anyone know a way to do this but with the first behavior where any atoms (or residues, which would presumably just require byres) which come within a cutoff of a residue at any point in the trajectory are included?  

I can see that one way to do this is to use the solution proposed by @sroet and then consolidate the output programmatically, but I have a total of 16 microseconds of MD for which I would do this, so I would really rather not do this so inefficiently if there is another way. I have checked into mdtraj.compute_neighbors but haven't seen anything with quite this behavior, it looks like contact_map is the only one with this functionality.  

Ultimately, I am hoping to feed this as an mdtraj selection string for more intensive analysis (in pyemma) so doing it with mdtraj itself or mdtraj selection syntax would be great if possible, but not strictly necessary so I thought that I'd post here as a suggestion for future functionality if there is not currently another method.

Thank you!

**Comment by sroet** [comment]
> I can see that one way to do this is to use the solution proposed by @sroet and then consolidate the output programmatically, but I have a total of 16 microseconds of MD for which I would do this, so I would really rather not do this so inefficiently if there is another way. I have checked into mdtraj.compute_neighbors but haven't seen anything with quite this behavior, it looks like contact_map is the only one with this functionality.

The way we did (something similar) in [`ContactMapExplorer`](https://github.com/dwhswenson/contact_map/) (which is a mostly stalled project by now) was by running [these lines](https://github.com/dwhswenson/contact_map/blob/3ae38ea40ac6529309592bafa2925f7f93abe27b/contact_map/contact_map.py#L555-L614) on every frame. If you just want a list of atoms out of it you can probably rewrite the loop to:
(**DISCLAIMER** the following code has not been tested/run and assumes you can load the whole trajectory in memory)
```python
import mdtraj as md
query = set([1,2,3]) # atom numbers of the residues you want to query
cutoff = 0.45 #cutoff in nm
traj = md.load('traj_file.xtc')
n_frames = len(traj)
atoms = set([])
for frame_number in range(n_frames):
    neighborlist = md.compute_neighborlist(traj, cutoff, frame_number)
    for atom_idx in query:
        neighbor_atoms = set(neighborlist[atom_idx])
        neighbor_atoms -= query #ignore the query atoms, comment out if you want to include them in the output
        atoms += neighbor_atoms
print(atoms) 
``` 
The reason it uses `md.compute_neighborlist` is because it was significantly faster than the base `md.compute_neighbors` (If I remeber correctly it was 1 or 2 orders of magnitude faster)
