### ISSUE TITLE
create atoms from center of mass

### ISSUE THREAD

**Issue by toontun** [mdtraj/mdtraj#1606]
Hello, 

I want to know if it is possible to add an atom to trajectory?

For example, I computed the centre of mass of three domains along my trajectory. I want to add an atom at the coordinates of each centre of mass to use a function which needs indices of atoms to work.

How can I do that? 

Thanks

**Comment by sroet** [comment]
The quickest way I found is to make a new trajectory with just the COM and then use `trajectory.stack`
(**DIsclaimer** The following code is altered compared to what I run, and untested but should be pretty close to what you need)
```python
# Get your original trajectory
traj1 = md.load('test.traj')
# Get the 3 center of mass xyz and stack them as frames so you end up with shape=(n_frames, n_COM, 3)
xyz2 = np.array(...)

# Make a clean topology
top2 = md.Topology()
# Add a chain
chain = top2.add_chain()
# Add a residue
res = top2.add_residue('COM', chain)
# Make a list of 3 elements (picked 3 metals here but you are free to use whatever gives the nicest coloring/reperesentation for you
# Keep in mind that if you do something that depends on masses that you pick something sensible
elements = [md.element.get_by_symbol('Au'), md.element.get_by_symbol('Ag'),  md.element.get_by_symbol('Cu')]
# Make a list of atom names
names = ['COM1', 'COM2', 'COM3']
for i, name in enumerate(names):
    top2.add_atom(name=name, 
                  element=elements[i], 
                  residue=res, 
                  serial=i+2000) # Pick a reasonable offset here

# Make a new trajectory with these xyz
traj2 = md.Trajectory(xyz=xyz2, topology=top2)
#Align the times
traj2.time = traj1.time

# Stack the trajs
traj_with_com = traj1.stack(traj2)
```

**Comment by toontun** [comment]
Ok, thank you, it is a well-explained answer! I managed to create a new trajectory with different centers of mass as an atom.

However, `xyz2` need to be shaped like this: (n_frames, 3, 3) because `md.Trajectory()` only accept array with shape (Any, 3, 3).
