### ISSUE TITLE
Memory Error when loading in Trajectory data

### ISSUE THREAD

**Issue by sdtruong** [mdtraj/mdtraj#1607]
I'm having an issue with loading in .xtc files. Apparently, this has been an issue before (#1458), but I haven't been able to find a fix personally. This is what happens when I load in a test .xtc file.

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-11-bb73d522fc15> in <module>
----> 1 test = md.load(filepath+'recon-struct/'+'conf_0_recon.xtc', top=filepath+'recon-struct/'+'conf_0_recon.gro')

~/opt/anaconda3/envs/mdaenv/lib/python3.9/site-packages/mdtraj/core/trajectory.py in load(filename_or_filenames, discard_overlapping_frames, **kwargs)
    431         _assert_files_or_dirs_exist(filename_or_filenames)
    432 
--> 433     value = loader(filename, **kwargs)
    434     return value
    435 

mdtraj/formats/xtc/xtc.pyx in mdtraj.formats.xtc.load_xtc()

mdtraj/formats/xtc/xtc.pyx in mdtraj.formats.xtc.load_xtc()

mdtraj/formats/xtc/xtc.pyx in mdtraj.formats.xtc.XTCTrajectoryFile.read_as_traj()

mdtraj/formats/xtc/xtc.pyx in mdtraj.formats.xtc.XTCTrajectoryFile.read()

mdtraj/formats/xtc/xtc.pyx in mdtraj.formats.xtc.XTCTrajectoryFile._read()

MemoryError: Unable to allocate 121. TiB for an array with shape (1294612224, 8592, 3) and data type float32
```

Is there a workaround now?

**Comment by rmcgibbo** [comment]
I think I fixed this on the master branch. What version are you running? Are you on OSX? And can you try with the top of tree?

**Comment by sdtruong** [comment]
> I think I fixed this on the master branch. What version are you running? Are you on OSX? And can you try with the top of tree?

I think I'm running the latest version since I installed with `conda install -c conda-forge mdtraj`. And yes, I am running on OSX. Is this an issue? Could you explain what you mean by "top of tree"?

**Comment by rmcgibbo** [comment]
There is a fix for this issue, I believe, but it’s (so far) only here on github. We haven’t done a new “release” of the code to conda or pypi yet. So in order to get the fix, you need to install the source code from the “top” of the repository on github.

**Comment by rmcgibbo** [comment]
https://mdtraj.org/1.9.4/installation.html#compiling-from-source

**Comment by sdtruong** [comment]
> https://mdtraj.org/1.9.4/installation.html#compiling-from-source

I'm having a bit of issue with installing it via GitHub with the instructions on that page. I'm getting really verbose error, and this is at the end of all the warnings:

```
ERROR: Command errored out with exit status 1: /Users/sdtruong/opt/anaconda3/envs/mdaenv/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sdtruong/mdtraj/setup.py'"'"'; __file__='"'"'/Users/sdtruong/mdtraj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

This is after I do `pip install -e .` in the terminal.

**Comment by rmcgibbo** [comment]
I'm not sure what that is. Try maybe just running `python setup.py install` from that directory in the terminal, and if it doesn't work paste the entire output?

**Comment by sdtruong** [comment]
> I'm not sure what that is. Try maybe just running `python setup.py install` from that directory in the terminal, and if it doesn't work paste the entire output?

Sorry this kind of spiraled. When I do that, is there a way to move the module into a conda environment? I don't know which file(s) in my `mdtraj` folder to move to the conda environment where I'm doing analysis. Thanks!

**Comment by rmcgibbo** [comment]
I have no idea what that error is. Something with llvm-ar? Sorry.

**Comment by mattwthompson** [comment]
This is not a solution (if `python setup.py install` doesn't work, that blocks everything) but

> When I do that, is there a way to move the module into a conda environment? I don't know which file(s) in my mdtraj folder to move to the conda environment where I'm doing analysis.

If you run `pip install /path/to/pkg`/`python setup.py install`/etc. while a conda environment is activated, conda itself handles making sure the files are where they're supposed to be. Avoid manually moving files in and out of conda environments, and only use commands like above and `conda whatever` to manage environments.

**Comment by sdtruong** [comment]
> This is not a solution (if `python setup.py install` doesn't work, that blocks everything) but
> 
> > When I do that, is there a way to move the module into a conda environment? I don't know which file(s) in my mdtraj folder to move to the conda environment where I'm doing analysis.
> 
> If you run `pip install /path/to/pkg`/`python setup.py install`/etc. while a conda environment is activated, conda itself handles making sure the files are where they're supposed to be. Avoid manually moving files in and out of conda environments, and only use commands like above and `conda whatever` to manage environments.

I think this is getting very close to the solution. It seems that `pip install /path/to/pkg` does not work, but `python setup.py install` is getting there (though not quite yet). The outputs look a bit more promising, but I do end up getting an error by the end. It's very verbose, so here is the bottom of the output after I run `python setup.py install` while in the directory.

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/sdtruong/opt/anaconda3/envs/mdaenv/include -fPIC -O2 -isystem /Users/sdtruong/opt/anaconda3/envs/mdaenv/include -Imdtraj/rmsd/include -I/Users/sdtruong/opt/anaconda3/envs/mdaenv/lib/python3.9/site-packages/numpy/core/include -I/Users/sdtruong/opt/anaconda3/envs/mdaenv/include/python3.9 -c mdtraj/rmsd/src/theobald_rmsd.cpp -o build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/theobald_rmsd.o -msse2 -mssse3 -O3 -funroll-loops
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/sdtruong/opt/anaconda3/envs/mdaenv/include -fPIC -O2 -isystem /Users/sdtruong/opt/anaconda3/envs/mdaenv/include -Imdtraj/rmsd/include -I/Users/sdtruong/opt/anaconda3/envs/mdaenv/lib/python3.9/site-packages/numpy/core/include -I/Users/sdtruong/opt/anaconda3/envs/mdaenv/include/python3.9 -c mdtraj/rmsd/src/center.cpp -o build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/center.o -msse2 -mssse3 -O3 -funroll-loops
/Users/runner/miniforge3/conda-bld/python-split_1602715575872/_build_env/bin/llvm-ar rcs build/lib.macosx-10.9-x86_64-3.9/mdtraj/core/lib/libtheobald.a build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/theobald_rmsd.o build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/center.o
error: command '/Users/runner/miniforge3/conda-bld/python-split_1602715575872/_build_env/bin/llvm-ar' failed: No such file or directory
```

**Comment by mattwthompson** [comment]
`python -m pip install ...` is considered better practice these days, I think, although that probably won't make a difference.

In the past I've had to use this one-liner because I borked other configurations on my system: `CXX=clang++ CC=clang CFLAGS=-stdlib=libc++ pip install -e .` 

Perhaps the best thing to do would be update your operating system, as 10.9 is quite old now and may not play nicely with a brand new version of Clang.

**Comment by sdtruong** [comment]
> `python -m pip install ...` is considered better practice these days, I think, although that probably won't make a difference.
> 
> In the past I've had to use this one-liner because I borked other configurations on my system: `CXX=clang++ CC=clang CFLAGS=-stdlib=libc++ pip install -e .`
> 
> Perhaps the best thing to do would be update your operating system, as 10.9 is quite old now and may not play nicely with a brand new version of Clang.

Unfortunately, `python -m pip install ...` doesn't work either as you predicted.

I tried your one-liner, and it still throws an error.

```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/sdtruong/opt/anaconda3/envs/mdaenv/include -fPIC -O2 -isystem /Users/sdtruong/opt/anaconda3/envs/mdaenv/include -stdlib=libc++ -Imdtraj/rmsd/include -I/private/var/folders/hk/gdlp7dqn2tb4j1q4y7smpgm40000gn/T/pip-build-env-lb1ijebh/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/sdtruong/opt/anaconda3/envs/mdaenv/include/python3.9 -c mdtraj/rmsd/src/center.cpp -o build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/center.o -msse2 -mssse3 -O3 -funroll-loops
    /Users/runner/miniforge3/conda-bld/python-split_1602715575872/_build_env/bin/llvm-ar rcs build/lib.macosx-10.9-x86_64-3.9/mdtraj/core/lib/libtheobald.a build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/theobald_rmsd.o build/temp.macosx-10.9-x86_64-3.9/mdtraj/rmsd/src/center.o
    error: command '/Users/runner/miniforge3/conda-bld/python-split_1602715575872/_build_env/bin/llvm-ar' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sdtruong/opt/anaconda3/envs/mdaenv/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sdtruong/mdtraj/setup.py'"'"'; __file__='"'"'/Users/sdtruong/mdtraj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

I think it's strange my OSX says it's version 10.9 in the errors though. I actually just updated to Big Sur (11.0.1), so I don't know why it's not saying that instead. Any ideas?

**Comment by sroet** [comment]
Can you run the following (I found this the most reliable way of installing a git branch into a conda env):
(This assumes you have `git` installed)
```
conda create -n test python=3.9
conda activate test
conda install --only-deps mdtraj
python -m pip install git+https://github.com/mdtraj/mdtraj.git@master
```
This succesfully installed for me on ubuntu 20.04 (which should not be too different from OSX)

If this gives the same error, then it might that that package (`llvm-ar`) might not be usable for `python 3.9`. In that case I would open up a new shell (or run `conda deactivate`) and rerun the above code with `python=3.8` instead.

(I only recently saw a similar error when trying to install numpy `1.16.1` in python `3.9`)

**Comment by sdtruong** [comment]
> Can you run the following (I found this the most reliable way of installing a git branch into a conda env):
> (This assumes you have `git` installed)
> 
> ```
> conda create -n test python=3.9
> conda activate test
> conda install --only-deps mdtraj
> python -m pip install git+https://github.com/mdtraj/mdtraj.git@master
> ```
> 
> This succesfully installed for me on ubuntu 20.04 (which should not be too different from OSX)
> 
> If this gives the same error, then it might that that package (`llvm-ar`) might not be usable for `python 3.9`. In that case I would open up a new shell (or run `conda deactivate`) and rerun the above code with `python=3.8` instead.
> 
> (I only recently saw a similar error when trying to install numpy `1.16.1` in python `3.9`)

This works like a charm — thank you very much! It was an issue with `python 3.9`. As you suggested, I followed the above steps with `python=3.8`, and that was able to download the entire `mdtraj` module onto my Conda environment.

I'm very impressed with how you were able to spot this!
