### ISSUE TITLE
Request: New release?

### ISSUE THREAD

**Issue by dwhswenson** [mdtraj/mdtraj#1609]
Would it be possible to get a new release out on conda-forge in the near future? @jvreede is planning on using MDTraj in a tutorial for the annual [CECAM MolSim course](https://www.cecam.org/workshop-details/46) at the University of Amsterdam this January, and she ran into #1594 (fixed in #1601). Installing from source may be a considerable headache in a course with 100+ participants!

Thanks!

**Comment by dwhswenson** [comment]
Bumping this, and pinging @rmcgibbo and @mattwthompson in the hopes that it won't be too hard to cut a release.

The tutorial I mention above (which uses MDTraj, OpenMM, OpenPathSampling, NGLView, and more) will be in the afternoon of Mon 11 Jan (European time). We've set up a Binder for use if students can't install, but we'd like them to have the experience of installing the code simply to show them that installing with conda is easy, and they shouldn't be afraid of using these things in their own research!

**Comment by rmcgibbo** [comment]
Thanks for reminding me -- sorry, I should have done this earlier.

**Comment by rmcgibbo** [comment]
Good idea. Doing it now.

**Comment by rmcgibbo** [comment]
Conda-forge build: https://github.com/conda-forge/mdtraj-feedstock/pull/27

**Comment by rmcgibbo** [comment]
@dwhswenson: Is it important to you that `pip install mdtraj` pulls binary wheels from pypi, or are you only using conda?

**Comment by dwhswenson** [comment]
For the tutorial next week, only conda (we're also using OpenMM), so no rush on binary wheels. Of course they're always convenient!

**Comment by dwhswenson** [comment]
And thanks for getting this out!

**Comment by rmcgibbo** [comment]
It looks like some of the wheels are getting uploaded now https://anaconda.org/conda-forge/mdtraj/files?version=1.9.5 to the staging channel. Let me know if you'd like to test install from that channel, or I can just merge (in which case I think they move to the regular channel).

**Comment by dwhswenson** [comment]
No need for test installs -- I trust that nothing has broken in dihedral calculation or atom selection! (Or if it did, I'm not working on a platform where there's a problem.)

FWIW, I also don't need pypy, although I'm confused how there's suddenly a requirement satisfiability issue. OpenPathSampling is not (yet) noarch, requires MDTraj, and built a new version on conda-forge on Dec 24. (Actually, I just looked, and I guess we didn't build pypy on that -- perhaps we'd had problems with pypy and our ujson<2 req.)

**Comment by rmcgibbo** [comment]
Should be all merged and upload. Let me know if you have any problems.
