### ISSUE TITLE
can't visit "https://mdtraj.org/" Access Denied

### ISSUE THREAD

**Issue by tesla-cat** [mdtraj/mdtraj#1610]
![image](https://user-images.githubusercontent.com/28215638/103736501-5da76780-502b-11eb-96b3-c77be55369db.png)

**Comment by rmcgibbo** [comment]
I must have messed something up on AWS. I’ll look at this tomorrow

**Comment by jjlow** [comment]
I experienced the same issue yesterday and today.

**Comment by rmcgibbo** [comment]
Any better now?

**Comment by mattwthompson** [comment]
Not for me

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F7166B53931746F6</RequestId>
<HostId>wbuE3zAPLKA/rwlDXl/u/CTVAmNaBUKoOJXatdVU34xK+Jj0SFK6SVZyj5t6eiOubcmlbpb/yko=</HostId>
</Error>

**Comment by rmcgibbo** [comment]
Hm. It's working both from my phone and my desktop. Caching sucks. I'll try to keep tweaking.

**Comment by rmcgibbo** [comment]
Maybe now?

**Comment by mattwthompson** [comment]
Works for me now, but the main site redirects to 1.9.4 (https://mdtraj.org/1.9.4/index.html) and can't move to another version (either by the drop-down or editing the URL):
![image](https://user-images.githubusercontent.com/7935382/103798471-625e2280-500f-11eb-834d-43e1b5702d11.png)

Is this also caching or some other slow web rollout thing I don't understand?

**Comment by rmcgibbo** [comment]
The 1.9.4-only thing was preexisting. The whole infra for automatically posting new versions isn't working since the switch of the AWS account from Pandelab to me.

**Comment by jjlow** [comment]
It works for me now!  Thanks for the help!



John J. Low
Principal Computational Science Specialist
Computing, Environment and Life Sciences
Building 240, 2143
9700 South Cass Avenue
Argonne National Laboratory
Argonne, IL 60439.
630-252-0045
www.linkedin.com/pub/john-low/15/8b0/5aa/

________________________________
