### ISSUE TITLE
ustunparse and py38

### ISSUE THREAD

**Issue by gph82** [mdtraj/mdtraj#1613]
I'm not sure but I think the re-introduction of astunparse (https://github.com/mdtraj/mdtraj/commit/a8b2b9c57b7af876aaddcb54ac31ea8ab27a54c5) might be causing trouble. This is off a fresh py38 environment, with newest mdtraj 1.9.5. 

Probably related: https://github.com/simonpercivall/astunparse/issues/43#issuecomment-743255764
```
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mdtraj as md
In [2]: geom = md.load("3SN6.pdb.gz")
In [3]: geom.top.select("name O")

AttributeError                            Traceback (most recent call last)
<ipython-input-3-7de49f93a83f> in <module>
----> 1 geom.top.select("name O")

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/mdtraj/core/topology.py in select(self, selection_string)
   1054         """
   1055 
-> 1056         filter_func = parse_selection(selection_string).expr
   1057         indices = np.array([a.index for a in self.atoms if filter_func(a)])
   1058         return indices

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/mdtraj/core/selection.py in __call__(self, selection)
    397 
    398         func = ast.Expression(body=ast.Lambda(signature, astnode))
--> 399         source = astunparse.unparse(astnode)
    400 
    401         expr = eval(

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/astunparse/__init__.py in unparse(tree)
     11 def unparse(tree):
     12     v = cStringIO()
---> 13     Unparser(tree, file=v)
     14     return v.getvalue()
     15 

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/astunparse/unparser.py in __init__(self, tree, file)
     36         self.future_imports = []
     37         self._indent = 0
---> 38         self.dispatch(tree)
     39         print("", file=self.f)
     40         self.f.flush()

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/astunparse/unparser.py in dispatch(self, tree)
     64             return
     65         meth = getattr(self, "_"+tree.__class__.__name__)
---> 66         meth(tree)
     67 
     68 

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/astunparse/unparser.py in _Compare(self, t)
    694         for o, e in zip(t.ops, t.comparators):
    695             self.write(" " + self.cmpops[o.__class__.__name__] + " ")
--> 696             self.dispatch(e)
    697         self.write(")")
    698 

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/astunparse/unparser.py in dispatch(self, tree)
     64             return
     65         meth = getattr(self, "_"+tree.__class__.__name__)
---> 66         meth(tree)
     67 
     68 

~/miniconda3/envs/new_mdtraj/lib/python3.8/site-packages/astunparse/unparser.py in _Constant(self, t)
    549             self.write("...")
    550         else:
--> 551             if t.kind == "u":
    552                 self.write("u")
    553             self._write_constant(t.value)

AttributeError: 'Constant' object has no attribute 'kind'
```

**Comment by gph82** [comment]
py37 runs no prob

**Comment by tjlane** [comment]
I hit this today too, can confirm @gph82 it's related to changes in `ast` going from python 3.7 to 3.8. Basically `astunparse` hasn't kept pace... so this can be considered a bug in `astunparse` I guess.

I added a line here 

https://github.com/mdtraj/mdtraj/blob/3e007ad48469a9095f4249c0c4919a6edbbea75e/mdtraj/core/selection.py#L398

to print `ast.dump(astnode)`. Then running a simple test case:
```
traj.top.select('name == CA')
```
Gives:

python3.8
`Compare(left=Attribute(value=Name(id='atom', ctx=Load()), attr='name', ctx=Load()), ops=[Eq()], comparators=[Constant(value='CA')])`

python3.7
`Compare(left=Attribute(value=Name(id='atom', ctx=Load()), attr='name', ctx=Load()), ops=[Eq()], comparators=[Str(s='CA')])`

**Comment by sroet** [comment]
I just looked at the CI and on `master` it passes with `astunparse` `1.6.2` (instead of `1.6.3`). With `1.6.2` I can run the whole `mdtraj` test suite on both `python` `3.8` and `3.9`

**Comment by sroet** [comment]
This should be solved by #1621 for `pip` installs.
When https://github.com/conda-forge/mdtraj-feedstock/pull/30 is merged it should also be solved for `conda` installs.

**Comment by gph82** [comment]
Thanks, are you planning a bugfix release soon?

**Comment by rmcgibbo** [comment]
There should be a new build on conda-forge soon (incremented the build number, but not a "new release").

**Comment by sroet** [comment]
@gph82 I am not a maintainer of this code, just someone that got hit by the same error and somewhat proficient in setting build pins.

As conda-forge/mdtraj-feedstock#30 is now merged it should update the `conda` version once `conda-forge` is rebuild (I expect somewhere within the next 24 hours). As no code changed (just pinning some dependencies), it will not be a bugfix release, but just a new build number. `conda update mdtraj` should still pull in the new build and requirements (as soon as `conda-forge` is rebuild). 
For `pip install` you can manually downgrade astunparse by running `pip install astunparse==1.6.2`

**Comment by gph82** [comment]
Hi, thanks for the clarification. I simply pinned to 1.9.4 for my project. 

Just for clarification, outside conda, in particular here https://pypi.org/project/mdtraj/#files, will nothing change even if the code is different?

**Comment by rmcgibbo** [comment]
For installing via `pip`, can't you just `pip install mdtraj astunparse==1.6.2`, or pin astunparse in your project rather than pinning mdtraj.

I don't plan on doing another 1.9.5 release to pypi for this.

**Comment by gph82** [comment]
Thanks, that's the answer I was looking for, was a bit confused with "not releasing" but still putting new code on pypi (which you won't do, I get that now). 
Thanks for explaining :)

**Comment by rmcgibbo** [comment]
Cheers!
