### ISSUE TITLE
Wrong buffer dimensions in _geometry.whole_molecules

### ISSUE THREAD

**Issue by mquevill** [mdtraj/mdtraj#1614]
I was trying to use `make_molecules_whole()` when loading a .trr file, but kept getting the same error:
```
  File ".../mdtraj/core/trajectory.py", line 1932, in make_molecules_whole
    _geometry.whole_molecules(result.xyz, box, sorted_bonds)
  File "mdtraj/geometry/src/image_molecules.pxi", line 153, in mdtraj.geometry._geometry.whole_molecules
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```

I have tried a trajectory with only one molecule or only one frame, but get this same error every time.

Workflow I was using to get these errors:
```python
import mdtraj
traj = mdtraj.load_trr('bulk.trr',top='bulk.gro')
traj.make_molecules_whole()
```

This is installed with Conda via conda-forge.
```
mdtraj                    1.9.5            py38h4fbea22_0    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
```

**Comment by rmcgibbo** [comment]
Thanks for the clear bug report.

**Comment by mquevill** [comment]
I am able to run this function on a different .trr file that I have with no issue. I am not sure if it's something specific about the system I have or if it's a more generalized bug.

Here are the files that I was trying to use (remove the ".txt" suffix):
[bulk.gro.txt](https://github.com/mdtraj/mdtraj/files/5845416/bulk.gro.txt)
[bulk.trr.txt](https://github.com/mdtraj/mdtraj/files/5845417/bulk.trr.txt)

Please let me know if you need anything else to debug this.
