### ISSUE TITLE
how to understand the output of compute_distances

### ISSUE THREAD

**Issue by Byun-jinyoung** [mdtraj/mdtraj#1615]
[I'm trying to implement 'compute_distance'

Considering I had groupA and groupB, I implemented 'compute_distance' as below:
  ```
    group1 = top.select(f"resid {chain1_i} to {chain1_f}")

    group2 = top.select(f"({chain2_i} <= resid) and (resid <= {chain2_f})")

    pairs = np.array( [(i, j) for i in group1 for j in group2], dtype=np.int)
    atom_distances = md.compute_distances(traj, pairs)[0]
    print(f'atom_distance: {atom_distances.shape}, {atom_distances}')

```
The variable 'atom_distances' shape is ( # atoms of groupA  x  # atoms of groupB).
The fact what I wondering is that the order on distance values in 'atom_distances'.
How can I understand the order of comput_distances?? It followed the order of pairs of atoms?

**Comment by sroet** [comment]
The output order of `compute_distances` is the same as the order of `pairs` that you give as the input (for every frame in the trajectory). 

For this example code that would be `group1`-rows by `group2`-columns (as your list-comprehension loops over the whole of `group2` for each index of `group1`)
