### ISSUE TITLE
mdtraj installation error: PackagesNotFoundError

### ISSUE THREAD

**Issue by mathialakan** [mdtraj/mdtraj#1616]
I am trying to install mdtraj using conda-forge channel, but it seems the package is not available.

conda install -c conda-forge mdtraj 
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mdtraj

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-ppc64le
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/omnia/linux-ppc64le
  - https://conda.anaconda.org/omnia/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Any guides please?

**Comment by mattwthompson** [comment]
It's not built for PowerPC on `conda-forge` at the moment, and I don't think building from source will work due to the SSE code (see https://github.com/mdtraj/mdtraj/issues/1432#issuecomment-643827985) and some other issues linked there)

**Comment by rmcgibbo** [comment]
@mattwthompson: That CPU architecture is not supported.

**Comment by mathialakan** [comment]
Thanks @mattwthompson and @rmcgibbo, I was trying to install it on the summit which is based on IBM Power 9 system. Any possible ways to use mdtraj on the summit?

**Comment by rmcgibbo** [comment]
@mathialakan: Not that I'm aware of.

---------------------

I'm generally aware that there's some demand to support ppc64le, but there are not a lot of free developer cycles and as far as I am aware, there's no good way to test ppc64le code using free cloud continuous integration services like Azure Devops or Github Actions.

I'd be happy to merge ppc64le support into mdtraj if you or someone were to write the code, but I'd require it to come with runnable tests. Without ppc64le in the CI matrix, I'm worried that the maintenance and bitrot would be too much of a burden.

(Note: I did merge aarch64 support without having aarch64 cloud runners, but the situation is a bit different. With aarch64 you can get a machine on AWS for $0.03/hour super easily, and lots of people are going to have aarch64 laptops (Apple) pretty soon).

**Comment by frank-stonybrook** [comment]
@mattwthompson I was able to compile mdtraj on summit by manually comment out those modules which requires the unsupported compiler flags. Of course, you will not be able to use functions in the geometry module.

**Comment by peastman** [comment]
> there's no good way to test ppc64le code using free cloud continuous integration services like Azure Devops or Github Actions.

Travis supports testing on PPC.  We've been using it for OpenMM, but with travis abandoning open source, we're moving to testing it under emulation on Github Actions.  It's slow but it works.

**Comment by rmcgibbo** [comment]
That seems like a possible solution.

If someone were to file a PR with pcc64le tests and ppc64le emulation for testing, I'd be happy to merge it.
