### ISSUE TITLE
enable enforcePeriodicBox option to store unwrapped coordinates

### ISSUE THREAD

**Issue by franklhy** [mdtraj/mdtraj#1620]
Currently, `mdtraj.reporters.HDF5Reporter` only saves wrapped coordinates but discards image information, which could be important for the analysis of long term diffusion. Is it possible to enable the enforcePeriodicBox option to store unwrapped coordinates? (Similar to the enforcePeriodicBox option provided by the [PDBReporter](http://docs.openmm.org/development/api-python/generated/simtk.openmm.app.pdbreporter.PDBReporter.html) from openmm.)

I have a working modified version to include this option. Should I start a PR to include this feature?

**Comment by rmcgibbo** [comment]
Sure, I'd be happy to merge that.

I would be careful with the numerics for your analysis here. If everything is stored unwrapped in single precision floating point, it's very easy to lose precision that might be important. For NVT, you might have better results storing the "number of unwrappings" as an integer and the the position within the box in float32, if you're looking over long timescales.

**Comment by franklhy** [comment]
Thank you for the suggestions.

> For NVT, you might have better results storing the "number of unwrappings" as an integer and the position within the box in float32, if you're looking over long timescales.

This would be the ideal way of dealing with coordinates of long simulations, just like "dump x y z ix iy iz" in LAMMPS. I would love to see such a feature. However, my current modification is rather simple and does not calculate the integer "number of unwrappings".
