### ISSUE TITLE
energy at each frame of a trajectory

### ISSUE THREAD

**Issue by tesla-cat** [mdtraj/mdtraj#1623]
- **step 1**: I have two files `traj.nc` and `topo.psf`, I want to find out the potential and kinetic energy at each frame of this trajectory, and plot them against time, how to do this? (this should be a quite common function but i couldn't find it in the doc)

- **step 2**: suppose I can get a `energy vs time plot` from the above, I want to be able to change a single amino acid in the large protein simulated and repeat step 1 to study the mutation effect on the energy plot. I want to use **the same `traj` file** (because that is all I have, I am provided with the simulation result files by other people), in order to study the effect of mutation on the `energy vs time plot`. Would this be possible?

**Comment by rmcgibbo** [comment]
This is not possible with MDTraj.
