### ISSUE TITLE
vector between DNA and Protein 

### ISSUE THREAD

**Issue by mohamedmarzouk2020** [mdtraj/mdtraj#1624]
I want to calculate the vector between the COM of Protein and DNA ( actually I can get it by Vector function of Amber). 
However, The values I got too strange. 
I used this as a script,
top =('./../pacsMDrestrain/restart5/try25/wow.1TSRB_ZAFF2.prmtop')
traj_dir = './../pacsMDrestrain/restart5/try25/try25traj4msm/'
traj = md.load(traj_dir +'cyc2cd3.xtc', top=top)
dna = traj.atom_slice(traj.topology.select("resid 210 211 212 213 220 223 224 225 226 231 232 233 234 235 236 237"))
protein = traj.atom_slice(traj.topology.select("resid 27 28 29 72 73 74 75 76 148 149 151 155 156 157 158 181 185 188 189 191 192 193 196"))
traj_dir = './../pacsMDrestrain/restart5/try29/try29traj4msm/'
n_cycle = 122
count=0
vCOM=[]
interCOM=[]
for i in range(120, n_cycle+1):
        for j in range(1, 11):
            traj_name = str(traj_dir) + "cyc"+str(i)+"cd"+str(j)+".xtc"
            if (not os.path.exists(traj_name)):
                continue  
            count=count+1
            traj = md.load(traj_name,top=top)
            **d=md.compute_center_of_mass(protein)-md.compute_center_of_mass(dna)**
            vCOM.append(d)
for y in range(len(vCOM)):
        for i in range(len(vCOM[y])):
            #print(y,i)
            a=math.sqrt((vCOM[y][i][0])**2+(vCOM[y][i][1])**2+(vCOM[y][i][2])**2)
            interCOM.append(a) 

then the result which should be around 8 A or 20 and reach to 40 can't see in the output of MDtraj function (md.compute_COM), it gave results around 1 from first to last cycle 
<img width="437" alt="Screen Shot 0003-02-09 at 1 14 52" src="https://user-images.githubusercontent.com/54627410/107255864-1a9e4100-6a7c-11eb-87fc-72391c2df74f.png">

**Comment by rmcgibbo** [comment]
Unfortunately there's not much we can do to help you with this. Probably your input is wrong or you're misunderstanding some step in your analysis. It doesn't look like an mdtraj bug or issue.
