### ISSUE TITLE
Strange RMSD result when input is sliced trajectory

### ISSUE THREAD

**Issue by proteins247** [mdtraj/mdtraj#1626]
I loaded a trajectory (xtc file and PDB topo). I then sliced it down to CA only

    traj_ca = traj.atom_slice(traj.topology.select("name CA"))

Now I do

    for i in range(len(traj_ca)):
        a1 = mdtraj.rmsd(traj_ca, traj_ca, i)
        a2 = mdtraj.rmsd(traj_ca[:], traj_ca, i)

You expect the ith entry of a1 and a2 to be 0 since you're comparing the same structures at that index. But for certain choices of i, I get nonzero results at `a2[i]`. Values that are around 10^-3 or so.

Also, I did

    rmsds = np.zeros([len(traj_ca), len(traj_ca)])
    rmsds2 = np.zeros([len(traj_ca), len(traj_ca)])
    for i in range(len(traj_ca)):
        rmsds[i] = mdtraj.rmsd(traj_ca, traj_ca, i)
        rmsds2[i] = mdtraj.rmsd(traj_ca[:], traj_ca, i)
    np.isclose(rmsds[~np.eye(len(traj_ca), dtype=np.bool)], rmsds2[~np.eye(len(traj_ca), dtype=np.bool)])

I do get a few off-diagonal values that are different, but here the values are only slightly off, so mainly, the diagonal entries are the ones that are strange.

I am running `mdtraj 1.9.5` cloned off github and installed some time in the past few months.

**Comment by rmcgibbo** [comment]
This is probably just expected floating point noise.

**Comment by proteins247** [comment]
Minimal example:

    wget 'https://files.rcsb.org/download/1G03.pdb'
    # go to python
    import mdtraj
    mol = mdtraj.load("1G03.pdb")
    rmsds = np.zeros([len(mol), len(mol)])
    rmsds2 = np.zeros([len(mol), len(mol)])
    for i in range(len(mol)):
        rmsds[i] = mdtraj.rmsd(mol, mol, i)
        rmsds2[i] = mdtraj.rmsd(mol[:], mol, i)

Are off diagonal entries the same? `np.isclose(rmsds[~np.eye(len(mol), dtype=np.bool)], rmsds2[~np.eye(len(mol), dtype=np.bool)])`. Yes it appears so.

But what are the diagonal entries?

    rmsds2[np.eye(20, dtype=np.bool)]
    # result:
    array([0.        , 0.        , 0.        , 0.        , 0.        ,
           0.        , 0.        , 0.        , 0.        , 0.00068504,
           0.00068504, 0.        , 0.        , 0.00068504, 0.        ,
           0.        , 0.        , 0.00068504, 0.        , 0.        ])    

This may not affect users, but it is strange that `mdtraj.rmsd(mol, mol, i)` and `mdtraj.rmsd(mol[:], mol, i)` give different results.

**Comment by rmcgibbo** [comment]
I believe this is why: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/src/theobald_rmsd_sse.h#L256-L261

When we can detect that coordinates of the structures are pointers to the same region of memory, then the two are necessarily the same and the calculation is skipped and returns zero. When the two structures contain identical data but are not in the same region of memory, then the calculation is done and returns a number close to zero, but not exactly zero because of floating point noise.
