### ISSUE TITLE
Importing the module itself throws a ValueError

### ISSUE THREAD

**Issue by sodiumnitrate** [mdtraj/mdtraj#1628]
I just installed mdtraj using pip, and tried to import the module. It does locate the module and attempts to load it, but it throws a value error:

`Python 3.8.5 (default, Jul 21 2020, 10:48:26)`
`[Clang 11.0.3 (clang-1103.0.32.62)] on darwin`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import mdtraj as md`
`Traceback (most recent call last):`
 ` File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python3.8/site-packages/mdtraj/__init__.py", line 30, in <module>`
`    from .formats.registry import FormatRegistry`
`  File "/usr/local/lib/python3.8/site-packages/mdtraj/formats/__init__.py", line 4, in <module>`
`    from .dcd import DCDTrajectoryFile`
`  File "mdtraj/formats/dcd/dcd.pyx", line 1, in init mdtraj.formats.dcd`
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

**Comment by mattwthompson** [comment]
What version of NumPy?

**Comment by sodiumnitrate** [comment]
1.16.6

**Comment by sodiumnitrate** [comment]
Updating to 1.20 solved the issue. Thanks!
