### ISSUE TITLE
DocDeploy failing on master

### ISSUE THREAD

**Issue by sroet** [mdtraj/mdtraj#1630]
The CI is trying to access [http://www.mdtraj.org/versions.json](http://www.mdtraj.org/versions.json) to figure out which versions already exist for your documentation. However that file either does not exist or can't be accessed as it gives back 
```python
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
or (if you go to that link)
![Screenshot from 2021-03-14 17-34-47](https://user-images.githubusercontent.com/19587267/111076195-9ceeaa80-84eb-11eb-8c28-b2a6782526cb.png)

@rmcgibbo @mpharrigan @marscher @mattwthompson does any of you have access to the hosting server to allow/upload that file?(pinging you as you are the recipe-maintainers on the conda-forge/mdtraj-feedstock)

**Comment by rmcgibbo** [comment]
I redid all of the CI infra and doc deployment.  Should be fixed now.
