### ISSUE TITLE
Docs and function name for 'relative_shape_anisotropy' seem incorrect

### ISSUE THREAD

**Issue by nec4** [mdtraj/mdtraj#1632]
Hello. Loving the tools - Why is `mdtraj.relative_shape_antisotropy` not called `mdtraj.relative_shape_anisotropy`? I think the latter is the more accepted term (I don't know what 'antisotropy' is). This may be a spelling error. In addition, the documentation for the function return seems to be incorrect, suggesting that the function returns the acylindricity, not the relative shape anisotropy.

**Comment by rmcgibbo** [comment]
cc @KirillShmilovich, who contributed the code.

It looks like a typo to me. If you were able to contribute a fix (leaving the old name as an alias so that it doesn't break anyone's code), I think that would be much appreciated.

**Comment by rmcgibbo** [comment]
@nec4: Could you review #1634?
