### ISSUE TITLE
Possible MDtraj reading issue for a 1 atom molecule mol2 files

### ISSUE THREAD

**Issue by bc118** [mdtraj/mdtraj#1636]
Hello.

It appears MDtraj may be the source of this issue, which is why I am submitting it here.  When I generate a mol2 via VMD the mdtraj reader, used in conjunction with other packages appears to not accept the VMD mol2 file for 1 atom molecules.  An example of the VMD generated format and the accepted format.  If there is no bonds specification, or an empty space after the bond specification it fail.  Please see the examples below.  

Thanks for your time.

_**This is the mol2 file generated by VMD:**_
@MOLECULE
TMP
1 0 1 0 0
SMALL
NO_CHARGES

Energy = 0

@<TRIPOS>ATOM
1 _CH4 0.0000 0.0000 0.0000 C 1 _CH4 0.000000

@<TRIPOS>SUBSTRUCTURE
1 **** 1 TEMP 0 **** **** 0 ROOT

#generated by VMD

**_This is the edited version to produce a UA methane that is currently accepted:_**
@MOLECULE
MET
1 0 1 0 0
SMALL
NO_CHARGES

Energy = 0

@<TRIPOS>ATOM
1 _CH4 0.0000 0.0000 0.0000 C 1 _CH4 0.000000
@<TRIPOS>BOND
@<TRIPOS>SUBSTRUCTURE
1 **** 1 TEMP 0 **** **** 0 ROOT

#generated by VMD and modifed

**Comment by mattwthompson** [comment]
Do you know which MOL2 spec VMD uses? There are a few (something SYBYL, TRIPOS, and some number of others). I get confused all the time

**Comment by bc118** [comment]
TRIPOS is listed in the file that VMD generates, so I assume that is it.  I have attached the VMD generated file as well (as .txt so it will upload).  Note, the atom name needs to be modifed to do the UA methane.... "_CH4" as above

For more experienced users it is likely not a big issue for mbuild, but I am more concerned with new users and enabling uniform systems using mol2 files, which are also computationally friendly. 

[UA_methane.txt](https://github.com/mdtraj/mdtraj/files/6267224/UA_methane.txt)

**Comment by rmcgibbo** [comment]
This is probably the relevant code: https://github.com/mdtraj/mdtraj/blob/c0d3c985a61698d5a97c7772c373aa0a1a0300ee/mdtraj/formats/mol2.py#L170-L227

Based on the docstrings and the fact that this file has seen minimal updates in the last 7 years, I'm not particularly surprised. I'd be happy to accept any PRs that improve this code and enlarge the test suite.

**Comment by rmcgibbo** [comment]
For clarification: do VMD-produced mol2 files that contain systems with more than 1 atoms get loaded correctly? Is the issue specific to system with only 1 atom?

**Comment by bc118** [comment]
Yes.  Molecules with more than 1 atom load correctly if they are a bonded system, at least if they are built from VMD.  I never tested a fixed atom system without bonds (i.e., a crystal or similar.  )
