### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1642]
It's been a few months since the last release (1/4/21) and there's been something of a flurry of activity recently. This includes some important changes (a few bugfixes, one packaging fix, and a couple larger changes )that have been merged or may be finished soon

 #1612 #1633 and a few others (see https://github.com/mdtraj/mdtraj/compare/1.9.5...master)

Would it be appropriate to make a new release in the next week or so? If so, I can do/help with it.

There's one active open PR  (#1641) - any other patches people need in a release soon?

**Comment by rmcgibbo** [comment]
Yes, I agree. It would be good to make a new release after #1641 is merged (which will probably be in the next few minutes, once the CI finishes).

If you'd like to help, a very useful thing would be to file a PR that sets isReleased=True and "What's new" section with text for the release notes? Once that is merged we can do the release from the merge commit, and use the same text in the github form where release notes are show in the github UI.

**Comment by rmcgibbo** [comment]
Done
