### ISSUE TITLE
An inconsistency occurred as a result of the Rmsd analysis performed using the XTC file with MDtraj. 

### ISSUE THREAD

**Issue by Bio-Otto** [mdtraj/mdtraj#1644]
I am trying to analyze my XTC trajectory file which is produced with gromacs. I used the following script for rmsd analysis. But it gives abnormal shifts in the graph. What can be the reason for this?

``` python
    def get_rmsd_data(self, top, traj, stride=1, selection='backbone', name, superpose=False, chunksize=1000,
                      output=False, pbc=True):

        rmsds = []

        try:

            topology = md.load_topology(top)
            selection = topology.select(selection)

            first_frame = md.load_frame(traj, 0, top=topology)

            if pbc:
                first_frame.image_molecules(inplace=True)

            for chunk in md.iterload(traj, top=topology, chunk=chunksize, stride=stride):
                if pbc:
                    chunk.image_molecules(inplace=True)

                if not pbc and superpose:
                    print("SUPERPOSING..")
                    chunk.superpose(reference=first_frame, atom_indices=selection, parallel=True)
                rmsd = md.rmsd(chunk, first_frame, atom_indices=selection) * 10.0  # nm->A
                rmsds.append(rmsd)

            rmsds = np.concatenate(rmsds)

            time_to = len(rmsds)

            if output:
                with open('rmsd.dat', 'w') as f:
                    f.write('\n'.join(map(str, rmsds)))

            return {'RMSD': rmsds}

        except Exception as Err:
            print("problem in rmsd calculation: ", Err)
```

RESULT:
![image](https://user-images.githubusercontent.com/57147948/116007151-fc75c500-a616-11eb-8254-4cdacef3b1d8.png)

**Comment by sroet** [comment]
Looking at your code, and assuming you run it with `pbc=True` and are asking for the rmsd of multiple molecules (so `backbone` selects more than 1 `chain`). 

Then it might be due to the fact that not all of your molecules are imaged to the copy of the box that is the closest to your reference frame. See issue #1625 for a similar effect

If your selection only contains 1

**Comment by Bio-Otto** [comment]
The topology file contains only 1 chain. I think the problem did not occur due to the problem stated by you. Because the same problem occurs when I enter "chainid 0" for selection.
