### ISSUE TITLE
Using nematic order parameter where number of indices = 2 per molecule

### ISSUE THREAD

**Issue by ans94** [mdtraj/mdtraj#1645]
Dear all,

I wish to calculate the nematic order parameter for a molecule that contains two atoms. As such I am using compute_nematic_order. Please see below for my code. This is the first time I am using Python:

```
#Calculate S2 based on CP-SO vector (tail 1) 100-200ns
import mdtraj as md
from mdtraj.testing import get_fn
t = md.load('traj_CP1-SO_100-200ns.xtc', top='traj_CP1-SO_100.pdb')
chain_indices = [[n+x for x in range(2)] for n in range(0, 4000, 2)]
S2 = md.compute_nematic_order(t, indices=chain_indices)

import matplotlib.pyplot as plt
plt.plot(S2)

import pandas as pd
pd.set_option("display.max_rows", None, "display.max_columns", None)

dataframe = pd.DataFrame(S2)
print(dataframe)
```

When I run this code, a message appears:
```
C:\Users\Areeb\anaconda3\lib\site-packages\mdtraj\geometry\order.py:160: ComplexWarning: Casting complex values to real discards the imaginary part
  all_directors[:, i, :] = director
```

The code still runs and produces an answer that I expect, but I am worried I have made an error that affects my results. This message does not appear when I have used this code for 3-atom molecules and above, so I believe it is something to do with that.

I appreciate any insight provided. Let me know if anything is unclear.

**Comment by rmcgibbo** [comment]
Actually, I think since the moment of intertia tensor is always symmetric, this should be changed to eigh: https://github.com/mdtraj/mdtraj/blame/master/mdtraj/geometry/order.py#L304...

**Comment by ans94** [comment]
Ok thanks for the responses provided in such quick time. From what you have mentioned about degeneracy, does that mean compute_nematic_order should NOT be used for molecules less than 3 atoms?
