### ISSUE TITLE
Partially initialized module 'mdtraj' has no attribute 'load'

### ISSUE THREAD

**Issue by AGGA32** [mdtraj/mdtraj#1651]
Hello,

I have received this kind of error during the loading of trajectory. Attached below is the error:

![image](https://user-images.githubusercontent.com/69192258/120059391-ddd67400-c083-11eb-95b5-4828d2c061c5.png)

I created a new Conda environment and installed the latest version of `mdtraj`. I hope someone could help me. Thank you.

**Comment by sroet** [comment]
This seems to happen because of the way python resolves the name `mdtraj` in `import mdtraj as md`. 

The current setup tries to import your custom `mdtraj.py` instead of the installed `mdtraj`. 

The quickest solution is to rename your `mdtraj.py` script to something different.

**Comment by rmcgibbo** [comment]
That sounds like the right diagnosis. Good insight, Sander.
