### ISSUE TITLE
unable to import compute_distance_t

### ISSUE THREAD

**Issue by VietNguyen120195** [mdtraj/mdtraj#1652]
Recently, I am trying to compute the distances between pairs of atom_indices between two frames but I cant do it. How can I get it?

**Comment by rmcgibbo** [comment]
I'm sorry, but I don't understand your question. There's a function described in the documentation called [mdtraj.compute_distances](https://www.mdtraj.org/1.9.5/api/generated/mdtraj.compute_distances.html?highlight=compute_distances#mdtraj.compute_distances). Can you be more specific or concrete?

**Comment by VietNguyen120195** [comment]
Sorry for the confusion. What I am looking for is the function mdtraj.compute_distance_t which is necessary for function mdtraj.compute_rdf_t (van hove correlation function). However, I couldn't import those function. How can I import those functions?.

Thanks,

**Comment by rmcgibbo** [comment]
It's likely that you're using a version of mdtraj that was created before that function was added.

**Comment by VietNguyen120195** [comment]
I upgraded to latest version 1.9.5 but still couldn't import those functions. What is the version of these new implemented functions or how could I implement those functions on Pycharm IDE.

**Comment by rmcgibbo** [comment]
https://github.com/mdtraj/mdtraj/pull/1633 It looks like these will first appear in the next release (1.9.6). You'll need to install from the top-of-tree development version or wait for the new release.

**Comment by rmatsum836** [comment]
V 1.9.6 has been released so you should be able to install the new version from anaconda cloud or pypi, which includes the functions for calculation of van hove.
