### ISSUE TITLE
Unknown format errors should not be `IOError`/`OSError`

### ISSUE THREAD

**Issue by salotz-sitx** [mdtraj/mdtraj#1653]
For example in https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L255

If you have an unknown file extension then an `OSError` is raised (apparently `IOError` is now and alias for `OSError` and this is how it appears when it happens in an interpreter [PEP 3151](https://www.python.org/dev/peps/pep-3151/#confusing-set-of-os-related-exceptions)).

The library not knowing how to handle a particular string is not a problem with the OS, this error should be reserved for things like the file being unreadable or non-existent. There is no way to distinguish in a `try` statement between the two and there should be.

I propose a custom error type like `UnknownFormatError`.

**Comment by rmcgibbo** [comment]
I have no strong opinion. That seems fine.

**Comment by mattwthompson** [comment]
It's arguably personal preference, but I'm generally in favor of more custom exceptions.

Subclassing from `OSError` would likely prevent breaking existing code but is also maybe not so proper given that it's not really a subset of what `OSError` is meant to cover. It's probably fine either way.
