### ISSUE TITLE
Community Chat/Forum

### ISSUE THREAD

**Issue by salotz-sitx** [mdtraj/mdtraj#1654]
Looks like the discourse link in the README is broken/expired.

I suggest using gitter.im which is a zero-management way to communicate beyond the issue tracker (and can even act as triage).

(I tried to create the community just now and then the repo owner can approve the integration, but somethings not working ATM on their end.)

**Comment by salotz-sitx** [comment]
I need the repo owner to make the gitter room. The UI seems to be working now.

**Comment by rmcgibbo** [comment]
If you give me instructions, I can do it.

**Comment by salotz-sitx** [comment]
Go to [gitter](https://gitter.im/), connect your github account. Then press the '+' add a community for 'mdtraj'. I think it makes a default room for a community.

**Comment by rmcgibbo** [comment]
Okay: https://gitter.im/mdtraj/community
