### ISSUE TITLE
getting a average of some PDB structure from trajectory

### ISSUE THREAD

**Issue by AhmetGG** [mdtraj/mdtraj#1666]
Hi, I would like to average PDB structure from some frames in trajectory. But I couldn't do this using trajectory.superimpose. How can I do get average pdb structure of the certain frames?

**Comment by rmcgibbo** [comment]
There's no built-in solution for this in `mdtraj`.

There are many different ways of averaging. To simply average the Cartesian coordinates, you could do `trajectory.xyz.mean(axis=0)`, delegating the operation to `numpy`.

However, by reference to your comment about trajectory.superpose, I suspect you see the problem with this. If the system is rotating freely, this is going to give you a garbage answer. Perhaps what you really want is `min_{X_c} sum_{X} ( ||X-X_c||_M)` for some other distance metric, `||.||_M`, but you'll need to pick the distance metric. This is a somewhat tricky and possibly system-dependent problem; mdtraj does not have a turnkey solution.

**Comment by AhmetGG** [comment]
Thank you so much for informative reply. I am new user of simulation so I didnt recognize this issue you mentioned.I am trying to average all the pdb structures which get from one trajectroy. I wrote code for getting the avarege of structures but I am not sure whether it is correct. If not so what do I need to add?

#get the average coordinates:
import glob
import numpy
pdbfiles = glob.glob("trajectoryx.pdb")
a_files=open("trajectoryx.pdb")
lines =a_files.readlines()

D1 = {}
for pdbfile in pdbfiles:
    for atom in open(pdbfile):
        for line in lines:
            atid = line.split()[1]
            if pdbfiles.index(pdbfile) == 0:
                D1[atid] = {"x": [], "y": [], "z": []}
            x = float(line.split()[-6])
            y = float(line.split()[-5])
            z = float(line.split()[-4])
            D1[atid]["x"].append(x)
            D1[atid]["y"].append(y)
            D1[atid]["z"].append(z)
D2 = {}
for atid in D1:
    D2[atid] = {}
    D2[atid]["x"] = numpy.average(D1[atid]["x"])
    D2[atid]["y"] = numpy.average(D1[atid]["y"])
    D2[atid]["z"] = numpy.average(D1[atid]["z"])

**Comment by AhmetGG** [comment]
By the way, can I do the thing I want to do via clustering with md.rmsd?
