### ISSUE TITLE
Added atom selection for SASA

### ISSUE THREAD

**Issue by gph82** [mdtraj/mdtraj#1670]
Hi,

I've implemented an atom selection option for mdtraj.geometry.sasa here:
https://github.com/mdtraj/mdtraj/compare/master...gph82:sasa?expand=1

It allows to include/exclude some atoms from the SASA computation. They excluded atoms are still considered as potential surface accessibility blockers, it's just their own SASA doesn't get computed. This is particularly helpful for membrane-embedded proteins where you want the lipids "there" but you don't really care about their SASA.

Some thoughts:

- As for logic & naming conventions, I went with `atom_indices` because it's more consistent with the rest of mdtraj
- As for the uncomputed values, one could think of returning np.nans, s.t. the uncomputed values don't get mistaken for actual zero SASA values elsewhere
- The c++ code/interface could be perhaps be improved (passing a boolean array instead of an integer mask or even the indices themselves), but I don't see any overhead because of the new if/then clause. Running:
```
import mdtraj as md
geom = md.load("tests/data/bpti.pdb")
for ii in range(6):
    geom = geom.join(geom)
geom
#<mdtraj.Trajectory with 64 frames, 892 atoms, 58 residues, without unitcells at 0x7f45c3d3faf0>
```
takes about the same time
old :  ` %timeit md.shrake_rupley(geom) 1.08 s ± 40.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
new : `%timeit md.shrake_rupley(geom) #1.08 s ± 32.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each`)
plus the addition that you can now exclude stuff
```
%timeit md.shrake_rupley(geom, atom_indices=geom.top.select("name CA"))
102 ms ± 2.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
So, what do you think? Been meaning to do this since years, but kept going back to gmx sasa, now we can do it here ;)

**Comment by rmcgibbo** [comment]
Sounds good to me.

**Comment by gph82** [comment]
ok, opening the PR then

**Comment by justinrporter** [comment]
I love this! This would also speed up our [exposons]() method as well.

> uncomputed values, one could think of returning `np.nans`

I think this is the right way, so that the sasa interface doesn't change. (The flip side is that the allocated output array won't get smaller as you exclude atoms from the calculation.)

**Comment by gph82** [comment]
Jep. I wrestled with the C code some months ago and kept using my local fork which had some shameless hacks. Soon-ish I'll have some time for this and get back with a decent PR.
