### ISSUE TITLE
Molecules center of mass 

### ISSUE THREAD

**Issue by gabriela-correa** [mdtraj/mdtraj#1689]
Is there a way to calculate the center of mass of molecules in a system using mdtraj? 
I am running simulations with OpenMM and, unfortunately, there is no function for calculating the center of mass of molecules. That's why I have to do it in post-processing. I figured mdtraj could help me.

**Comment by sroet** [comment]
easiest way I found by running (assuming a limited set of molecules) for each molecule
```python
import mdtraj as md
import numpy as np

traj = md.load("1vii_3frames.pdb")
com = md.compute_center_of_mass(traj, select="protein") # change the select= string here to your molecule
```
that will give you the `com` of the "protein" selection for every frame in `traj`

**Comment by gabriela-correa** [comment]
Thanks.
It is a good idea to use when performing umbrella sampling simulations in OpenMM. However, it is not good for plotting density profile.
