### ISSUE TITLE
Support from reading from File like objects

### ISSUE THREAD

**Issue by salotz-sitx** [mdtraj/mdtraj#1691]
For some cases it would be useful to load directly from a [file-like object](https://docs.python.org/3/glossary.html#term-file-object).

For instance if you are loading structures from a package tarball you get the data as bytes and no file so you have to make a temporary file to access it.

Another use case would be reading file strings from a database rather than a file system.

See this for example of how this normally works: https://docs.python.org/3/library/io.html

**Comment by rmcgibbo** [comment]
I don't think this is going to be very easy. Most of the trajectory format code (at least for the trajectories that I assume people care about) is in C or C++, often incorporated into MDTraj third party sources, and uses libc-level file manipulation code. e.g. https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/xtc/src/xdrfile.c.

**Comment by rmcgibbo** [comment]
If you actually wanted to do this in your systems, I'd recommend making a FUSE filesystem or unpacking your tarfile onto a ramdisk, or something that.

**Comment by salotz-sitx** [comment]
I wondered as much... I guess close this?
