### ISSUE TITLE
how to skip  "WARNING: two consecutive residues with same number (PRO, VAL)" when loading a gro file?

### ISSUE THREAD

**Issue by lucl13** [mdtraj/mdtraj#1693]
Dear all,

How I can skip the warning " WARNING: two consecutive residues with same number (XXX, XXX)" when loading a gro file? It is annoying. 

When I convert the gro file to pdb file and load it, it works fine. 

Best,
Chenlin

**Comment by therealchrisneale** [comment]
Not perfect, but perhaps the best available option:

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    traj = mdtraj.load('my.gro')
