### ISSUE TITLE
Remove use of `simtk` imports

### ISSUE THREAD

**Issue by dotsdl** [mdtraj/mdtraj#1695]
[OpenMM 7.6.0 removed the top-level `simtk` namespace](https://github.com/openmm/openmm/releases/tag/7.6.0). There is a shim in place for now, but use of `simtk` in imports is now deprecated.

**Comment by dotsdl** [comment]
I will take this on.

**Comment by dwhswenson** [comment]
I think I did this in #1668, no?

**Comment by mattwthompson** [comment]
Yep, should be in 1.9.7!

**Comment by dotsdl** [comment]
Ah, thanks folks. Apologies for the noise; I've been working on [`fah-xchem`](https://github.com/choderalab/fah-xchem) and we're seeing `No module named 'simtk.openmm.app.topology'` from our logs. I suspected `mdtraj` first and saw usages of `simtk` in current `master`, but failed to dig much deeper before raising this issue.

I think our problem is coming from [perses](https://github.com/choderalab/perses); apologies for barking up the wrong tree!
