### ISSUE TITLE
Upload wheels as part of release process

### ISSUE THREAD

**Issue by Seanny123** [mdtraj/mdtraj#1701]
As discussed in #1699, currently 1.9.6 has Python wheels whereas 1.9.7 only provides the source as `.tar.gz` which is then compiled.

Is the release process for `mdtraj` documented anywhere? Can I help contribute wheels for Linux?

**Comment by mattwthompson** [comment]
I would have probably used this if I remembered: https://github.com/mdtraj/mdtraj/tree/1.9.5/devtools#wheels

Remind me if I need to log in to a Linux box to make manylinux wheels, or can I do it directly from macOS?

**Comment by rmcgibbo** [comment]
It looks like that README file got deleted -when I cleaned up the CI stuff -- maybe it should be spruced up and moved somewhere else (wiki)?

**Comment by rmcgibbo** [comment]
Generally the preferred way to build wheels now, I think, is to get the manylinux docker image (https://github.com/pypa/manylinux), build the wheels inside the image, and then run `auditwheel`, which is installed inside the image.

**Comment by mattwthompson** [comment]
>  Are you familiar with using Docker images as build environments? If not, I'd be happy to give you a tutorial.

Yes, the missing bit in the chain of my technical familiarity here is that this is the only project I've built wheels for in the past 2 years (everything else being conda-based because of OpenMM) so I don't remember/am not familiar with the current best practices.

Agree it these docs should be revived somewhere as a release checklist. I don't have strong feelings where.

**Comment by Seanny123** [comment]
@rmcgibbo would you like help contributing to this wiki entry? This repo doesn't seem to have a wiki associated to it? Alternatively, a `how-to-release.md` file would also be sufficient?

**Comment by rmcgibbo** [comment]
Yes, I can contribute. A markdown file would be fine with me too.
