### ISSUE TITLE
Trajectory.save_pdb does not write bonds between standard residues in the CONECT section

### ISSUE THREAD

**Issue by atharva-kelkar** [mdtraj/mdtraj#1703]
When I try to use the `Trajectory.save_pdb` method, the pdb file does not capture all bonds in the CONECT section. Sample code shown below -

```
# traj is an MDTraj trajectory object
for bond in traj.topology.bonds: 
    print(bond[0].index, bond[1].index)
```
gives the following output:
```
0 1
1 2
2 3
4 5
2 4
```
However, when I save the PDB file, using traj.save_pdb(file_name), the PDB file contains only 2 unique bonds instead of 5. Reading through the `PDBTrajectoryFile` class, I spot the following piece of code:
```
# Identify bonds that should be listed as CONECT records.
standardResidues = ['ALA', 'ASN', 'CYS', 'GLU', 'HIS', 'LEU', 'MET', 'PRO', 'THR', 'TYR',
                    'ARG', 'ASP', 'GLN', 'GLY', 'ILE', 'LYS', 'PHE', 'SER', 'TRP', 'VAL',
                    'A', 'G', 'C', 'U', 'I', 'DA', 'DG', 'DC', 'DT', 'DI', 'HOH']
conectBonds = []
if self._last_topology is not None:
    for atom1, atom2 in self._last_topology.bonds:
        if atom1.residue.name not in standardResidues or atom2.residue.name not in standardResidues:
            conectBonds.append((atom1, atom2))
        elif atom1.name == 'SG' and atom2.name == 'SG' and atom1.residue.name == 'CYS' and atom2.residue.name == 'CYS':
            conectBonds.append((atom1, atom2))
```

Why is the writing of CONECT lines limited to non-standard residues and specific atoms in Cysteine? Can we extend the CONECT definition to include all bonds in the `Topology` object?

**Comment by rmcgibbo** [comment]
I think the general idea here is that in PDB files, a certain set of bonds is implied given the residue names and the 1D toplogy of bonds. For example, if you make something like ACE-ALA-NME in a normal tool and then save it to PDB, you expect to get something like this (made with VMD).

```
CRYST1    0.000    0.000    0.000  90.00  90.00  90.00 P 1           1
ATOM      1 HH31 ACE     1       2.000   1.000  -0.000  1.00  0.00           H  
ATOM      2  CH3 ACE     1       2.000   2.090   0.000  1.00  0.00           C  
ATOM      3 HH32 ACE     1       1.486   2.454   0.890  1.00  0.00           H  
ATOM      4 HH33 ACE     1       1.486   2.454  -0.890  1.00  0.00           H  
ATOM      5  C   ACE     1       3.427   2.641  -0.000  1.00  0.00           C  
ATOM      6  O   ACE     1       4.391   1.877  -0.000  1.00  0.00           O  
ATOM      7  N   ALA     2       3.555   3.970  -0.000  1.00  0.00           N  
ATOM      8  H   ALA     2       2.733   4.556  -0.000  1.00  0.00           H  
ATOM      9  CA  ALA     2       4.853   4.614  -0.000  1.00  0.00           C  
ATOM     10  HA  ALA     2       5.408   4.316   0.890  1.00  0.00           H  
ATOM     11  CB  ALA     2       5.661   4.221  -1.232  1.00  0.00           C  
ATOM     12  HB1 ALA     2       5.123   4.521  -2.131  1.00  0.00           H  
ATOM     13  HB2 ALA     2       6.630   4.719  -1.206  1.00  0.00           H  
ATOM     14  HB3 ALA     2       5.809   3.141  -1.241  1.00  0.00           H  
ATOM     15  C   ALA     2       4.713   6.129   0.000  1.00  0.00           C  
ATOM     16  O   ALA     2       3.601   6.653   0.000  1.00  0.00           O  
ATOM     17  N   NME     3       5.846   6.835   0.000  1.00  0.00           N  
ATOM     18  H   NME     3       6.737   6.359   0.000  1.00  0.00           H  
ATOM     19  CH3 NME     3       5.846   8.284   0.000  1.00  0.00           C  
ATOM     20 HH31 NME     3       4.819   8.648   0.000  1.00  0.00           H  
ATOM     21 HH32 NME     3       6.360   8.648   0.890  1.00  0.00           H  
ATOM     22 HH33 NME     3       6.360   8.648  -0.890  1.00  0.00           H  
```

With no CONNECT records, because all of the bonds are "standard".

It may be the case that there's a bug here with `load_pdb` not injecting the standard bonds, but this logic that you quoted in PDBTrajectoryFile for `connectBonds` seems reasonable to me.

**Comment by peastman** [comment]
Here's what the [PDB spec](http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT) says about it.

> CONECT records are present for:
>
> - Intra-residue connectivity within  non-standard (HET) residues (excluding water).
> - Inter-residue connectivity of HET  groups to standard groups (including water) or to other HET groups. 
> - Disulfide bridges specified in the  SSBOND records have corresponding records.

**Comment by atharva-kelkar** [comment]
Thanks Robert and Peter. This makes sense to me. My issue is that it 
(a) leads to a mismatch in PDB files that are loaded and then saved 
(b) also makes adding bonding information through the topology challenging 

I think the addition of an `add_all_bonds` option could be useful in the `save_pdb` method.

> It may be the case that there's a bug here with `load_pdb` not injecting the standard bonds into the trajectory/topology object when loading, but this logic that you quoted in PDBTrajectoryFile for `connectBonds` seems reasonable to me.

I think this bug exists and is more relevant for coarse-grained atoms with non-standard definitions.

**Comment by rmcgibbo** [comment]
I don't want to add a method for saving out PDB files that don't follow the PDB spec, but I would be amenable to fixing the mismatch between load_pdb and save_pdb by fixing the load_pdb side of the equation to inject the standard bonds into the topology object.

**Comment by atharva-kelkar** [comment]
Thanks, Robert. A quick check of loading the PDB file you generated in the comment above shows correct insertion of standard bonds in the loaded topology. Closing this issue here.

**Comment by rmcgibbo** [comment]
It seems like `https://github.com/mdtraj/mdtraj/issues/1518` suggests that there are sometimes inconsistencies between the save side and the load side, no?

**Comment by atharva-kelkar** [comment]
Yup you're right. I'm closing only this issue because `save_pdb` does not write bonds between standard residues for a reason (_i.e._, to follow standard PDB spec).

I am working on figuring out the issue pointed out in #1518.
