### ISSUE TITLE
when trajectory contains no unit cell information

### ISSUE THREAD

**Issue by catbert44** [mdtraj/mdtraj#1704]
Hello, I'd like to know how to set the unit cell lengths/angles for a trajectory that doesn't include dimensions of unit cell (e.g. a xyz-type trajectory)? I need to give this information to use PBC.  

I've tried the following:

t = md.load('traj.xyz', top='output.pdb')
t[0].unitcell_lengths = [1.85, 1.85, 1.85]

However, print(t[0].unitcell_lengths) still gives "None"

Thank you for your feedback in advance.

**Comment by mattwthompson** [comment]
IIRC XYZ files do not conventionally store box information. But you can just set them `t.unitcell_lengths = loaded_array` after loading/preparing the array from some other source.
