### ISSUE TITLE
XTCReporter Trajectories from killed runs can't be loaded?

### ISSUE THREAD

**Issue by apayne97** [mdtraj/mdtraj#1705]
More of a question than an issue, but I have some trajectories run in OpenMM that were killed due to timeout on a cluster, and when I try to load them, I get this error:

t = md.load_xtc(xtc_path, top=top)

```
OSError: Malformed XTC file. Number of atoms <= 0. Are you sure this is a valid GROMACS xtc file?
```

If I use the dcd reporter, I can load in dcd files that have been killed just fine.

I have other trajectories from XTC reporter that were not killed, and those also load in just fine.

Is there a way to resolve this? I would like to use these trajectories if possible.

Thanks.

**Comment by rmcgibbo** [comment]
It's probably possible, but unfortunately, I don't have the bandwidth to help. You'd have to read the XTC code closely to understand how the header is supposed to be arranged, and then maybe look at your files in a hex editor and edit them by hand to fix the header.

**Comment by apayne97** [comment]
Forgot to resolve this issue, I just wasn't actually saving a proper xtc file and had nothing to do with killed runs.
