### ISSUE TITLE
MDTraj.org loads docs for 1.9.5; 1.9.7 has been released

### ISSUE THREAD

**Issue by dwhswenson** [mdtraj/mdtraj#1707]
When I go to https://mdtraj.org/, I'm redirected to the docs labeled as the 1.9.5 version at https://www.mdtraj.org/1.9.5/index.html. I expect this to redirect to latest, which should be 1.9.7.

At https://www.mdtraj.org/1.9.5/index.html, there are no versions in the version dropdown, and https://www.mdtraj.org/1.9.7/index.html gives an Access Denied error.

**Comment by dwhswenson** [comment]
Looks like this may also be the problem behind #1702; didn't catch from titles in a quick glance at open issues.

**Comment by rmcgibbo** [comment]
Yes, it looks like the docs have been pushed only to "/development" for the last few months. I'll fix it.

**Comment by rmcgibbo** [comment]
Fixed
