### ISSUE TITLE
 ImportError: cannot import name 'compute_distances_t'

### ISSUE THREAD

**Issue by rexeor** [mdtraj/mdtraj#1709]
Hello dear users and developers,

I have installed mdtraj in python3.6 with pip. The installation has been successful... but when I have run the mdtraj tests I have got an error, it seems that the module '**compute_distances_t**' cannot be found. If anyone could help me I would be very grateful.

[mdtraj] $ py.test
================================================= ============= test session starts ================================= ==============================
platform linux - Python 3.6.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 - /usr/local/bin/python3.6
cachedir: .pytest_cache
rootdir: / home / mdtraj, configfile: pytest.ini, testpaths: tests, examples
plugins: anyio-3.4.0
collected 1197 items / 1 error / 1196 selected

================================================= =================== ERRORS ============================= ========================================
_____________________________________________________ ERROR collecting tests / test_distance.py _____________________________________________________
ImportError while importing test module '/home/mdtraj/tests/test_distance.py'.
Hint: make sure your test modules / packages have valid Python names.
Traceback:
/usr/local/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import (name [level:], package, level)
tests / test_distance.py: 30: in <module>
    from mdtraj.geometry.distance import compute_distances, compute_distances_t, compute_displacements, find_closest_contact
E ImportError: cannot import name 'compute_distances_t'
================================================= ============== warnings summary ================================= ===============================
examples / test_examples.py: 22
  /home/mdtraj/examples/test_examples.py:22: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo? You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    for fn in os.listdir (test_dir) if fn.endswith ('. ipynb')]

- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================= =========== short test summary info ================================== ===========================
ERROR tests / test_distance.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!
================================================= ========= 1 warning, 1 error in 1.19s ================================ ===========================

**Comment by sroet** [comment]
I cannot reproduce this on a clean `python 3.6` env.
```
conda create -n test python=3.6
conda activate test
pip install mdtraj
pip install pytest tables nbformat jupyter pandas gsd networkx matplotlib scikit-learn
cd mdtraj
py.test
```
outputs:
```
=============== 1043 passed, 110 skipped, 65 xfailed, 1462 warnings in 465.89s (0:07:45) ================
```

How did you install mdtraj? Do you mind running `python -c 'import mdtraj; print(mdtraj.version.version)'` (not from the github repo) and make sure that is `1.9.7` as expected? (that function is only present since mdtraj 1.9.7)

Also, if you are running in a virtual env/conda env are you sure pytest is installed in the right env? (your output shows it is using /usr/local/bin/python3.6)

**Comment by rexeor** [comment]
> 

Hello,

Thank you very much for your reply. I installed mdtraj with the following command "pip3.6 install mdtraj". When I have run the command python3.6 -c 'import mdtraj; print (mdtraj.version.version)' the output was "1.9.5". So I must download version 1.9.7 and install it from source. 

I am not using virtual env / conda, I am launching python3.6 directly from the bash shell... but I installed pytest in the same way as mdtraj with "pip3.6 install pytest". So the main problem if I want to use that function is that I don't have mdtraj version 1.9.7 installed. 

 Regards, many thanks!

**Comment by sroet** [comment]
> So I must download version 1.9.7 and install it from source.

That is one option. Another is that you try to run `pip3.6 install git+https://github.com/mdtraj/mdtraj.git@1.9.7` that should grab this github repository, checks out the tag `1.9.7` and installs [that version of the code](https://github.com/mdtraj/mdtraj/tree/1.9.7). ([Doc link for this command](https://pip.pypa.io/en/stable/topics/vcs-support/#git)). Hope that helps!

**Comment by rexeor** [comment]
> > So I must download version 1.9.7 and install it from source.
> 
> That is one option. Another is that you try to run `pip3.6 install git+https://github.com/mdtraj/mdtraj.git@1.9.7` that should grab this github repository, checks out the tag `1.9.7` and installs [that version of the code](https://github.com/mdtraj/mdtraj/tree/1.9.7). ([Doc link for this command](https://pip.pypa.io/en/stable/topics/vcs-support/#git)). Hope that helps!

It helped me a lot, thank you very much! After installing mdtraj version 1.9.7 and running "pytest" I got the following output:

=== 1037 passed, 115 skipped, 65 xfailed, 1400 warnings in 607.93s (0:10:07) ===
