### ISSUE TITLE
load_mol2 cannot handle files with comments before first @<TRIPOS>

### ISSUE THREAD

**Issue by roseane-reis** [mdtraj/mdtraj#1710]
When mol2 files had comments in the first lines, the load_mol2 function gave the error: 'function' object has no attribute 'key'
The error is in function def _parse_mol2_sections(x), mol2.py
It is easily fixable by handling the '#' when comments are present in the file.

**Comment by rmcgibbo** [comment]
Can you upload a file that reproduces the bug?
