### ISSUE TITLE
Inplace change input filenames

### ISSUE THREAD

**Issue by htian97** [mdtraj/mdtraj#1713]
`load` function drops the first element for given file list.

```python
filenames = ['1.dcd', '2.dcd', '3.dcd']
trajs = md.load(filenames, top=top)
print(filenames) 
#['2.dcd', '3.dcd']
```

I think maybe it comes from this line where the `filename_or_filenames ` variable is changed inplace. 
https://github.com/mdtraj/mdtraj/blob/51779e2c820df155782ec24f6d9e2701939cc539/mdtraj/core/trajectory.py#L420

**Comment by rmcgibbo** [comment]
I think there was a previous issue or PR someone filed on this very same thing. Looking.

**Comment by rmcgibbo** [comment]
https://github.com/mdtraj/mdtraj/pull/1706

**Comment by htian97** [comment]
@rmcgibbo Thanks for mentioning that:smiley: But still..., `filename_or_filenames = filename_or_filenames[1:]` will inplace change filename list that's similar to pop.

**Comment by rmcgibbo** [comment]
Can you install from the master branch and see if it fixes the behavior for you?

**Comment by htian97** [comment]
oops, I was still using the latest stable version. Yeah the master branch works fine. Thanks!
