### ISSUE TITLE
Support for PDB chainID

### ISSUE THREAD

**Issue by pgbarletta** [mdtraj/mdtraj#1714]
Hi, I implemented this minor feature that has came up before a few times (eg: #873). 
I understand from reading some issues that this is not high priority for maintainers, but it is for me and I believe it could be for many people, so I'd deeply appreciate if you let me make a PR to have this built into mdtraj.

The feature is already half-implemented and I did my best to minimize the modifications to the library:
1. `chain_id` is added to the Topology's `Chain` class. It's set by the constructor and it has a default value so the old way of constructing a chain still works.
2. New `Topology.add_chain()` also accepts a `chain_id` with a default value, so everything else works.
3. `PDBTrajectoryFile.read_model()` now calls `add_chain()` with the `chain_id` attribute from `PdbStructure.chain`, which already reads and stores the chainID from the PDB.
4. When writing PDBs `PDBTrajectoryFile.write()` now checks `chain.chainid` before setting `chainName` to A-Z according to `chainIndex`. If the `chainid` attribute from the chain object is set, then it will use that character.

**Comment by rmcgibbo** [comment]
Sounds reasonable. Looking forward to the PR.

**Comment by pgbarletta** [comment]
Thanks!
