### ISSUE TITLE
Custom loaders that already contain topologies fail _parse_topology() check

### ISSUE THREAD

**Issue by nffaruk** [mdtraj/mdtraj#1716]
In v1.9.3 trajectory.load() had an [if statement](https://github.com/mdtraj/mdtraj/blob/1.9.3/mdtraj/core/trajectory.py#L369) checking for the "top" kwarg before calling _parse_topology(). Now that if statement is gone in v1.9.7 and our custom loader set up using the formats.registry.FormatRegistry.register_loader() decorator doesn't work because _parse_topology() is called and it checks through hardcoded topology extensions before getting a chance to realize our trajectory contains a topology.

**Comment by rmcgibbo** [comment]
The probblem is that `_parse_topology` isn't actually looking into the FormatRegistry at all, right? Would you be able to make a patch?

**Comment by nffaruk** [comment]
I think h5 is one of the file types on the hardcoded list of trajectory files that include topologies, so it should pass the check, but there could be a bug for it as well.

I will try to make a patch.
