### ISSUE TITLE
load() removes first element from a list of filenames

### ISSUE THREAD

**Issue by CharlieLaughton** [mdtraj/mdtraj#1717]
I see:
>>> import mdtraj as mdt
>>> xtcfiles = ['test1.xtc', 'test2.xtc']
>>> print(xtcfiles)
['test1.xtc', 'test2.xtc']
>>> t = mdt.load(xtcfiles, top='complex.prmtop')
>>> print(t)
<mdtraj.Trajectory with 20 frames, 39755 atoms, 11977 residues, and unitcells>
>>> print(xtcfiles)
['test2.xtc']

I get the same result for other file formats - if you pass load() a list of trajectory filenames, it will remove the first item from the list.

**Comment by rmcgibbo** [comment]
I thought that was fixed. What version of mdtraj do you have? Is the fix in https://github.com/mdtraj/mdtraj/pull/1706 not working, or do you have a version that doesn't include that?

**Comment by CharlieLaughton** [comment]
I have 1.9.7, which seems to be the most recent in Pypi. I hadn't spotted the previous issue, I guess the fix just hasn't made it through yet.
