### ISSUE TITLE
Support for affinity propagation clustering?

### ISSUE THREAD

**Issue by tanoury1** [mdtraj/mdtraj#1720]
Hi,
Does MDTraj support the affinity propagation algorithm for clustering trajectories as described by Frey and Dueck?  

Thank you,
Jerry

**Comment by rmcgibbo** [comment]
MDtraj doesn't really directly have any clustering methods implemented, but should give you the ability to pull out the features you want as vectors and then use any other implementation of the clustering algorithm in python.
