### ISSUE TITLE
Perform analysis on a subset of particles

### ISSUE THREAD

**Issue by gyorgy-hantal** [mdtraj/mdtraj#1724]
Hello,

Perhaps this question has been asked already, but I couldn't find any hint on how to solve it, so I ask it here.

I need to choose a subset of atoms in every frame based on some criteria and perform some shape analysis on this subset of atoms. I understand that these functions take a whole trajectory object as argument, but in my case the set of particles change in every frame.

What I can do is to create a new trajectory object based on my selection in every frame and pass it to the given tool. I saw in an example how to create a new trajectory: 

`t_new = md.Trajectory(xyz=<numpy array of coordinates>, topology=None)`

now I can compute the geometrical center: `compute_center_of_geometry(t_new)`
But if I want to compute the gyration tensor I also need to pass a topology which contains the masses. How do I create a topology object?

Is there a better way of doing what I need?

Thanks a lot!
Gyorgy

**Comment by mattwthompson** [comment]
Trajectories have topologies dangling off of them and I bet they're kept in sync after slicing - `t_new.topology` is probably what you're after

**Comment by gyorgy-hantal** [comment]
Perhaps I miss something very basic here, but if I use the xyz attribute of the trajectory object (`t.xyz[iframe,iatom,:]`) to pick the coordinates of the required atoms then it only gives me a numpy array without the trajectory information. (so unfortunately `t_new.topology` doesn't work.)

Trajectory object I can only slice according to frames but not atoms.
Is there a way to generate a trajectory object containing information on one single atom (or a subset of them) in one single frame?
Or can I slice the topology object and pick topology information of only the necessary atoms?

Alternatively, can I create a topology object with the necessary masses and pass it to the new trajectory (just like I do it for the coordinates)?

**Comment by mattwthompson** [comment]
I think you might be looking for `Trajectory.atom_slice`?

**Comment by gyorgy-hantal** [comment]
atom_slice (or restrict_atoms) works perfectly, thanks for the suggestion!

However, I am not able to get the masses right. I am using gromacs, but I am not able to read a tpr topology file. And I don't see how I can set the atomic masses by hand. Atom types guessing (as I can see it in `topology.atom(i).element.name`) doesn't yield the right type, therefore the guessed masses are also wrong.

I can try to convert my topology file to a format that mdtraj reads and contains the masses, but is there a more direct way?

**Comment by sroet** [comment]
# Important things to keep in mind with atom_slice

**always** give an ordered list to `atom_slice`, otherwise you run into issues like #1664 .

Also, after `atom_slice` the atom indices are reset (so atom(13) becomes atom(1) after `atom_slice([12,13,14])`).



Now for your question
> I can try to convert my topology file to a format that mdtraj reads and contains the masses, but is there a more direct way?

This is the safest way, and I would advise you to use it. There is however a more "MDTraj"-focused way, where you can construct the topology yourself. 
(The following code is untested)
```
import mdtraj as md
from collections import Counter

# This needs to be an ordered list of all the elements of your atoms (same order as the xyz)
elements = ['H','O','H']
# Make an empty topology
top = md.Topology()
# Add a chain and residue
chain = top.add_chain()
res = top.add_residue('mol', chain)

# Make a counter to keep track of atomnumbers
atom_counter = Counter()

# Now fill the topology
for atom in elements:
    # Get the number of the atom in this file
    atom_number = atom_counter[atom]
    # Get the atom element
    element = md.element.get_by_symbol(atom)
    # Add everything to the topology
    top.add_atom(name=atom+str(atom_number), 
                 element=element, 
                 residue=res, 
                 serial=atom_number)
    # Update the atom counter
    atom_counter.update(atom)
trj = md.Trajectory(xyz=<xyz>, top=top)
```

This is adapted from the boiler-plate code I use for generating mdtraj topologies from xyz files (this is tested and working):
```
import mdtraj as md
from collections import Counter
#As xyz does not have a topology, we need to construct one.
filename = "ferrocene_0.xyz" # This needs to be a single frame
# Make an empty topology
top = md.Topology()
# Add a chain and residue
chain = top.add_chain()
res = top.add_residue('mol', chain)

# Make a counter to keep track of atomnumbers
atom_counter = Counter()

# Now fill the topology
with open(filename,'r') as f:
    # Read lines
    # Skip the first two lines
    _ = f.readline()
    _ = f.readline()
    for line in f.readlines():
        #split the line and take the atom
        atom = str(line.split()[0])
        # Get the number of the atom in this file
        atom_number = atom_counter[atom]
        # Get the atom element
        element = md.element.get_by_symbol(atom)
        # Add everything to the topology
        top.add_atom(name=atom+str(atom_number), 
                     element=element, 
                     residue=res, 
                     serial=atom_number)
        # Update the atom counter
        atom_counter.update(atom)
trj = md.load(filename, top=top)
```

**Comment by gyorgy-hantal** [comment]
Building the topology manually like that indeed solved my problem: I was able to tell for every atom what their type was and this way the right mass was attributed.
Thanks a lot!
