### ISSUE TITLE
RMSD between frames before and after translation/rotation is not 0

### ISSUE THREAD

**Issue by wehs7661** [mdtraj/mdtraj#1726]
Hi, 
Recently I found a case where `mdtraj.rmsd` seemed to fail. Specifically, I was trying to translate/rotate a trajectory with a random vector/random angle and I compared the trajectories frame to frame before and after the translational/rotational perturbations. Ideally, if the trajectories were aligned correctly before RMSD calculations and PBCs were considered correctly, the RMSD between the trajectories frames before and after the transformation should be 0. 

However, I found that not all the frames had 0 RMSD as compared to the same frame after perturbations. For the frames having a non-zero RMSD value, the RMSD tended to be very small (~1E-4) but not negligible. To better demonstrate this, I've set up an example in a jupyter notebook that can be found in the zipped folder attached here. I'm wondering if there is a potential issue in `mdtraj.rmsd` or if I actually missed something in my case. 

Thanks a lot!
[RMSD_test.zip](https://github.com/mdtraj/mdtraj/files/8251350/RMSD_test.zip)

**Comment by rmcgibbo** [comment]
This is the expected level of floating point precision. See eg https://github.com/mdtraj/mdtraj/issues/1626
