### ISSUE TITLE
Topology.select() syntax

### ISSUE THREAD

**Issue by mghattas100** [mdtraj/mdtraj#1737]
While analyzing some structures using mdtraj, I came across some small molecules/non-standard amino acid residues whose heavy atom often contains ' (prime) as part of the atom name.

For example, 
ADP molecule has those sets of coordinates:
HETATM 3455  O5' ADP A 453      42.294 -13.213  78.459  1.00 12.64           O
HETATM 3456  C5' ADP A 453      42.590 -14.108  77.392  1.00 13.53           C
HETATM 3457  C4' ADP A 453      41.448 -14.447  76.491  1.00 10.82           C
HETATM 3458  O4' ADP A 453      40.494 -14.957  77.301  1.00 15.71           O
HETATM 3459  C3' ADP A 453      40.682 -13.265  75.988  1.00 14.91           C
HETATM 3460  O3' ADP A 453      41.370 -12.856  74.849  1.00 12.12           O
HETATM 3461  C2' ADP A 453      39.320 -13.747  75.593  1.00 12.94           C
HETATM 3462  O2' ADP A 453      39.390 -14.592  74.453  1.00 19.09           O
HETATM 3463  C1' ADP A 453      39.150 -14.581  76.828  1.00 14.16           C

If I try running:
`structure.topology.select("name O3' and resid 452")`

it would give this error:

    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/Users/mghattas/miniconda3/envs/prot_state/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2779, in safe_execfile
        self.compile if shell_futures else None)
      File "/Users/mghattas/miniconda3/envs/prot_state/lib/python3.7/site-packages/IPython/utils/py3compat.py", line 168, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/Users/mghattas/git/SCPS/protonate.py", line 609, in <module>
        het_atm_h_check = motherstructure.h_topology.select('name {} and resid {}'.format(j, het_atm_residue_index))
      File "/Users/mghattas/miniconda3/envs/prot_state/lib/python3.7/site-packages/mdtraj/core/topology.py", line 1073, in select
        filter_func = parse_selection(selection_string).expr
      File "/Users/mghattas/miniconda3/envs/prot_state/lib/python3.7/site-packages/mdtraj/core/selection.py", line 378, in __call__
        raise ValueError('\n'.join(lines))
    ValueError: Expected end of text, found "'"  (at char 7), (line:1, col:8): name O3' and resid 452

How can I use prime when it's part of the atom name while using .select function? 
I tried those other commands with no success:

`structure.topology.select("resid 452 and name O3\'")
`
OR
```
atm_name = "O3'"
structure.topology.select("resid 452 and name {}".format(atm_name))
```

**Comment by rmcgibbo** [comment]
The code suggests you might be able to use a quoted string
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/selection.py#L329-L336

Maybe `resid foo and name "O3'"`.

**Comment by mghattas100** [comment]
Thank you!!
