### ISSUE TITLE
Unable to install mdtraj

### ISSUE THREAD

**Issue by yangyangdotcom** [mdtraj/mdtraj#1756]
I am new to mdtraj and wanted to install it. I followed https://mdtraj.org/1.9.3/installation.html to do the installation. I tried using conda, the CLI shows that the installation is successful but I can't import mdtraj to my python code. Anyone knows how to solve this problem? Much appreciated.

**Comment by Justin-J-Miller** [comment]
Hi yangyangdotcom! Could you provide a little more information about which of the installation instructions you used? If you used conda to install, could you verify that you've activated the conda environment that you installed mdtraj in?
