### ISSUE TITLE
MDtraj python library for Python 3.9.13

### ISSUE THREAD

**Issue by abdusemiabduweli** [mdtraj/mdtraj#1757]
我使用pip install mdtraj安装mdtraj时，遇到了不少麻烦。但经过挣扎，最后成功了。

https://github.com/abdusemiabduweli/mdtraj

上面链接中的两个文件夹是我安装完mdtraj后，从 ...\Python39\Lib\site-packages 拷过来的，希望对大家有用。

我的环境：

Python 3.9.13

windows 11 64位 22000.978

https://github.com/abdusemiabduweli/mdtraj

When I tried to install mdtraj by using pip install mdtraj, I got so many errors. After two days of trying, I finally successfully installed mdtraj. These two folders in the link above are from my `...\Python39\Lib\site-packages `directory. I hope these folders work for you.

My environment:

Python 3.9.13

windows 11 64 22000.978

**Comment by mattwthompson** [comment]
https://github.com/mdtraj/mdtraj/discussions/1793
