### ISSUE TITLE
success to install on M1 Ventura 13.2

### ISSUE THREAD

**Issue by aspitaleri** [mdtraj/mdtraj#1765]
For most Mac M1 users:
git clone mdtraj
cd mdtraj
CC=/usr/bin/gcc CXX=/usr/bin/g++ python3 setup.py build
CC=/usr/bin/gcc CXX=/usr/bin/g++ python3 setup.py install

clang15 compile mdtraj but once import give errors with undefined symbol

**Comment by mattwthompson** [comment]
With 1.9.8 released this workaround is hopefully not necessary. If it is: https://github.com/mdtraj/mdtraj/discussions/1793
