### ISSUE TITLE
pip install mdtraj failing on Ventura

### ISSUE THREAD

**Issue by rbharath** [mdtraj/mdtraj#1768]
I'm trying to install mdtraj on a fresh conda environment on Ventura with `pip install mdtraj` and I'm getting a failure building the wheel. I am not on M1. I have not yet tried the workaround from #1765 with building from source though. Raising this issue in case anyone else has run into this issue

**Comment by rbharath** [comment]
I'm on python 3.9 so I don't think this is related to https://github.com/mdtraj/mdtraj/issues/1761 but I'm not sure

**Comment by mattwthompson** [comment]
Once we fix this we should probably upload wheels, I think - is that still considered `pip`/PyPI best practices?

**Comment by mattwthompson** [comment]
I can reproduce this, or something similar, so whatever's causing it is probably not architecture and more likely something changing with the compiler.

I think this it the relevant bit:
```
      building 'mdtraj.geometry.drid' extension
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/mattthompson/mambaforge/envs/mdtraj-1768/include -fPIC -O2 -isystem /Users/mattthompson/mambaforge/envs/mdtraj-1768/include -Imdtraj/geometry/include -I/private/var/folders/p1/176rcfkn6zlbbjq4bdjmv2pr0000gn/T/pip-build-env-0ousrr6q/overlay/lib/python3.11/site-packages/numpy/core/include -I/Users/mattthompson/mambaforge/envs/mdtraj-1768/include/python3.11 -c mdtraj/geometry/drid.cpp -o build/temp.macosx-10.9-x86_64-cpython-311/mdtraj/geometry/drid.o -msse2 -mssse3 -O3 -funroll-loops --std=c++11 -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare
      mdtraj/geometry/drid.cpp:230:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mdtraj
Failed to build mdtraj
ERROR: Could not build wheels for mdtraj, which is required to install pyproject.toml-based projects
```

and this jogs my memory because it's the same as #1761 which we have yet to fix. I assume your builds are failing for the same reason - please let us know if you're seeing something different.

**Comment by mattwthompson** [comment]
1.9.8 includes a fix that should take care of this - please let us know if that's not the case
