### ISSUE TITLE
image_molecules overwrites original coordinates even with inplace=False

### ISSUE THREAD

**Issue by CharlieLaughton** [mdtraj/mdtraj#1769]
Hi,

I notice the following behaviour (mdtraj 1.9.7):

>>> import mdtraj as mdt
>>> t = mdt.load('test_good.nc', top='test.parm7')
>>> print(t.xyz[0,0])
[-0.4629839  -0.97166234 -2.3075812 ]
>>> t2 = t.image_molecules(inplace=False)
>>> print(t2.xyz[0,0])
[1.3345304 1.4162045 1.6006372]
>>> print(t.xyz[0,0])
[1.3345304 1.4162045 1.6006372]

Is this what should happen or a bug? I can offer a PR to fix this if desired.

**Comment by sukritsingh** [comment]
Now that this is fixed, I think we can close this issue now, right? Will close but let me know if something pops up. Thanks again!
