### ISSUE TITLE
Iterload fails for large DCD files on Windows

### ISSUE THREAD

**Issue by reedharrison** [mdtraj/mdtraj#1770]
I encountered an issue using mtraj.iterload with large DCD files on Windows (~12 GB) that results in an OSError as follows:

> File mdtraj\formats\dcd\dcd.pyx:221, in mdtraj.formats.dcd.DCDTrajectoryFile.__cinit__()
> OSError: Could not open file: 6m0j_P1_trajectory.dcd

This DCD file in particular is about 12 GB, and can be loading in chunks successfully on Linux:

`for chunk in md.iterload(filename='6m0j_P1_trajectory.dcd', chunk=100, top=psf):`
`    print(chunk)`

Smaller DCD files can also be read fine on Windows with iterload, so it seems to be a problem specific to large DCD files.

What I think is happening is that "open_dcd_read" is failing at line 219 in "mdtraj/formats/dcd/dcd.pyx", but I'm not sure what the exact problem is. Has anyone run into a problem like this before?

**Comment by reedharrison** [comment]
Tried updating dcdplugin.c to a more recent version. Had to make some additional changes to get it to compile, but it does allow mdtraj.iterload to read the 12 GB DCD successfully. Could use more testing to make sure these changes didn't break anything else.

**Comment by mattwthompson** [comment]
Could you please submit the changes as a PR?

**Comment by reedharrison** [comment]
Closing this issue since it appears fixed.
