### ISSUE TITLE
Loop potentialEnergy values on HDF5 files

### ISSUE THREAD

**Issue by pguillem** [mdtraj/mdtraj#1773]
Hi all,
Is there an example that I could follow to find the lower potentialEnergy value in a HDF5 file and return its frame number? maybe even export a PDB of such frame?.

Energies are being written from HDF5Reporter (Openmm) so I'm sure its there. I just don't know how to loop or acces this values.

Best
Pedro

**Comment by sukritsingh** [comment]
Could you clarify what is being written into your OpenMM object from the HDF5reporter - perhaps a code snippet? If you are printing out the Energies into the file over time you should be able to read in the trajectory object and identify the maximal frame using `argmax`

**Comment by pguillem** [comment]
Hello @sukritsingh. Thanks for taking the time to respond. I was able to do it by loading the h5 file with python and  looping the right property
