### ISSUE TITLE
Error with TNG imports

### ISSUE THREAD

**Issue by mastersubhadeep** [mdtraj/mdtraj#1775]
I was trying to install via pip on Windows.
After successful installation, the following line was causing problems because this was not built automatically.

Line 50 of __init__.py: from .formats.tng import load_tng
Line 49 of core.trajectory.py: from mdtraj.formats import TNGTrajectoryFile

For now, I have commented them out and am able to do my analysis.

**Comment by mattwthompson** [comment]
This is probably related to https://github.com/mdtraj/mdtraj/issues/1761

**Comment by jeremyleung521** [comment]
tng code was removed in 1.10
