### ISSUE TITLE
Speeding up install in google colab (binary wheels?)

### ISSUE THREAD

**Issue by ajasja** [mdtraj/mdtraj#1779]
I'm using Google colab for educational and demonstration purposes.
I can do `!pip install mdtraj`, however that takes 3-5 min, which is a really long time (alphafold 2 can be installed in 3 min:)

Are there binary wheels somewhere? That would solve a lot of problems.
(Or I guess I can do a conda install, but then I have to install conda into a google colab).

Any tips are welcome.

**Comment by ajasja** [comment]
This is the output
![image](https://user-images.githubusercontent.com/19926/236534877-59bccd51-ffeb-4e6c-9aba-0a3c27779674.png)

**Comment by mattwthompson** [comment]
What version of Python? I think I uploaded wheels on the last release but I don't remember

#1761 maybe related

**Comment by ajasja** [comment]
Thanks for the quick response!

Google colab is currently using 3.10 
![image](https://user-images.githubusercontent.com/19926/236546495-85ccdb3d-d7ca-40db-ba9b-e40d78d471a0.png)

Pypi only reports having the source
![image](https://user-images.githubusercontent.com/19926/236546721-3953b8ea-c59b-4783-802c-8bb3a23e2396.png)

Binary wheels would be wonderful.

**Comment by mattwthompson** [comment]
I can make binary wheels if you could link some references on what the current best practices are. It's been a couple years since I've done it and with MDTraj being compiled code, it can be a bit tricky. I'm also on Apple Silicon right now, if that makes things trickier.

**Comment by ajasja** [comment]
That would be great! I have not built a binary wheel yet (most of my stuff is pure python).

I think the best way is that the CI system builds the wheel as well. 
Would this be enough to get started:
https://github.com/pypa/cibuildwheel ?

**Comment by mattwthompson** [comment]
Thanks again for the suggestion, and I agree that distributing wheels is the way to go here. I'll move this discussion to #1794, which we'll use to track adding the automation to do this for us. For the last two releases I've done it locally, but I think it's limited to one version of Python and one architecture. (I could build them for ~3 Python versions and possibly 2-3 architectures, but I'm more eager to get `cibuildwheel` running than setting up several virtual environments to locally build wheels for each release.)
