### ISSUE TITLE
Duplicated bonds caused by a bug when interpreting CONECT records in a PDB file

### ISSUE THREAD

**Issue by yaoyic** [mdtraj/mdtraj#1783]
This line is supposed to check whether the bond noted by the CONECT records is missing from the current topology. If so, the bond will be added.
https://github.com/mdtraj/mdtraj/blob/287770b9fc61d01efed2f76c4ce26124e98fedac/mdtraj/formats/pdb/pdbfile.py#L592
Based on the PDB format and the implementation, the same pair will arrive here twice, i.e., `(atom1, atom2)` and `(atom2, atom1)`. The if statement above is supposed to be `False` when either version already exists in the current topology. However, the if statement turns out always true and both orders will be added as bonds, thus causing duplication.

The problem is not with the Boolean logic, but due to a very old change in the `Bond` type. Once upon a time `Bond` type was simply a 2-element tuple of `atom1` and `atom2`, but now it's a subclass to `NameTuple` containing more information (cf. PR #1308). The code here (and maybe somewhere else as well?) was not adapted accordingly, so of course any `bond` to be tested (Tuple[Atom, Atom]) will not be `in` a set of `Bond`s.

Suggestion:
```Python
# temporarily convert it to the good old format
existingBonds = set((bond.atom1, bond.atom2) for bond in top_new.bonds)
for bond in connectBonds:
    if bond not in existingBonds and (bond[1], bond[0]) not in existingBonds:
        self._topology.add_bond(bond[0], bond[1])
        existingBonds.add(bond)
```

**Comment by sukritsingh** [comment]
Oh interesting! Do you have an example where this problem comes up? Just so I can replicate myself (and so it's on the record here).
