### ISSUE TITLE
API changes for GSD 3.0

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1789]
See also https://github.com/MDAnalysis/mdanalysis/issues/4172

**Comment by sukritsingh** [comment]
Since this is merged you think we can close this issue?

**Comment by mattwthompson** [comment]
It looks like we want to make sure either 2.x or 3.0.1+ are installed. I can update the conda package, not sure what to do with the PyPI side of things. I guess we can just hope users install the most recent version.

**Comment by mattwthompson** [comment]
This should be good to close once the linked PR is merged, which with any luck will be handled by the c-f bot
