### ISSUE TITLE
image_molecules does not work in mdtraj 1.9.7 with Python 3.10

### ISSUE THREAD

**Issue by nmroussey** [mdtraj/mdtraj#1796]
Hello,

I have found that all uses of image_molecule in python 3.10 (on MacOS) returns an array of nan, and is over writing my original trajectory positions, even when inplace=False. I have tried this on multiple PDB/DCD combos and had the same outcome. This issue is NOT happening with mdtraj 1.9.7 and Python 3.9 on the same machine.

For example when I do the below (with either 'dcd' or after making the dcd into a trajectory object):

pdb = mdj.load_pdb('my_pdb.pdb')
dcd = mdj.load_dcd('md_dcd.dcd', pdb.topology)
imaged = dcd.image_molecules()

OR

protein = dcd.topology.guess_anchor_molecules()
imaged = dcd.image_molecules(anchor_molecules=protein, make_whole=True)

imaged.xyz returns an array of [nan, nan, nan].
dcd.xyz also returns an array of [nan, nan, nan] when it was NOT nan before image_molecules was called.

Unfortunately, I cannot upload sample data.

Any help would be appreciated!

**Comment by sukritsingh** [comment]
Oh that's *really* weird.
>  is over writing my original trajectory positions, even when `inplace=False`

This is unfortunately a previously reported pathology and something I've seen across versions. I'll have to dig into it a bit but if you want to submit a PR that resolves it please feel free to do so!

> This issue is NOT happening with mdtraj 1.9.7 and Python 3.9 on the same machine. 

This version variation + nan returns are completely new to me. Unfortunately, I have a python 3.10/MDTraj 1.9.8 environment and I cannot replicate this issue with my own files (or in 3.9 either).  If you can find a shareable example that replicates this issue then that would be super useful! 

My one thought would be seeing if you didn't try to pass a `guess_anchor_molecules` output and either defined them manually or didn't pass it at all, does that still return nans?

**Comment by nmroussey** [comment]
Yes, it still returns nan for everything. I have tried every combination I can think of for arguments for image_molecules and after it is run, any and all positions become nan.

**Comment by sukritsingh** [comment]
The long standing issue of trajectory overwriting even with `inplace=False` should be fixed now by #1816 ! Hopefully it is no longer a problem!
