### ISSUE TITLE
mdtraj pip install error 

### ISSUE THREAD

**Issue by Harshitasahni** [mdtraj/mdtraj#1802]
I get this error while I pip install mdtraj 

Collecting mdtraj==1.9.8
  Using cached mdtraj-1.9.8.tar.gz (2.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Requirement already satisfied: imageio in /usr/local/lib/python3.10/dist-packages (2.25.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from imageio) (1.22.4)
Requirement already satisfied: pillow>=8.3.2 in /usr/local/lib/python3.10/dist-packages (from imageio) (8.4.0)

**Comment by mattwthompson** [comment]
Not a whole lot to go off of here, my first guess is that it's related to #1800 in which Cython must be downgraded to something like `Cython~=0.29`

**Comment by mattwthompson** [comment]
See https://github.com/mdtraj/mdtraj/issues/1800#issuecomment-1646607150
