### ISSUE TITLE
Feature suggestion: guess bonds

### ISSUE THREAD

**Issue by fwaibl** [mdtraj/mdtraj#1803]
Dear MDTraj developers,

I was trying to use mdtraj.make_molecules_whole on a trajectory without complete bond information, which only fixed molecules with bonds. As a workaround, I came up with the following to guess bonds based on inter-atomic distances:

```
import mdtraj as md
import numpy as np
from scipy.spatial import KDTree

# from https://en.wikipedia.org/wiki/Van_der_Waals_radius
vdw_radii = {
    md.core.element.hydrogen: 1.2,
    md.core.element.carbon: 1.7,
    md.core.element.nitrogen: 1.55,
    md.core.element.oxygen: 1.52,
    md.core.element.fluorine: 1.47,
    md.core.element.phosphorus: 1.8,
    md.core.element.sulfur: 1.8,
    md.core.element.chlorine: 1.75,
    md.core.element.copper: 1.4,
}

def guess_bonds(traj: md.Trajectory, frame=0):
    xyz = traj.xyz[frame] % traj.unitcell_lengths[frame]
    vdw = np.array([vdw_radii[atom.element]/10 for atom in traj.top.atoms])
    max_dist = np.max(vdw) * 2
    tree = KDTree(xyz, boxsize=traj.unitcell_lengths[frame])
    pairs = tree.query_pairs(max_dist, output_type='ndarray')
    distance = md.compute_distances(traj[frame], pairs)[0]
    is_contact = distance < np.sum(vdw[pairs], axis=-1)
    return pairs[is_contact].astype(np.int32)
```

Is there interest to implement something like this in MDTraj? If yes, I could offer to extend my function further (e.g., non-orthogonal unit cell vectors, more VdW radii). Or does such a function already exist and I just could not find it?

Best,
Franz

**Comment by mattwthompson** [comment]
I'm inclined to keep this a downstream feature. For individual systems it's not too hard to implement, but expanding out to more of the periodic table, accounting for bond order, and also accounting for different local chemical environments is notoriously tricky. RDKit has a [solution](https://mdtraj.org/1.9.4/api/generated/mdtraj.Topology.html) for this but it took ages

**Comment by sukritsingh** [comment]
Agreed with Matt on this - it also requires additional imports from `scipy.spatial` that could end up breaking things if changes to KDTree were ever made, so it would probably be easiest to let this be a downstream feature. 

That said - feel free to open up a discussion about this in the Discussions tab! Approaches like this could be a good discussion point to include there (and perhaps eventually in a wiki/docs of some kind!)

**Comment by sukritsingh** [comment]
> However, in many cases (such as make_molecules_whole) it is already helpful to know which atoms are bonded to each other at all, assuming all single bonds.

Totally agree. However, I wonder how well the "assuming all single bonds" assumption would hold anyways for most systems (amino acids have double bonds too!). There are topology references within MDTraj and OpenMM to help recognize the topology of certain residues, so you can always write out CONECT records as needed perhaps too (Just spitballing here).

> By the way, is there a recommended place to share snippets / tricks of mdtraj code? Or should this go into the discussions page?

Great question! It's honestly still an open one, but for now I had created the [Discussions tab](https://github.com/mdtraj/mdtraj/discussions) to try and create a forum for discussions and snippets like these. Your code snippet is very helpful and I can see many people benefiting from it, so please feel free to start off a post there about it!
