### ISSUE TITLE
DeprecationWarning: invalid escape sequence '\g'

### ISSUE THREAD

**Issue by speleo3** [mdtraj/mdtraj#1806]
I'm getting several "DeprecationWarning: invalid escape sequence".

These can also be detected using a linter like `ruff` or `flake8` with the [W605](https://beta.ruff.rs/docs/rules/invalid-escape-sequence/) rule:
```sh
ruff check --select W605 mdtraj
```
```sh
flake8 --select W605 mdtraj
```

Most of these strings come from math expressions in docstrings, but also several regular expressions are affected.

The easy solution is to use [_raw string_](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) syntax (`r` prefix) for those strings.

I'd be happy to make a pull request.

**Comment by mattwthompson** [comment]
A PR that raw-ifies regex strings would be welcome, I expect.

I have a slight preference for leaving the existing math expressions in place where possible - I assume `flake8` is just not good with parsing TeX stuff - even if that requires workarounds like `# noqa` or turning off that rule for particular files.

It's worth exploring `flake8` or similar for the entire codebase at some point; no need to do that here

**Comment by speleo3** [comment]
There are actual errors in the TeX strings which would get fixed by raw strings. Example:

Docstring of [mdtraj.asphericity](https://www.mdtraj.org/1.9.8.dev0/api/generated/mdtraj.asphericity.html?highlight=asphericity#mdtraj.asphericity), current:
![asphericity-current](https://github.com/mdtraj/mdtraj/assets/1239490/aa970109-8536-43e8-8f58-185ede3e7c03)

After raw string fix:
![asphericity-raw](https://github.com/mdtraj/mdtraj/assets/1239490/e48e6603-23d1-44ec-afda-815b2fa87c41)
