### ISSUE TITLE
Build docs in CI

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1809]
I know RTD has nice tools for building docs in PRs; this is nice for ensuring changes don't break things and being able to see the docs built on a feature branch.

**Comment by sukritsingh** [comment]
For some reason I actually assumed all the docs were being built in the CI but I didn't realize they weren't! Agree that it would be good to do this

**Comment by sukritsingh** [comment]
I think this would be addressed in parallel with #1810 by using RTD to build the docs? I'll just need to figure out who has the keys to the main webpage so we can push it there...

**Comment by mattwthompson** [comment]
Yup, RTD kills two birds with one stones here. I just don't remember how things currently work (or worked) and it might have been separated out

**Comment by sukritsingh** [comment]
Are there any downsides/caveats we may need to be aware of if we pivot to RTD @mattwthompson ? I can't think of any major ones off the top of my head but I don't know how much of a change our docs would need for RTD to build things appropriately...

**Comment by mattwthompson** [comment]
There shouldn't be anything major as long as Sphinx will build the docs. Given they haven't been built in a while, there might be some updates needed but it shouldn't be anything too major. If they can be built i.e. locally, there isn't much work required to host them on RTD, just a YAML config file that we can copy from elsewhere and setting up the project on RTD which should just take a few clicks. Oh, and redirecting with mdtraj.org if we want to continue doing that.

I'll add I like RTD because it's what I'm familiar with and use at OpenFF - if people want other solutions I'm certainly open to it.

**Comment by sukritsingh** [comment]
Yeah I like RTD for its search feature and I think that could be useful. I know the MDTraj docs scrape some API information directly from the code - could RTD handle something like that? This isn't a pure python project after all...

> as long as Sphinx will build the docs. Given they haven't been built in a while, there might be some updates needed but it shouldn't be anything too major. If they can be built i.e. locally, there isn't much work required to host them on RTD, just a YAML config file that we can copy from elsewhere and setting up the project on RTD which should just take a few clicks. 

I can't do it tonight (may be this weekend or next week) but happy to give trying to build the docs locally a whirl and seeing what updates we need to make.

The more "manually hosted" copies contain the older docs for MDTraj (ie you could look up versions going back to 2014) - do we see any value in preserving those? I'm not entirely sure to be honest.

**Comment by mattwthompson** [comment]
> could RTD handle something like that? 

Not sure, I saw there's some tooling that does this and I'm too scared to open those files.

> do we see any value in preserving those?

Mixed feelings; Google likes to point users to versions from several years ago which can cause headaches in some projects, but the API is really stable. On the other hand, I don't want users to come across dead links ... if it's easy enough to host it'd be nice to keep them around.

**Comment by sukritsingh** [comment]
Sorry for the delay (finally catching up post grant deadline) - I'm also in the boat of "I think it may be worth preserving at least some links because of what people will easily find" 

> Not sure, I saw there's some tooling that does this and I'm too scared to open those files.

Hah same boat. Let me see what I can dig up and see if RTD can handle it better now...

**Comment by sukritsingh** [comment]
Just noting here that some changes in RTD/docs dependencies may have an impact 
also 
https://blog.readthedocs.com/defaulting-latest-build-tools/

Will retest with these updates!

**Comment by sukritsingh** [comment]
Can't believe I never asked this, but do we know if there's an RTD login already associated with MDTraj? If not I'll go ahead and make one so I can try building with RTD (unless we think something else is a better fit now)

**Comment by mattwthompson** [comment]
I just claimed/squatted that URL. Let me know your RTD username and I'll add you (and whoever else) there. There'll probably be a config file or two needed to get them building again

**Comment by sukritsingh** [comment]
Great! I think for now just me and you is fine (unless someone chimes in here). 

My RTD username is `sukritsingh`

And yeah it'll probably need a few config files - will look into this now (my first time!)
