### ISSUE TITLE
shrake-rupley error quits instead of raising error

### ISSUE THREAD

**Issue by smiles724** [mdtraj/mdtraj#1817]
This is a repeated request for shrake-rupley function. The prior issue can be found here https://github.com/mdtraj/mdtraj/issues/1300. 

 thx

**Comment by mattwthompson** [comment]
A PR to fix this behavior would be welcome

**Comment by sukritsingh** [comment]
> A PR to fix this behavior would be welcome

Endorsing this - please feel free to submit a PR that address this behavior!

I'll have to read through that issue in more depth (it's from 2017) but if you could provide an example file+code to reproduce this behavior then I'm happy to try making inroads.

**Comment by smiles724** [comment]
> > However, I believe the contributors should pay more attention to it for users' purposes.
> 
> I understand that it is frustrating to run into software bugs, so I recognize where you're coming from. Speaking only for myself, I would just respectfully like to point out that this project is maintained by volunteers. The contributors to this project have spent a significant amount of their free time, weekends and holidays on this project, but they do not owe you their time. The maintainers welcome bug reports and contributions of any kind, but comments like this can come across as entitled and can be demotivating (at least to me). Remember: the software was distributed to you at no cost, without any warranty of fitness, and with a license that allows you to make any modifications you see fit to make.

Apologize for the impolite request. I meant no offense. I really appreciate all the efforts and hard work that all volunteers spent in developing and maintaining this repo. 

As a matter of fact, I have implemented the Python script via "subprocess" to tackle the problem. Therefore, it is no longer trapping me anymore. 

I really understand that you and other contributors support this algorithm with no pay and are completely self-motivated. Unlike other packages that are profitable, you make it open and spend your valuable spare time to promote the community.Thanks again!
