### ISSUE TITLE
xrdlib deprecation warning

### ISSUE THREAD

**Issue by richardjgowers** [mdtraj/mdtraj#1818]
I'm getting this warning in a test suite:  `/Users/runner/micromamba-root/envs/openfe_env/lib/python3.11/site-packages/mdtraj/formats/__init__.py:6: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13`

Over in mda land we made this as a drop in replacement:

https://pypi.org/project/mda-xdrlib/

**Comment by mattwthompson** [comment]
Those imports do different things, one for the Python layer and one for the C layer (note it's a `.pyx` file, not a normal Python file). I also think that looks a namespace collision, but that [appears to be](https://stackoverflow.com/a/20268478) how it's done in Cython world

**Comment by padix-key** [comment]
That is true, having it both imported and cimported simply makes attributes from Python and C world available. However, as far as I saw in this case, `xdrlib` is only used to call functions/types from [`xdrlib.pxd`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/xtc/xdrlib.pxd) and nothing from the Python standard library module `xdrlib.py` is called.

**Comment by mattwthompson** [comment]
Maybe the Python import can be skipped, I'm not sure having almost no Cython experience myself. I'd happily review a PR that gives it a shot
