### ISSUE TITLE
RMSD method 

### ISSUE THREAD

**Issue by Harshitasahni** [mdtraj/mdtraj#1823]
What is the unit (Ang or nm) for the rmsd's calculated using mdtraj.rmsd?
https://mdtraj.org/1.9.4/api/generated/mdtraj.rmsd.html

**Comment by mattwthompson** [comment]
MDTraj uses nanometers throughout for all distance measurements, if I recall correctly

https://www.mdtraj.org/1.9.8.dev0/examples/introduction.html?highlight=unit

**Comment by sukritsingh** [comment]
All distances in the `Trajectory` object are stored and reported in nanometers. All time units are picoseconds, and angles are stored in degrees

**Comment by Harshitasahni** [comment]
Thank you everyone, All distances in the pdb file are stored and reported in Ang. But mdtraj converted and results are always in nm.

**Comment by sukritsingh** [comment]
I think we can close this issue for now since we've answered your question? Let me know if we should reopen!
