### ISSUE TITLE
Memory leak in NetCDF reporter

### ISSUE THREAD

**Issue by sef43** [mdtraj/mdtraj#1831]
This is a duplicate of https://github.com/mdtraj/mdtraj/issues/1345 which is currently closed.

It recently appeared again as an OpenMM issue: https://github.com/openmm/openmm/issues/4298

Using the mdtraj.NetCDFReporter causes eventual simulation slow down due to a memory leak. The issue comes from the scipy.io.netcdf library. It can be fixed by using the NetCDF4 library as done here: https://github.com/ParmEd/ParmEd/issues/619

**Comment by mattwthompson** [comment]
This one? https://pypi.org/project/netCDF4/

**Comment by sef43** [comment]
Yep thats the one!. Both ParmEd and MDAnalysis use that library for writing NetCDF if it is available. However they do not have it as a dependency and they both fallback to the scipy version if the NetCDF4 python package is not installed. This seems to be due to some compatibilities with how Amber links to its own NetCDF library. There is more discussion here: https://github.com/MDAnalysis/mdanalysis/issues/506#issuecomment-225081416 (Not sure if this is still a problem in 2023)

**Comment by mattwthompson** [comment]
It looks like this is the same project packaged to conda, which we might want to include or nudge users towards installing in the next version? https://anaconda.org/conda-forge/netcdf4

It's at least used in a bunch of projects I vaguely recognize: https://gist.github.com/mattwthompson/d290dba85668e403b0d5a5451ca256ef

**Comment by mattwthompson** [comment]
#1831 / 1.10
