### ISSUE TITLE
Overwriting an Existing HDF5Reporter

### ISSUE THREAD

**Issue by Heezch** [mdtraj/mdtraj#1843]
I'm currently working with a Python script with OpenMM where I need the functionality to overwrite an existing HDF5Reporter with the same name in a simulation. My goal is to either append a new reporter or replace the existing one, depending on whether it's already present.

However, I encountered a `ValueError` indicating that the HDF5 file is already opened and needs to be closed before it can be reopened in write mode. I attempted to address this by checking for the error, closing the existing reporter, and then appending a new one. Here's the code snippet I used:

```
from mdtraj.reporters import HDF5Reporter

try:
    simulation.reporters.append(HDF5Reporter(f'{self.name}.h5', 100))
except ValueError as e:
    if 'already opened' in str(e) and self.override:
        # Attempting to close the existing HDF5Reporter
        for reporter in simulation.reporters[:]:  # Copy of the list for iteration
            if isinstance(reporter, HDF5Reporter) and reporter._filename == f'{self.name}.h5':
                reporter.flush()  # Writing out any pending data
                reporter.close()  # Closing the file
                simulation.reporters.remove(reporter)  # Removing the closed reporter
                break
        # Appending a new HDF5Reporter
        simulation.reporters.append(HDF5Reporter(f'{self.name}.h5', 100))
    else:
        raise
```
Despite these steps, the error persists. I also tried deleting the file using `os` module, but it seems the state remains in RAM, leading to the same error (resetting the kernel would allow me to initialize using the same name and overwrite). Am I missing something obvious? If there is no solution within the same state of the kernel, I will probably adjust the filename, but ideally I do not want to do that. Thank you for having a look at my issue.

**Comment by sukritsingh** [comment]
Thanks for bringing this up! Generally I've found that once you attach the reporter to the `simulation` object all you have to do is run a loop or something simple to append everything as it's running in a single simulation.

> I need the functionality to overwrite an existing HDF5Reporter with the same name in a simulation
 Can you provide a full script example of your usecase where you're running into this issue? You may need to reinitialize the `simulation` object to overwrite/append the existing reporter (otherwise OpenMM will keep it open).

I confess I've only used the OpenMM reporters and have only ever converted completed trajectories into HDF5 files, so I haven't used this reporter myself.

**Comment by sukritsingh** [comment]
Noting that appending in general appears to be tough with HDF5 files - this issue has been brought up before in #1750 - would welcome a PR fix to this!

**Comment by Heezch** [comment]
Thanks for your comments and suggestions! I have indeed accessed the reporters via the simulation object and was then able to close the reporter without much effort: `simulation.reporters[0].close()`
