### ISSUE TITLE
Cannot select residues with names starting with numbers

### ISSUE THREAD

**Issue by cmwoodley** [mdtraj/mdtraj#1851]
Just something I noticed when processing an example MD trajectory from the[ gcprmd repository](https://gpcrmd.org/view/97/).

The following snippet:

```
import mdtraj as md

t = md.load('../Example_MD/gpcrmd_97/10932_trj_97.xtc', top='../Example_MD/gpcrmd_97/10936_dyn_97.pdb', stride=50)
topology = t.topology

topology.select('resname 1Q5')
```

Returns an empty array.

Manually renaming the residue to something else resolves the issue.

Not a big deal, but may cause some confusion. Cheers!

**Comment by sukritsingh** [comment]
Thanks for responding @RobertArbon ! Yes, `select` allows for regex operators for residues starting with numbers since that's a fairly uncommon use case (never occurring with proteins, and usually only specific ligands)....Did this work? I can close this issue if so!

**Comment by cmwoodley** [comment]
Apologies for the delay in replying - yes this worked! Thank you both for replying!
