### ISSUE TITLE
Faster way to split one trajectory into several?

### ISSUE THREAD

**Issue by helmutcarter** [mdtraj/mdtraj#1852]
I need to take the frames from a single trajectory and assign them to several different trajectories based on a list of labels corresponding to the frames. Is there a fast way to do this? From what I can tell, the following code is very slow:
```
for frame, label in zip(trajectory, labels):
    if bin_dict[bin_num] == None:
        bin_dict[bin_num] = frame
else:
    bin_dict[bin_num] += frame
```
My trajectory is 50,000 frames, and I have no more than 10 bins to sort the frames in to. Execution time also seems to increase with the number of atoms in the system.

**Comment by mattwthompson** [comment]
I don't know what `bin_dict` is doing there (50,000 key-value pairs?) but strightforwardly slicing your trajectory may be faster: https://www.mdtraj.org/1.9.8.dev0/examples/introduction.html?highlight=slice

**Comment by helmutcarter** [comment]
`bin_dict` would only have up to 10 key-value pairs, because there are only up to 10 different bins. But by the end of it `bin_dict[3]` might be `<mdtraj.Trajectory with 5200 frames, 4605 atoms, 1531 residues, and unitcells>`. I will try slicing and report back. Maybe I just need to rewrite in C++.

**Comment by mattwthompson** [comment]
It looks like you're reconstructing each trajectory via appending each frame, one at a time, which is probably slow in the Python layer. You should try slicing, no need to write new C++ code

**Comment by helmutcarter** [comment]
Is there a way to do this without appending each frame? I thought you were suggesting I change how I access each frame to be something like:
~~~
        for frame_idx in range(len(trajectory)):
            if bin_dict[labels[frame_idx]] == None:
                bin_dict[labels[frame_idx]] = trajectory[frame_idx]
            else:
                bin_dict[labels[frame_idx]] += trajectory[frame_idx] 
~~~
The labels (and thus the frames I want to access) are in a random order. Given list `[1,6,8,3,2,8,1,6,3,9,1]` there's no way I can use slicing to grab all the `1`'s at one time, is there?

**Comment by mattwthompson** [comment]
If you already know the frames you want to slice out, you don't need to loop through the trajectory and append individual frames. You can just slice according to the indices you want in one go - that's the beauty of slicing.

Grabbing duplicate frames and frames in non-sequential order is a bit strange, but I don't see why you couldn't try [NumPy-style indexing](https://numpy.org/doc/stable/user/basics.indexing.html) on the slice, i.e.

```python
In [17]: numpy.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])[[1,6,8,3,2,8,1,6,3,9,1]]
Out[17]: array([8, 3, 1, 6, 7, 1, 8, 3, 6, 0, 8])

**Comment by helmutcarter** [comment]
For clarity, I'm not grabbing any duplicate frames; each element in my list of labels corresponds to a frame, and the value of the element is which bin (cluster, really) it needs to end up in. But, this solution works perfectly. I was not aware of numpy-style indexing, so I thank you for your prompt insight! The function now executes in about 3 seconds. For posterity, here is what I ended up doing:
~~~
    idx_dict = {}
    output_dict = {}
    for label in list(dict.fromkeys(labels)): # get deduplicated list of labels to iterate over
        idx_dict[label] = [x for x, y in enumerate(labels) if y == label]
    for label in idx_dict:
        output_dict[label] = trajectory[np.array(idx_dict[label])]
~~~
