### ISSUE TITLE
wheels of mdtraj

### ISSUE THREAD

**Issue by bojunliu0818** [mdtraj/mdtraj#1857]
Hello everyone, will we be posting the MDTraj wheels for various Python versions and platforms to PyPI? Would it be good to create a new branch utilizing cibuildwheels to do this? I can also create a pull request if needed, thanks!

**Comment by mattwthompson** [comment]
#1794 

Although it looks like somebody already did it #1833

**Comment by bojunliu0818** [comment]
Oh sounds great! Sorry I missed that. Is it going to be merged for uploading wheels on pypi?

**Comment by mattwthompson** [comment]
Probably so, but there isn't much urgency until a release is necessary

**Comment by bojunliu0818** [comment]
Got it! But there is one thing that I am currently responsible for maintaining msmbuilder, which depends on MDTraj as a build dependency. Consequently, I am unable to build msmbuilder wheels in the absence of MDTraj wheels. May I ask if it would be good that we temporarily create a sub-branch to manually upload the wheels for MDTraj 1.9.9?

**Comment by mattwthompson** [comment]
It might be easiest to just build wheels locally an and upload them; I did this once (or at least I think it was me ...) for what's online for 1.9.9: https://pypi.org/project/mdtraj/1.9.9/#files

If I can dig up the commands I ran then, I can probably get Apple Silicon wheels up, and then if somebody runs them on a Linux machine that takes care of the major platforms.

**Comment by bojunliu0818** [comment]
Great! Previously I have built all wheels using a cibuildwheels in my forked repo https://github.com/bojunliu0818/mdtraj/blob/duplicate-whl/.github/workflows/wheels.yml. I downloaded these wheels files built from the workflow and manually uploaded them on pypi: https://pypi.org/project/mdtraj-duplicate/#files. The only difference is I marked the name with as 'duplicate' to avoid confusions. Here I can directly build these wheels of mdtraj based on 1.9.9 released source code, and probably someone could then help to upload them on pypi?

**Comment by mattwthompson** [comment]
Any idea why the Linux file is ~5x as large as the macOS files? Is this typical of `manylinux` builds?

**Comment by bojunliu0818** [comment]
Yeah, I guess so. As manylinux file needs to be compatible with many different versions of linux platforms

**Comment by bojunliu0818** [comment]
Sorry wait, I just found that if I built it locally, it's 2.5Mb. I am not sure why manylinux file from cibuild seems much larger.

**Comment by bojunliu0818** [comment]
Also, for macos, I didnt specify universal2, which is typically larger

**Comment by jeremyleung521** [comment]
Closing this since we're already manually building wheels for 1.10.*. We will be implementing the cibuildwheels github action for 1.10.2 onwards.
