### ISSUE TITLE
Attempt to follow SPEC 0

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1863]
Most projects in this ecosystem roughly follow NEP 29, but recently there's a shift towards SPEC 0 which is effectively no different but irons out a few details around the edges and casts a wider net.

https://numpy.org/neps/nep-0029-deprecation_policy.html
https://scientific-python.org/specs/spec-0000/

**Comment by sukritsingh** [comment]
Closing this issue since it looks like you already addressed it!
