### ISSUE TITLE
Numpy 2.0 Release is imminent 

### ISSUE THREAD

**Issue by jeremyleung521** [mdtraj/mdtraj#1873]
Just wanted to ping the maintainers here that Numpy 2.0 will release soon (`rc1` was released March 29th, 2024).  Right now, there are no version restrictions on the numpy version. With the amount of cythonized numpy here, it might be wise to pin to `numpy<2` before things (potentially) break in PyPI (and conda). 

Here are the places that need to be changed:
Conda-forge:
https://github.com/conda-forge/mdtraj-feedstock/blob/main/recipe/meta.yaml

Setup.py:
https://github.com/mdtraj/mdtraj/blob/master/setup.py#L263

[Build time](https://github.com/mdtraj/mdtraj/blob/master/pyproject.toml#L6) should be fine since that's constrained by `oldest-supported-numpy`, which is deprecated and doesn't support `numpy2`.

### Other info

Numpy 2.0 release status:
https://github.com/numpy/numpy/issues/24300

More Info on Numpy 2.0:
https://numpy.org/devdocs/release/2.0.0-notes.html
https://numpy.org/devdocs/numpy_2_0_migration_guide.html

**Comment by mattwthompson** [comment]
Thanks for the reminder

* We should probably pin the upcoming version.
* I don't know what can be done about older versions that are already out there on PyPI, I assume their policy on immutability makes it a non-starter
* As far as I'm aware, `conda-forge` has some magic that will keep 1.x pinned until we change that in a feedstock? I'm hazy on this - if you've looked into this recently I'm happy to defer
* For testing this with 2.0, should the `"oldest-supported-numpy",` line be removed?

**Comment by jeremyleung521** [comment]
> Thanks for the reminder
> 
>     * We should probably pin the upcoming version.
> 
>     * I don't know what can be done about older versions that are already out there on PyPI, I assume their policy on immutability makes it a non-starter
> 
Unfortunately you'd have to release [a post patch](https://peps.python.org/pep-0440/#implicit-post-releases) for those. Pinning it in the newest version should be sufficient though.

>
>     * As far as I'm aware, `conda-forge` has some magic that will keep 1.x pinned until we change that in a feedstock? I'm hazy on this - if you've looked into this recently I'm happy to defer
> 
As long as you push the build number and pin everything to `numpy<2` in that recipe, you won't need a new version number on conda-forge, I think.

>
>     * For testing this with 2.0, should the `"oldest-supported-numpy",` line be removed?

Yes, and replaced with `numpy`. `Numpy>=2` can only run cython files compiled with `numpy >=2.0`.  The functionality of `oldest-supported-numpy`  is not necessary as of `numpy>=1.25` anyways. But `numpy >=1.25` is only available for `python >=3.9`.

**Comment by jeremyleung521** [comment]
Update: June 16th is the planned release date.
https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448

**Comment by padix-key** [comment]
Is there already timeline, when `mdtraj` will support `numpy` 2.0? In https://github.com/biotite-dev/biotite we use `mdtraj` as optional dependency for trajectory loading and we plan to migrate to NumPy 2.0 in the upcoming weeks.

I can understand, if this is currently no priority for your project. In this case we would probably resort to forking the trajectory loading part of `mdtraj` for now.

**Comment by janash** [comment]
Hi @padix-key - we are currently making plans for NumPy 2.0 support, but the timeline is likely longer than the next few weeks.

**Comment by k9cdt** [comment]
Hi developers, I ran ruff on the mdtraj code according to the recommendations here:

https://numpy.org/devdocs/numpy_2_0_migration_guide.html

And the results show "All checks passed!" as of 9/16. I guess the migration to numpy 2.0 will be then pretty straightforward. Is there a way we can conduct the test and see if the only thing needs to be changed is `pyproject.toml`?

**Comment by mattwthompson** [comment]
@k9cdt There is much more work to be done, see #1923 for the most recent work on this. You're welcome to create your own changeset and open a PR, but it might be easier to coordinate with Jeremy who has already make some progress here

**Comment by k9cdt** [comment]
Thanks for mentioning the PR! I will take a look and see if there's anything I can do

**Comment by jeremyleung521** [comment]
Dusted and closed. Will be released as part of `1.10.2`.

See https://github.com/mdtraj/mdtraj/pull/1928
