### ISSUE TITLE
Upstream macOS compiler fix

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1883]
https://github.com/conda-forge/mdtraj-feedstock/pull/56, probably just the file `recipe/patches/001-fix-clang-16-builds.patch`

I'm not sure why this is a problem only in the feedstock; CI here seems to be chugging along just fine

This might be a 30-second fix, but with my luck it'll turn into a 2-hour diversion so I'm just parking it here for now

**Comment by sukritsingh** [comment]
Maybe I'm missing something (apologies if so) but it looks like the `main` branch on the feedstock doesn't contain `recipe/patches/001-fix-clang-16-builds.patch` ? All I see in `recipe/patches/` [folder](https://github.com/conda-forge/mdtraj-feedstock/tree/main/recipe/patches) is `mdinspect_six.patch`

Does `001-fix-clang-16-builds.patch` need to be readded in? The file looks quite different relative to `mdinspect_six`

**Comment by mattwthompson** [comment]
Good catch - this line is in the TNG extension, which was removed, so I think the other lines aren't needed either

https://github.com/conda-forge/mdtraj-feedstock/pull/56/files#diff-5055114ac13ac6f043ce7259af85af12723fd5aa04671cba30b95ef3cccd9b47R21
