### ISSUE TITLE
mdtraj fails to load pdb correctly, the number of atoms is wrong

### ISSUE THREAD

**Issue by smliu1997** [mdtraj/mdtraj#1912]
For the attached pdb file (it is a pdb format file, but I have to change it to .txt file so that I can upload), if I load it with mdtraj, mdtraj will lead to a trajectory with 188 atoms, but clearly it has 189 atoms in all. An example code is like this:

```
import mdtraj

traj = mdtraj.load_pdb('protein1_ca.txt')
print(traj.n_atoms)
```

[protein1_ca.txt](https://github.com/user-attachments/files/16255880/protein1_ca.txt)

**Comment by mattwthompson** [comment]
I forget / don't know if PDB files need a header or if that's just convention

For what it's worth, OpenMM without guidance also thinks there are 188 atoms

```python
In [1]: import openmm.app

In [2]: openmm.app.PDBFile("../../Downloads/protein1_ca.txt").topology.getNumAtoms()
Out[2]: 188

**Comment by smliu1997** [comment]
I don't think the header is necessary, since I made many files of similar format (as you can see, I picked out CA atoms from some pdb files). Only the specific one I attached leads to the bug, while others work fine.

**Comment by sukritsingh** [comment]
> I forget / don't know if PDB files need a header or if that's just convention

Depends on who you ask, in my experience. Some folks would define a PDB file as having the header, and anything else as just "PDB-format" like. 

In general it's expected that PDB format files do have a header though. If other files besides the one you attached work fine, it may just be due to how MDTraj is reading that file in particular (or a quirk of reading a `txt` file rather than anything else).

**Comment by smliu1997** [comment]
I agree maybe having a header is more formal. However, I think if mdtraj is robust, then it should behave consistently for all the pdb files without header. It is really strange that only this specific file has the problem, while there seems to be nothing special for this pdb file.

**Comment by smliu1997** [comment]
Also I just tried adding a header to the file. I added such a header at the first line "HEADER    PROTEIN                 30-APR-01" but still mdtraj only found 188 atoms

**Comment by smliu1997** [comment]
Ok I think I know what goes wrong. It is not related to the header. In the original pdb file atom 43 and 44 (residue named AGLU and BGLU) are weird and recognized as 1 atom. I will check the original pdb file, and mdtraj is fine.

**Comment by smliu1997** [comment]
Also even if in principle having a header in pdb is formal, I think in some cases if people use some scripts to pick out or write pdb files, they don't add header (I don't have this habit, I saw other people's code also do not write header for pdb). I think mdtraj is working well to read pdb without header, and I think it should be able to do that.

**Comment by sukritsingh** [comment]
> In the original pdb file atom 43 and 44 (residue named AGLU and BGLU) are weird and recognized as 1 atom. 

In some PDB crystal structures, residues annotated as AGLU and BGLU like that usually indicate two alternative conformations of the same residue from the X-ray density data. It may be worth revisiting your initial structure and identifying which of those conformations to keep.
