### ISSUE TITLE
Release 1.10.1

### ISSUE THREAD

**Issue by mattwthompson** [mdtraj/mdtraj#1926]
Now that I've pushed #1904 ahead without an external review, I think we're ready to look at making a 1.10.1 release. Anybody need to sneak something in? Otherwise I think this should be similar to 1.10.

I don't think there are any changes we want to, or could, make to Python compatibility.

There's been a couple stabs at updating for Cython 3.x but I don't think they're complete just yet.

Anything else I'm forgetting?

**Comment by jeremyleung521** [comment]
https://github.com/mdtraj/mdtraj/pull/1833 `cibuildwheels`? I could help build wheels manually like last time if we don't want to rush.

**Comment by mattwthompson** [comment]
I won't have more time for a few days but it looks likely we'll include #1917 and thereby actually be on Cython 3

**Comment by jeremyleung521** [comment]
Closing this because it's now released :)

For any future readers, make a new Issue or comment in the [discussions](https://github.com/mdtraj/mdtraj/discussions/1942) if needed.
