### ISSUE TITLE
superpose() doesn't apply the final translation

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#261]
If you superpose against a reference that isn't centered, the final coordinates are in the right rotational state, but they remain centered at the origin, not translated to sit on top of the reference.

**Comment by araabr** [comment]
Hi Robert,

When I do trajectory.superpose with a reference frame and with or without arom_indices, then check the xyz's before and after superpose they seem to be the same and it looks like superpose is not aligning trajectories... 

------
t=md.load(trajlist, top=topfile, stride=1)
ts = t.superpose(t, frame=0)
------

Thanks
Ara
