### ISSUE TITLE
Match fields in our HDF5 format with the AMBER NetCDF format

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#33]
@kyleabeauchamp: The AMBER NetCDF format is really intelligent. It has all the info you want in there, and it's very explicit about the format. It has places for a version tag, on the format, and for labeling what units things are in. These are all things that our HDF5 format lacks.

We should make a new version of our HDF5 format that formalizes it, and makes it match the AMBER NetCDF format as much as possible.

We should also do some performance benchmarks to check if we _really_ need our own proprietary format.

**Comment by hainm** [comment]
@rmcgibbo: mdtraj web says that netcdf in amber is twice "fatter" than xtc (and .h5) http://mdtraj.org/latest/hdf5_format.html 

But I think the netcdf in amber is built on top of hdf5, how the compression different?

(For my curiosity)

**Comment by rmcgibbo** [comment]
xtc and .h5 only store 16 bits per x/y/z coordinate.

**Comment by rmcgibbo** [comment]
Actually, I don't think .h5 uses 16 bits. But .xtc does and .lh5 does (but lh5 is deprecated).

**Comment by hainm** [comment]
So h5 and amber netcdf should have same size now? (sorry, i should save files and check myself but using phone now).

**Comment by rmcgibbo** [comment]
yeah, i think so.

**Comment by rmcgibbo** [comment]
or pretty close. it's not going to be exactly the same, because the compression is a little different. amber netcdf uses netcdf3, which is quite different than netcdf4 and doesn't use hdf5.

**Comment by hainm** [comment]
Thanks. G9.
