### ISSUE TITLE
Efficient loading of multiple frames from a single file

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#336]
Say you have a single file (e.g. xtc) that you want to load specific frames from. It would be nice to do this efficiently. Currently, you can use `md.open()` to get the XTCTrajectoryFile handle, which exposes the seek/tell methods you need. But you can't build a trajectory from the return value of XTCTrajectoryFile.read() without format-specific code, since different trajectory files give different return values from that method.

If you just want a _single_ frame from the file, `md.load_frame` will do this perfectly.

I think the ideal solution is to expand the range of types that allowed as input to `md.load_frame`. If, in addition to accepting a string as input it could also accept an open `XXXTrajectoryFile` handle, then I think you would be in business.

```
handle = md.open('path-to-file.xtc')
for index in indices:
    md.load_frame(handle, index, top=top)
```

cc: https://github.com/rmcgibbo/mixtape/pull/53

**Comment by synapticarbors** [comment]
+1

**Comment by mpharrigan** [comment]
cc #1038
