### ISSUE TITLE
Add support for Desmond .dtr trajectory files

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#361]
The source distribution for vmd 1.9.1 includes `plugins/molfile_plugin/src/dtrplugin.cxx` which is licensed under the BSD 3-clause, and would be suitable for inclusion in MDTraj. Note that inclusion of dtrplugin.cxx means that compiling MDTraj will require a C++ compiler in addition to a C compiler, but I don't think that's too bad.

This isn't particularly high priority for me (I don't use desmond). But if you do, speak up.

**Comment by mpharrigan** [comment]
Has this been done? #624

**Comment by rmcgibbo** [comment]
yeah.
