### ISSUE TITLE
Appending to DCD / HDF reporters

### ISSUE THREAD

**Issue by kyleabeauchamp** [mdtraj/mdtraj#441]
Should it be possible to append to DCD or HDF reporters?  I'm envisioning something like this:

```
try:
    with open(chk_filename, 'rb') as f:
        simulation.context.loadCheckpoint(f.read()) 
    print("Loaded %s" % chk_filename)
except IOError:
    pass

dcd_file = open(dcd_filename, 'a')  # Try to append
simulation.reporters.append(mdtraj.reporters.DCDReporter(dcd_file, output_frequency, atomSubset=atom_indices))
simulation.reporters.append(app.CheckPointReporter(open(chk_filename, 'w'), output_frequency, step=True, time=True, speed=True))
simulation.step(n_steps)

```

Basically, if we support an append mode, we can use the CheckPointReporter to autoresume and append to trajectories the way gromacs does.

**Comment by kyleabeauchamp** [comment]
Probably low enough priority to close this one...

**Comment by InfluenceFunctional** [comment]
@kyleabeauchamp just checking in - did this end up going somewhere? Functionality like what you described at the top would be great, if it exists.

**Comment by jgreener64** [comment]
Agree this would be great to have.
