### ISSUE TITLE
[WIP] lprmsd is systematically off

### ISSUE THREAD

**Issue by cxhernandez** [mdtraj/mdtraj#523]
I've been trying to implement my own version of the lprmsd k_centers algorithm, but I've found that `mdtraj.rmsd` is systematically off from the VMD implementation and a numpy implementation that I made.

In the image below you can see an rmsd plot with `mdtraj.rmsd` shown in blue, VMD in red, and numpy in green. Notice that the VMD and numpy implementations are overlapping:
![image](https://cloud.githubusercontent.com/assets/5142365/3804884/c384e77e-1c2c-11e4-8b38-e6a95f1aeced.png)

You can find an ipython notebook with all my data and code [here](https://www.dropbox.com/sh/67jvrfk9sv3dafi/AAAR4EG38--HamIgIaCfizyBa) in the 'lprmsd' folder.

**Comment by mchelem** [comment]
@cxhernandez Did you eventually find out what was causing the discrepancy? I am having a similar issue.

**Comment by cxhernandez** [comment]
@mchelem: It turned out that for my use case all I had to do was:

``` python 
# define standard RMSD fucntion (w/o rotation)
def rmsd(traj, ref, idx):
    return np.sqrt(np.sum(np.square(traj.xyz[:,idx,:] - ref.xyz[:,idx,:]),
                          axis=(1, 2))/idx.shape[0])

# superpose atomset 1
traj.superpose(ref, atom_indices=idx1)

# calculate RMSD for atomset 2
r = rmsd(traj, ref, idx2)
```

Where `idx1` is the set of atoms you want to align your trajectory to the reference, and `idx2` is the set of atoms for which you want to calculate the RMSD. 

I believe what was tripping me up before was that `md.lprsmd` would align to a subset but then calculate the RMSD for all atoms in the system, and  `md.rmsd` would calculate the RMSD for a subset of atoms but only after having superposed to all atoms in the system.

**Comment by Vinvin-Zhang** [comment]
# define standard RMSD fucntion (w/o rotation)
def rmsd(traj, ref, idx):
    return np.sqrt(**3***np.sum(np.square(traj.xyz[:,idx,:] - ref.xyz[:,idx,:]),
                          axis=(1, 2))/idx.shape[0])

why do you mutiple it by 3?
