### ISSUE TITLE
Refactor setup.py into multiple files

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#578]
In #577, and #573 today I had to modify `setup.py`, and realized that it's getting to be a bit of a mess. It's over 400 lines, and its becoming an unsightly mix of procedural code with some random functions and classes that monkey patch with the terminally-broken `distutils`. There's no way of getting *around* all of this monkey patching and complexity, but I think moving the functions into a separate file and importing them would be a good start.

**Comment by mpharrigan** [comment]
This has been done
