### ISSUE TITLE
Refactor _topology_from_subset

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#583]
From #579, it seems silly to me that we're going through a lot of hoops to have `_topology_from_subset` work for both the OpenMM topology object and the mdtraj Topology object. We have a `mdtraj.Topology.from_openmm` method which does the conversion anyways, so IMO we should encapsulate all of the conversion logic there, in one place. Each additional change to `md.Topology` makes maintaining `_topology_from_subset` harder.

Also, this should be coupled with #553, since that also moves part of the topology-manipulation complexity from being buried deep within the reporters code into the topology object itself.

**Comment by mpharrigan** [comment]
cc #1089
