### ISSUE TITLE
WebGL viewer passing numpy arrays as base64 strings

### ISSUE THREAD

**Issue by gabrielelanaro** [mdtraj/mdtraj#621]
Hi! I've been studying the code for the WebGL viewer, I would like to propose a strategy that could be implemented to improve the performance. 

The main bottleneck I found (for now) is the transferring of the numpy array of coordinates to/from javascript: https://github.com/SimTk/mdtraj/blob/master/MDTraj/html/trajectory_widget.py#L115
The coordinate array is handled recursively (float-by-float) by the underlying ipython machinery.
 
One alternative is to pass the numpy data as a base64 string. 

    >>> import base64
    >>> import numpy as np
    >>> base64.b64encode(np.array([0, 1, 2], 'int32'))
    'AAAAAAEAAAACAAAA'

We pass the string, along with shape/type information and then we decode it back from JS using the library https://github.com/niklasvh/base64-arraybuffer: http://jsfiddle.net/xnd4hkL3/

If you think that's a good idea I can write the code myself!

**Comment by mpharrigan** [comment]
cc #1022
