### ISSUE TITLE
`is_protein` fails for nonstandard residue names

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#637]
For example, `ASH` = protenated Asp and `CYP` = palmitoylated Cys were not recognized as "protein" residues and were not included in my featurization. `HIP` = protenated HIS worked, however. I see there is an alias for this defined in `pdb/data/pdbNames.xml`

Possible fixes:
 1. Add aliases for every conceivable residue name in `pdbNames.xml`
 2. Switch logic of `is_protein`. e.g. VMD looks for any residue which contains atoms named `C, N, CA, O` ref: http://www.ks.uiuc.edu/Research/vmd/vmd-1.3/ug/node133.html

**Comment by synapticarbors** [comment]
I'll add that I just stumbled across this issue when dealing with histidine naming conventions from NAMD/CHARMM (i.e. `HSD`, `HSE`).

**Comment by kyleabeauchamp** [comment]
I vote to postpone this because it is related to a longer-term discussion of how to best maintain compatibility between code that is duplicated in OpenMM and mdtraj (e.g. topology and PDB parsers)

**Comment by mpharrigan** [comment]
Sure.

This issue should be kept open, though

**Comment by cxhernandez** [comment]
https://github.com/mdtraj/mdtraj/pull/871 might help with this to some extent, since `residues.py` has been updated to include all residues found in the PDB.

**Comment by mpharrigan** [comment]
fixed in #871
