### ISSUE TITLE
Disable default replacement of non standard water names?

### ISSUE THREAD

**Issue by HubLot** [mdtraj/mdtraj#638]
Hi,

By default, when you load a pdb, the non standard water residues and water atoms are replaced by the standard ones. 
In my case, *SOL* --> *HOH* for the residue and *HW1*, *HW2*,*OW* --> *H1*, *H2*, *O*.
Is it possible to bypass this behavior?
Although it's useful in most of the cases, it becomes unhandy when you dealing with different forcefields and/or MD software. For example, I'm using charmm forcefield with Gromacs and I need to keep the water residus and atoms names that way (SOL, HW1, ...) so I can re-use my PDB later for new MD.

Thanks.

**Comment by gVallverdu** [comment]
Hello
Did you do something about this issue ?
I see it is closed but was a decision taken about this ?
Thanks
Germain
