### ISSUE TITLE
Performance degrading when using NetCDFReporter

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#643]
I wanted to report a performance issue I've observed when using the `NetCDFReporter` in some recent simulations I've run. The machine is running Centos 6.5 with 4xGTX680 and using the latest version of mdtraj from pip (1.0.0) and OpenMM (6.1.0.dev-c4acc7d).

I'm running the wca-dimer model from John Chodera in a little custom app script that I wrote. I've included all of the code in the following gist:
https://gist.github.com/synapticarbors/2cfceba28d4674d81989

Instructions for re-creating the issue with the code come at the end of this.

Basically, when I run the `NetCDFReporter` and look at output from the  `app.StateDataReporter`, I see performance start out at about 2.8E3 ns/day. After running for about 5-10 minutes, the performance decreases constantly over the run to about 760 ns/day.

As a point of reference, when using the `HDF5Reporter` and leaving everything else unchanged, in concert with the `app.StateDataReporter`, I see initial reports of achieving 2.62E3 ns/day, which over the same simulation time decreases to about 2.34E3 ns/day. It's unclear to me without a bit more digging whether the `HDF5Reporter` is also slowly decreasing in performance or if the performance is just converging given additional statistics. With no trajectory reporter, I consistently get about 3.7E3 ns/day. I realize that the 250 time step interval between trajectory writes is incurring non-negligible overhead, but I'm not as concerned about that right now.

To run the test, first generate the initial coords:

```bash
python gen_bstate.py
```

There are a few cmd line options which should be trivial to select.

Then run the app:

```bash
python openmm_app.py -c bstates/init_coords_a.npy -s system.xml -i integrator.xml -d 0 -w 250 -o bf_test/test_nc -n 2500000 &>bf_test/test_nc.log
```

I switched the trajectory reporter by just commenting/uncommenting the appropriate line.

**Comment by rmcgibbo** [comment]
I'm going to close this, since I'm not sure what we can do about it.

**Comment by rmcgibbo** [comment]
Feel free to reopen.

**Comment by swails** [comment]
Does `netCDF4` have the same degradation?  Or `Scientific.IO.NetCDF`? (unlike scipy, those are linked against the NetCDF libs)

**Comment by swails** [comment]
ParmEd can use all 3 backends, so I'll look into it when I get some time
