### ISSUE TITLE
issue with compute_distances

### ISSUE THREAD

**Issue by TensorDuck** [mdtraj/mdtraj#654]
Found that compute_distances results are inconssitent with distance calculations from VMD. Checked for multiple frames.
Also found that the xyz coordinates loaded in for the trajectory are 100% correct. Using the xyz values to calculate the pair distance between results in the correct pair distances, again checked for multiple trajectories.

Not sure why I have this bug. Did I miss something?

**Comment by rmcgibbo** [comment]
Closing this, since it appears resolved.
