### ISSUE TITLE
Number of residues wrong

### ISSUE THREAD

**Issue by kyleabeauchamp** [mdtraj/mdtraj#658]
This is with one of the DESRES HP35 PDBs: https://gist.github.com/kyleabeauchamp/8c3e9d6c4ad27c3e0aa8

```
In [1]: import mdtraj as md

In [2]: t = md.load('./native.pdb')

In [3]: t
Out[3]: <mdtraj.Trajectory with 1 frames, 577 atoms, 70 residues, and unitcells at 0x7f086f681fd0>
```

**Comment by rmcgibbo** [comment]
I don't think there's an mdtraj problem here. The pdb file has each residue listed twice, first in acending order, and then on line 288 it repeats and lists all the residues again.

https://gist.github.com/kyleabeauchamp/8c3e9d6c4ad27c3e0aa8#file-native-pdb-L286-L290

**Comment by kyleabeauchamp** [comment]
wontfix

**Comment by juanmit** [comment]
So, does it affect the results when to calculate the distances ?  I met an error with a similar file(ascending order --> repeats) 
The error is warnings.warn("WARNING: two consecutive residues with same number.

Thanks for helping.
