### ISSUE TITLE
Expand documentation of testing style / idiom

### ISSUE THREAD

**Issue by kyleabeauchamp** [mdtraj/mdtraj#674]
So our testing style guide is a bit sparse (http://mdtraj.org/latest/style.html) for new users to pick up on how we do things.  E.g. things like writing small, self-contained functions as tests whenever possible.  Catching corner cases.

**Comment by rmcgibbo** [comment]
+1 to adding stuff.

Some of the comments you made on the pymbar thread could be adapted, or we might be able to find some relevant open source narrative description of testing style on python.org/sklearn/astropy/etc.
