### ISSUE TITLE
Webpage examples missing?

### ISSUE THREAD

**Issue by swails** [mdtraj/mdtraj#675]
Is it just my browser, or are all of the examples in the mdtraj webpage missing?

For example: http://mdtraj.org/latest/examples/atom-selection.html just shows a blank page with a title.  Same with every other page except the "introduction" tab...

**Comment by kyleabeauchamp** [comment]
Same issue here

**Comment by rmcgibbo** [comment]
Good spot. Probably a new version of something. The code for building the
examples docs in the msmbuilder repo is a little bit more advanced right
now, so maybe we can port that over.

**Comment by rmcgibbo** [comment]
Fixed now.
