### ISSUE TITLE
shiftx2 problems

### ISSUE THREAD

**Issue by vvoelz** [mdtraj/mdtraj#692]
Looks like mdtraj-0.9.1 (is this is latest version? hard for me to tell) doesn't work with the latest version of SHIFTX2 v1.08, released July 2014.     I downloaded the earlier version of SHIFTX2 v1.07, released Jan 2012, and it seems to work fine.  I think there are new filename extensions and internal text format of output files in v1.08 that is messing the mdtraj wrapper scripts.

Just though you'd like to know.  In any case, there is no mention of what SHIFTX2 versions are compatible with mdtraj on the web documentation.  That might be a good thing to include.

--Vince

**Comment by kyleabeauchamp** [comment]
You should upgrade mdtraj to 1.2

**Comment by rmcgibbo** [comment]
It looks like the tests run against shiftx2-v107-20120106. MDTraj versions
are here: https://github.com/mdtraj/mdtraj/releases, or
https://binstar.org/omnia/mdtraj/files. The dropdown menu on mdtraj.org
should also show the version numbers.

**Comment by vvoelz** [comment]
The only versions I see in the drop down menu says “latest”


I’ll update to v 1.2 as kyle suggests!

**Comment by rmcgibbo** [comment]
(I don't think there has been any change to the nmr module since 0.9.1, but still good to upgrade).

**Comment by rmcgibbo** [comment]
Does the version selector  dropdown menu not show up in your browser though? E.g

![untitled](https://cloud.githubusercontent.com/assets/641278/5750384/248fe3dc-9c09-11e4-8aa0-080612c27651.png)

**Comment by vvoelz** [comment]
What the hell?  Now it works!  I’m using Safari 7.1.   No doubt browser weirdness on my end :)    —Vince

**Comment by rmcgibbo** [comment]
I fixed it a couple weeks ago (it definitely used to be broken). Your browser might have had an old version in the cache. Glad to know its working now :)

**Comment by rmcgibbo** [comment]
It looks like the `-b` batch mode is broken in shiftx2 1.0.8
```
$ ~/miniconda/bin/python /Users/rmcgibbo/Downloads/shiftx2-v108-mac-20140707/shiftx2.py -b 'MDTraj/testing/reference/2E*.pdb'
## SHIFTX2 Ver 1.08 (Released July 7, 2014) ##
cp: None: No such file or directory
Traceback (most recent call last):
  File "/Users/rmcgibbo/Downloads/shiftx2-v108-mac-20140707/shiftx2.py", line 778, in <module>
    tempinfile = tempfolder + os.path.basename(infile)
  File "/Users/rmcgibbo/miniconda/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by rmcgibbo** [comment]
This is fixed now.

**Comment by cing** [comment]
I just reported the broken batch problem to the Wishart lab. Maybe there should be a little warning in the docs to use ShiftX2 1.07 until they fix the latest version?
