### ISSUE TITLE
Sidechain and backbone selection not working

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#695]
Maybe I'm misunderstanding something about the selection DSL, but I think that the `sidechain` and `backbone` keywords are not working properly:

```python
In [3]: import mdtraj as md
In [4]: from mdtraj.testing import get_fn

In [5]: t = md.load(get_fn('2EQQ.pdb'))
In [6]: t.atom_slice(t.top.select('backbone'))
Out[6]: <mdtraj.Trajectory with 20 frames, 423 atoms, 28 residues, without unitcells at 0x10a74a390>

In [7]: t.top.select('backbone').shape
Out[7]: (423,)

In [8]: t.top.select('all').shape
Out[8]: (423,)

In [9]: t.top.select('sidechain').shape
Out[9]: (423,)

In [10]: t.top.select('name C or name CA or name N or name O').shape
Out[10]: (112,)
```

It appears as if with either keyword, you're just getting back all of the atom indices. I'm running this off of master but it was also in the 1.2 release on Omnia. I don't believe there are any tests that would have caught this.

**Comment by kyleabeauchamp** [comment]
Looks like a bug to me

**Comment by synapticarbors** [comment]
The following line also looks suspect:

https://github.com/mdtraj/mdtraj/blob/master/MDTraj/core/selection.py#L107

It appears as if `is_sidechain` is being mapped to the same expression as `is_backbone`.

**Comment by kyleabeauchamp** [comment]
Looks like the culprit

**Comment by synapticarbors** [comment]
That's definitely one problem

```
In [20]: t.topology.select_expression('backbone')
Out[20]: '[atom.index for atom in topology.atoms if atom.is_backbone]'

In [21]: t.topology.select_expression('sidechain')
Out[21]: '[atom.index for atom in topology.atoms if atom.is_backbone]'
```

but that's not the whole thing as:

```
[atom.index for atom in topology.atoms if atom.is_backbone]
```

also give you all of them atoms instead of just the backbone ones.

**Comment by synapticarbors** [comment]
Something is going wrong in the list comprehension that I'm not entirely understanding:

```
In [28]: [(atom.index, atom.is_backbone()) for atom in t.topology.atoms if atom.is_backbone]
Out[28]:
[(0, True),
 (1, True),
 (2, True),
 (3, True),
 (4, False),
 (5, False),
 (6, False),
 (7, False),
 (8, False),
 (9, False),
 (10, False),
 (11, False),
 (12, False),
 (13, False),
 (14, False),
 (15, False),
 (16, False),
...
(417, False),
 (418, False),
 (419, False),
 (420, False),
 (421, False),
 (422, False)]
```

The logic of `is_backbone` is working, but the if-statement isn't filtering the comprehension.

**Comment by synapticarbors** [comment]
Nevermind, I see it now. `is_backbone` a method and not a property.

**Comment by synapticarbors** [comment]
Ok, I can make a PR that fixes this:

1. Fix the `is_sidechain` expression mapping
2. Change `is_backbone` and `is_sidechain` to properties
3. Write appropriate tests.

**Comment by mpharrigan** [comment]
That would be fantastic

**Comment by rmcgibbo** [comment]
Fixed, I think. Thanks @synapticarbors (#696).
