### ISSUE TITLE
Pre-compile NMR codes on travis

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#699]
Travis spends a non-trivial amount of time compiling the shiftx2 and sparta+ NMR codes on every PR. Precompiling them and then stashing them somewhere could be a win.

**Comment by kyleabeauchamp** [comment]
Yeah, could probably build a conda package

**Comment by rmcgibbo** [comment]
This is done now for shiftx2. Not in a pretty way, but w/e.
