### ISSUE TITLE
[FR] Superpose based on selection string rather than atom index

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#702]
The current `superpose` method is somewhat rigid in that it assumes that the reference and trajectory have the same atom indexing. That is the `atom_indices` keyword takes a set of indices and applies them identically to both the reference and trajectory. I can imagine instances where you have an xtal structure without hydrogens or some other model that you want to use as a reference, and there will not be a one-to-one mapping between specific atom identities and the atom indexing. 

Instead I propose that `atom_indices` be replaced with an atom selection. The selection would be applied to both the trajectory and the reference and if the length of the two resulting atom index lists are not identical, then an error is raised (This is basically how VMD handles things). You have to still be a little careful about the ordering of atoms though. I guess an additional check could be made to ensure that the element list or atom names were the same.

**Comment by kyleabeauchamp** [comment]
So we might also look into how the superposition and alignment stuff works in similar packages, such as mdanalysis.  I think we have mostly punted on a refactor / cleanup of this stuff.

**Comment by synapticarbors** [comment]
Here's MDAnalysis's alignment function argument signature:

http://mdanalysis.googlecode.com/svn/trunk/doc/html/documentation_pages/analysis/align.html#MDAnalysis.analysis.align.rms_fit_trj


>select
1. any valid selection string for selectAtoms() that produces identical selections in mobile and reference; or
2. a dictionary {'mobile':sel1, 'reference':sel2} (the fasta2select() function returns such a dictionary based on a ClustalW or STAMP sequence alignment); or
3. a tuple (sel1, sel2)
When using 2. or 3. with sel1 and sel2 then these selections can also each be a list of selection strings (to generate a AtomGroup with defined atom order as described under Ordered selections).

**Comment by rmcgibbo** [comment]
There are a lot of different ways to do it. Not sure whats best.
 - `atom_indices` has the advantage of being very flexible, but a little low level. atom selections are easier to use, but less flexible. being able to allow both seem likes an advantage.
 - we don't currently have a Trajectory-level API that lets you specify different indices for `self` and reference.
   * this could be done by letting you pass in two pairs of `atom_indices`
   * or two atom selection strings
   * or one atom selection string thats applied to both topologies.

**Comment by synapticarbors** [comment]
@rmcgibbo I think having the flexibility to specify a set of indices or a selection string would be nice. An API that allows for all three inputs seems good. In any of these cases, there could be a reasonable set of checks made to ensure that the operation is feasible and/or reasonable. At the very least, a check for having the same number of atoms in each selection should be done. Then it's debatable if you want to raise an error (or issue a warning) if the underlying atom identities don't match in the two selections.

Either way, I think increasing the flexibility of the method is important as the use case is a fairly routine operation that people do.

PS - I'm enjoying working with mdtraj quite a bit. Just converted a bunch of Anton data to the new .h5 format. Previously I had a custom h5py solution that borrowed a python molfile wrapper from an older version of DE Shaw's [TimeScapes](http://timescapes.biomachina.org/) package to get at the trajectory data. h5py was nice because it has the HDF5 scale/offset compression filter, but I didn't have a good topology solution and had a complex process to get from array indices to residue and atom identities, and visualizing the trajectories was also problematic and required some laborious steps. mdtraj really fixed a lot of those issues.

**Comment by rmcgibbo** [comment]
Glad to hear that things are working well for you. Maybe we could incorporate some of those tricks to reduce file size into the .h5 format? I think rounding the coordinates to the nearest ~0.001A, especially if done in way thats aware of the bitwise aspects of float32 storage, can help something like zlib get better compression out of the arrays. (https://github.com/mdtraj/mdtraj/issues/287) But there's probably a lot ore that could be done too.

**Comment by synapticarbors** [comment]
In my recent code with mdtraj, I used the `quantize` method from PyTables as was suggested in https://github.com/mdtraj/mdtraj/issues/287 and in a gist of your's that I stumbled upon.

**Comment by rmcgibbo** [comment]
What kind of file size reduction did you get?

**Comment by synapticarbors** [comment]
So for one of the Anton stk files, the entire `workdir` was 5.2 GB. I took a subset of the atoms dropping the total from 90610 to 58985. The resulting .h5 file using the `quantize` (`least_significant_digit=3`) pre-processor was 1.6 GB. Without `quantize` the .h5 file was 2.8 GB. Given just the reduction in atoms, I would expect the Anton trajectory size to have dropped to 3.4 GB.

**Comment by mpharrigan** [comment]
We have the ability to specify different indices for reference and the trajectory, and I don't think we're going to modify the api to take in selection strings directly. Use `topology.select()`
