### ISSUE TITLE
Enhance PSF parser

### ISSUE THREAD

**Issue by swails** [mdtraj/mdtraj#711]
Right now, the PSF parser works like the Amber prmtop parser -- it just dumps everything into the same chain and numbers residues (and atoms) sequentially.  This is fine for most functionality, but it might be helpful to CHARMM/PSF users if more of the information in the PSF file made its way into `Topology`.

**Comment by rmcgibbo** [comment]
In particular, the re #710, the psf file contains residue numbers which are currently not included in the topology, but could be added as `resSeq` entries.

**Comment by swails** [comment]
> In particular, re #710, the psf file contains residue numbers which are currently not included in the topology, but could be added as resSeq entries.

Right, and SEGID -> chains

**Comment by swails** [comment]
Implemented by #735

**Comment by rmcgibbo** [comment]
Done.
