### ISSUE TITLE
Bug in lengths_and_angles_to_box_vectors()

### ISSUE THREAD

**Issue by peastman** [mdtraj/mdtraj#713]
I believe line 87 of unitcell.py is incorrect.  It currently reads

    cy = c_length*(np.cos(alpha) - np.cos(beta)*np.cos(gamma))

I think it should be

    cy = c_length*(np.cos(alpha) - np.cos(beta)*np.cos(gamma))/np.sin(gamma)

You can see why that must be true be calculating dot(b,c)/(b_length*c_length).  The result *ought* to be cos(alpha).

**Comment by swails** [comment]
I was actually *just* looking at this.  I believe you're right.

**Comment by rmcgibbo** [comment]
It looks like the tests for that method are basically nonexistent. We should be testing the round-tripping of `lengths_and_angles_to_box_vectors` and `box_vectors_to_lengths_and_angles`.

**Comment by swails** [comment]
> It looks like the tests for that method are basically nonexistent. We should be testing the round-tripping of lengths_and_angles_to_box_vectors and box_vectors_to_lengths_and_angles.

Agreed.  This morning I tried round-tripping for a truncated octahedron, and gamma came out to like 107 degrees (the others were 109 degrees, as they should be).

**Comment by swails** [comment]
Correction: alpha came out wrong.
