### ISSUE TITLE
license for `html` package

### ISSUE THREAD

**Issue by hainm** [mdtraj/mdtraj#715]
Hi all,

I am also developing a package called pytraj, which is a wrapper for cpptraj in AMBER. (https://github.com/pytraj/pytraj).

mdtraj has very nice feature for viewing molecule with ipython-notebook (http://nbviewer.ipython.org/github/kyleabeauchamp/mdtraj/blob/master/examples/WebGL-Viewer.ipynb).

I am thinking about "stealing" its code for `pytraj` but I am not so sure about its licences. For other files in mdtraj, the developers explicitly copy the notice in the header of each file but not those in ./MDtraj/html folder (except external codes in ./MDtraj/html/static). Would you mind adding info to those? (or may be I miss something) Thanks.

Hai

**Comment by rmcgibbo** [comment]
Unless otherwise specified in the file, it's all LGPLv2 or later.

**Comment by hainm** [comment]
thx.

Hai

**Comment by rmcgibbo** [comment]
Also, there are still some issues with the topology translation from python to javascript -- for proteins with nonstandard amino acids and stuff, the webgl thing breaks for certain views. I think it uses the atom name 'CA' to draw the ribbon, and doesn't behave nicely if a residue doesn't have one. At some point I'll get around to fixing that...

**Comment by rmcgibbo** [comment]
If you end up making some improvements to that code, I'd love to roll it back in.

**Comment by cxhernandez** [comment]
@gabrielelanaro has also optimized the trajectory viewing portion bit as well in [chemview](https://github.com/gabrielelanaro/chemview). It's missing a lot of the different protein representations, but it's been on my TODO

**Comment by rmcgibbo** [comment]
Closing this.
