### ISSUE TITLE
[FR] implicit or to select atoms from a list

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#723]
Unless I'm missing some undocumented trick, if I want to make a selection based on a list of resids, I would need to write something like:

```
sel = traj.top.select('protein and heavy and (resid 12 or resid 17 or resid 21 or resid 35 or resid 36 or resid 39 or resid 204 or resid 207 or resid 208 or resid 210 or resid 211 or resid 212 or resid 242 or resid 372 or resid 376)')
```

it would be nice to have the ability to use a VMD-style implicit `or` and write the selection more compactly as:

```
sel = traj.top.select('protein and heavy and resid 12 17 21 35 36 39 204 207 208 210 211 212 242 372 376')
```

**Comment by mpharrigan** [comment]
We could probably introduce something like `"resid in 12 17 21"` where `in` would be treated like `gt`, `eq` etc and uses the python `in` operator.

In the mean time, you can use python selection
```
[a.index for a in topology.atoms if a.residue.is_protein
                             and a.is_heavy
                             and a.residue.resSeq in [12, 17, 21]]
```

**Comment by mpharrigan** [comment]
This is beyond the scope of the atom selection language for now
