### ISSUE TITLE
'heavy' selection does not match docstring

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#727]
The docstring for `select_atom_indices` states that the `heavy` selecton keyword returns:

>   All non-hydrogen atoms that are not symmetry equivalent. By
>   symmetry equivalent, we mean atoms identical under an exchange
>   of labels. For example, heavy will exclude the two pairs of
>   equivalent carbons (CD, CE) in a PHE ring.

However the [code](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L888) only selects non-hydrogen protein atoms:

```python
        elif selection == 'heavy':
            atom_indices = [a.index for a in self.atoms if
                            a.element != elem.hydrogen
                            and a.residue.is_protein]
```

**Comment by kyleabeauchamp** [comment]
See #736
