### ISSUE TITLE
[FR] Atom select check for valid keywords

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#728]
I think it would improve user experience and reduce silent errors if the selection DSL did some checking for valid keywords:

```python 
In [43]: traj.top.select('protein').shape
Out[43]: (7705,)

In [44]: traj.top.select('protein and heavy').shape
Out[44]: (7705,)

In [45]: traj.top.select('protein and dog').shape
Out[45]: (7705,)
```

**Comment by swails** [comment]
> In [45]: traj.top.select('protein and dog').shape
> Out[45]: (7705,)

I suspect all the atoms in your system *would* actually be present in a dog, though...

**Comment by ctk3b** [comment]
> I suspect all the atoms in your system would actually be present in a dog, though...

Definitely a feature. Have you tried "protein and rock"?

**Comment by swails** [comment]
> Definitely a feature. Have you tried "protein and rock"?

Psh.  Stop thinking small.

```Python
In [46]: traj.top.select('protein and mars').shape
Out[46]: (7705,)
```

Sounds like a Science paper to me.  "**Proteins found on Mars!**"

**Comment by synapticarbors** [comment]
@swails Stop thinking small.

```python
In [46]: traj.top.select('protein and god').shape
Out[46]: (7705,)
```

**Comment by swails** [comment]
Good luck publishing *that* in *Science*...

**Comment by mpharrigan** [comment]
Nice find. It is parsing random strings as literals

**Comment by rmcgibbo** [comment]
Fixed.
