### ISSUE TITLE
1.3.0 Release Timeline

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#732]
Does anyone have strong opinions about a timeline for a 1.3.0 release? We've generally been releasing every 2-3 months and ~100-200 commits to master, so we're getting to a good time. 1.2.0 was released close to 3 months ago.

Below is the list of PRs merged since 1.2.0. It's nothing too major, but there are some good new features like `compute_rdf` from @ctk3b, a bunch of functions for thermodynamic properties from @kyleabeauchamp, and a fair number of bug fixes, warts fixed, and improvements to the docs.

Is there anything particularly urgent on the issue tracker that we should prioritize beforehand?

```
PR #731: Update analysis.rst
PR #730: Update rdf.py
PR #724: [ENH] compute RDF
PR #729: [ENH] Don't allow bare literals in selection expressions
PR #726: Add n_bonds convenience function to topology
PR #725: Refactor and fix .gitignore(s)
PR #722: Fix gro loading for issue 721
PR #720: Update new_to_python.rst
PR #719: Update new_to_python.rst
PR #718: [DOCS] Help! How do I get started?
PR #714: Bugfix for utils.unitcell.length_and_angles_to_box_vectors
PR #709: Update MANIFEST.in
PR #703: [WIP] fix #701
PR #708: Move scripts directory
PR #707: Allow numbers in literals, but not in 1st character
PR #704: compute_neighbors was missing in docs
PR #698: [MAINT] Simplify travis setup and make the project layout more cannonical
PR #700: Added additional aliases for HIS
PR #697: Typo in mdcrd.py
PR #696: Fixed bugs in backbone and sidechain selection
PR #694: version number to 1.3.0.dev0
PR #691: Include tip3 water
PR #690: typo atom_selection.rst
PR #689: Fix edit on GH link
PR #688: SSE3
PR #687: Docs for thermodynamic quantities
PR #685: Test PSF Fix
PR #684: PEP440 version number
PR #680: scikit-learn is needed for the PCA notebook
PR #679: Include nitrogen atoms as h-bond acceptors
PR #681: Updat to test_bonds.py that accepts N as acceptor
PR #678: [MAINT] Example docs + version dropdown
PR #677: update version number in conda-recipe
PR #642: [WIP] Add some calculations of static dielectric and other stat. mech quantities...
PR #671: Fix docs push to s3
PR #668: 100K atom fix to PDB parser
```

**Comment by mpharrigan** [comment]
+1 release every 2-3 months

**Comment by kyleabeauchamp** [comment]
Couple of thoughts on my end:

1.  When OpenMM 6.3 hits beta, we want to run through some compatibilty tests with the cycle of topology conversions
2.  I may want to adjust the API for some of the thermodynamic quantities after a wednesday morning meeting where I look at different methods for estimating errorbars.

**Comment by rmcgibbo** [comment]
1. Good point. There were a couple of changes to the OpenMM topology in the current master. We should make sure that we're in sync with them.
2. Do the routines for the thermodynamic quantities currently return any error bars?

**Comment by kyleabeauchamp** [comment]
re number (2).  Currently, no. The issue is that error bars will depend on the statistical inefficiency, so I need to work through the best way to expose the necessary parts for running things through pymbar.timeseries.

**Comment by rmcgibbo** [comment]
Okay, we might be able to hold that off then, I'm not sure. IMHO there are still some significant questions about the different integrated autocorrelation time estimators. Especially if there are questions there, and some packaging / software engineering questions about whether mdtraj should dependent on pymbar, or if that code should be ported / copied / etc -- we might be better off releasing 1.3.0 first and then deciding these questions later.

I opened #733 for the other issue you raised. If anyone can think of other issues that might be release blockers, go ahead and open an issue with the 1.3.0 milestone tag, or add that tag to an issue that's already open.

**Comment by kyleabeauchamp** [comment]
Sounds good

**Comment by rmcgibbo** [comment]
Would there be any objections to me cutting the release right now?

**Comment by mpharrigan** [comment]
No objection

**Comment by kyleabeauchamp** [comment]
no objection

**Comment by rmcgibbo** [comment]
Done.

**Comment by kyleabeauchamp** [comment]
PS: regarding the error estimates thermodynamic quantities, I've found a nice library that implements several of the most common block bootstrap estimators.  AFAIK, their implementation is sufficiently general to handle Trajectory objects and arbitrary functions acting on them.  Could be useful for the HMC code as well, thought I'd share a snippet:

```
bootstrap = arch.bootstrap.CircularBlockBootstrap(block_length, traj=traj)

def bootstrap_func(traj):
    return md.geometry.static_dielectric(traj, charges, temperature)

results = bootstrap.apply(bootstrap_func, num_bootstrap)
epsilon_err = results.std()
```

**Comment by rmcgibbo** [comment]
also there's https://github.com/cgevans/scikits-bootstrap

**Comment by kyleabeauchamp** [comment]
Arch is maintained by a professor of econometrics and also seems to be pretty feature complete for time series stuff:

http://arch.readthedocs.org/en/latest/bootstrap/timeseries-bootstraps.html

**Comment by rmcgibbo** [comment]
Cool. Thanks for the link.
