### ISSUE TITLE
is capi/test_capi needed?

### ISSUE THREAD

**Issue by pfrstg** [mdtraj/mdtraj#756]
In getting mdtraj running at Google, I realized I did not make an equivalent of
```
   libtheobald = StaticLibrary(
        'mdtraj.core.lib.libtheobald',
        sources=[
            'mdtraj/rmsd/src/theobald_rmsd.c',
            'mdtraj/rmsd/src/center.c'],
        include_dirs=[
            'mdtraj/rmsd/include'],
        export_include=['mdtraj/rmsd/include/theobald_rmsd.h',
                        'mdtraj/rmsd/include/center.h'],
        # don't enable OpenMP
        extra_compile_args=(compiler.compiler_args_sse2 +
                            compiler.compiler_args_sse3 +
                            compiler.compiler_args_opt))
```

Or put anything in core/lib for that matter.

The only test that appears to fail is test_capi and the only reference to capi is that test and the `__init__.py`

What is all this for? Is it needed?

**Comment by kyleabeauchamp** [comment]
AFAIK it's used in MSMBuilder: https://github.com/msmbuilder/msmbuilder/search?utf8=%E2%9C%93&q=capi

**Comment by kyleabeauchamp** [comment]
https://github.com/msmbuilder/msmbuilder/blob/master/setup.py#L146

**Comment by kyleabeauchamp** [comment]
And `msmbuilder.libdistance` provides the engine for calculating pairwise distances for use in various clustering algorithms.

**Comment by pfrstg** [comment]
If it's just for msmbuilder, shouldn't it be moved there?

**Comment by kyleabeauchamp** [comment]
I think the issue is that we need a C-level API for various MDTraj functions that MSMBuilder can use for structure featurization, so it's not as simple as just moving everything to MSMBuilder.  @rmcgibbo knows more about the design vision here.

**Comment by rmcgibbo** [comment]
> In getting mdtraj running at Google, I realized I did not make an equivalent of...

I'm not sure that I quite understand.

Are you using a different build process than the `setuptools` / `distutils` build in our `setup.py`/`basesetup.py` file? Do you have a traceback or a build log, or can you share any of the details of your build system? 

Part of the "service" that `mdtraj` provides basically is a static library (`.a` / `.obj`) that implements the [rmsd calculation](http://en.wikipedia.org/wiki/Root-mean-square_deviation_of_atomic_positions). the `msmbuilder` project uses this to implement some clustering stuff without the performance overhead of python function calls, but I assume that other packages conceivably might want to use it too. To my knowledge, this is the fastest implementation of the rmsd calculation available in any package.

If you guys don't need this at google, there's no harm in skipping that part of the build, and ignoring the corresponding test failure.

**Comment by pfrstg** [comment]
Correct, we are using a different build process. We haven't talked about it too much publicly, but here's one abstract about it
http://www.cs.cornell.edu/Courses/cs7190/2012sp/retreat/field-abstract.html

AFAICT, this .a is just compiled into the 
msmbuilder.libdistance
extension. So as long as I get those linked together, it should work, right?

**Comment by rmcgibbo** [comment]
> AFAICT, this .a is just compiled into the  msmbuilder.libdistance extension. So as long as I get those linked together, it should work, right?

Yep.

And if you aren't using msmbuilder (or a different extension that also links against that `.a`), then you don't need this static library.

**Comment by pfrstg** [comment]
After successfully getting mdtraj to work, I am in the process of getting msmbuilder working :-)

**Comment by rmcgibbo** [comment]
Oh, cool!
