### ISSUE TITLE
Undefined symbol: GOMP_parallel

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#765]
Compiling master on biox3 with gcc 4.9.1 I get the following

```
>>> import mdtraj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harrigan/opt/miniconda3/envs/mdmsm/lib/python3.4/site-packages/mdtraj-1.4.0.dev0-py3.4-linux-x86_64.egg/mdtraj/__init__.py", line 49, in <module>
    from mdtraj._rmsd import rmsd
ImportError: /home/harrigan/opt/miniconda3/envs/mdmsm/lib/python3.4/site-packages/mdtraj-1.4.0.dev0-py3.4-linux-x86_64.egg/mdtraj/_rmsd.cpython-34m.so: undefined symbol: GOMP_parallel
```

**Comment by mpharrigan** [comment]
```
$ ldd _rmsd.cpython-34m.so 
        linux-vdso.so.1 =>  (0x00007fff2bdff000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007fafbb931000)
        libpython3.4m.so.1.0 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fafbb713000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fafbb37f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fafbb176000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e76e00000)
```

Probably not a good sign

**Comment by mpharrigan** [comment]
It works with the system gcc 4.4

Above I was `module load`ing gcc 4.9

**Comment by rmcgibbo** [comment]
If you compile with the gcc49 module, you might need to have that module
loaded when you run for the correct runtime libraries?

**Comment by mpharrigan** [comment]
I do

**Comment by mpharrigan** [comment]
This is probably a biox3 thing

**Comment by mpharrigan** [comment]
Works on ubuntu 14.10 with gcc 4.9

**Comment by swails** [comment]
The loader is configured to pull `/usr/lib64/libgomp.so` at runtime to resolve OpenMP symbols, whereas the GCC 4.9 OMP libs were used at compile time.

What is the output of `strings /etc/ld.so.cache | grep gomp`?  That should show you what shared objects were cached in the standard `ld` search path (or you could look at `/etc/ld.so.conf` to see the directories it is configured to search through).

I *think* that you can set `LD_LIBRARY_PATH` to override `/etc/ld.so.conf` -- so if you locate where the GCC 4.9 module stores its system libraries and add those to `LD_LIBRARY_PATH`, does that fix things?

**Comment by mpharrigan** [comment]
`module load` updates `LD_LIBRARY_PATH` with the 4.9 path
