### ISSUE TITLE
Is Travis *really* testing anything besides Python 2.7?

### ISSUE THREAD

**Issue by swails** [mdtraj/mdtraj#766]
I'm trying to do something similar to the build environment with ParmEd as what is being done here with mdtraj.  I can't seem to get Conda to test anything but Python 2.7, though, so I came back to the mdtraj Travis logs to see what was being done differently.

Unless I'm reading this wrong, the answer is "nothing", and what we think should be the Python 3.3 and 3.4 tests are in fact just using Python 2.7.

Here is a chunk of output from the install.sh part of a Python 3.3 build: https://travis-ci.org/mdtraj/mdtraj/jobs/54279404#L329-L341  -- isn't that saying that it's using Python 2.7?  What am I missing?

**Comment by kyleabeauchamp** [comment]
I think we previously solved this problem.  At this point, all testing happens through building the conda package, which includes a testing phase.  See the paste below from line 1610:

```
BUILD END: mdtraj-dev-1.4.0.dev0-np17py33_0

TEST START: mdtraj-dev-1.4.0.dev0-np17py33_0

Fetching package metadata: ..............

Solving package specifications: ...................

The following packages will be downloaded:

```

**Comment by ctk3b** [comment]
Are the lines you linked just the mini conda install? 3.3 gets installed later https://travis-ci.org/mdtraj/mdtraj/jobs/54279404#L474

**Comment by kyleabeauchamp** [comment]
Essentially, we're letting `conda-build` handle all the tricky py27 vs. py34 environment stuff, rather than keeping track of it ourselves.  This is particularly useful because it allows us to handle additional important library versions--e.g. notice that `np17` marker, which means we're building and testing against a particular numpy version.

**Comment by swails** [comment]
Right -- I was just looking at the miniconda install.  I was trying to see where the environment variables set in the `env` matrix were getting propagated to conda.  I'll keep looking.

Thanks!

**Comment by kyleabeauchamp** [comment]
https://github.com/mdtraj/mdtraj/blob/master/.travis.yml#L19

http://conda.pydata.org/docs/build.html#environment-variables-that-affect-the-build-process
