### ISSUE TITLE
Atom Selection DSL and chainID

### ISSUE THREAD

**Issue by pfrstg** [mdtraj/mdtraj#769]
From my reading of documentation/code, it doesn't look like the Atom Selection DSL includes the chainID.

Is this an oversight or is there any fundamental reason for this?

**Comment by mpharrigan** [comment]
Just an oversight. I can submit a PR later today to add it. 

Note that mdtraj just stores chain indices (0-indexed integer) and not the "names" (letters) that might be in a pdb.

**Comment by mpharrigan** [comment]
Added in #770
