### ISSUE TITLE
Inconsistencies between from_dataframe docstring and implementation

### ISSUE THREAD

**Issue by synapticarbors** [mdtraj/mdtraj#774]
Just playing around with the `Topology` `from_dataframe` method, I found a couple of issues related to inconsistencies between the docstring and the actual functionality:

- docstring says that `bonds` keyword argument is optional (defaults to `None`), but code raises a type error if `bonds` is not an instance of a `np.ndarray`.
- docstring says that the `serial` column must be specified in the dataframe, but the column check (https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L388) doesn't include it, so you get an error message that isn't particularly user friendly. 

Current workaround to the first issue if you have a system without bonds is just to pass in an empty numpy array.

**Comment by kyleabeauchamp** [comment]
See if #775 works for you
