### ISSUE TITLE
MDTraj + VMD Strange behavior

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#780]
I'm pulling a bunch of frames from a bunch of trajectories and combining them into one single trajectory (`dcd` format, topology is a `prmtop`). When I view the result in VMD ... it's very odd.

 1. "cartoon" doesn't work. `stride` fails with 
```
No hydrogen bonds found in /tmp/filedSFHt7
ERROR) Unable to find Stride output file: /tmp/filehsSZ1B
ERROR) Stride::read_stride_record: unable to read output file from Stride
ERROR) Call to Stride program failed.
```
 2. "cartoon" doesn't work in a very odd way. It makes a bunch of wispy curves along the backbone:
![wt2](https://cloud.githubusercontent.com/assets/4967059/6910671/205027f4-d70b-11e4-9dda-22bbb84f8046.png)

 3. "cpk" is weird too: All the atoms are really small. Their names and types appear normal.
![wt2](https://cloud.githubusercontent.com/assets/4967059/6910693/5cc750e0-d70b-11e4-804a-94f079650682.png)

 4. Saving as pdb instead breaks in a more understandable way: All the coordinates are centered around like 900 angstroms so the fields start overlapping.

 5. Loading the trajectories from which I am extracting the frames works normally (using the same `prmtop` files)

The script I'm using to pull structures is somewhat complicated (see next comment) and there is probably something subtly wrong with it, but I don't know why these symptoms are being observed.

**Comment by mpharrigan** [comment]
Here's the script:
https://gist.github.com/mpharrigan/61ce6cf4caab5dcd2398

Loading each frame as a "Trajectory" was slow and memory intensive, so I just load the relevant arrays and create the "Trajectory" objects at the end

**Comment by schwancr** [comment]
Maybe it's a unit problem? The bond lengths (from dcd coordinates) are just much bigger than the atomic radii (from atom type).

**Comment by mpharrigan** [comment]
Ooo maybe you're right

**Comment by mpharrigan** [comment]
Aha. When using `f.read()` manually, it doesn't convert to nm

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/dcd.pyx#L145

Thanks @schwancr !

**Comment by rmcgibbo** [comment]
I think this is in the docstring, right?
