### ISSUE TITLE
Create docs page about IPython notebook widget

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#790]
It should:
  - show off the feature with an interactive widget
  - document how to use the feature
  - list the required dependencies (ipython version, etc).

Getting the interactive widget running in the docs is a little tricky, because the widget model depends on having a running IPython kernel backend, so we have to work around that a bit.

**Comment by cxhernandez** [comment]
Get some still frames and pretend it's the real thing?
