### ISSUE TITLE
add unit (nm) in doc

### ISSUE THREAD

**Issue by hainm** [mdtraj/mdtraj#792]
Hi,

I am working on stealing mdtraj' objects to [pytraj] (https://github.com/pytraj/pytraj) and having hard time to assert the result (like comparing distances from mdtraj and pytraj calculation). It turned out that pytraj used Angstrom for unit and mdtraj use nm (?).

Since mdtraj targets wider audience, it's really great if you can add unit to the doc in method.

    Definition:  md.compute_distances(traj, atom_pairs, periodic=True, opt=True)
    Docstring:
    Compute the distances between pairs of atoms in each frame.

    Parameters
    ----------
    traj : Trajectory
        An mtraj trajectory.
    atom_pairs : np.ndarray, shape=(num_pairs, 2), dtype=int
        Each row gives the indices of two atoms involved in the interaction.
    periodic : bool, default=True
        If `periodic` is True and the trajectory contains unitcell
        information, we will compute distances under the minimum image
        convention.
    opt : bool, default=True
        Use an optimized native library to calculate distances. Our optimized
        SSE minimum image convention calculation implementation is over 1000x
        faster than the naive numpy implementation.

    Returns
    -------
    distances : np.ndarray, shape=(n_frames, num_pairs), dtype=float
        The distance, in each frame, between each pair of atoms.

**Comment by mpharrigan** [comment]
That function will use whatever units are used for `traj`, which is usually nanometers. This is in the docstring for `Trajectory`

http://mdtraj.org/latest/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory

**Comment by hainm** [comment]
thx. it's good to know.

Hai
