### ISSUE TITLE
Update bioRxiv manuscript

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#793]
1. The URL for the github repo in the availability section is outdated (points to simtk/)
2. *Many many citations are missing.* We originally left these out because of the 2 page limit for Bioinformatics, but I'm fine just leaving it on bioRxiv, in which case there is no page limit.
3. There are some embarrassing punctuation typos.
4. A couple features are missing that should be mentioned. For instance, the paper has a list of file formats that are supported, but isn't complete.

**Comment by cxhernandez** [comment]
I'm willing to help out! I think we should just update the paper– maybe elaborate on some features/examples– and then send it elsewhere. PLOS Computational Biology accepts [software articles](http://www.ploscollections.org/article/browseIssue.action?issue=info:doi/10.1371/issue.pcol.v03.i10), and I don't think we'd have to change our current format very much.

**Comment by mpharrigan** [comment]
lol at all the assignments

**Comment by cxhernandez** [comment]
Haha yeah.... I thought you could have multiple assignees

**Comment by kyleabeauchamp** [comment]
I'm also happy to take a pass of serious edits or reformats, just ping me.
