### ISSUE TITLE
What is `atom.serial`

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#800]
And how is it different than `atom.index`?

This doesn't seem to be documented anywhere

**Comment by rmcgibbo** [comment]
For the PDB format, it's supposed to be the number associated in the pdb file with the atom, called "serial" [here](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM). These aren't always contiguous or starting with zero.

**Comment by mpharrigan** [comment]
Maybe we can add at least a little comment in the code

**Comment by rmcgibbo** [comment]
+1
