### ISSUE TITLE
[FR] Interface with PyRosetta API

### ISSUE THREAD

**Issue by cxhernandez** [mdtraj/mdtraj#806]
Something like:

``` python
from rosetta import *
import mdtraj as md

pose = pose_from_seq('AAAAAAAA')
struct = md.load_rosetta(pose)
```
would be sweet.

**Comment by kyleabeauchamp** [comment]
Does that even belong here?  IMHO, Parmed might be a better place for this.

**Comment by kyleabeauchamp** [comment]
E.g. Rosetta -> Parmed -> MDTraj or Rosetta -> Parmed -> OpenMM

**Comment by kyleabeauchamp** [comment]
But I agree it is totally useful

**Comment by kyleabeauchamp** [comment]
Also, Parmed is awesome, long live parmed

**Comment by cxhernandez** [comment]
Either way is fine with me. I thought it might be natural to analyze an ensemble of structures from Rosetta directly in MDTraj, but Parmed would definitely be nice for the OpenMM bindings.
