### ISSUE TITLE
NetCDF loader not registered for ".ncdf"

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#807]
the save routine for netcdf creates files with that suffix, but the loader is not registered for it. So I guess the writer is registered, but the loader is not.

t = Trajectory(...)
t.save('foo.ncdf')
mdtraj.load('foo.ncdf')

yields IOError: Sorry, no loader for filename=foo.ncdf

**Comment by swails** [comment]
Should be added by #808 

I've actually never seen `ncdf` used as a NetCDF extension (the supported ones were `.nc` and `.netcdf`), but obviously somebody added it to `Trajectory.save`.

**Comment by marscher** [comment]
git blame is your friend :)
