### ISSUE TITLE
Does iterload load complete files into memory before chunking them?

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#809]
I wonder if this the case for formats not explicitly handled in this function (like xtc, dcd, lh5 and h5).

in core.Trajectory.py:

            t = load(filename, **kwargs)
            for i in range(len(t), chunk):
                yield t[i:i+chunk]

**Comment by rmcgibbo** [comment]
Yes, that should probably be extended to cover more formats.

**Comment by marscher** [comment]
I guess the infrastructure to do so is already there for most formats?

**Comment by rmcgibbo** [comment]
yeah, there's really nothing special about the (dcd, xtc, lh5, h5) loaders -- all the infrastructure is there for the other formats too.

**Comment by rmcgibbo** [comment]
This is now fixed for all formats.
