### ISSUE TITLE
What formats for .gz and .bz2?

### ISSUE THREAD

**Issue by pfrstg** [mdtraj/mdtraj#812]
https://github.com/mdtraj/mdtraj/pull/810
put in place the utility function for .gz and .bz2 loading/saving of formats. But it only connected it for .gz in .pdb and .xyz.

What is the set of formats you would like .gz and .bz2 support for?

**Comment by kyleabeauchamp** [comment]
I think that PDB.gz is the main requirement here, as that is a industry-standard format.  I think the other combinations are useful in niche applications but lower priority.  So I guess my answer is:

1.  PDB.gz
2.  Whatever else you need for your application

**Comment by pfrstg** [comment]
Maybe we are done then. (2) is .xyz.gz for me

**Comment by rmcgibbo** [comment]
I think we're good here then.
