### ISSUE TITLE
centering/reimaging structures split under PBC

### ISSUE THREAD

**Issue by evanfeinberg** [mdtraj/mdtraj#814]
Hi All, 

I'm sure there's a really simple solution to this problem. In simulations run under PBC, oftentimes different parts of the receptor will seem "split up."  When using MiniBatchKMedoids, some of my cluster centers have this issue (e.g., see image here). In cpptraj, this is easily resolved by using "center [residues]" then "image origin center". Is there an equivalent way to center/reimage coordinates in mdtraj so that when I visually inspect the cluster centers the receptor is "together?" 

Thanks!
Evan

(the following did not work):
 t = md.load("/home/enf/b2ar_analysis/clusters_allprot/43.pdb")
t.center_coordinates()
t = md.save_pdb("/home/enf/b2ar_analysis/43_centered.pdb")

![screen shot 2015-04-28 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/1760982/7381389/b8d3fe70-edb7-11e4-914d-3429266e60f9.png)

**Comment by kyleabeauchamp** [comment]
It could be implemented.  See #490

**Comment by kyleabeauchamp** [comment]
Also #787

**Comment by evanfeinberg** [comment]
Thanks @kyleabeauchamp . Perhaps I'll have the chance to do implement this later in my rotation. In the mean time perhaps I'll write a little bash script using gromacs or cpptraj as a temporary measure.

**Comment by kyleabeauchamp** [comment]
It should be feasible to do mdtraj -> pytraj (which contains cpptraj) -> mdtraj

**Comment by evanfeinberg** [comment]
OK, I'll give it a try!

On Tue, Apr 28, 2015 at 3:32 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> It should be feasible to do mdtraj -> pytraj (which contains cpptraj) ->
> mdtraj
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/814#issuecomment-97245635>.
>



-- 
Evan N. Feinberg | Ph.D. Student,
     Stanford University, 2018 | M.D. Student,
          Yale School of Medicine, 2022

**Comment by swails** [comment]
> In cpptraj, this is easily resolved by using "center [residues]" then "image origin center". Is there an equivalent way to center/reimage coordinates in mdtraj so that when I visually inspect the cluster centers the receptor is "together?"

Actually you are making things even more complicated than they need to be.  In cpptraj, you can use `autoimage` with no arguments, and that will almost always do exactly what you want it to do.

[pytraj](http://github.com/pytraj/pytraj) is a set of Cythonized bindings to cpptraj (as @kyleabeauchamp mentioned), and @hainm has added support for loading trajectories from `mdtraj`.  So what you can do is go mdtraj->pytraj->autoimage->mdtraj all rather seamlessly.

@rmcgibbo -- pytraj also has pretty nice performance when it comes to iterating over trajectories, has automatic trajectory type determination (that doesn't depend on filename extensions), and much faster parsing capabilities for ASCII-based trajectories like Amber mdcrd files and ARC trajectories.

**Comment by hainm** [comment]
FYI: in pytraj, I added (10*traj.xyz) to convert mdtraj traj to pytraj object. May be I will add option like:
load_mdtraj(m_traj, autoconvert=False) to keep original coords

https://github.com/pytraj/pytraj/blob/master/pytraj/externals/_load_mdtraj.py#L27

Hai

**Comment by rmcgibbo** [comment]
Yeah, it seems like a great tool! It would be nice to add this feature (pbc imaging) natively into mdtraj too. The other particular features you mentioned, @swails, aren't on my personal todo list, but obviously could be great if someone wanted to implement them.

**Comment by hainm** [comment]
per 
"automatic trajectory type determination (that doesn't depend on filename extensions), and much faster parsing capabilities for ASCII-based trajectories like Amber mdcrd files and ARC trajectories."

--> this is excellent work in [cpptraj] (https://github.com/mojyt/cpptraj)

**Comment by evanfeinberg** [comment]
Thank you, @swails , @rmcgibbo , and @hainm , I will try this and report back. Really appreciate the insights everyone!

**Comment by swails** [comment]
Well low-hanging fruit could be to add a wrapper around pytraj (if it's available) to take advantage of its functionality.  Intelligent imaging like what `autoimage` in cpptraj does is actually a bit of a challenge -- see [here](https://github.com/mojyt/cpptraj/blob/master/src/Action_AutoImage.cpp) (that is just the "intelligent" part -- the imaging code for general triclinic cells is elsewhere).

Automatic file-type determination would be a bit of an undertaking in `mdtraj` (and the current approach based on extensions is pretty good), and ASCII trajectories are, to be frank, foolish to use (but people use them nonetheless).  @rmcgibbo -- how would you feel about wrapping some pytraj functionality in mdtraj?  (pytraj is conda-installable from the pytraj channel)

**Comment by rmcgibbo** [comment]
I think for reasons of completeness, stability, and simplicity, adding the imaging/pbc feature to mdtraj itself would be the best solution. Obviously the easiest way to do this would involve copying/porting code, in whole or in part, from another package, but as I understand it, licensing issues prevent doing that with cpptraj. Gromacs and mdtraj are identically licensed, so that's a possibility.

**Comment by swails** [comment]
Yea, I think cpptraj is GPL

**Comment by evanfeinberg** [comment]
```

import pytraj.io as mdio
from pytraj import adict
	for i in range(0, len(files)):i
		pdb = files[i]
		conformation = mdio.load(pdb, pdb)
		f0 = conformation[0]
		adict['autoimage']("", f0, conformation.top)
		new_file = "%s/%d.pdb" %(new_dir, i)
		mdio.save(new_file, traj = f0, top = conformation.top)
```

This seemed to generally work, thanks for your insights everyone!! There were a couple messed up hydrogens after the reimaging, however, that were in the completely wrong place. I circumvented it by just stripping and re-adding the hydrogens with a script in PyMol, which is ok as a temporary measure. I'm going to try this again by loading in the pdb and dcd together and reimaging the result. Do the dcd files and/or mae files hold more info about the periodic boundary conditions than plain old pdb files that avoid such reimaging issues?

**Comment by kyleabeauchamp** [comment]
Are you talking about multi-frame PDB files?  A multi-frame PDB files contains only a *single* box vector, while a DCD contains a box vector for each frame.

**Comment by hainm** [comment]
hi @evanfeinberg, 

if you have only small trajectory (fit into memory),  you can do this (work well with master git version)
```python
    import pytraj.io as mdio

    for i in range(0, len(files)):
        pdb = files[i]
        conformation = mdio.load(pdb, pdb)[:] # add [:] to convert to mutable FrameArray
        #print (conformation)
        conformation.autoimage()
        new_file = "%s/%d.pdb" %(new_dir, i)
        conformation.save(newfile)
```

In  your script, only one single fame is loaded from disk to save memory (which is good for Tb data)

You can check this too: http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/Trajectory.ipynb

Hai

**Comment by evanfeinberg** [comment]
Thank you, @hainm , that's much cleaner. I'm only doing it on single PDB files representing single frames (to answer @kyleabeauchamp ) at the moment. I suppose I could reimage the whole trajectory but there's ~3 TB of it so I was planning on just reimaging when needed. 

I assume this is all the box info needed?

![screen shot 2015-04-30 at 2 37 18 pm](https://cloud.githubusercontent.com/assets/1760982/7423005/8d4d7af2-ef46-11e4-8c5e-a333922ac1e1.png)

**Comment by evanfeinberg** [comment]
Hi @hainm : I tried your much cleaner version of the reimage code. However, I received the following error message:

Traceback (most recent call last):
  File "subsample3.py", line 802, in <module>
    sample_clusters(clusterer_dir, traj_dir, lag_time, n_samples=1)
  File "subsample3.py", line 749, in sample_clusters
    reimage(save_dir)
  File "subsample3.py", line 566, in reimage
    conformation.autoimage()
AttributeError: 'pytraj.FrameArray.FrameArray' object has no attribute 'autoimage'

Any idea why this is? 

Cheers,
Evan

**Comment by hainm** [comment]
Hi

It's likely I updated 'autoimage' for FramArray after your installation.

Can you please try installing pytraj from github again? 

If this is your first time doing this, you might want to

```python
python setup.py build -faster_build
python setup.py install
```

(Use multiple cores for compiling cython files).

I will try to update binstar verson too. 

Ps: with the most updated pytraj, use can directly load mdtraj object and then do autoimage too (note: amber uses Angstrom while mdtraj use nm).

```python
import pytraj.io as io
traj = io.load_mdtraj(its_traj_object)
```
Hai

**Comment by swails** [comment]
Let's take pytraj-related issues to the pytraj issue tracker -- I think that would be better for both projects.  You can always link to issues in other packages as well.

For instance, to link to this issue in the pytraj repo, just reference it as mdtraj/mdtraj#814

**Comment by hainm** [comment]
@evanfeinberg 
I just update `pytraj-dev` in `binstar`

`conda install pytraj-dev -c pytraj --force`

Jason is right that creating an issue in `pytraj` channel is more appropriate. It's easier to keep track and to let other know about the errors. thanks.

Hai

**Comment by evanfeinberg** [comment]
Hi: 

If anyone in our lab ( @cxhernandez , @mpharrigan , @msultan , @rmcgibbo , etc.) needs to reimage a large number of trajectories using mdtraj, with pytraj as a dependency, I created a little gist with the insights above that should do the trick pretty fast: 

https://gist.github.com/evanfeinberg/6d1379b1556cef92d0ec#file-reimage-py

Cheers,
Evan

**Comment by mpharrigan** [comment]
This is added in #1058
