### ISSUE TITLE
MiniBatchKMedoids documentation link broken

### ISSUE THREAD

**Issue by evanfeinberg** [mdtraj/mdtraj#815]
Hi, I can't find documentation page or paragraph for MiniBatchKMedoids. This may be due to a very small typographical error on: http://msmbuilder.org/latest/cluster.html
in which it is called "MinibatchKMedoids" instead (the "b" in Batch should be capitalized, and due to the case sensitivity of python it won't work otherwise). I assume it takes basically the same parameters as MiniBatchKMeans vis-a-vis batch size, etc.?

Cheers,
Evan

**Comment by rmcgibbo** [comment]
Good spot. I made the fix. You can check the docstring from inside a python or interactive IPython session by using `help(MiniBatchKMedoids)` or `MiniBatchKMedoids?` from IPython (the `?` gives you the help text for any function inside IPython).

**Comment by evanfeinberg** [comment]
Nice, thanks!
