### ISSUE TITLE
[FR] compute_bonds, compute_molecules

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#819]
I've been thinking about what we need to implement "whole"ing trajectories with PBCs (#814, #490, #787).

Two subsidiary task are
 - computing the bond graph (list of all chemical bonds in the system, determined by pairwise distance below some cutoff), and;
 - identifying molecules from the bond graph (the connected components).

The first task is essentially the same thing as the neighborlist in a simulation code, so perhaps we could just drop something in without coding it from scratch. I spent an hour or two trying understand the NeighborList code in OpenMM, but it's hard to use that code because it (a) requires a lot of the OpenMM infrastructure to compile -- you can't just grab one or two files (b) I don't really understand it.

**Comment by rmcgibbo** [comment]
Also, OpenMM's handling of triclinic cells is simplified by restricting to "lattice reduced" vectors, but the rest MDTraj uses general triclinic cells without any restriction, which makes it trickier for me to understand how the OpenMM code works or just copy it over.

**Comment by ctk3b** [comment]
If a naive cutoff distance suffices for your purposes and no bond breaking occurs, this should work for a). Differentiating between bond-types to adjust the cutoffs wouldn't be hard either.

```python
traj = md.load('some.pdb')
pair_list = select_pairs(t, selection1='all', selection2='all')
distances = md.compute_distances(traj, pair_list)    
bonds = pair_list[np.where(distances[0] < BOND_CUTOFF)]

for bond in bonds:
    traj.add_bond(*bond)
```
However, `pair_list` can become memory limiting depending on your system size.

For b), this should detect the molecules but will require a few more lines to get all the residue info back in.
```python
graph = traj.top.to_bondgraph()
for sub_graph in graph.connected_components():
    chain = traj.add_chain()
    for atom_index in sub_graph:
        # re-create residues
        # add atoms
```

**Comment by rmcgibbo** [comment]
There's also compute_neighbors, but the implementation is crap :). I want to implement a proper neighborlist.

**Comment by swails** [comment]
> There's also compute_neighbors, but the implementation is crap :). I want to implement a proper neighborlist.

You gain some efficiency from a complex neighborlist (e.g., a Verlet list built from a cell decomposition), but you lose a lot of benefit from neighborlists in general by virtue of being a trajectory analysis program rather than an MD program, I think.  And using a naive pairlist (like the Verlet list used in the OMM Reference platform) yields negative benefit here (best-case) :).

For very large systems it's probably a nice speedup, but do you know the crossover point of where the list-building followed by the pair calculation is noticeably faster than the current brute-force approach?

**Comment by swails** [comment]
I don't understand why you're using the bond cutoff criteria for determining covalent bonds here?  Don't most of the topology instances instantiated here (*including* PDB files with standard residue names) come pre-loaded with a list of Bonds?  Why not just use that? (And the recursive "tagging" algorithm is very efficient for this -- O(N)).

**Comment by rmcgibbo** [comment]
Sometimes the topology has full bond information. Oftentimes it doesn't though. Anyways, for a variety of analysis tasks, I'm pretty sure a cell based neighborlist would be quite useful. I don't know the crossover point though.

**Comment by swails** [comment]
Also, there are many ways of "whole"-ing a system -- the trick is how to pick the best unit cell center, in my experience.

**Comment by swails** [comment]
OK -- I thought it usually did.  e.g., Gromacs topology, PDB files with standard residues, Amber, and CHARMM files all have bonds defined (as does the MDTraj h5 traj format, right?).
