### ISSUE TITLE
Latest version of docs is totally broken

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#820]
See e.g. http://mdtraj.org/latest/analysis.html

**Comment by marscher** [comment]
Try pinning down sphinx version to build the docs to 1.2.3, since they've introduced a bug in 1.3.1 which renders autosummaries toctree unusable in some cases.

**Comment by swails** [comment]
Are they going to fix it?  Or is this a kind of "we've fixed a long-standing bug that you've relied on" thing?

**Comment by marscher** [comment]
It has already been reported (#1822) and I think they gonna fix it soon.

**Comment by swails** [comment]
Nice.  You can actually reference that issue directly by doing sphinx-doc/sphinx#1822

Thanks for the info!

**Comment by marscher** [comment]
No problem. It took me some time to figure this out, so I just wanted to
save you some time, since our docs also looks like your current state
after upgrade to recent sphinx.

**Comment by rmcgibbo** [comment]
Thanks guys.
