### ISSUE TITLE
netcdf should be close properly

### ISSUE THREAD

**Issue by hainm** [mdtraj/mdtraj#821]
Hi,

I am playing with `load_netcdf` but got this kind of error

```
In [54]: m_traj = md.load_netcdf ("md11.nc", top="myparm.prmtop")
/home/haichit/anaconda3/lib/python3.4/site-packages/scipy/io/netcdf.py:287: 
RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, 
when netcdf_variables or arrays referring to its data still exist. 
All data arrays obtained from such files refer directly to data on disk, and 
must be copied before the file can be clean
```

this did not happen when I call `m_traj = md.load_netcdf ("md11.nc", top="myparm.prmtop")` in the first time. But calling 2nd time in ipython notebook cause this error.

I got the same problem when playing with `netcdf` in `scipy`? Just want to report to you guys (this happens randomly but not very frequently).

Hai

**Comment by hainm** [comment]
ah, by the way, it's quite slow to `import mdtraj as md` in the first time.

**Comment by rmcgibbo** [comment]
this is related to a known design flaw in scipy.io.netcdf: https://github.com/scipy/scipy/pull/3960, https://github.com/scipy/scipy/issues/3630, https://github.com/scipy/scipy/pull/3633
