### ISSUE TITLE
Save forces in HDF5Reporter

### ISSUE THREAD

**Issue by zonca** [mdtraj/mdtraj#828]
Would it be possible to implement saving forces in HDF5Reporter?
I think some users would be interested to have that functionality.

**Comment by kyleabeauchamp** [comment]
I think the Parmed NetCDF reporter supports forces, right?

https://github.com/ParmEd/ParmEd/blob/master/chemistry/openmm/reporters.py#L295

**Comment by zonca** [comment]
didn't know about that!
great, I'll use that instead, thanks.
