### ISSUE TITLE
Examples/WebGL viewer failing on OS X

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#829]
I'm trying to test the waters with MDTraj and installed via conda into my anaconda python 2.7, then fired up my iPython notebook viewer with the examples from GitHub. After evaluating the second box in https://github.com/mdtraj/mdtraj/blob/master/examples/WebGL-Viewer.ipynb I get this:

```
OSError                                   Traceback (most recent call last)
<ipython-input-2-cc86fc55fde2> in <module>()
      1 from mdtraj.html import TrajectoryView, enable_notebook
----> 2 enable_notebook()

/Users/dmobley/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-macosx-10.5-x86_64.egg/mdtraj/html/install.py in enable_notebook()
     51     libs = ['iview.js','surface.min.js','objexporter.js','filesaver.js','context.js']
     52     fns = [resource_filename('mdtraj', os.path.join('html', 'static', f)) for f in libs]
---> 53     install_nbextension(fns, verbose=0)
     54     display(_REQUIRE_CONFIG)
     55 

/Users/dmobley/anaconda/lib/python2.7/site-packages/IPython/html/nbextensions.pyc in install_nbextension(path, overwrite, symlink, user, prefix, nbextensions_dir, destination, verbose)
    174     nbext = _get_nbext_dir(nbextensions_dir, user, prefix)
    175     # make sure nbextensions dir exists
--> 176     ensure_dir_exists(nbext)
    177 
    178     if isinstance(path, (list, tuple)):

/Users/dmobley/anaconda/lib/python2.7/site-packages/IPython/utils/path.pyc in ensure_dir_exists(path, mode)
    586     if not os.path.exists(path):
    587         try:
--> 588             os.makedirs(path, mode=mode)
    589         except OSError as e:
    590             if e.errno != errno.EEXIST:

/Users/dmobley/anaconda/lib/python2.7/os.pyc in makedirs(name, mode)
    148     if head and tail and not path.exists(head):
    149         try:
--> 150             makedirs(head, mode)
    151         except OSError, e:
    152             # be happy if someone already created the path

/Users/dmobley/anaconda/lib/python2.7/os.pyc in makedirs(name, mode)
    155         if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
    156             return
--> 157     mkdir(name, mode)
    158 
    159 def removedirs(name):

OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

Any pointers? I'm guessing I've done something simple which was wrong (and of course I see the immediate issue is that this doesn't have permission to work within my /usr/local/share directory, but I don't know why it's trying to modify things there..).

**Comment by kyleabeauchamp** [comment]
I think we may have already fixed this bug in the github master, but not in any of the available releases /conda packages.  One such bug was fixed in april, but the latest release was in february. 

https://github.com/mdtraj/mdtraj/pull/789

**Comment by kyleabeauchamp** [comment]
The underlying issue was the IPython 3.0 (e.g. jupyter) came out a few months ago and introduced some major changes under the hood.

**Comment by davidlmobley** [comment]
Any chance of a new minor point release for conda? (I'm teaching a class tomorrow where the students asked me if I could show them a bit about using MDTraj so we were going to fire up some examples in class; probably half of them only install things via conda).

**Comment by davidlmobley** [comment]
(I will check if using master fixes my issue).

**Comment by davidlmobley** [comment]
@kyleabeauchamp - yes, that does it. To be more specific about why I would *so much* like this available via conda - probably 1/3 to 1/2 of the students are very new to any type of scientific computing that doesn't involve using a GUI, and are on Windows which I never use. I have no interest in/knowledge of translating all the "normal" instructions I give into the appropriate Windows versions so they can install stuff via other routes, so thus far I've avoided using anything in class which can't be installed via conda.

I suppose if it will work as simply as having them download the zip file, extract it, and type "python setup.py install" somewhere, then I can probably do it. But I don't have a Windows machine to test on... Ugh.

**Comment by kyleabeauchamp** [comment]
Here's a question: does the IPython molecule viewer even work on Windows + IPython3?  I imagine this combination has possibly never been attempted.

**Comment by davidlmobley** [comment]
Heh. Well, I suppose I'll possibly find out. :) It's actually been
surprising to me how many things *DO* work on Windows without problems. So
far we haven't actually run into anything that didn't. (f2py, inline
plotting, openeye tools including depiction, ...).

On Wed, May 20, 2015 at 4:18 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> Here's a question: does the IPython molecule viewer even work on Windows +
> IPython3? I imagine this combination has possibly never been attempted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/829#issuecomment-104069459>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by ostrokach** [comment]
I am having the same issue:

Using the `mdtraj` and `mdtraj-dev` packages from conda, with Python 2.7 I get the `Permission denied` error, and with Python 3.4 I get no output, when I try to run the `WebGL-Viewer.ipynb` example.

**Comment by ostrokach** [comment]
Never mind... The Python 3.4 version works fine in Firefox and Chrome, just not Chromium. Weird. 
Thanks a lot, it looks great!
