### ISSUE TITLE
TrajectoryView widget won't display when secondary structure not present if selected

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#831]
I pulled the examples simulation-with-openmm and used it to generate an `ala2.h5` file which I then loaded into the trajectory viewer via the code below. It turns there is an issue (bug/undocumented restriction) where if secondary structure is specified to be shown for this system (presumably because it is too small to have secondary structure) the viewer won't display, and no error is given. Specifically:

```
from __future__ import print_function
import mdtraj as md

traj = md.load('ala2.h5')
print(traj)
from mdtraj.html import TrajectoryView, enable_notebook
enable_notebook()

widget = TrajectoryView(traj, primaryStructure = 'ball & stick', secondaryStructure='ribbon')
widget
```
fails to produce any output, but if I replace the `widget = ` line with `widget = TrajectoryView(traj, primaryStructure = 'ball & stick')` it displays just fine. Presumably the fact that this is too small to have secondary structure means the viewer is choking...

**Comment by kyleabeauchamp** [comment]
Is this the same issue?  https://github.com/mdtraj/mdtraj/issues/597

**Comment by rmcgibbo** [comment]
This shouldn't be too hard to fix. I had been considering it a low
priority, because I wasn't sure if anyone was actually using this feature
in production.

But it sounds like it's being used for teaching, so that raises the
priority.
