### ISSUE TITLE
Coloring seems not to work properly by any scheme in TrajectoryView of small molecule mixture; maybe doesn't understand GAFF atom types?

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#834]
I was experimenting with a simple visualization of a mixture of two small molecules (phenol and cyclohexane) and trying to get the molecules to show up in different colors. However, none of the TrajectoryView coloring options give that result, I just end up with identical colors for all atoms (including hydrogens) in every case. Possibly it's an issue with interpretation of GAFF atom names or something.  I'm linking to input files below to show what I'm talking about.

```
import mdtraj as md
traj = md.load( 'data/tleap/phenol_cyclohexane_3_100.inpcrd', top = 'data/tleap/phenol_cyclohexane_3_100.prmtop' )

topology = traj.topology
phenol = topology.select('resid 1 to %s' % Nsolu)

from mdtraj.html import TrajectoryView, enable_notebook
enable_notebook()

widget = TrajectoryView(traj, primaryStructure='ball & stick', colorBy='residue')
widget
```

Inputs: https://drive.google.com/file/d/0B5sFkoaaNUxtM1dHR2VCSkk1eTQ/view?usp=sharing

I also poked around for a while in the help for TrajectoryView to see if I could figure out how to color a specific selection (i.e. `phenol` in my code) with a different color but it was non-obvious (it's not clear that it's possible). I also tried the other options to colorBy but all of them result in identical colors for all atoms.

If I had to guess what's going on, I'd guess that for some reason this is written in a way which doesn't understand GAFF atom types so all the atoms are effectively treated as if they are identical, and that residues (while correctly numbered) are also not handled correctly in non-protein cases somehow.

**Comment by rmcgibbo** [comment]
I looked at these files today. Unfortunately the viewer doesn't really have the ability to do atom selections and color them differently. That would be nice, but it might be hard to implement. The easier thing to do would be to have better default colors for small molecules. I think it was coded up with only proteins in mind.

**Comment by hainm** [comment]
@davidlmobley 

you can try `nglview` (supports mdtraj, pytraj, mdanalysis, ...): https://github.com/arose/nglview

![picture1](https://cloud.githubusercontent.com/assets/4451957/12707315/bd83b012-c860-11e5-972d-08a794ef12ea.png)

If you have any questions, feel free to open a new issue there
