### ISSUE TITLE
Improved Amber prmtop support

### ISSUE THREAD

**Issue by swails** [mdtraj/mdtraj#839]
The Amber prmtop parser included in mdtraj right now works fine with standard topology files created by tleap.  But it doesn't work with chamber-style topology files or those defining the Amoeba force field.

Would you be amenable to me replacing the Amber topology file parser with a (significantly) stripped-down version of mine from ParmEd?  And if so, I have two parsers: a pure-Python one that's a bit slower than the one you currently have (since the parser here does type-conversions only on-demand and uses only a small subset of the information in the prmtop, whereas mine converts everything) and one written in C++ with C-Python bindings (C-API, not Cython) that is substantially faster than both.

In both cases, I make use of the pure-Python `fortranformat` [package](https://bitbucket.org/brendanarnold/py-fortranformat/) to parse "complicated" Fortran format statements (it's too slow for general use by ~1 order of magnitude).

It's not *really* necessary, since people can use the following recipe (provided they have ParmEd and OpenMM installed):

```Python
import mdtraj as md
import chemistry as chem

top = md.core.topology.Topology.from_openmm(
        chem.load_file('some_file').topology
)
traj = md.load('traj.nc', top=top)
```

But then they need both ParmEd and OpenMM installed (through conda, presumably).  The above will actually work when `some_file` is a Charmm PSF file, an Amber topology file (old-style, new-style, chamber-style, and Amoeba-style), a Gromacs topology file, a GRO file, a PDB file, or a mmCIF file, with file-type determined by content rather than file extension.

**Comment by kyleabeauchamp** [comment]
I'm happy with whatever  works for you.  I do sometimes worry about you having to maintain the same code in three different places (parmed, openmm, mdtraj).

**Comment by swails** [comment]
That's a fair point.  Since I always have ParmEd and OpenMM installed, the above works fine for me.

**Comment by rmcgibbo** [comment]
Do you have a good sense of what changes are minimally required to load the chamber prmtops into mdtraj topologies? My impression from https://github.com/pandegroup/openmm/issues/887 was that a very small number of changes would be sufficient (e.g. using fortranformat in a couple places).

I'd like to minimize the amount of code churn.

**Comment by swails** [comment]
> My impression from pandegroup/openmm#887 was that a very small number of changes would be sufficient (e.g. using fortranformat in a couple places).

haha -- my "fix" in OpenMM was to raise an exception as soon as an unrecognized fortran format was detected.  It does nothing to try and parse it correctly, since it wouldn't support the resulting prmtop, anyway.

`fortranformat` is too slow to really consider using -- it slowed down prmtop parsing in my tests by a factor of 10.  The only format in common use that my `FortranFormat` class can't handle is `(i2,a78)` used in chamber topologies, and that section only stores 6 lines at most.

Let me see if I can come up with a shorter hack (which would just ignore the sections with unrecognized formats and just hope they're not important for mdtraj).

**Comment by rmcgibbo** [comment]
Right. I understand. I was referring to the Chamber file that @apeck12 was using in her issue, not the "fix". My impression from looking at the code was that a minimal fix for the issue on the mdtraj side (allowing that file to be parsed) would be quite simple.

**Comment by swails** [comment]
It's looking like it.

**Comment by swails** [comment]
Yea, it was super easy.

**Comment by swails** [comment]
Added in #840.

**Comment by rmcgibbo** [comment]
Fantastic. Thanks @swails!
