### ISSUE TITLE
Trajectory widget failing on virtual site lookup?

### ISSUE THREAD

**Issue by ctk3b** [mdtraj/mdtraj#851]
I assume this is related to the recent change for virtual sites in #835?
```python
mdtraj/mdtraj/html/trajectory_widget.py in _computeSecondaryStructure(self)
    138                 for a in top.residue(r).atoms:
    139                     result[a.index] = {
--> 140                         'ss': SS_MAP[ss],
    141                         'ssbegin': (r==rindxs[0] and ss in set(['H', 'E'])),
    142                         'ssend': (r==rindxs[-1] and ss in set(['H', 'E']))}

KeyError: 'NA'
```

Ignoring `'NA'` in the secondary structure computation fixes the issue for me but I'm not sure if this is the best way to solve this.

**Comment by rmcgibbo** [comment]
LOL whoops. I guess I should have waited a couple more minutes before cutting the release. The error isn't from virtual sites -- it's just from #841 that added the NA code.

**Comment by rmcgibbo** [comment]
It kind of sucks that we don't have any tests for the IPython notebook widget. I'm not quite sure how to go about adding a test to see if the view widget actually shows up in the browser.

**Comment by cxhernandez** [comment]
Maybe we can adapt some of the nosetests from [ipywidgets](https://github.com/ipython/ipywidgets)?
