### ISSUE TITLE
RMSD calculation

### ISSUE THREAD

**Issue by frank-stonybrook** [mdtraj/mdtraj#854]
Right now we are trying to calculate the rmsd of each frame in trajectory1 based on one/several frames of trajecotry2. Since the coordinate bases for trajectory1 might be different from trajectory2,  I am wonder whether it is possible to directly calculate rmsd using md.rmsd(trajectory1, trajectory2)? Or there might be better way to do it?

Thanks
Cong

**Comment by kyleabeauchamp** [comment]
Can you explain what you mean by "the coordinate bases might be different"?

**Comment by frank-stonybrook** [comment]
For example the trajectory1 might be one comes from a MD simulation and trajectory 2 is the crystal structure which downloaded from protein data bank. The issue which I am worrying about is the translation.

**Comment by frank-stonybrook** [comment]
Hi Kyle, 

I could use center_coordinate to eliminate the translation movement in trajectory1, but how could I make sure that coordinates of the crystal structure in trajectory2 is consistent with trajectory1??

Best
Cong

**Comment by kyleabeauchamp** [comment]
OK, so you are going to have to manually figure out a way to map the atoms of one structure onto the other structure.  This will probably involve writing some python code.

**Comment by frank-stonybrook** [comment]
Thanks! I am wondering whether it is possible to append two trajectories together and then do the center_coordinate on the mixed trajectory. 

Cong

**Comment by kyleabeauchamp** [comment]
You cannot append two trajectories that have different numbers of atoms.  You would have to manually select (`atom_slice()`) the desired atoms and also pay attention to atom ordering.

**Comment by frank-stonybrook** [comment]
Hi Kyle, 
Thx! I already matched the amount of atoms in both trajectories, Is there any built-in functions that I can use to append two trajectories together?

Cong

**Comment by kyleabeauchamp** [comment]
`traj.join()`

**Comment by frank-stonybrook** [comment]
Great! Thanks.

**Comment by mpharrigan** [comment]
Or `traj1 + traj2`

**Comment by frank-stonybrook** [comment]
Thanks Matthew!
