### ISSUE TITLE
Helper function for extracting atom pair indices?

### ISSUE THREAD

**Issue by kyleabeauchamp** [mdtraj/mdtraj#855]
This might be useful for making the atompairs PCA example cleaner---it would avoid using itertools.  While I love itertools, I think our goal is to make the example look as easy as possible.  

I think the desired function would be something like `pairs = traj.top.atompair_indices(some_option=True)`

The code might be airlifted from here: https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/subset_featurizer.py#L9

**Comment by ctk3b** [comment]
Not sure if this does exactly what you want but maybe helpful: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L903

**Comment by kyleabeauchamp** [comment]
I think that's good enough for now.
