### ISSUE TITLE
Weird test failure?

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#858]
@ctk3b do you have any idea what this test failure is? looking at the build history, it looks stochastic which is really weird 
https://travis-ci.org/mdtraj/mdtraj/jobs/66089453

**Comment by ctk3b** [comment]
That is really strange... I can't reproduce it locally. There's also nothing fancy happening [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/lammpstrj.py#L374). It's just determining the index of the columns for atom id's, types and their coordinates.

**Comment by rmcgibbo** [comment]
yeah, also when the tests rerun, it doesn't always error out. i can't reproduce locally either.

**Comment by ctk3b** [comment]
The keyerror always seems to come from `'y'`

**Comment by ctk3b** [comment]
Could try adding some debug info like printing `columns` in the error message to see if it reveals anything?

**Comment by ctk3b** [comment]
@rmcgibbo, could you restart the Travis build for #859? https://travis-ci.org/mdtraj/mdtraj/builds/66102333

Or better yet, can you think of a more systematic way to debug this?

**Comment by rmcgibbo** [comment]
done

**Comment by rmcgibbo** [comment]
I got it to reproduce (stochastically)

```
rmcgibbo@vspm9  ~/local/mdtraj (3.4.2) ‹master› 
$ nosetests mdtraj/tests/test_trajectory.py:test_seek_read_mode
/home/rmcgibbo/local/mdtraj/mdtraj/core/trajectory.py:396: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')
.
----------------------------------------------------------------------
Ran 1 test in 1.486s

OK
rmcgibbo@vspm9  ~/local/mdtraj (3.4.2) ‹master› 
$ nosetests mdtraj/tests/test_trajectory.py:test_seek_read_mode
/home/rmcgibbo/local/mdtraj/mdtraj/core/trajectory.py:396: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')
E
======================================================================
ERROR: mdtraj.tests.test_trajectory.test_seek_read_mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rmcgibbo/local/mdtraj/mdtraj/formats/lammpstrj.py", line 374, in _read
    self._xyz_columns = [columns['x'], columns['y'], columns['z']]
KeyError: 'z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/rmcgibbo/local/mdtraj/mdtraj/tests/test_trajectory.py", line 412, in test_seek_read_mode
    xyz = md.load(get_fn(b), top=get_fn('native.pdb')).xyz
  File "/home/rmcgibbo/local/mdtraj/mdtraj/core/trajectory.py", line 404, in load
    value = loader(filename, **kwargs)
  File "/home/rmcgibbo/local/mdtraj/mdtraj/formats/lammpstrj.py", line 111, in load_lammpstrj
    return f.read_as_traj(topology, n_frames=n_frames, stride=stride, atom_indices=atom_indices)
  File "/home/rmcgibbo/local/mdtraj/mdtraj/formats/lammpstrj.py", line 207, in read_as_traj
    xyz, cell_lengths, cell_angles = self.read(n_frames=n_frames, stride=stride, atom_indices=atom_indices)
  File "/home/rmcgibbo/local/mdtraj/mdtraj/formats/lammpstrj.py", line 262, in read
    frame_coords, frame_lengths, frame_angles = self._read()
  File "/home/rmcgibbo/local/mdtraj/mdtraj/formats/lammpstrj.py", line 376, in _read
    raise IOError("Invalid .lammpstrj file. Must contain 'id', "
OSError: Invalid .lammpstrj file. Must contain 'id', 'type', 'x*', 'y*' and 'z*' entries.

----------------------------------------------------------------------
Ran 1 test in 0.872s

FAILED (errors=1)
rmcgibbo@vspm9  ~/local/mdtraj (3.4.2) ‹master› 
$ nosetests mdtraj/tests/test_trajectory.py:test_seek_read_mode
/home/rmcgibbo/local/mdtraj/mdtraj/core/trajectory.py:396: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')
.
----------------------------------------------------------------------
Ran 1 test in 1.342s
```

**Comment by rmcgibbo** [comment]
like 1/10 times or so

**Comment by ctk3b** [comment]
Ok I got it too.
```python
OSError: Invalid .lammpstrj file. Must contain 'id', 'type', 'x*', 'y*' and 'z*' entries. 
 {'y': 3, 'zu': 4, 'x': 2, 'type': 1, 'id': 0}  # columns (what I parse out)
 ['id', 'type', 'xu', 'yu', 'zu']  # column headers (what's actually in the file)
```
 The issue must occur here:
https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/lammpstrj.py#L370

I really can't imagine this but is there some weird race condition buried in this clause?
```python
columns[header[0]] = columns.pop(header)
```

**Comment by ctk3b** [comment]
Nevermind.. that was dumb. Thank you @swails

**Comment by swails** [comment]
For anyone interested, the basic issue is this (code snippet below for reference):

```Python
            for header in columns:
                if header in {'x', 'y', 'z', 'xs', 'ys', 'zs', 'xu', 'yu', 'zu',
                              'xsu', 'ysu', 'zsu'}:
                    columns[header[0]] = columns.pop(header)
```

What this is doing is modifying the container as it's being iterated over, which results in undefined behavior (I'm surprised it didn't raise an exception, although a key was put back immediately so the number of keys never changed).  But dicts aren't ordered, so weird things can be happening.  I'd have thought it deterministic, though.  It can't be a race condition -- the GIL takes care of that (well, that and you don't use multiple threads).

I'm not sure if #860 was the best approach (I didn't look at the code carefully enough to see exactly what it was trying to do and why), but it should do the trick, I think.

But this raises another question: what is *supposed* to happen here?  Because if `x`, `xs`, `xu`, and `xsu` are all in the columns dict, then `columns['x']` could literally be any of those.  Dicts aren't ordered -- maybe you *want* an `OrderedDict` here? or will only one of those keys ever be present?

**Comment by ctk3b** [comment]
`x`, `xs`, `xu`, and `xsu` are all different types of coordinates that can be [dumped from LAMMPS](http://lammps.sandia.gov/doc/dump.html). They can be output in any order you specify. 

This code determines which column the required fields to construct a `Trajectory` are in the very first time that `_read` is called. One issue with the current implementation is that if a user dumps multiple types of x-coordinates, it will only read whichever is defined last.

**Comment by swails** [comment]
> One issue with the current implementation is that if a user dumps multiple types of x-coordinates, it will only read whichever is defined last.

No it won't.  It'll dump whichever one it feels like dumping.  The dict is unordered -- the order of iteration is not defined, so different platforms can do different things.

Maybe you should switch to an OrderedDict so it *is* well-defined, at least?
