### ISSUE TITLE
center_coordinates

### ISSUE THREAD

**Issue by frank-stonybrook** [mdtraj/mdtraj#867]
Hi, 

I am right now using mdtraj to calculate rmsd of a protein-peptide complex. I want to know what exactly trajectory.center_coordinates do. Does it superpose all the frames from the trajectory, What algorithm does it use, Kabsch? If possible, please attach any reference. 

Best
Cong

**Comment by rmcgibbo** [comment]
Did you look at the docstring or code? The docstring says "Center each trajectory frame at the origin (0,0,0)." It does not say anything about superposing. There is a method called `superpose` that does that, which uses Theobald QCP.

**Comment by frank-stonybrook** [comment]
Thanks Robert! 
Later I read some papers. So the center_coordinates is minimizing the translation movement by superimposing the centroid of frames and the superpose is minimizing the rotation matrix by applying quaternion characteristic polynomial algorithm, right?
