### ISSUE TITLE
[FR] Add Residue Code Attribute

### ISSUE THREAD

**Issue by cxhernandez** [mdtraj/mdtraj#870]
It might be nice to be able to get residue 1 letter codes from the `Topology` object like:

``` python
>> res = topology.residue(1)
>> print(res.name)
'ALA'
>> print(res.code)
'A'
```

**Comment by kyleabeauchamp** [comment]
If you do this, it might be cool to have a to_fasta decorator as well

**Comment by cxhernandez** [comment]
:+1:

**Comment by rmcgibbo** [comment]
Good idea. What is the desired `code` for `Residue`s that aren't protein?

To implement, probably all that's required is to add the mapping as a dict to https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/residue_names.py, and then one method on `Residue`, although we could also add something that uses this to the atom selection syntax.

**Comment by cxhernandez** [comment]
Maybe just leave it at `None` if it's not protein or is non-canonical?

**Comment by rmcgibbo** [comment]
+1
