### ISSUE TITLE
Removing all atoms but those selected

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#874]
Forgive my denseness, but the nice [atom selection example notebook](https://github.com/mdtraj/mdtraj/blob/master/examples/atom-selection.ipynb) didn't have an example of deleting all atoms except the ones we were interested in.  Is there an easy way to do this?

**Comment by kyleabeauchamp** [comment]
You're looking for `traj.atom_slice(atom_indices)`.

We should add an example of this here: http://mdtraj.org/latest/examples/atom-selection.html

**Comment by jchodera** [comment]
Thanks!

**Comment by kyleabeauchamp** [comment]
For completeness, we should also have an example of slicing along the time axis on that same page.

**Comment by jchodera** [comment]
Showing both slicing the topology and slicing the positions would be highly useful.

**Comment by kyleabeauchamp** [comment]
The topology is automatically sliced by the trajectory function--it does both.

**Comment by jchodera** [comment]
I'm struggling to try to figure out how to make an mdtraj `Trajectory` object from OpenMM `topology` and `positions` object.  The obvious idiom doesn't seem to work:
```
mdtraj.Trajectory(xyz=fixer.positions, topology=fixer.topology) 
```
Maybe it would be worthwhile to have an example if this in the docs too?

**Comment by jchodera** [comment]
Or maybe we just need OpenMM `Topology` objects to not be so braindead?

**Comment by kyleabeauchamp** [comment]
Conversion from the OpenMM Topology is a class member function.  `Topology.from_openmm()`

**Comment by jchodera** [comment]
Not having any luck with this idiom either:
```
mdtraj_top = mdtraj.Topology.from_openmm(fixer.topology) 
atom_indices = mdtraj_top.select(ligand_dsl).tolist()
subset_topology = mdtraj_top.select(atom_indices).to_openmm()
```
This gives me:
```
Traceback (most recent call last):
  File "mhc-peptide-tcr.py", line 244, in <module>
    subset_topology = mdtraj_top.select(atom_indices).to_openmm()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/core/topology.py", line 847, in select
    filter_func = parse_selection(selection_string).expr
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/core/selection.py", line 347, in __call__
    parse_result = self.expression.parseString(selection, parseAll=True)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/utils/external/pyparsing.py", line 1099, in parseString
    instring = instring.expandtabs()
AttributeError: 'list' object has no attribute 'expandtabs'
```

**Comment by jchodera** [comment]
I think it would help to have some solid examples of how to bounce back and forth between OpenMM objects (`Topology`, `positions`) and MDTraj objects (`Trajectory`, `Topology`).  There is some nice stuff about reporters in the docs and IPython notebooks, but little in the way of "here's how you go back and forth".

**Comment by kyleabeauchamp** [comment]
The `top.select()` function uses string queries.  You are mixing up index based slicing and string-based queries.

**Comment by jchodera** [comment]
You're right!  I wanted `top.subset()`.

**Comment by jchodera** [comment]
Success!  Will summarize some notes in the morning.
