### ISSUE TITLE
Faster Gzip handling

### ISSUE THREAD

**Issue by kyleabeauchamp** [mdtraj/mdtraj#880]
Obvious this is low priority, but I recently figured out several ways to speed up python parsing (read / write) of GZipped text files.  

The easy solution likely gives a 2X speedup over `GZipFile` and it involves using BufferedReader whenever possible.

The harder solution is something like 10X over naive GZipfile and it involves using pipes to use the system GZip commands.  This pushes more work into C code and also spawns a separate thread.  See https://github.com/marcelm/cutadapt/blob/master/cutadapt/xopen.py#L50 for details, I've also proposed some changes to that project (https://github.com/marcelm/cutadapt/pull/132).

**Comment by mpharrigan** [comment]
-1 `Popen`, not very cross-platform

**Comment by rmcgibbo** [comment]
+1 to a cross-platform 2X speed improvement though.

**Comment by marcelm** [comment]
The code in cutadapt falls back to using a regular `gzip.open` when `Popen` does not work.

If you want to use the module, we could create a separate package and both have it as a dependency.

**Comment by kyleabeauchamp** [comment]
I thought about closing this, but at the very least I should update it for correctness:

1.  The gzip handler I mentioned has now been split out into a separate repo: https://github.com/marcelm/xopen and is available on pypi and bioconda

**Comment by marscher** [comment]
It is also available on conda-forge, so we could directly use it. What do you think?

**Comment by marcelm** [comment]
For compression, I recently realized that `gzip.open` is actually just as fast as regular gzip if you use identical compression levels. The command-line gzip uses 6 by default, but `gzip.open` uses 9, which makes it a lot slower. If you use `gzip.open` with `compresslevel=6`, then there is virtually no difference.

For decompression, I even made the observation that `gzip.open` is actually *faster* than using `zcat` (or `gzip -dc`) on the command line.

You can still gain some advantages (for both compression and decompression) by spawning an external `pigz` process (using `xopen`, for example), but if you go for a lower compression level, it may be good enough already.

Ah, and one other observation: Compression performance also depends on your Python installation. Python packages from conda-forge were 20% faster at compression than the system-installed ones on Ubuntu.
