### ISSUE TITLE
DCD file reader allows only one reader at a time under Windows

### ISSUE THREAD

**Issue by fabian-paul** [mdtraj/mdtraj#882]
We have discovered a stange Windows bug. The DCD reader only allows to have one reader at once. Apparently the file is locked, even if we open it only for reading.
This only happens with DCD files, changing DCD to XTC in the example makes the problem disappear.
```Python
import mdtraj
import numpy as np

top = 'test.pdb'
with open(top, 'w') as f:
    print>>f, ('ATOM  %5d C    ACE A   1      28.490  31.600  33.379  0.00  1.00' % 0)

trajfile = 'file.dcd'
t = mdtraj.load(top)
t.xyz = np.arange(1000  * 3).reshape((1000, 1, 3))
t.time = np.arange(1000)
t.save(trajfile)

fh1 = mdtraj.iterload(trajfile,top=top)
next(fh1)

fh2 = mdtraj.iterload(trajfile,top=top)
next(fh2)
```
gives:
```
IOError: Could not open file: file.dcd
```

**Comment by rmcgibbo** [comment]
Huh. Very interesting. I have a Windows machine now, so I should be able to try to debug this.

**Comment by rmcgibbo** [comment]
If you want to try debugging this, I would probably start by adding some print statements to https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/src/dcdplugin.c#L787.

**Comment by fabian-paul** [comment]
Well, if I understand this correctly, sharing is disabled explicitly in https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/dcd/include/fastio.h#L103
The comment in that line (disallow sharing with other processes) is wrong. The WIN-API documentation says "If this parameter is zero and CreateFile succeeds, the file or device cannot be shared and cannot be opened again until the handle to the file or device is closed." So sharing is also disabled within the same process and not only across different processes.
I think the correct value should be FILE_SHARE_READ (1).
