### ISSUE TITLE
principal component analysis

### ISSUE THREAD

**Issue by vvoelz** [mdtraj/mdtraj#883]
Sorry to nitpick, but the spelling should be "principal" not "principle".  I noticed you have several scripts and documentation pages with the incorrect spelling

**Comment by rmcgibbo** [comment]
good catch. thanks!

**Comment by mpharrigan** [comment]
Wow, good to know... I always thought it was principle. Makes sense in hindsight

**Comment by mpharrigan** [comment]
Fixed with referenced PRs
