### ISSUE TITLE
license for ./devtools/ files

### ISSUE THREAD

**Issue by hainm** [mdtraj/mdtraj#890]
Hi,

I am just wondering if possible for `mdtraj` change license for ./devtools/ folder to BSD ones?

I would like to adapt them for travis build and upload to binstar for `pytraj`. thanks.

Hai

**Comment by rmcgibbo** [comment]
Sure, +1. Maybe you can file a PR to add a note to devtools/README.md that everything in this directory is BSD?

**Comment by hainm** [comment]
thanks. do you want BSD 2 or 3 clause?

**Comment by rmcgibbo** [comment]
2 clause
