### ISSUE TITLE
new version of pandas messes up SHIFTX2 wrapper

### ISSUE THREAD

**Issue by yunhuige** [mdtraj/mdtraj#895]
In mdtraj/nmr/shift_wrappers.py , line 162, I found an error with results.pivot_table() because the latest version of pandas gets rid of keywords rows= and cols= and instead uses index= and columns=.

I was able to fix it using:

<code>results = results.pivot_table(index=["resSeq", "name"], columns="frame", values="SHIFT")
 latest version of pivot_table</code>

**Comment by rmcgibbo** [comment]
Sweet. Good catch. Do you want to file a pull request?

**Comment by mpharrigan** [comment]
I think this was fixed a while ago
