### ISSUE TITLE
TNG Format Support

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#903]
GROMACS 5 has a new trajectory format (`.tng`) that apparently gets better compression. They have BSD code available as a C library too. We should add support for this.

**Comment by ctk3b** [comment]
The paper describing the format for the curious: http://onlinelibrary.wiley.com/doi/10.1002/jcc.23495/full

**Comment by marscher** [comment]
I have a branch for this feature, but unfortunately I haven't found the time to continue it. Do you want to create a TNG branch and I add a PR to this, so you guys can continue working on it?

**Comment by mpharrigan** [comment]
@peastman Is this something you'd be interested in helping out with?

**Comment by peastman** [comment]
Could be.  I'm not familiar with the format, but I'll take a look at the paper.

**Comment by peastman** [comment]
@marscher what's the status of your code?  What have you done so far, and what still needs to be done?

**Comment by marscher** [comment]
It is rather rudimentary:

* imported tng lib, compile it, provide Cython bindings for functions
  to read basic attributes like coordinates, n_atoms, n_frames).
* basic TNGTrajectoryFile class in Cython, reads frame coordinate
  and exposes what has so far been defined in the binding.
* very basic test (2 cases)..

There is already a implementation in VMD-plugins:

https://www-s.ks.uiuc.edu/Research/vmd/plugins/doxygen/tngplugin_8C-source.html

(just as reference)

**Comment by peastman** [comment]
Ok, thanks.  I think I can take it from there.

**Comment by marscher** [comment]
Thanks for taking over. Where shall I put the code?

**Comment by peastman** [comment]
I already pulled it from your repository.

**Comment by peastman** [comment]
Where did you get the TNG library from?  I've run into what seems to be a bug in the `tng_util_box_shape_read()` routine for reading box shapes.  The argument for the box shape is declared as `float **box_shape`, but in fact it's returning a pointer that points to doubles, not floats.  Where do I report the problem?

**Comment by marscher** [comment]
Nasty one...

Its part of GROMACS.
https://github.com/gromacs/gromacs/blob/master/src/external/tng_io/src/tests/tng_io_read_pos_util.c

**Comment by peastman** [comment]
Ok, thanks.  Also, where did you get the example tng file from?  Did you create it yourself?  If so, how?

**Comment by marscher** [comment]
Am 28.05.2016 um 17:35 schrieb peastman:
> Ok, thanks. Also, where did you get the example tng file from? Did you create it yourself? If so, how?
There is one example file in the source tree of gromacs (I think it is in the tests folder of tng).

**Comment by marscher** [comment]
I guess this can be closed? @mpharrigan

**Comment by cxhernandez** [comment]
done in https://github.com/mdtraj/mdtraj/pull/1125
