### ISSUE TITLE
Configurable unit system in Trajectory

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#91]
Currently, `Trajectory` always has nanometer-degree-picosecond units. It might be nice if this were more configurable. It could also introduce the possibility for confusion. I consider this low priority, but I'm just going to post it up here to be archived.

cc: https://github.com/tjlane/odin/issues/56

**Comment by mpharrigan** [comment]
I think this would be a bad thing. See all the units issues in openmm

**Comment by kyleabeauchamp** [comment]
Bas Rustenburg has also explored using the `pint` library for some of our ITC MCMC code.  In my experience, that library also has many quirks.  In particular, doing performance optimization of code has generally required stripping the units, performing opererations, and then re-adding the units.  

For this reason, I think we might just want to use a fixed unit system in MDTraj, at least until the various unit packages are more pleasant to work with.

**Comment by rmcgibbo** [comment]
sounds good to me.
