### ISSUE TITLE
[FR] Optional argument to md.load() which specifies the distance unit

### ISSUE THREAD

**Issue by ctk3b** [mdtraj/mdtraj#914]
For example, if I want to load a `.dcd` file that I know was written in nanometers (against convention), it would be nice to be able to write something like `md.load('traj.dcd', top='top.pdb', distance_unit='nanometers')`. The [`.lammpstrj` format](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/lammpstrj.py#L101) already has something like this in anticipation of supporting multiple [LAMMPS unit sets](http://lammps.sandia.gov/doc/units.html). This should also enable reading trajectories written in reduced units by providing a `simtk.Quantity`.

Do you foresee any obvious problems with adding an optional argument which modifies the file objects' `distance_unit` attribute?

**Comment by rmcgibbo** [comment]
My intuition is that this would really confuse most users. It's not that hard to just multiply inplace the `xyz` array, right?

**Comment by hainm** [comment]
in my experience, I was very surprised when mdtraj autoconvert Amber traj from Angstrom to nm. (I opened the issue about unit before).

and I beleiv 1st page of mdtraj does not say anything about this: http://mdtraj.org/latest/

**Comment by rmcgibbo** [comment]
All of mdtraj uses the same unit system, regardless of the format that you use. I'm quite confident that this was the right design call, as opposed to exposing data to users in the "native" units of whatever format they loaded the data from.

We can add this to the front page of the docs.

**Comment by hainm** [comment]
just curious, what's your motivation to use 'nm'? does openmm use 'nm'?

**Comment by mpharrigan** [comment]
See here for justification of using nm-amu-ps
http://docs.openmm.org/6.3.0/userguide/theory.html#units

**Comment by ctk3b** [comment]
> My intuition is that this would really confuse most users.

I'm a bit worried about this too but was hoping that as an optional feature, it wouldn't be that impactful.

> It's not that hard to just multiply inplace the xyz array, right?

Sure but then you also need to adjust the unitcells.

This is a fairly minor inconvenience on our end but I just wanted to see if this sounded like a potentially useful idea to others.

**Comment by hainm** [comment]
> See here for justification of using nm-amu-ps
http://docs.openmm.org/6.3.0/userguide/theory.html#units

thanks
