### ISSUE TITLE
[FR] Principal axes of rotation

### ISSUE THREAD

**Issue by mpharrigan** [mdtraj/mdtraj#916]
Analysis functions to (1) get moment of inertia tensor and (2) sorted principal axes of rotation

This would be a nice thing to have.

**Comment by cxhernandez** [comment]
+1

**Comment by ctk3b** [comment]
MOI tensor calculation is here: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/order.py#L135

**Comment by mpharrigan** [comment]
Haha whoops. Sorry @ctk3b 

New request! Add that function to the docs, and maybe a convenience function for sorted principal axes

**Comment by ctk3b** [comment]
+1 :)
