### ISSUE TITLE
Can't swap coordinates in trajectory

### ISSUE THREAD

**Issue by frank-stonybrook** [mdtraj/mdtraj#919]
I try to swap two atoms' coordinates in t.xyz. When I use the normal strategy(lst=t.xyz, lst[i],lst[j]=lst[j],lst[i]), I find out that only lst[i] is changed to lst[j] while lst[j] stays the same.  

I don't understand why it happens. Same strategy seems work well with normal python list object. 

Thx!

**Comment by swails** [comment]
> I don't understand why it happens. Same strategy seems work well with normal python list object.

Smells like a numpy bug, perhaps.  What happens if you do this on a raw numpy array?  What version of numpy are you using?  And what is your exact code snippet?

**Comment by frank-stonybrook** [comment]
This is my code:

t=md.load('reference.pdb')
def swap_coordinates(trajectory,i,j):
	top=t.topology
	coordinates=t.xyz
	coordinates[0][j],coordinates[0][i]=coordinates[0][i],coordinates[0][j]
swap_coordinates(t,0,1)

I just test on a raw numpy array, it works well. The version of numpy in my machine is 1.9.2.

Thx!

**Comment by frank-stonybrook** [comment]
Sorry, a little mistake. This is my original code:
t=md.load('reference.pdb')

def swap_coordinates(trajectory,i,j):
	coordinates=t.xyz
	print(coordinates)
	coordinates[0][j],coordinates[0][i]=coordinates[0][i],coordinates[0][j]
	print(coordinates)
swap_coordinates(t,0,1)

**Comment by frank-stonybrook** [comment]
Sorry, a typo "coordinates=trajectory.xyz". Can everyone tell me why it happens?

**Comment by hainm** [comment]
it's better if you running your script in ipython and post the real data output from screen to avoid typos.

**Comment by frank-stonybrook** [comment]
Sure! This is the ipython results:
'''
In [1]: import mdtraj as md

In [2]: t=md.load('reference.pdb')

In [3]: def swap(t,i,j):
    coordinates=t.xyz
    print(coordinates[0][0],coordinates[0][1])
    coordinates[0][0],coordinates[0][1]=coordinates[0][1],coordinates[0][0]
    print(coordinates[0][0],coordinates[0][1])
   ...:     

In [4]: swap(t,0,1)
(array([ 1.40810001, -1.04859996, -0.1869    ], dtype=float32), array([ 1.48629999, -0.93370003, -0.22939999], dtype=float32))
(array([ 1.48629999, -0.93370003, -0.22939999], dtype=float32), array([ 1.48629999, -0.93370003, -0.22939999], dtype=float32))
'''

**Comment by hainm** [comment]
it's likely numpy problem like @swails  said

output
```python
normal
[-0.0808     -0.88730001 -0.208     ] [ 0.41890001 -0.76819998 -0.025     ]
[ 0.41890001 -0.76819998 -0.025     ] [ 0.41890001 -0.76819998 -0.025     ]
swap_np
<class 'numpy.ndarray'>
[-0.0808     -0.88730001 -0.208     ] [ 0.41890001 -0.76819998 -0.025     ]
[ 0.41890001 -0.76819998 -0.025     ] [ 0.41890001 -0.76819998 -0.025     ]
```

script:
```python
import mdtraj as md

t = md.load('./polyAT.pdb')

def swap(t,i,j):
    coordinates=t.xyz
    print(coordinates[0][0],coordinates[0][1])
    coordinates[0][0],coordinates[0][1]=coordinates[0][1],coordinates[0][0]
    print(coordinates[0][0],coordinates[0][1])

def swap_np(xyz,i,j):
    coordinates=xyz
    print(coordinates[0][0],coordinates[0][1])
    coordinates[0][0],coordinates[0][1]=coordinates[0][1],coordinates[0][0]
    print(coordinates[0][0],coordinates[0][1])

print('normal')
swap(t, 0, 3)

# 2
t = md.load('./polyAT.pdb')
xyz = t.xyz.copy()
print('swap_np')
print(type(xyz))
swap_np(xyz, 0, 3)
```

**Comment by frank-stonybrook** [comment]
Thanks Hai!

But I get different results for raw np.array(my version is 1.9.2). 

In [1]: import numpy as np

In [2]: array=np.array([0,1,2,3])

In [3]: array[0],array[1]=array[1],array[0]

In [4]: print array
[1 0 2 3]

This strategy works well with raw np.array. So I think the problem might not come from np.array. 

Then I further run a test with different swap method(it is validated with raw np.array and works well).
The script:

import mdtraj as md
import numpy as np

t=md.load('reference.pdb')

def swap_coordinates(trajectory,i,j):
	coordinates=trajectory.xyz
	temp0=coordinates[0][0]
	temp1=coordinates[0][1]
       print('the original temp0',temp0)
	print('the original temp1',temp1)
	coordinates[0][1]=temp0
	print('the original temp1',temp1)
	coordinates[0][0]=temp1

swap_coordinates(t,0,1)

The results:
('the original temp0', array([ 1.40810001, -1.04859996, -0.1869    ], dtype=float32))
('the original temp1', array([ 1.48629999, -0.93370003, -0.22939999], dtype=float32))
('the original temp1', array([ 1.40810001, -1.04859996, -0.1869    ], dtype=float32))

I think the problem comes from the reassigning the value of temp1.Once I changed the coordinates[0][1] to temp0, the temp1 was also reassigned to temp0.  In my understanding, once the variables 'temp1' has been assigned to coordinates[0][1], it shouldn't be changed no matter how we change the value of coordinates[0][1]. So I guess the bug might come from mdtraj. 

Can anyone explain it to me?

Thanks a lot!
Cong

**Comment by hainm** [comment]
```python
In [1]: import numpy as np

In [2]: array=np.array([0,1,2,3])

In [3]: array[0],array[1]=array[1],array[0]

In [4]: print array
[1 0 2 3]
```

in this example. you're showing the result for array with ndim = 1. In my previous post, I showed the result for  ``ndim = 3`` (xyz).

**Comment by frank-stonybrook** [comment]
Thanks! I fix this problem with copy.copy(). Actually in this operation" temp1=coordinates[0][1]", both the value and a pointer are assigned to temp1, therefore any further changes to coordinates[0][1] will also apply to temp1. In order to avoid it, I use temp1=copy.copy(coordinates[0][1]). Then everything works fine now.

**Comment by rmcgibbo** [comment]
Great.
