### ISSUE TITLE
best way to superpose with one set of atoms and calculate RMSD with another?

### ISSUE THREAD

**Issue by steven-albanese** [mdtraj/mdtraj#923]
I'm currently trying to superpose trajectories containing a protein with a mutant to a reference wild type structure and then calculate RMSD for a specific set of atoms. What is the best way to superpose say, using all atoms except for the mutated residue (knowing that the atom indices with be different due to the mutant) and then calculated RMSD for a different set of atoms?

**Comment by mpharrigan** [comment]
See #915

**Comment by hainm** [comment]
it's likely that @steven-albanese wants to superpose with a given atom indices and then calculate rmsd for another mask.

If yes, I think you need to do ``rmsfit`` then calculate ``rmsd_nofit`` (if ``mdtraj`` has this method)

**Comment by mpharrigan** [comment]
The above pr can accommodate that. The two steps are `superpose` (arbitrary ref, query inds) and `rmsd` (arbitrary ref, query inds)

**Comment by mpharrigan** [comment]
The `rmsd` function doesn't do any superposition

**Comment by steven-albanese** [comment]
This did the trick!

**Comment by gph82** [comment]
Hi guys, feature request sort of following up on this. What would you say to superpose getting two sets of indices. My use case is two experimental pdbs with entire missing fragments where I want my superposition transformation to maximize overlap between a group of say 100 atoms shared by both structures which happen to occur as say [0:100] in one pdb and [10:110] in the other

**Comment by rmcgibbo** [comment]
n.b.: If the mapping is unknown, you can also use the lprmsd function.
