### ISSUE TITLE
mdtraj-dev not updating on binstar

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#924]
Last upload seems to have been one month ago:
https://binstar.org/omnia/mdtraj-dev/files

There seems to be an error in `after_success.sh`:
https://travis-ci.org/mdtraj/mdtraj/jobs/78652842#L7360
```
Traceback (most recent call last):
  File "devtools/travis-ci/update-versions.py", line 7, in <module>
    from msmbuilder import version
ImportError: No module named msmbuilder
```

Also, from earlier, this error
https://travis-ci.org/mdtraj/mdtraj/jobs/78652842#L359-L365
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!
!!  The 'binstar' conda package has been renamed to 'anaconda-client'.
!!  Please run:
!!
!!    conda install anaconda-client
!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
suggests `binstar` needs to be changed to `anaconda-client` here:
https://github.com/mdtraj/mdtraj/blob/master/devtools/travis-ci/install.sh#L12

I will create a PR if I can get my fork to update over airplane wifi...

**Comment by jchodera** [comment]
Looks like the authentication token has expired:
https://travis-ci.org/mdtraj/mdtraj/jobs/78669284#L3623
```
[Unauthorized] Authentication token has expired 
```
Might need someone with direct commit access to fix this (@rmcgibbo?).

**Comment by rmcgibbo** [comment]
Looks fixed:
```
Uploading file omnia/mdtraj-dev/1.5.0.dev0/linux-64/mdtraj-dev-1.5.0.dev0-np16py27_0.tar.bz2 ... 
[warning] Distribution linux-64/mdtraj-dev-1.5.0.dev0-np16py27_0.tar.bz2 already exists ... removing 
 uploaded 15478 of 15478Kb: 100.00% ETA: 0.0 minutes
```
