### ISSUE TITLE
Load only desired frames for multiple trajectories

### ISSUE THREAD

**Issue by steven-albanese** [mdtraj/mdtraj#931]
Is it possible to say, only load trajectories from after `first_frame_of_interest`? Or is the `slice` method my best bet?

**Comment by mpharrigan** [comment]
Using the lower-level file-like objects (e.g. http://mdtraj.org/latest/api/generated/mdtraj.formats.DCDTrajectoryFile.html) you can call `seek(first_frame_of_interest)` and then `read_as_traj(topology)` [or `read()` if you just need the coordinate numpy arrays.
