### ISSUE TITLE
Automatic dependency resolvation with pip

### ISSUE THREAD

**Issue by marscher** [mdtraj/mdtraj#933]
I wonder if you would accept a PR which drags in dependencies like NumPy and Cython during installation with pip. If one installs a mdtraj dependent project in a clean environment the order of installation might get resolved wrong, if these are not declared in a setuptools specific manner.

This would not interfere with conda, since automatic downloading has been blocked in recent versions of conda-build anyway.

If one opts in cython during setup time, one should considerate to request the users to have at least setuptools >= 18, because since this version the hassle of cython builds has been fixed.

What do you think?

**Comment by rmcgibbo** [comment]
I have tried packaging things in the past using setuptools' `install_requires`, and always had very poor experiences. It never quite worked correctly, and would do things such as downloading and compiling numpy from source (sloooow) even when it was already installed, etc.

Perhaps with the new versions of setuptools, this behavior has been improved? I'd be totally willing to give it a try again.
