### ISSUE TITLE
global distance test

### ISSUE THREAD

**Issue by euhruska** [mdtraj/mdtraj#937]
Is there a global distance test (GDT) function in mdtraj? I think it's pretty important since it's the scoring function at CASP. See: http://research.omicsgroup.org/index.php/Global_distance_test

**Comment by rmcgibbo** [comment]
no, a function for gdt in mdtraj hasn't been written yet.

**Comment by euhruska** [comment]
Are there chances one will be written in near future?

**Comment by rmcgibbo** [comment]
It's not on my personal agenda, but if you'd like to contribute code, I'm always happy to merge PRs.

**Comment by euhruska** [comment]
Alright, maybe I will look into that.
