### ISSUE TITLE
.h5 file visualization failure 

### ISSUE THREAD

**Issue by frank-stonybrook** [mdtraj/mdtraj#947]
Hi,
I use mdconvert to convert a pdb file to a .h5 file. However, I find out that the vmd couldn't proper handle the .h5 file:

Info) Using plugin h5md for structure file /home/frank/Desktop/3DFR_reduced.h5
ERROR) BaseMolecule: init_atoms called with invalid number of atoms: 0
ERROR) molecule_structure: Unable to read structure for molecule 1
ERROR) molecule_structure: severe error indicated by plugin aborting loading of molecule 1

I test with other .h5 files which provided by VMD-h5mdplugin group in GIthub and they work well. I guess that the problem happens in the converting process of mdconvert. 
However, there isn't any warning during the converting process:

$ mdconvert -o 3DFR_reduced.h5 3DFR_reduced.pdb 
converted 1 frames, 1375 atoms

Is there any difference between mdconvert converted .h5 file and standard .h5 file. 

Thanks
Cong

**Comment by rmcgibbo** [comment]
The mdtrraj h5 file is in this format: http://mdtraj.org/latest/hdf5_format.html. Despite the same file extension, this is not the same as the h5md format (http://nongnu.org/h5md/).

**Comment by frank-stonybrook** [comment]
Thanks, rmcgibbo!
