### ISSUE TITLE
Deviation of rmsd between VMD and Mdtraj 

### ISSUE THREAD

**Issue by frank-stonybrook** [mdtraj/mdtraj#948]
I am trying to figure out a rmsd calculation difference between VMD and mdtraj. The rmsd calculation protocol:
1. Align trajectory to reference using atom indices 'protein_noH';
2. Calculate rmsd of trajectory using atom indices 'ligand_atoms';

For mdtraj method, the command I use is:
```python
t.superpose(ref,0,protein_noH);
rmsd = md.rmsd(t,ref,0,ligand_atoms,precentered=False)
```

For VMD, I find out that the result is almost the same with the numerical implementation method.  So I use the numerical results to represent the VMD results. 
In image below, you could see an VMD plot with mdtraj.rmsd in red and vmd in green
![figure_1](https://cloud.githubusercontent.com/assets/10855977/10495574/983b8202-728a-11e5-8394-146323dfc0f7.png)

These are the script and input files: 
https://www.dropbox.com/sh/mlf92dvyfpob6wi/AABOBd8pQmT_R-awG_fBMxGFa?dl=0

**Comment by rmcgibbo** [comment]
`md.rmsd` optimally aligns the desired atom indices. your mdtraj code is not implementing the "align on one set of atoms and compute the deviations on another set of atoms without alignment".

**Comment by frank-stonybrook** [comment]
Hi Robert,

I don't quite understand the 'md.rmsd optimally aligns the desired atom indeces'. You mean that if I write
rmsd = md.rmsd(t,ref,0,ligand_atoms,precentered=False)	

the md.rmsd will automatically realign the trajectory based on ligand atoms??

**Comment by rmcgibbo** [comment]
Yes.

**Comment by rmcgibbo** [comment]
It doesn't actually rotate the coordinates inplace, but it does compute the minimum root mean squared diplacement rmsd after application of the optimal rotation matrix.

**Comment by cxhernandez** [comment]
related (I think): https://github.com/mdtraj/mdtraj/issues/523

**Comment by rmcgibbo** [comment]
Maybe it would help clear up confusion if we added the mathematical definitions calculations being performed to the docstring.

**Comment by frank-stonybrook** [comment]
Yeah, adding mathematical definitions will be more clear. Another thing which confuses me is definition of align. It seems that the alignment means optimizing rotation matrix in mdtraj while in vmd, alignment means eliminating both translational and rotational movement of a trajectory. Maybe rephrasing align with minimizing rotational matrix will be better.

**Comment by frank-stonybrook** [comment]
@rmcgibbo I am wondering why don't adding an argument in md.rmsd to manually turn off this rotating. That will be much more convenient to calculate L-RMSD which requires to superimpose only the receptor part of complex before calculating the rmsd of ligand. Meantime the user will have less confusion about what the rmsd does when performing calculation. Just my personal opinion. 
Thanks for your reply. 
Cong

**Comment by rmcgibbo** [comment]
Yes, this might be a feature worth adding. We're happy to accept patches if you'd like to file a PR. You can also do it in one line of numpy. `np.sqrt(np.mean(np.square(xyz[:,ligand_indices]-xyz[0,ligand_indices]),axis=(1,2)))`.

**Comment by mpharrigan** [comment]
Is this a different problem then aligning on one set of atoms and calculating rmsd on a different set of atoms, which I recently implemented #915

**Comment by frank-stonybrook** [comment]
@mpharrigan I am not quite sure whether the new rmsd function could satisfy my request.  If I specify both the atom_indices and ref_atom_indices in the new rmsd function, the rmsd will superpose based on ref_atom_indices and won't realign target to ref based on atom_indices?? If that is the case, then it is the same problem. 
Cong

**Comment by cing** [comment]
Just a heads up future readers, @rmcgibbo's numpy one liner is actually off by a constant inside the square root. RMSD is an average over N not 3N. If you want to use the cool double axis mean you need to add a `3` back in ;)

```
np.sqrt(3*np.mean(np.square(xyz[:,ligand_indices]-xyz[0,ligand_indices]),axis=(1,2)))
```

**Comment by frank-stonybrook** [comment]
Thanks for your reminding, Christopher!
​
