### ISSUE TITLE
error: unknown file type '.pyx' (from 'mdtraj/formats/xtc/xtc.pyx')

### ISSUE THREAD

**Issue by hainm** [mdtraj/mdtraj#953]
hi,

I am installing mdtraj (master) but got above error. Any idea why?

this is the end of errors
```bash
running build_ext
building 'mdtraj.formats.xtc' extension
error: unknown file type '.pyx' (from 'mdtraj/formats/xtc/xtc.pyx')
```

```bash
$ git log | head
commit 46f7cb9262db6afaf7dfc4c4165b30adecb026a4
Merge: 18bb3c9 3746e66
Author: Robert T. McGibbon <rmcgibbo@gmail.com>
Date:   Tue Oct 20 14:59:47 2015 -0700
```

```bash
$ python -c 'import cython; print(cython.__version__)'
0.23.4
```

PS: It's fine to install pytraj's pyx files.

**Comment by rmcgibbo** [comment]
could be related to #934? what version of setuptools do you have installed?

**Comment by rmcgibbo** [comment]
yeah, I can reproduce this error if I install setuptools 17. @marscher: do you know if there's a better way to test the version of setuptools? I don't think https://github.com/mdtraj/mdtraj/blob/master/setup.py#L230-L236 is sufficient.

**Comment by hainm** [comment]
> what version of setuptools do you have installed?

quite outdated (it's in anaconda, so ...)

```bash
$ python -c 'import setuptools as s; print(s.__version__)'
0.6
```

**Comment by rmcgibbo** [comment]
I believe setuptools>=18 is an installation requirement, re #933, #934, which enables `pip install mdtraj` to work even if the user doesn't have `numpy` and `cython` installed.

**Comment by hainm** [comment]
may be try to import numpy and cython first and check setuptools later?

**Comment by rmcgibbo** [comment]
It's not that simple. My preference would be just to make `setuptools>=18` are hard requirement.

**Comment by hainm** [comment]
closed. I think my conda env is messed up, already have v18 for setuptools but 0.6 was used. Just create new env and was able to install mdtraj.

**Comment by rmcgibbo** [comment]
You can always `rm -rf /path/to/anaconda/envs/<your_env/lib/pythonX.Y/site-packages/setuptools-*`.

**Comment by hainm** [comment]
> You can always rm -rf 

this is exactly what I do. After remove by `-rf`, I reinstalled by 
`conda install setuptools --force`

and this is what I got

```
python3.4/site-packages/setuptools-18.4-py3.4.egg/setuptools/dist.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'packaging'
```

conda is really weird recently. Especially this: https://github.com/conda/conda/issues/1720

**Comment by marscher** [comment]
The old version of setuptools is not capable of directive setup_requires, otherwise it should have risen an exception. We can try adding a __requires__ = 'setuptools>=18' line at the top of the setup file and check, if it leads to an error with this plain old setuptools version.

**Comment by rmcgibbo** [comment]
Even with setuptools==17, which I tried, I didn't get a warning about an inadequate version of setuptools or an automatic installation of a later version.

**Comment by rmcgibbo** [comment]
Actually, no, that's wrong.

**Comment by hainm** [comment]
@rmcgibbo 
FYI: turns out that the error with `AttributeError: 'module' object has no attribute 'packaging'` is due to old `pkg_resources.py` file. Delete it will solve my problem.

http://stackoverflow.com/questions/28967785/attribute-error-installing-with-pip
