### ISSUE TITLE
Periodic boundary conditions

### ISSUE THREAD

**Issue by juanmit** [mdtraj/mdtraj#956]
Are there anyways in mdtraj solving the pbc problem? I would like to get of "atom-jumping" problems.

Thanks a lot.

**Comment by mpharrigan** [comment]
Most (all?) of the analysis functions take into account pbc

Having the ability to make trajectories imaged pretty for a movie is on the wishlist (a la `gmx trjconv -pbc mol` or `cpptraj`'s `autoimage`)

**Comment by swails** [comment]
That doesn't actually get rid of the atom jumping problem in general.  What you'd need to do for that is something along the lines of cpptraj's "unwrap", which is harder to do efficiently in Python.  That's basically where you follow a *single* periodic image for the entire simulation (helps you measure stuff like diffusion).

But yes, #930 was the first step in supporting "pretty" wrapping.

**Comment by juanmit** [comment]
Thanks all for replying. I think my problem was solved by using the very original files in .dcd, which contains all the necessary info, but .dcd files take much more memory than reading .xtc(protein only) files. I am checking my results now. Or I can re-create a new tpr file for trjconv command -pbc whole for further analysis. Thanks for helping.
