### ISSUE TITLE
ValueError on import

### ISSUE THREAD

**Issue by bas-rustenburg** [mdtraj/mdtraj#958]
I get this error on importing mdtraj, not sure what is causing it. 
```
zsh 794 % python
Python 2.7.10 |Anaconda 2.2.0 (64-bit)| (default, Oct 19 2015, 18:04:42) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import mdtraj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bas/miniconda3/envs/py2k/lib/python2.7/site-packages/mdtraj/__init__.py", line 29, in <module>
    from mdtraj.formats.registry import _FormatRegistry
  File "/home/bas/miniconda3/envs/py2k/lib/python2.7/site-packages/mdtraj/formats/__init__.py", line 2, in <module>
    from mdtraj.formats.dcd import DCDTrajectoryFile
  File "__init__.pxd", line 155, in init dcd (mdtraj/formats/dcd/dcd.c:10359)
ValueError: numpy.dtype has the wrong size, try recompiling
```
I have this version installed. 
```
zsh 795 % conda list mdtraj
# packages in environment at /home/bas/miniconda3/envs/py2k:
#
mdtraj                    1.4.2               np110py27_0  
```

**Comment by mpharrigan** [comment]
What version of numpy do you have installed?

**Comment by rmcgibbo** [comment]
that means mdtraj was built against a different version of numpy than the one you have installed.

**Comment by bas-rustenburg** [comment]
```
<bas@lmis8010:~>
zsh 796 % conda list numpy
# packages in environment at /home/bas/miniconda3/envs/py2k:
#
numpy                     1.10.1                   py27_0
```

**Comment by rmcgibbo** [comment]
can you paste the md5 of `/home/bas/miniconda3/pkgs/mdtraj-1.4.2-np110py27_0.tar.bz2`?

**Comment by bas-rustenburg** [comment]
Here you go:
```
zsh 801 % md5sum /home/bas/miniconda3/pkgs/mdtraj-1.4.2-np110py27_0.tar.bz2
f97a30dde21efd92e62afa3b180a6cd6  /home/bas/miniconda3/pkgs/mdtraj-1.4.2-np110py27_0.tar.bz2
```

**Comment by rmcgibbo** [comment]
we had some problems with conda-build around the time this package was built, so it might have been broken during the build, but I thought I deleted those packages.

```
$ wget https://anaconda.org/omnia/mdtraj/1.4.2/download/linux-64/mdtraj-1.4.2-np110py27_0.tar.bz2
[... snip ...]
rmcgibbo@vspm9  ~ (3.4.2)
$ md5sum mdtraj-1.4.2-np110py27_0.tar.bz2
f97a30dde21efd92e62afa3b180a6cd6  mdtraj-1.4.2-np110py27_0.tar.bz2
```

**Comment by rmcgibbo** [comment]
looks like its not that...

**Comment by mpharrigan** [comment]
Should we increment the "build" number so that it will auto upgrade

**Comment by rmcgibbo** [comment]
Not a bad idea.

**Comment by bas-rustenburg** [comment]
Funny enough, I can't seem to reproduce this on another pc with the same python and numpy version...  Not sure why it's not working normally on this particular case. Even a fresh conda environment still gives me the error.

**Comment by rmcgibbo** [comment]
Same OS too?

**Comment by bas-rustenburg** [comment]
Ubuntu 15.04 for the failing one, Ubuntu 12.04.5 LTS for the working one.

**Comment by rmcgibbo** [comment]
Huh. My assumption previously was that the mdtraj .tar.bz2 binary was just broken, but maybe that's not the case

**Comment by rmcgibbo** [comment]
You might have multiple versions of numpy installed, either with PYTHONPATH, LD_LIBRARY_PATH, pip/setuptools installing a second shadow-copy in your site-packages folder?

**Comment by bas-rustenburg** [comment]
`pip uninstall numpy` did the trick! Thanks, something installed numpy in  ~/.local/lib/python2.7/site-packages/  and somehow that was picked up.

**Comment by bas-rustenburg** [comment]
May have spoken too soon..I'm seeing it again, though I got rid of it for a moment. It's probably something with my environment, not mdtraj. Feel free to close.

**Comment by bas-rustenburg** [comment]
Yet another shadow-copy when I started a new shell. I think I got rid of them all now and it's working.
