### ISSUE TITLE
All PDBs from RCSB contain CRYST1 record, but some of them are nonsensical fillers

### ISSUE THREAD

**Issue by swails** [mdtraj/mdtraj#970]
The question is, what heuristic test can we come up with that will serve as a useful test for when we can issue warnings?

I have 2 ideas:

1. Calculate a simple density using the volume of the unit cell and the total mass of the system.  Emit a warning if it is well outside the range of acceptable values.  For instance, I think the unit cell dimensions for NMR structures are tiny (1x1x1 A).  This is from 2KOC:

```
CRYST1    1.000    1.000    1.000  90.00  90.00  90.00 P 1           1
```

2. Pull out the `EXPDTA` record and fail if it exists by is *not* X-Ray diffraction.

I personally like the first option better, as it is a more useful warning IMO.  I can work on a PR if people agree.

cc pandegroup/openmm#1176

**Comment by mpharrigan** [comment]
Fixed by #974
