### ISSUE TITLE
Bonds based on CONECT records are not added for multi-model files

### ISSUE THREAD

**Issue by rafwiewiora** [mdtraj/mdtraj#977]
CONECT records are required to be after the last ENDMDL, hence [pdbstructure.py](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbstructure.py#L203-L212) only fills `connects` for the last model. 

However, [pdbfile.py] (https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L524) appends bonds based on the `connects` from the first model. 

Simply change [the pdbfile.py line] (https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L524) to:
``` python
for connect in pdb.models[-1].connects:
```
works. Should I PR this revolutionary modification?

**Comment by rmcgibbo** [comment]
Sounds good.

> Should I PR this revolutionary modification?

Perfect.
