### ISSUE TITLE
pip install mdtraj fails without Cython

### ISSUE THREAD

**Issue by rmcgibbo** [mdtraj/mdtraj#984]
`pip install mdtraj` (1.5.0, just released) does not seem to work without Cython installed, even with setuptools >= 18. @marscher, if you have a second, could you take a look at this? I'm tempted to revert #934.

```
$ pip install mdtraj
  Running setup.py bdist_wheel for mdtraj
[ ... snip ...]
  2 warnings generated.
  clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/rmcgibbo/miniconda/envs/3.5/include -arch x86_64 -Imdtraj/formats/xtc/include/ -Imdtraj/formats/xtc/ -I/private/var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-vjm8bkn9/mdtraj/.eggs/numpy-1.10.1-py3.5-macosx-10.5-x86_64.egg/numpy/core/include -I/Users/rmcgibbo/miniconda/envs/3.5/include/python3.5m -c mdtraj/formats/xtc/xtc.c -o build/temp.macosx-10.5-x86_64-3.5/mdtraj/formats/xtc/xtc.o
  clang: error: no such file or directory: 'mdtraj/formats/xtc/xtc.c'
  clang: error: no input files
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mdtraj
```
```
$ python -c 'import setuptools; print(setuptools.__version__)'
18.4
```

**Comment by mpharrigan** [comment]
Should I hold off on pushing 1.5.1 to resolve/revert this?

**Comment by rmcgibbo** [comment]
I'm not sure. Really setuptools is just a mess. `setup_requires` is smart enough to try to install Cython, but it doesn't actually use pip to install cython (which can get the binary wheel in ~2 seconds), it uses `easy_install` which tries to build Cython from source.

**Comment by rmcgibbo** [comment]
The first thing that `pip` does when you run `pip install mdtraj -vvv` after downloading the tarball is run `python setup.py egg_info`. And right there, setuptools stupidly calls `easy_install` to try to download/compile Cython. Uggh.

**Comment by mpharrigan** [comment]
Let's continue suggesting users install mdtraj conda package. If they need to install from source, install cython conda package. If they want to get more fancy, they can probably figure out that things are a mess and work around

**Comment by rmcgibbo** [comment]
> Let's continue suggesting users install mdtraj conda package.

I agree with that. But people are still going to use PyPI.

If we revert #934, at least we can give a helpful error message to people using pip/pypi (hey, you need to get these dependencies first, and sorry we can't reliably auto-install them for you). With the current master, they just get a cryptic failure.

**Comment by mpharrigan** [comment]
Ok, do you want to go ahead and revert?

**Comment by rmcgibbo** [comment]
Alright. Working on it now.

**Comment by marscher** [comment]
What is missing is to ship pre-cythonized c files created by Distutils/Setuptools sdist phase to avoid installing Cython. If Cython is there, one gonna use it. We use this pattern successfully on our PyPI release of msmtools and pyemma. Sorry that I've forgotten to include this one in #934. 

At least the setup succeeds in case of missing Cython (and pre-cythonized files) by dragging in a fresh installation - this combination works like a charm on Linux and OSX (and Windows users with a sane environment).

**Comment by marscher** [comment]
Actually I'm not aware of which method setuptools uses to handle temporary (like setup phase) dependencies. If there is a binary around, setuptools should install this one preferably, if it does not this is should be considered a bug in setuptools.

**Comment by rmcgibbo** [comment]
Setuptools uses easy_install, not pip, to install setup_requires. See e.g. https://bitbucket.org/dholth/setup-requires by one of the pip developers that tries to work around this. And also http://article.gmane.org/gmane.comp.python.distutils.devel/24218, for why even install_requires doesn't work well.

Basically, my sense is that both setup_requires and install_requires are too broken to be useful. I think on balance, the best way to serve users is just to try to import numpy and cython, and provide a helpful error message if they're not available.
