### ISSUE TITLE
Add kwarg to load positions only from the first model?

### ISSUE THREAD

**Issue by rafwiewiora** [mdtraj/mdtraj#991]
Another thing that came up in my whole-PDB analyses - currently 195 files do not load, because they throw the:

```
'PDB Error: All MODELs must contain the same number of ATOMs'
```

[here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L501-L512).

From a quick look, it's stuff like - only some models have waters, there's a proton missing somewhere etc. 

I'd like to add the `use_all_models` kwarg  to `load_pdb` and be able to set it to `False` in my scripts - positions are loaded only from the first model and the problem is avoided. Are you guys ok with adding that in? 

Just to point out using `load_frame` to only load the first frame/model doesn't work because that loads positions for all frames before picking the needed ones anyway. 

One issue that I'm not yet sure if it will arise, but I'm looking now - in #980 we've added appending CONECT bonds from the last model, but for these files where all models don't have the same atoms it's not clear to me what the meaning of CONECT is - is that ensured to work with the last model in the PDB / first / any other? Looking into that now. Ideally, I want to be able to use the model in those files that gives me as much info as possible.

**Comment by rmcgibbo** [comment]
I'm not really sure about this. I assume that comes from the spec -- that all of the models must contain the same number of atoms, right?

**Comment by swails** [comment]
> I'm not really sure about this. I assume that comes from the spec -- that all of the models must contain the same number of atoms, right?

Only partially.  This is from the spec:

* This record is used only when more than one model appears in an entry. Generally, it is employed
mainly for NMR structures. The chemical connectivity should be the same for each model. ATOM, HETATM, ANISOU, and TER records for each model structure and are interspersed as needed between MODEL and ENDMDL records.
* The numbering of models is sequential, beginning with 1.
* All models in a deposition should be superimposed in an appropriate author determined manner and
only one superposition method should be used. Structures from different experiments, or different
domains of a structure should not be superimposed and deposited as models of a deposition.
* All models **in an NMR ensemble** should be homogeneous – each model should have the exact
same atoms (hydrogen and heavy atoms), sequence and chemistry.
*Deposition of minimized average structure (if available) must be accompanied with ensemble and
must be homogeneous with ensemble.
*A model cannot have more than 99,999 atoms. Where the entry does not contain an ensemble of
models, then the entry cannot have more than 99,999 atoms. Entries that go beyond this atom limit
must be split into multiple entries, each containing no more than the limits specified above .

(emphasis added).  That leaves some wiggle room for having different numbers of atoms per model.

**Comment by swails** [comment]
[HTML reference](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#MODEL) -- I always use the PDF, so I never think to refer to the website.

**Comment by rmcgibbo** [comment]
It seems kind of ambiguous. As @rafwiewiora pointed out, the connect records become unclear with the looser interpretation.

**Comment by swails** [comment]
Agreed.  Maybe it would be worthwhile to add something like `keepmodels=<int or 'all'>`, with the default being `all`.  It certainly has the potential of being a hefty change, though, and one we would likely want to initiate upstream in OMM.

**Comment by rafwiewiora** [comment]
I've seen some ugly hacks out there where people put parts of structures longer than 99,999 atoms in multiple models to be able to have them in one file... But obviously that's not in the database. 

I've looked at those 195 files that fail more closely: 46 of those are actually multi-model X-ray structures (I  was a bit surprised to see X-ray multimodels but it makes sense - for example you have separate models of activated and non-activated rhodopsin in one file) - I guess some of those can justifiably have different numbers of atoms. But the 149 NMR files clearly break the specifications - will report to the PDB. 

As far as the CONECT is concerned, 88 / 195 don't have a CONECT record, of the remaining 107, in 67 the atom numbers in CONECT can refer to different atoms depending on which model you look. Will report this to PDB too. 

So I'm just going to consider these useless for my work, too little incentive to try to get any information from <0.2% of the database. Don't really need the kwarg then - if you guys think that might be useful to add anyway (and it'll take a second to do) then can do it, otherwise good to close I guess.

**Comment by rmcgibbo** [comment]
This sounds good to me. Thanks for doing all of this -- it sounds like it was a lot of work. And the fact that many of the bugs you encountered are arguably bugs in the PDB repository as opposed to bugs in the MDTraj code gives me some confidence that, in large part, we're doing things correctly.

**Comment by rafwiewiora** [comment]
Sure thing, no problem at all! 

> And the fact that many of the bugs you encountered are arguably bugs in the PDB repository as opposed to bugs in the MDTraj code gives me some confidence that, in large part, we're doing things correctly.

Definitely, it's a good test for MDTraj and it passes solidly. 

So yes or no on the kwarg?
