### ISSUE TITLE
Support of __len__ in xyz files? 

### ISSUE THREAD

**Issue by ppxasjsm** [mdtraj/mdtraj#992]
It would be useful if `__len__` in xyz files was implemented, so that there is a support for reading .xyz files with pyemma. 
See https://github.com/markovmodel/PyEMMA/issues/621#

**Comment by rmcgibbo** [comment]
I'm not sure that this can be done efficiently, but that probably doesn't matter.

**Comment by marscher** [comment]
Thank you @ctk3b and @rmcgibbo :+1:
